### ISSUE TITLE
Forwarding SOCKS5 over UDP

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#100]
golang's x/net doesn't yet support SOCKS5 over UDP.

This library looks promising in its stead: [txthinking/socks5](https://github.com/txthinking/socks5).

Follow-up from #45

**Comment by ignoramous** [comment]
Today's TCP impl:

https://github.com/celzero/outline-go-tun2socks/blob/81ff0f9992aa755550ef1d8b1177bbeb6c2d1ea0/tunnel/intra/tcp.go#L252-L258

https://github.com/celzero/outline-go-tun2socks/blob/81ff0f9992aa755550ef1d8b1177bbeb6c2d1ea0/tunnel/intra/tcp.go#L312-328

Corresponding missing UDP impl:

https://github.com/celzero/outline-go-tun2socks/blob/81ff0f9992aa755550ef1d8b1177bbeb6c2d1ea0/tunnel/intra/udp.go#L421-438

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> golang's x/net doesn't yet support SOCKS5 over UDP.
> 

If not UDP associate supported.

Can it use socks5 for hostname resolving passthrough directly via socks5 port?

**Comment by ignoramous** [comment]
> Can it use socks5 for hostname resolving passthrough directly via socks5 port?

If I understand your question right, then don't think so.

**Comment by ignoramous** [comment]
Done: https://github.com/celzero/firestack/commit/35c46f5932174909af0f58c954e650a882d797ad
