### ISSUE TITLE
v055: Missing 🐘 🐢 indicators

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1000]
*Network Log* shows an 🐘 when recieved/transmitted bytes are more than 500kb in size.

But: 🐘 isn't shown when the connection breaches the mb mark.

Similarly, for a few users 🐢 is never shown when a connection breaches 2min mark. At least one user was on LineageOS.

<details>
<summary>screenshots</summary>
NewPipe breaching MBs but no 🐘:

![IMG_20230819_235425_954](https://github.com/celzero/rethink-app/assets/852289/ff024187-14f1-4f1e-8a68-f9ce3abb24a2)

NewPipe breaching the 2min barrier but no 🐢:

![IMG_20230819_235429_554](https://github.com/celzero/rethink-app/assets/852289/1a78655b-54ed-4f54-860b-71d7ffd6fb7f)
</details>

**Comment by hussainmohd-a** [comment]
Fixed: 1c6dd486
