### ISSUE TITLE
Cloudflare DOH not using ipv6

### ISSUE THREAD

**Issue by chris122380** [celzero/rethink-app#1001]
Cloudflare DOH only shows using 1.1.1.1 when going to https://1.1.1.1/help. The DOH doesn't appear to be using IPv6. It should be using all 4 IP addresses and not just 1.1.1.1.

**Comment by ignoramous** [comment]
Rethink's DoH client will use which ever IPs are functional. It doesn't bias towards IPv4 or IPv6.

**Comment by chris122380** [comment]
> Rethink's DoH client will use which ever IPs are functional. It doesn't bias towards IPv4 or IPv6.
> 
> But if you mean to say that DoH over IPv6 only servers don't work... then that's a bug. But that's not what you mean?

The IPv6 servers are not working. If I run an IPv6 test using different IPv6 test websites it works fine with rethink turned off but the moment I turn it on using cloudflare it no longer works. 

https://1.1.1.1/help should report all four IP addresses if it properly is working. I would try using 1dot1dot1dot1.cloudflare-dns.com but I think that is DNS over tls which I don't see an option to add that.

**Comment by chris122380** [comment]
It looks like any DOH, Dnscrypt, and even a Dns Proxy using ipv6 isn't using ipv6 correctly. 

Using https://test-ipv6.com/ to test IPv6 (there may be more effective way for me to test it on my phone I just don't know what it is)

**Comment by ignoramous** [comment]
I think you're confusing two different things.

To use IPv6, go to *Configure* -> *Network* -> *Choose IP version* and set it to *Auto* or IPv6.

*Auto* used either IPv4 or IPv6 depending on the underlying network (wifi / mobile). It is an experimental feature.

You can confirm the IP protocols in-use from looking at the footer of the bottomsheet that comes up when you tap on the down-arrow next to the START / STOP button on Rethink's homescreen.

**Comment by chris122380** [comment]
> I think you're confusing two different things.
> 
> To use IPv6, go to _Configure_ -> _Network_ -> _Choose IP version_ and set it to _Auto_ or IPv6.
> 
> _Auto_ uses either IPv4 or IPv6 depending on the underlying network (wifi / mobile). It is an experimental feature.
> 
> You can confirm the IP protocols in-use from looking at the footer of the bottomsheet that comes up when you tap on the down-arrow next to the START / STOP button on Rethink's homescreen.

Thank you that fixed the problem.
