### ISSUE TITLE
WireGuard does not work with IPv6 endpoints?

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1002]
Ref: https://github.com/celzero/rethink-app/issues/52#issuecomment-1684945189

**Comment by ignoramous** [comment]
Just tested WireGuard with IPv6, it works.

**Comment by outusuke** [comment]
endpoint works but server does not use ipv6 alongside ipv4, test done with warp+

**Comment by ignoramous** [comment]
I see failures with v6-only wg-interface address. Basically, WireGuard is timing out trying to send out v6 packets despite proper routes. This is a strange one indeed.

**Comment by ignoramous** [comment]
Made a bunch of improvements and IPv6 works without any issue now.

Although, do note that IPv6 with WireGuard behaves as expected only when Rethink's tunnel itself has IPv6 routes (that is, *Configure* -> *Network* -> *Choose IP version* must be set to either *IPv6* or *Auto* AND the underlying network, be it wifi or mobile, *must* have IPv6 connectivity).

**Comment by ignoramous** [comment]
Should be fixed in [`v055a`](https://www.reddit.com/r/rethinkdns/comments/166m2rd/v055a_a_glitch_in_the_matrix/). Thanks for the bug report. Tracking this one down was fun!

Feel free to reopen if that's not the case.

**Comment by outusuke** [comment]
I tested it and it's working fine now, thanks for the fix
