### ISSUE TITLE
Wireguard configuration page cannot be scrolled and buttons are blocking the switches

### ISSUE THREAD

**Issue by bestpika** [celzero/rethink-app#1006]
Hello, on my phone, if there are five profiles in wg, the switch of the last profile will be blocked by the button for adding a new profile.
If there are more than five profiles, the sixth profile will be off-screen and I won’t be able to scroll to access it.
I’m not sure if everyone’s phone has this problem, but it happened on my phone.

My phone runs on Android 9, Mi A1.
App version is v055.

**Comment by hussainmohd-a** [comment]
@bestpika Thank you for reporting the issue. 

We could add padding to the `RecyclerView` to fix this. This padding will create a buffer space between the last entries and the FAB.
