### ISSUE TITLE
v055: Start on reboot does not work

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1008]
[A user writes](https://www.reddit.com/r/rethinkdns/comments/15r1eq9/comment/jx2hvn8/?utm_source=reddit&utm_medium=web2x&context=3),

> Yeah I have always on vpn turned on, and also have the start on boot enabled. It doesn't seem to start though. I'm on calyx os.

Prior: #893

**Comment by ignoramous** [comment]
More,

> Other start-automatically apps seem to start just fine. I also ran the don't kill my app tests and it passed just like stock pixel. For example, syncthing starts up just fine. The rethink app starts and pushes a notification saying it's off, but doesn't turn on the protection automatically, so I have to go into the app and hit "start".

**Comment by TechD123** [comment]
Can confirm the above, also CalyxOS. Tried generating a log, but it fails immediately ("Error loading log file ").

Will update if I manage to get one or if the behavior changes.

Appreciate all the hard work!!

**Comment by ignoramous** [comment]
We think https://github.com/celzero/rethink-app/pull/856 is causing this issue which fixes other important issues.

We are looking to get our code in order so none of the issues would happen but it may take a long while, and so as an immediate measure, we will ship an quick fix for this issue in `v055a`.

**Comment by hussainmohd-a** [comment]
Fixed start-on-boot issue on tested devices. Additional testing required for confirmation on other devices. https://github.com/hussainmohd-a/rethink-app/commit/c667f34e5c7d3a30be065cc73eed755b9a7710eb

**Comment by hussainmohd-a** [comment]
Closing for now; will reopen if further attention is needed.
