### ISSUE TITLE
Tunable Kt and GoLog levels for release builds 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1011]
> Is there any way I can set the log level to include these, without having to switch to a debug build of the Rethink app?

_Originally posted by @Rhys-T in https://github.com/celzero/rethink-app/issues/1005#issuecomment-1686847830_

**Comment by hussainmohd-a** [comment]
Starting from version v055n, users can set the log level from the UI according to their preference for both Kotlin and Go log levels.
