### ISSUE TITLE
v055: SOCKS5 / HTTP tunnels through Shadowrocket does not work

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1017]
A user reports that tunnels through to [Shadowrocket](https://play.google.com/store/apps/details?id=com.v2cross.proxy) (SOCKS5/HTTP) in v054c and previous versions worked fine, but are broken in v055.

In one instance, I found that the newly installed Shadowrocket wasn't excluded from the tunnel despite being set as the target app in the SOCKS5 dialog.

Manually excluding Shadowrocket however did not work either, as ALL connections were refused by the Shadowrocket endpoint.

**Comment by ignoramous** [comment]
A user writes,

> I noticed this feature: to enable or disable the SOCKS5 proxy for Shadowrocket, you need to stop then start the VPN connection in DNS&Firewall.

**Comment by hussainmohd-a** [comment]
In version v055j, a new user setting has been introduced allowing users to select whether to exclude the configured app. By default, this setting is enabled (true).

https://github.com/celzero/rethink-app/pull/1425/commits/83fad651ab9aaab63a2e98b08cd1b9f984fa5664
