### ISSUE TITLE
block domain rules being marked/highlighted as allowed in DNS log?

### ISSUE THREAD

**Issue by sinjoe** [celzero/rethink-app#1022]
Setting custom blocked domain rules, it still being marked/highlighted as allowed in DNS log. If I tap on the DNS domain log, its says resolved, but drop down option shows its Block, instead of No Rule or Trust.

Is this normal?

I dont know if this is related, but custom blocked domain rules is for system app.

I dont know if someone already brought this up or this is already known. And sorry if its confusing

**Comment by ignoramous** [comment]
1. Universally *blocked* domains showing up with *answers* in DNS log is fine as long as there's some app that *trusts* (allows) that blocked domain.

2. If not, DNS should deny resolving universally (global) blocked domains.

We are aware of and have fixed the 2nd case in `v055a` (releasing in a day or two or three), if that's the bug you're reporting.

**Comment by hussainmohd-a** [comment]
Thanks for the update. Closing this as fixed.
