### ISSUE TITLE
Add support DNS (IPv4, IPv6)

### ISSUE THREAD

**Issue by Stu75e** [celzero/rethink-app#1025]

**Comment by ignoramous** [comment]
This is already supported.

*Configure* -> *DNS* -> *Other* -> *Dns Proxy* -> "+" and add any IPv4 or IPv6 addresses there.

**Comment by ignoramous** [comment]
Closing. Please reopen if you think I misunderstood your query / feature request. Thanks.

**Comment by Stu75e** [comment]
Hello, unfortunately, I could not find out exactly what their names are by searching on Google, but I will send a few of them, I think you will understand.

Google  8.8.8.8    8.8.4.4

Couldflare 1.1.1.1     1.0.0.1

Yandex 77.88.8.8     77.88.8.1

**Comment by Stu75e** [comment]
You cannot put a dot between the numbers and write a second server like this program below

![Screenshot_20231019-094709_Rethink](https://github.com/celzero/rethink-app/assets/133971463/bba2ca45-999b-413b-b71e-6acebbd69ade)
![Screenshot_20231019-094857](https://github.com/celzero/rethink-app/assets/133971463/fdc9deb6-ce79-406a-9af4-49c9d25a0309)

**Comment by ignoramous** [comment]
> You cannot put a dot between the numbers and write a second server like this program below

Gotcha, but primary server is enough ;) I'll reopen this bug, but I don't see us adding a secondary server anytime soon, as in practice, it isn't really required.
