### ISSUE TITLE
Bypass universal apps resetting

### ISSUE THREAD

**Issue by das22** [celzero/rethink-app#1026]
Hi,

I'm running the v055 app on a Xiaomi device with MIUI 14/Android 13. It works brilliantly aside from one hiccup - the apps I define to bypass universal firewall rules (blocked when locked, unknown source, DNS bypassed and port 80 in my case) get forgotten/reset every now and then. For me these are 2 music and one communicator app and I have to re-enable the bypass for them every few hours/days (doesn't seem to be a regular interval). Interestingly the apps I set as blocked or isolated aren't forgotten. Is there any way to resolve this? 

Cheers!

PS. I also struggle with the app not auto-starting (e.g. after system restart or opening it) but I saw that reported already. Same story as for the others (e.g. always-on VPN setting does not help). Just mentioning it in case the 2 issues could be related somehow.

**Comment by ignoramous** [comment]
Thanks. We'll look into this on priority to see if there's something glaringly obvious going wrong. 

Btw, do you have a *Work Profile* setup on your Android (for dual apps / parallel space / privacy)?
