### ISSUE TITLE
Feature request: Show tcp request body in Android App

### ISSUE THREAD

**Issue by Zelakolase** [celzero/rethink-app#1027]
Title.

**Comment by ignoramous** [comment]
You mean, decrypt https? If so, that's #55 

If you mean, PCAP exported to a file, that's already supported. Go to *Configure* -> *Settings* -> *Packet capture* -> *Output to Downloads folder* to enable this.

**Comment by Zelakolase** [comment]
decryption of https and showing the request body of general tcp requests (http/dns/etc..)

**Comment by ignoramous** [comment]
In that case, please track #55
