### ISSUE TITLE
Ip & port rules enhanment

### ISSUE THREAD

**Issue by smexyy** [celzero/rethink-app#1034]
Hello, we need to add an option to import txt file or add an option to insert alot of ip rules at once.

Its very annoying to add ip rule one by one.

**Comment by ignoramous** [comment]
Agreed. Tracked here:
- #794 

Feel free to re-open in case I misunderstood the ask.

**Comment by smexyy** [comment]
Waiting for a year just to add the option to import IP addresses from text files is incredibly frustrating.

**Comment by ignoramous** [comment]
> Waiting for a year just to add the option to import IP addresses from text files is incredibly frustrating.

Well, it is not that we have been on a vacation for the entire year.

Eitherways, if you donate [$1500](https://svc.rethinkdns.com/r/sponsor) ([the cost of running RDNS for 1 month](https://forum.f-droid.org/t/24062)), we'll drop everything and implement this feature. Let me know (:
