### ISSUE TITLE
Pause and stop the app from notification bar.

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#104]
A user has asked for ability to pause or stop the app from the persistent  notification that's shown for the service.

Although this feature is redundant given "quick settings tile" that we inherited from Intra pretty much does the same thing.

Explore.

**Comment by amithm7** [comment]
This is quite handy, but the notification goes away too, currently; making it less functional than than the quick setting tile.

Would be better if it is a start / stop (pause) toggle, easier to get to than quick setting tile.

**Comment by ignoramous** [comment]
The notification goes away since the app doesn't need to run as a foreground service anymore (to run a VPN tunnel).

To keep the notification around _could_ be wasteful, but I can see how it improves the user experience. Any examples of apps that do this? NetGuard?

**Comment by amithm7** [comment]
Blokada does this (probably need to turn on a setting to keep alive the notification).

This helps in quickly toggling the ad-blocker, in case it breaks some website.

**Comment by ignoramous** [comment]
Gotcha. Not sure what Blokada does, but _pausing_ the app is likely what you're looking for (not _stop_); that is, the service runs but all connections are allowed (as if the firewall was _paused_).

#204 and #21

**Comment by ignoramous** [comment]
Impl in #354
