### ISSUE TITLE
Per app firewall rules.

### ISSUE THREAD

**Issue by MinekPo1** [celzero/rethink-app#1051]
I would like to override individual firewall rules for some apps, but have others apply.

As an example, I would like to allow messaging app A to make network requests in the background, but only when the device is unlocked, while having other apps be restricted to only making requests when in use.

**Comment by hussainmohd-a** [comment]
Thank you for reporting the issue. A similar issue is already present, and you can track it at #720. We are closing this issue and will update the progress in #720.
