### ISSUE TITLE
"Background" Firewall Rule

### ISSUE THREAD

**Issue by supsm** [celzero/rethink-app#1056]
RethinkDNS's "Block all apps when device is locked" and "Block any app not in use" universal rules are very helpful, but sometimes we want to make an exclusion to these rules for an app that we expect to run in the background. Currently, it seems the only option is to exclude the app from firewall **and DNS**, which could be undesirable. There should instead be an option to exclude apps from these two rules. Alternatively, "Background" could be an individual app rule instead of a universal rule.

**Comment by supsm** [comment]
I have just discovered that a "bypass universal" rule exists for apps. I still think it may be useful to have background network access as its own rule due to its importance.

**Comment by ignoramous** [comment]
Thanks.

> I have just discovered that a "bypass universal" rule exists for apps. I still think it may be useful to have background network access as its own rule due to its importance.

Yep, see: #720 (closing as dup, feel free to reopen in case I misunderstood your request). We intend to implement it once we complete other high priority tasks.
