### ISSUE TITLE
Error connecting to DNSCrypt server when using a custom server

### ISSUE THREAD

**Issue by TalOrenshtein** [celzero/rethink-app#1057]
When adding a custom server and trying to use it, I get the "Error connecting to DNSCrypt server" error, no matter what server. I tried few from the [official resolver page](https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md), nothing works. Even if they work on other platforms or apps.
For example, the server "dnscrypt.be"
sdns://AQcAAAAAAAAADzE5My4xOTEuMTg3LjEwNyAzWmXOT_I8k2BKJzxIJ_iYoXRQRWcR0Q1FFyrJWtvogxsyLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQuYmU
If there's a way to get a log file, let me know and I'll add mine.

**Comment by ignoramous** [comment]
> sdns://AQcAAAAAAAAADzE5My4xOTEuMTg3LjEwNyAzWmXOT_I8k2BKJzxIJ_iYoXRQRWcR0Q1FFyrJWtvogxsyLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQuYmU

From what I'm seeing, this server is down permanently.

Can you see if built-in AdGuard or Quad9 DNSCrypt endpoint works?

**Comment by TalOrenshtein** [comment]
> > sdns://AQcAAAAAAAAADzE5My4xOTEuMTg3LjEwNyAzWmXOT_I8k2BKJzxIJ_iYoXRQRWcR0Q1FFyrJWtvogxsyLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQuYmU
> 
> From what I'm seeing, this server is down permanently.
> 
> Can you see if built-in AdGuard or Quad9 DNSCrypt endpoint works?

Built in servers works when using them without relays. I'm using this server among others daily and gave said server as an example. 

Other examples :
- scaleway ams
`sdns://AQcAAAAAAAAADTUxLjE1LjEyMi4yNTAg6Q3ZfapcbHgiHKLF7QFoli0Ty1Vsz3RXs1RUbxUrwZAcMi5kbnNjcnlwdC1jZXJ0LnNjYWxld2F5LWFtcw `

- scaleway fr
`sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc`

- dnscrypt.pl
`sdns://AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjEyODoyMDUzIH9hfLgepVPSNMSbwnnHT3tUmAUNHb8RGv7mmWPGR6FpGzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5wbA`

No of them works, with or without relays. Each one of them works on my PC for example. As shown at my PC's DNSCRYPT log:
```
[2023-10-15 11:30:14] [NOTICE] -    68ms dnscrypt.be
[2023-10-15 11:30:14] [NOTICE] -    69ms scaleway-ams
[2023-10-15 11:30:15] [NOTICE] -    81ms scaleway-fr
[2023-10-15 11:30:15] [NOTICE] -    96ms dnscrypt.pl
```

I will try to add a built in server as a custom server to see if it works.

**Comment by TalOrenshtein** [comment]
So, I found a custom server that does work. So I'm not sure what's going on here

* dct-nl1: DNSCrypt | IPv4 only | Non-logging | Non-filtering | DNSSEC | Naaldwijk, Netherlands.

```sdns://AQcAAAAAAAAAEzIzLjEzNy4yNDkuMTE2Ojg0NDMgEWD0g0vsKFqwslGBKql8eTiu1RvK2dzZIxLfR7ctlAwXMi5kbnNjcnlwdC1jZXJ0LmRjdC1ubDE```

**Comment by ignoramous** [comment]
Thanks for your report. I will do my investigation once `v055b` is out and get back.

**Comment by ignoramous** [comment]
> dct-nl: `sdns://AQcAAAAAAAAAEzIzLjEzNy4yNDkuMTE2Ojg0NDMgEWD0g0vsKFqwslGBKql8eTiu1RvK2dzZIxLfR7ctlAwXMi5kbnNjcnlwdC1jZXJ0LmRjdC1ubDE`

doesn't return dnscrypt certs. Is this working with your dnscrypt client? If so, which one?

> cs-ro: `sdns://AQIAAAAAAAAADTE0Ni43MC42Ni4yMjcgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz`

this one returns certs (only over tcp and not udp) but doesn't respond to dnscrypt queries at all.

**Comment by ignoramous** [comment]
In [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b) the servers listed in this bug now work.

Thanks a lot for detailed bug report. Sorry it took this long to get to the bottom of it, even though the fix was entirely straight-forward.
