### ISSUE TITLE
 redirect/static list 

### ISSUE THREAD

**Issue by leao-nardo** [celzero/rethink-app#1060]
like theres blocklists , allowlist , denylist , to add a redirect/static list would be a good idea
. when the user add an adress it can default to localhost ::1 and can be set to custom adress..
because something break with the not found response but can work like that. to manually add to a redirect would fix those without needing to allow then. and many others use cases for this

**Comment by ignoramous** [comment]
Thanks; see: #316 

Closing as dup, please feel free to reopen if it isn't.
