### ISSUE TITLE
Wireless debugging when using WireGuard

### ISSUE THREAD

**Issue by cohesive-flight** [celzero/rethink-app#1061]
When I enable wireless debugging with an active WireGuard connection, the IP displayed is the WireGuard's private IP address (10.xxx.xxx.x) rather than the IP assigned to the device by my local network. I used to have this problem when using my VPN provider's native app, but I was able to fix this by excluding the "settings" system app through my provider's implementation of split tunneling. This method, however, does not work with Rethink. I tried enabling the "Do not route Private IPs" option and disabling the "Block all connections without VPN" system option, but that did not solve this. 

I did notice a small bug from doing this, however. The "Do not route Private IPs" option will be grayed out when enabling the "Block all connections without VPN" system option, but it'll still continue to be enabled. So any app that's not routed through WireGuard won't be able to access any private IPs, unless you use a domain that resolves to one (not sure how this works, but this occurred when using a private domain on my own local DNS resolver, which I used through System DNS), or you temporarily disable the "Block all connections without VPN" system option to disable it. It should probably automatically disable it when enabling the block, or leave it toggleable with a disclaimer.

**Comment by ignoramous** [comment]
> When I enable wireless debugging with an active WireGuard connection

To be clear, you mean wireless debugging with ADB ([ex](https://archive.is/FnrQO))?

> I used to have this problem when using my VPN provider's native app, but I was able to fix this by excluding the "settings" system app through my provider's implementation of split tunneling.

The equivalent for Rethink would be to *Exclude* the *Settings* app (from the homescreen, click *Apps* -> search for *Settings* -> tap on it -> tap on *Firewall rules for this app* -> *Exclude*). See if doing so works out?

> The "Do not route Private IPs" option will be grayed out when enabling the "Block all connections without VPN" system option, but it'll still continue to be enabled.

This is working as intended (: A few folks turn "Do not route Private IPs" ON to specifically block LAN connections with VPN in *Lockdown* ("Block connections without VPN"). I can see why that can be confusing... but VPN Lockdown itself is a power user feature, and so we kind of half expect folks to understand the implications of using it. You're right though, we should include some disclaimer to make it explicitly clear about its behaviour when in VPN *Lockdown* mode.
