### ISSUE TITLE
SEND_FAIL when switching networks

### ISSUE THREAD

**Issue by skibbipl** [celzero/rethink-app#1064]
So I have following setup: haproxy linked to a domain and redirecting requests to different services on my home server. One is AdGuardHome DNS server set in DOH mode. I'm using it in rethink DNS as a DNS server. Some time ago I did a reconfiguration on my DNS and set a split-brain setup. Basically when I'm on local network all requests to `mydns.domain.tld` are redirected to local IP (eg. 192.168.2.100) instead of my external IP. When I'm outside of my network all DNS requests are redirected to my external IP.
Since that change every time I change network from local to external or vice-versa rethink DNS stops working and I see in the logs `SEND_FAIL` errors. When I restart the connection everything works again. Do you know if this is a rethink DNS issue or perhaps my setup needs fixing?

**Comment by ignoramous** [comment]
> Since that change every time I change network from local to external or vice-versa rethink DNS stops working and I see in the logs SEND_FAIL errors.

For those `send_fail` entries, do you see short `0`ms to `3`ms round-trip time, or higher?

> When I restart the connection everything works again. Do you know if this is a rethink DNS issue or perhaps my setup needs fixing?

Can you see if tapping on the "refresh" button in top right-hand corner of *Configure* -> *DNS* UI also makes recovery?

This is likely a Rethink issue, but one Rethink is built to recover from. I'm surprised it doesn't pick up the new IPs on network changes.

Can you switch to "Verbose" in *Configure* -> *Settings* -> *Log Level*, then switch networks so `send_fail`s happen, and then email the "bug report" from *About* screen? Or, if you're technical enough, go through the output from `adb logcat | grep -iE "(dns:|doh:|wall:|alg:)"` for clues, or share that output with us?

**Comment by ignoramous** [comment]
Okay, I think we've fixed it: https://github.com/celzero/firestack/commit/a8cc0b2ee74e114919c6b196ecb1d5652f682b98 / https://github.com/celzero/firestack/commit/6e4cc95aaf1a4192db50db217579d327ee9259ee

Should be part of the next release `v055b` in a few days from now.

**Comment by ignoramous** [comment]
More fixes in `v055d`: https://github.com/celzero/firestack/commit/066e7e5758a938d167570dedd8183dd584d64303
