### ISSUE TITLE
Resolve Wireguard endpoints with user-preferred DNS as set in Rethink

### ISSUE THREAD

**Issue by iulko** [celzero/rethink-app#1069]
Please implement that the endpoint resolving for Wireguard goes thru Rethink DNS not directly thru system DNS so that we can keep our wireguard endpoint hostname private.

Wireguard-> Resolve DNS for endpoint.com -> DOH in Rethink

instead of

Wireguard->System DNS  for endpoint.com -> Unsecure DNS

**Comment by ignoramous** [comment]
I took a look at the code, but at first glance, it looks like we'd require to change upstream WireGuard  to achieve this, which is really out of scope of our project. I'll continue looking if there's a way to change this behaviour, though...

**Comment by iulko** [comment]
> I took a look at the code, but at first glance, it looks like we'd require to change upstream WireGuard to achieve this, which is really out of scope of our project. I'll continue looking if there's a way to change this behaviour, though...

What you mean by "upstream Wireguard"?

I had an idea that could help with #1013 and this issue

The endpoints with hostnames would beresolved by Rethinkdns and only than IP is passed to wireguard on connect/reconnect, this way you could check if IP changed and that would make Dynamic DNS also work.

rethink dns example.com resolve -> IP -> Sending IP to wireguard -> connecting
On reconnecting:
rethink dns example.com resolve -> IP -> Sending IP to wireguard -> connecting

The configs and all user side inputs would stay the same, only the app would know to not send endpoint directly to wireguard if its a hostname

What you think about this idea?

**Comment by ignoramous** [comment]
> What you think about this idea?

This seems like it *should* work, yes.

> What you mean by "upstream Wireguard"?

[wireguard-go](https://github.com/WireGuard/wireguard-go).

**Comment by iulko** [comment]
> > What you think about this idea?
> 
> This seems like it _should_ work, yes.

I hope it does, thanks for your time trying to make it work, this is two issues done with one stone ;)

**Comment by ignoramous** [comment]
Resolved with "Fallback DNS" (also Default DNS) which is always guaranteed to work unlike "user-preferred DNS". This is done so because, connectivity issues as reported from the field will be hard to debug (as we'll have to keep guessing if it was DNS that broke or something else).

Impl in v055b: https://github.com/celzero/rethink-app/releases/tag/v0.5.5b

**Comment by ignoramous** [comment]
> Does that mean that the wireguard endpoint is now ALWAYS resolved by fallback DNS? ( i understand your reasons)

Yes.

> If its "yes", could we have a DOH Cloudflare as an option in Fallback DNS?

Already present. `Rethink`, `Cloudflare`, and `Google` are all DoH "fallbacks". `None` is *System DNS*.
