### ISSUE TITLE
Blocklist activated without being selected

### ISSUE THREAD

**Issue by GrimPixel** [celzero/rethink-app#1079]
Sites on ParentalControl are blocked without selecting them.
It is on Android 10. Which clues do I need to provide?

**Comment by ignoramous** [comment]
Please share domain names where you saw this mismatch, and the blocklist URL.

Are you using *on-device blocklists* or *RDNS+*? If you can you copy paste the resulting URL here?

- For on-device blocklists, choose "Copy as RDNS+ URL"; then paste it here.
- For RDNS+, tap on the "edit" icon and click the "copy" button; then paste it here.
   - If you're using *RDNS+*, make sure to update to the latest blocklist version from *Configure* -> *DNS* -> *Rethink DNS* (and look for a green-coloured chip / button at the top right corner, then tap on it if it says *Check for updates* or *Update available*).

**Comment by GrimPixel** [comment]
Confusion cleared: RDNS was activated. This turned out to be a user interface problem: “Rules” applies to System DNS only; Rules for Rethink DNS are located at “Rethink DNS”.

**Comment by ignoramous** [comment]
Sorry, I still don't understand. I am missing some context here. *System DNS* does not have blocklists. There is either *on-device blocklists* or blocklists via *RDNS+*. 

Anyhow, I am closing this issue as you seem to indicate that it is longer one? If you feel this issue remains, please feel free to reopen the bug after making sure the blocklist updates did not fix this issue you're seeing. Thanks.

**Comment by GrimPixel** [comment]
OK. Let me explain my thought at the first glance of the settings: I saw there is something about blocklists, so I tapped on it and saw the list. Then I found those “System DNS”, “Other DNS”, “Rethink DNS”, so I assumed that the blocklist are the same for all the three options.

**Comment by ignoramous** [comment]
> Then I found those “System DNS”, “Other DNS”, “Rethink DNS”, so I assumed that the blocklist are the same for all the three options.

Your observation is correct: *on-device blocklists* (and other *domain* rules) apply to ALL DNSes (*System DNS*, *Other DNS*, *Rethink DNS*).

What's not clear is, is the original reported issue (`Sites on ParentalControl are blocked without selecting them`) an issue at all? If so, I don't really understand what the issue really is. If it isn't, then we're good :D

**Comment by GrimPixel** [comment]
You are right. It applies to all the three. I didn't know that there are additional blocklists for Rethink DNS, which I didn't notice. I thought that the only blocklists are those under “rules”.
