### ISSUE TITLE
Inconsistent state after editing rule

### ISSUE THREAD

**Issue by opk12** [celzero/rethink-app#1089]
For one specific app, I want to trust a domain that the app has not connected to, because I know from another phone that it will be needed. In the Universal rules section, per-app rules, there is not a `+` button (#1088) so I tried to **edit** a rule. But now the universal rule disagrees with the Apps section's settings.

* I opened the Apps section:
  * I set the app Matrix Element to Isolate.
  * I opened the settings for Element.
  * From the connection list, I trusted `vector.im` (tap the check mark to become blue).
* Then I opened the Universal rules section - Per-app rules - Domain rules.
  * I tapped on the pencil icon and changed `vector.im` to `scalar.vector.im`, then tapped to authorize.
  * (bug) The toast message said the domain was successfully **added**, instead it was actually modified, because `vector.im` was no more in the list.
* I returned to the App section's settings page of Element:
  * `vector.im` has a blue tick.
* (bug) So is vector.im now trusted (because blue tick) or not (because not listed in the Universal rules)?

**Comment by hussainmohd-a** [comment]
Fixed: 2ce2cf2
> (bug) The toast message said the domain was successfully added, instead it was actually modified, because vector.im was no more in the list.

Made numerous improvements in the Domain Manager for v055b, which fixed the bug described below. Please reopen the issue if you encounter it again.
>(bug) So is vector.im now trusted (because blue tick) or not (because not listed in the Universal rules)?
