### ISSUE TITLE
Wireguard Select Application Crashes with Mull

### ISSUE THREAD

**Issue by supsm** [celzero/rethink-app#1091]
For some reason there are two entries for the mull app in "Add/Remove Applications" in wireguard. Clicking either of them (or select all/none) causes the entire app (and accessibility service) to crash. I have not tried reinstalling either app because I do not wish to lose all my data, but I have tried multiple system restarts. 
![Screenshot_20231003-115304.png](https://github.com/celzero/rethink-app/assets/60897356/c6de3f65-5ef9-4a48-9342-b3a12f425116)

**Comment by supsm** [comment]
No other app experiences this issue, they can all be toggled. Also, it seems that Mull is still being proxied in this state.

**Comment by supsm** [comment]
The main app list is fine, there is only 1 Mull and I can allow or block it without issue

**Comment by supsm** [comment]
I reinstalled mull. There are now three copies. ![Screenshot_20231004-004035.png](https://github.com/celzero/rethink-app/assets/60897356/7646761f-3c74-48bc-9dcd-4a5521446ac2)

**Comment by hussainmohd-a** [comment]
Hi @supsm, could you please click on the refresh button at the top of the Add/Remove Apps screen, located right next to the search bar?

**Comment by supsm** [comment]
Hi, after a few more reinstalls (for unrelated reasons), the issue seems to have fixed itself. I'm pretty sure I did press that button a few times before and it didn't have any effect. Feel free to close this issue if you think it's a one-off.

**Comment by ignoramous** [comment]
> Feel free to close this issue if you think it's a one-off.

Rethink refreshes its app database periodically (typically every 3 hours, but could take longer). The *refresh* button in *Apps* UI is a way to trigger one pronto. 

At any rate, Rethink shouldn't crash. We'll take a look.

**Comment by supsm** [comment]
Thanks. I had this issue for quite a while (a few weeks at least), but fortunately now it's resolved somehow. I'm not sure how this issue is reproduced, but I think at least 1 reinstall is needed. I installed/uninstalled from within f-droid, not the system installer.

**Comment by hussainmohd-a** [comment]
Resolved duplicate entries in proxy-app mappings from v055e to v055i. Closing this issue, feel free to reopen this if you encounter this issue again.
