### ISSUE TITLE
v055a can't get blocklists : either not downloading (fdroid) or no option for it (play)

### ISSUE THREAD

**Issue by SodaFormulas** [celzero/rethink-app#1094]
Installed the latest version of the app on a Google Pixel 3 (Android 12).

With the F-Droid version : there's the red option to activate the blocklists, but when clicking on it the blue downloading blocklist button stays on loop and doesn't seem to download anything. I get the same behavior with the APK on Github.

With the PlayStore version (through Aurora), that red line about the blocklists isn't even there and so I can't add blocklists at all.

Edit : I managed to download the blocklist with the f-Droid version but to do it the VPN/DNS must not be activated first...

![F-droid/Github version](https://github.com/celzero/rethink-app/assets/13819982/c0f51492-6af7-423a-87b1-6dc665d45e14)

![Google Play version](https://github.com/celzero/rethink-app/assets/13819982/9d6e3980-4c47-4a79-a4b4-8102ab4faf5e)

**Comment by ignoramous** [comment]
> Edit : I managed to download the blocklist with the f-Droid version but to do it the VPN/DNS must not be activated first...

Did you have VPN in *lockdown* aka "Block connections without VPN"? If so, see https://github.com/celzero/rethink-app/issues/983

**Comment by SodaFormulas** [comment]
> Did you have VPN in lockdown aka "Block connections without VPN"?

Nope. I just clicked on the big start button immediatly after launching the app for the first time. I tried using another DNS, it was the same. After installing 3 different versions I tried to download the lists first and voilà.

**Comment by ItsIgnacioPortal** [comment]
On v055h I was able to download the blocklists after enabling the "Use in-app downloader" setting.

**Comment by ignoramous** [comment]
Closing as in-app downloader worked. We need to improve the UI around downloads so the users won't be in the dark about just why these are erroring out and what remedial actions to take for different errors: #1435
