### ISSUE TITLE
dnsleak.com shows vpn dns as well as custom dns

### ISSUE THREAD

**Issue by anxiouslelimo** [celzero/rethink-app#1095]
I have rethink app configured with protonvpn wireguard config and custom dns in mull browser set as max.rethinkdns.com. After enabling wireguard with mull, dnsleaktest.com gives two dns entries. One is max.rethinkdns.com and the other protonvpn dns. This doesn't happen all the time. So is there a dns leak?

**Comment by ignoramous** [comment]
> After enabling wireguard with mull, dnsleaktest.com gives two dns entries. One is max.rethinkdns.com and the other protonvpn dns.

Do you have the `Prevent DNS leaks` option turned ON in *Configure* -> *DNS*? If not, turn it ON.

Also, is "Show website icon in DNS logs" turned ON? If so, turn it OFF.

Those two settings confuse `dnsleaktest.com`, which tbh isn't suited to test "leaks" for encrypted protocols like DoH / DoT / DNSCrypt ([ref](https://archive.is/04UKD)).

**Comment by ignoramous** [comment]
Strange, let's see if this has automagically fixed in `v055b` (almost ready for a release), because we've changed a tonne in the network engine.

**Comment by ignoramous** [comment]
(we don't see leaks in our testing in `v055f`. closing. feel free to reopen)
