### ISSUE TITLE
Quad9 Dnscrypt + Relays = No Internet

### ISSUE THREAD

**Issue by RedSteel-1** [celzero/rethink-app#1099]
It's impossible to use Dnscrypt with Relays.

Steps:
- DNS -> Dnscrypt -> choose Quad9 Security -> press "Relays" -> choose all or some relays -> to go the main screen.
- wait 1 minute
- see "No Internet"
- try to open a webpage in the browser: doesn't open.
- stop and start Rethink -> see "No Internet" again.

Then:
- Remove the selection for all Relays and keep Dnscrypt Quad9 Security without Relays, then stop-start Rethink.
- Rethink now says "Protected", and browser can now load webpages.

**Comment by ignoramous** [comment]
Quad9 doesn't *seem* to support Relays, unfortunately. Try other DNSCrypt endpoints?

**Comment by ignoramous** [comment]
The included endpoints are chosen because they're deployed world wide and not regional. I don't think there are very many dnscrypt providers that have servers all over the globe.

I'm closing this issue as there's nothing more we can do wrt Quad9 not supporting Relays. You can however consider [contacting them](https://quad9.net/support/contact).

**Comment by ignoramous** [comment]
Quad9 is not used as Relay but as Target.

And I don't see how Quad9 says they support it when they clearly don't. The issue with their deployment is they are probably rejecting larger UDP packets. Can't be sure.

I'll reopen this issue, but we are also unsure what to do to make Quad9 work (when the other targets / resolvers work just fine).

**Comment by ignoramous** [comment]
We've fixed this (Quad9 servers are apparently unhappy with the anti-censorship related TCP manipulation Rethink does; but we've modified it and it looks like Quad9 is happy with it). Thanks for the bug report and following up with Quad9 on our behalf.

This bug would have resolved way sooner if only Quad9 had helped us with some logs (but I understand why they wouldn't)...

Please verify once `v055o` is out (in a day or two). Thanks.
