### ISSUE TITLE
Split tunnel for H1 Connect & Socks5 tunnels

### ISSUE THREAD

**Issue by RedSteel-1** [celzero/rethink-app#1105]
Currently,
one can choose to either forward only TCP connections of selected programs (via the "Proxy -> Orbot" settings),
or route all connections of all programs without the ability to select the programs (via the "Proxy -> Other" settings).

Could the ability to route All connections of Selected programs be added?

This could be an option in the "Proxy -> Other" settings, to route either all programs, or to route programs from the list (the list similar to the one "Proxy -> Orbot" settings).

**Comment by ignoramous** [comment]
Believe we're already implementing this, but unsure if it will land in `v055b`. Perhaps in a later release.

**Comment by ignoramous** [comment]
see also: #995

**Comment by ignoramous** [comment]
Please follow impl at
- #1126
