### ISSUE TITLE
RDNS Error

### ISSUE THREAD

**Issue by HKADSV** [celzero/rethink-app#1114]
When using rdns the app says no internet, after a restart, force stop & clear cache it changes to DNS error.
 
DNS Tab shows a latency of around 50ms.

**Comment by HKADSV** [comment]
Also not working on a second device. 
DNS down?

**Comment by Doc-4** [comment]
I have the same issue under RDNS Max default server. 
Immediate "no internet" with that configuration. Connecting to the default sky one works.

**Comment by tomara-x** [comment]
hello friends! same issue here

**Comment by Cabbagejinx** [comment]
Same problem here.
I had "Prevent DNS leaks" in the DNS settings and "Block when DNS is bypassed" in the firewall on, so every connection was either getting blocked or proxied. Saw that none of the Max resolvers were working, and all of them gave "No internet". Looks like all the Max resolvers are down.

**Comment by olivlefou** [comment]
Same issue

To resolve :

Use DNSCrypt Adguard
![Screenshot_2023-10-16-11-41-35-455_com celzero bravedns](https://github.com/celzero/rethink-app/assets/148057547/bda40cfc-9f7c-4373-a93e-ab0722e3f2ec)

**Comment by muellerto** [comment]
Yes, this has been an issue since today in the early morning also here. I couldn't connect the first time at about 4:00 UTC and never since then.

**Comment by ignoramous** [comment]
Hi all,

The automatic cert renewal failed. We renewed the certs a few moments ago and things are back up and working though the traffic has been significantly reduced (I imagine from folks moving to other resolvers).

I am terribly sorry that this happened. It was an embarrassing mistake.

We take good care in keeping all our servers up and running but this time and failed to notice as the email alarming us of traffic drops were sent to spam. I'll work to improve our alarming and monitoring.

I almost exclusively use `max` but switched to `sky` to test a few new features and forgot to switch back, else I'd have noticed this error myself. Thankfully, `sky`, which gets 75% of the total traffic, was unaffected.

Do feel free to email me `mz` at `celzero` dot `com` in case you notice such outages.
