### ISSUE TITLE
Wireguard's PersistentKeepalive option doesn't work

### ISSUE THREAD

**Issue by PetrVladimirov** [celzero/rethink-app#1123]
Despite having PersistentKeepalive set (e.g. to '120'), rethink wireguard client doesn't send keepalive packets.

It can be easily observable on the wireguard server side: while other (non-rethink wg clients) show the latest handshake every scheduled period (e.g. 120 seconds), for the rethink wg client the latest handshake timestamp is actually the latest attempt of the phone app to traffic data through the wg tunnel.

So on unstable networks it causes a delay to start routing the data through the rethink wg tunnel.

**Comment by ignoramous** [comment]
Thanks. For keep-alives, Rethink defers to the official WireGuard implementation. There was an active issue where keep-alives cost a considerable battery drain on smartphones, so unsure if upstream has disabled it in lieu of that. What behaviour wrt keep-alives do you observe with the latest Android WireGuard client?

Btw, there's another unrelated issue why WireGuard connections drop (WireGuard disables "roaming" on smartphones, that is, moving from one network to another needs a restart of the the official WireGuard client for Android, unlike on other platforms) #1097, but we've introduced our own fixes for this in `v055b` (which is yet to be released).

**Comment by ignoramous** [comment]
@PetrVladimirov `v055b` is up on [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b) / [Website](https://rethinkdns.com/download) (for Play Store / F-Droid, you'd have to wait a few more days as the version is pending review). Please do check if `v055b` improved WireGuard connectivity issues you were seeing.

**Comment by PetrVladimirov** [comment]
@ignoramous thank you so much for your work! Sure, I'll try to do it promptly as soon as I get the new version installed.

**Comment by PetrVladimirov** [comment]
@ignoramous, I've checked and it seems that the `Persistent keepalive` option is still not respected by Rethink WG. 

On the server side "Handshake" timestamp is sometimes updated, but with much bigger intervals than it should be as per the configured `Persistent keepalive` option on the Rethink side. E.g. every 5-10 minutes instead of 30, 60, 90, 120 seconds I set in the Rethink WG-tunnel. Probably these updates happen because of an app push or from some other (?) keepalive approaches.

The WG-tunnel itself shows its status as "Idle" and comment like "Active since 12 min ago" despite having keepalive set to 60, 90 or 120.

Just in case, it is not written anywhere in Rethink WG GUI, but I believe that Rethink's `Persistent keepalive` option is in seconds (as per the WG standard).

**Comment by ignoramous** [comment]
WireGuard's `KeepAlive` and `Handshake` are two different things (as far as I can tell).

> The WG-tunnel itself shows its status as "Idle" 

*Idle* in Rethink denotes whether actual *data* is being sent, and does not bother itself with *control* messages (such as `KeepAlive` or `Handshake` packets).

> Just in case, it is not written anywhere in Rethink WG GUI, but I assume that Rethink's Persistent keepalive

Yes, it is in seconds. We should probably show that in the UI somewhere.

**Comment by ignoramous** [comment]
Rethink since `v055n` leverages *KeepAlive* packets to detect *responsive* tunnel to "load balance" among multiple *active* "Always-on" WireGuard configs, and it does work as expected.

I'm closing this issue in light of that. Please feel free to reopen in case you find *KeepAlive* packets are never sent in the scenarios you're testing for. Thanks.
