### ISSUE TITLE
Whitelist widget truncates long titles 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#113]
![screenshot](https://user-images.githubusercontent.com/852289/96485802-4d68c300-125a-11eb-9a94-d70cc8bd4966.jpg)

See image.

Whitelist widget is shown form two screens in v05x:

1. Universal Firewall.

2. App Settings.

**Comment by ignoramous** [comment]
![Screenshot_20201018-013344.jpg](https://user-images.githubusercontent.com/852289/96487921-e697d980-125a-11eb-9047-1fa74200107f.jpg)

**Comment by hussainmohd-a** [comment]
Removing dialog now will have ellipsis if the app name is more than 15 characters. The color of the textview (whitelisted apps) is changed to #BDBDBD
