### ISSUE TITLE
Custom rule doesn't apply unless I turn Rethink off-on or switch DNS

### ISSUE THREAD

**Issue by sinjoe** [celzero/rethink-app#1133]
Adding custom rules doesn't apply unless I turn Rethink app off-on or switch other DNS then back to Rethink.
Example:
- open brave, visit blocked site, stop  brave completely
- add trusted universal rule
- open brave, and site still being blocked
- switch DNS to Quad9 then back to Rethink or turn Rethink app off&on
- open brave, site isn't being block anymore

Refrehing DNS, Re-download blocklist, turn network (wifi/mobile data) off&on doesn't fix it.

I forgot how it works before.
But wasn't it like:
- open brave, visit blocked site, completely stop brave
- add trusted universal rule
- open brave, site is not block anymore

I might misremember how it actually works.

I remember seeing issue thread, explaining how universal block/trust rule works. But can't seem to find it.

**Comment by ignoramous** [comment]
> open brave, and site still being blocked

There's a 15s timeout before *Android* (not Rethink) forgets the blocked domain (which has now been trusted / allowed). Can you confirm if that's not the case?

**Comment by ignoramous** [comment]
We could reduce it to 5s or provide a knob for this. But, reducing these timeouts may be inefficient since the usecase of trusting a blocked domain is not the common usecase (as in, most blocked domains remain blocked for eternity).

**Comment by ignoramous** [comment]
>  "added custom domain rules will take effect after 15s."

This makes sense.

> Although, a knob to manually refresh custom rules would be great too.

The caches within Rethink aren't the problem; they *refresh* immediately. It is the caches maintained by Android which are, and unfortunately, there's no API (not that I know of) to inform Android to flush / invalidate them (which is okay, because it is an absurd thing to have an API for ;)

**Comment by hussainmohd-a** [comment]
Closing as not an issue.
