### ISSUE TITLE
Pause in lockdown mode

### ISSUE THREAD

**Issue by iulko** [celzero/rethink-app#1134]
Pause in lockdown mode don't work, propably because the way the app pause is by bypassing the VPN for all apps which is not possible in lockdown mode. 

Could we have a pause mode in lockdown also by "allow" for all apps? Is not the same thing, but close enaught

**Comment by ignoramous** [comment]
*VPN Lockdown* is enforced by Android as "any app bypassing an active VPN will have all its internet connection dropped". *Pausing* Rethink is those apps bypassing an active VPN; and hence dropped connections. Nothing that we could do, as an app, that'll change Android's behaviour. In fact, if anything, the current behaviour is perfectly valid and secure.

**Comment by iulko** [comment]
Well that was my point that to change from bypassing to "allow" all apps in pause mode.
Same as going to app list and Allowing all apps manually, would work differently for VPN Lockdown in this way.

Pressing Pause in Lockdown mode -> App is changing all apps to "Allow" -> Pause stop -> all apps back to using app list Allow/Block etc

**Comment by ignoramous** [comment]
Gotcha. Thanks. Sounds like something we can implement.

**Comment by p-f-w** [comment]
But is possible to bypass "always_on_vpn_lockdown" by set apps in  "always_on_vpn_lockdown_whitelist", active when vpn is down, i have yesterday tested it.

(OT: RethinkDNS lost set system dns every time short after start, but after stop the whitelistening app can work with url, not only with ip as RethinkDNS, after restart short time is it possible ti refreh the browser with preset Url …)

**Comment by ignoramous** [comment]
> But is possible to bypass "always_on_vpn_lockdown" by set apps in "always_on_vpn_lockdown_whitelist", active when vpn is down, i have yesterday tested it.

See #224

**Comment by ignoramous** [comment]
Impl in [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b): https://github.com/celzero/rethink-app/commit/cfbc4ee6618a3699b38980b2977331b44755aeb5

https://github.com/celzero/rethink-app/blob/main/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L329-L332
