### ISSUE TITLE
Notification Isn't Persistent

### ISSUE THREAD

**Issue by ironveil** [celzero/rethink-app#1136]
When Rethink is active, there is an option to add a notification where I can easily toggle Rethink on and off. However, this notification isn't persistent and can easily be swiped away. Maybe there should be a toggle to make the notification persistent?

**Comment by iulko** [comment]
This should only be an option, I am happy with the fact is not persistent, other VPN have persistent ones and is annoying

**Comment by ignoramous** [comment]
Nice. You could, if you want to, consider sending us a pull-request (with a screenshot of how it looks, if possible)? No pressure.

**Comment by ironveil** [comment]
> Nice. You could, if you want to, consider sending us a pull-request (with a screenshot of how it looks, if possible)? No pressure.

Added one to #1139
