### ISSUE TITLE
Add System Components as a Firewall category

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#114]
even though it remains unknown what happens when system components (`uid` outside the application range) are firewalled (or can they bypass a VPN network at-will?), users can inadvertently firewall them from the Network Monitor screen's running logs.

If those logs are cleared for some reason, then the user has no way to unblock a system component until a new network log appears. Not a good experience, especially when the user may really really want to unblock such components blocked by mistake or whatever.

Ref this for `uid`s outside of the app-range: [codesearch/android/platform/system/core/libcutils/include/private/android_filesystem_config.h](https://cs.android.com/android/platform/superproject/+/master:system/core/libcutils/include/private/android_filesystem_config.h)

**Comment by hussainmohd-a** [comment]
Apps which are part of APP_START(10000) to APP_END(19999) are added in the system components. Need to figure out a way on adding the applications which are part of core components like GPS/WiFi/RADIO/System/Camera/Audio.
