### ISSUE TITLE
rethink dns is down?

### ISSUE THREAD

**Issue by sinjoe** [celzero/rethink-app#1144]
![Screenshot_2023-11-18-23-47-31-41](https://github.com/celzero/rethink-app/assets/141518184/ceb8892f-1e99-4c56-9f09-bf4cad853e42)
It says dns is failling, when trying to check for filter update, it says "something went wrong"

When trying to access filter to check on sky.rethinkdns there's this error message
" This website has been temporarily rate limited

You cannot access this site because the owner has reached their plan limits. Check back later once traffic has gone down."

**Comment by ignoramous** [comment]
Yes:

```
sky.rethinkdns.com, hosted on Cloudflare, is down due to payment issues. We are unable to clear the dues. We're in touch with Cloudflare support to see why these payments won't go through.

As a mitigation, we're redirecting ALL traffic to our servers on Fly.

If you're using the Rethink app, please manually switch to using max.rethinkdns.com.

Apologies for the outage but we're so helpless.
```

https://www.reddit.com/r/rethinkdns/comments/17y8pg8/skyrethinkdnscom_down_as_payments_fail/

**Comment by A20N** [comment]
Unfortunately I also have no internet when connecting to the max DNS. Maybe I'm doing something wrong, but it is correct/enough to switch from sky to max right?

**Comment by ignoramous** [comment]
> ok noted, thanks. Should I close this issue?

I'll leave it open until we get a resolution on this from Cloudflare.

> Maybe I'm doing something wrong, but it is correct/enough to switch from sky to max right?

In the app? Yes, it should be enough. Though, Fly has long had problems dealing with the amount of traffic of our resolvers and they have never fully rectified it. If you're in one of the regions where their load balancer is dropping connections, that'd explain what you're seeing. Such region-specific connectivity issues is the main reason we recommend Sky over Max.

**Comment by limbusdev** [comment]
Even with max.rethinkdns.com downloading blocklists is impossible. Tapping the button simply does nothing.

**Comment by ignoramous** [comment]
Unfortunately, since blocklists are also on Cloudflare, there's no way to get them.

Hopefully, we get things up and running by today or tomorrow. If not, I'm going to have to look for alternatives.

**Comment by limbusdev** [comment]
There should be at least some feedback.
