### ISSUE TITLE
Plead add "specialAndroidAccounts" like AFWall+ or NetGuard

### ISSUE THREAD

**Issue by p-f-w** [celzero/rethink-app#1148]
https://github.com/search?q=repo%3Aukanth%2Fafwall%20specialAndroidAccounts&type=code

or

https://github.com/search?q=repo%3AM66B%2FNetGuard%20%22%2F%2F%20Add%20root%22&type=code

there are some connections were nice would be able to block

(root“ UID 0,
„DNS daemon“ UID 1051,
„android dns“,
„Keiner“ UID 9999 „nobody“,
„Medienserver“ UID 1013 „android.media“, „MultiCastDNSResponder“ UID 1020 „android.multicast“,
„GPS daemon“ UID 1021 „android.gps“)

only "root", "DNS-Daemon", "MultiCastDNSResponder" and GPS daemon shows here in NetGuard some or many connections

I think, you know the "app"  "com.google.android.trichromelibrary" with changing her UID on every update? Is not listed in apps, but notify installation with UID in NetGuard (only sometimes(?)). Per mdm i have seen also deinstallation one times. It is possible to add and set rules for this "app"?

**Comment by p-f-w** [comment]
sorry, can't edit here under android, topis should beginning with "Please …

The Question to "com.google.android.trichromelibrary" is related to the topic but further off topic

**Comment by ignoramous** [comment]
These already are accounted for in Rethink. You'd see them in the "Apps" list only if these "specialAndroidAccounts" send ANY outgoing internet request. Otherwise, they are not shown. Some examples are, MDNSR, GPS, DNS, ANDROID etc;

If this isn't the case, please reopen this bug.
