### ISSUE TITLE
local blocklists - how to enable?

### ISSUE THREAD

**Issue by stilsch** [celzero/rethink-app#1151]
Hi privacy-freaks,
I tried to find the option to enable the local DNS blocklists in v055a like proposed at least on a screenshot https://rethinkdns.com/

![grafik](https://github.com/celzero/rethink-app/assets/3663262/95517af5-8cd4-443a-8686-53d39701aa2c)

...but simply could not find the option to do so. 

Was it removed in v055a or I'am to dump to find?

**Comment by limbusdev** [comment]
It is somewhat hidden. Go to Configure > DNS > System DNS > Local Blocklists > Click "Deactivated".

Its currently not working, though. The Server is not available. Clicking the download button shows no feedback at all.

**Comment by limbusdev** [comment]
![Screenshot_20231120-171640_1_1](https://github.com/celzero/rethink-app/assets/6540152/f4995bfb-9251-4ebe-8360-49250ec71324)

Strange. For me it's there

**Comment by stilsch** [comment]
I've uninstalled the version that came with the Google Play Store and reinstalled it via FDroid - now the option is available.
I think it should be mentioned somewhere that the versions shipped via different stores have different features.

**Comment by NatoBoram** [comment]
> The Server is not available. Clicking the download button shows no feedback at all.

… Oh. I guess it's a very bad time to discover this app. I guess I'll just uninstall and try again in a few days/months?

**Comment by stilsch** [comment]
> > The Server is not available. Clicking the download button shows no feedback at all.
> 
> … Oh. I guess it's a very bad time to discover this app. I guess I'll just uninstall and try again in a few days/months?

coming from Netguard I am very happy. 
Also - this app has a really huge feature set (firewall, DNS, logging, VPN, Proxy, filtering,...) and an even broader use-cases I never seen in such an app before - its understandable that not everything can work from the start.

Kudos to the developers and don't stop - Its a great app I don't what to miss anymore!

**Comment by NatoBoram** [comment]
Sure, I'm okay with that, I just said it was a bad timing for me.

**Comment by ignoramous** [comment]
> Sure, I'm okay with that, I just said it was a bad timing for me.

Yep, and a very bad time for us! The service hosted on Cloudflare has been down for 6 days now due to no fault of our own. We're already thinking about moving out, but it won't be easy (as code changes needed are vast)...

**Comment by NatoBoram** [comment]
> (as code changes needed are vast)

Oh no

Best of luck with that!

**Comment by limbusdev** [comment]
> > Sure, I'm okay with that, I just said it was a bad timing for me.
> 
> Yep, and a very bad time for us! The service hosted on Cloudflare has been down for 6 days now due to no fault of our own. We're already thinking about moving out, but it won't be easy (as code changes needed are vast)...

Could you at least add a mirror for local blocklists? Even when the DNS server is down this could still be useful - that means, if we are able to download them ^^"
