### ISSUE TITLE
Backup format

### ISSUE THREAD

**Issue by anpic** [celzero/rethink-app#1161]
Why is the binary format chosen for backup settings?
Are you planning to implement another format like JSON so that we can edit some settings before transferring to other devices?

**Comment by ignoramous** [comment]
> Why is the binary format chosen for backup settings?

Believe it is plain sqlite format. You'd be able to view contents with in any sqlite3-compatible tool.

> Are you planning to implement another format like JSON 

Not at this time. Believe the sqlite3 format is nice and universal already. Do you see additional benefits with JSON?

**Comment by anpic** [comment]
> Believe it is plain sqlite format

Oh, I'm sorry :)
This is not at all obvious by extension ;)

**Comment by anpic** [comment]
> Do you see additional benefits with JSON?

None other than the ability to edit even in a text editor

**Comment by ignoramous** [comment]
That's a niche usecase. Don't think we want to support it given we'd have to convert possibly 100k+ items to json on device. Also unlikely that text editors on phones can open such large files. If we are going to open these files on a PC, well sqlite is even better than json to view / update the contents.

I'm closing this bug, but if you disagree with what I mention above, feel free to reopen.

**Comment by anpic** [comment]
> I'm closing this bug

I didn't say it was a bug, just a suggestion :)

**Comment by ignoramous** [comment]
> I didn't say it was a bug, just a suggestion :)

See:

- #1470
