### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [celzero/rethink-app#1169]
Add material themed icon

**Comment by ignoramous** [comment]
Who's going to design one for us? we aren't designers. If you can or know someone who would contribute voluntarily, please send help. (:

btw, would this be a dup of #953?

**Comment by ignoramous** [comment]
Then... I don't understand what "material icon" means. Can you link to Google's documentation or some such

**Comment by ayaen** [comment]
actually ended up here to see where the material icon thing was being tracked and wow @saltsoftdrink you came off sounding a bit bossy dont you think? anyways glad that its not closed and someone is tracking it.

**Comment by ayaen** [comment]
And by the way the link you sent is totally unrelated. @ignoramous I looked into the repo and there are only pngs for launcher icon so we will need to have [adaptive icons]https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) . The app icon is quite nice already and it should look great in material you.
