### ISSUE TITLE
Android WebView Update force stops BraveDNS v051

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#117]
A user has written to us that whenever webview updates, BraveDNS app is force-closed.

This is likely related to the recently introduced webview related changes in the app to show blocklist configurations.

**Comment by hussainmohd-a** [comment]
Now the webview errors are handled while creating the activity and the activity is started based on the changes. Testing in progress with various devices.

**Comment by ignoramous** [comment]
This still happens in v053.

```
The Android System WebView is still interfering with the background operation of RethinkDNS. Is there any success in trying to stop this problem? I just updated the Android System WebView and it stopped RethinkDNS even with the "VPN always on" feature enabled. And, it doesn't restart rethinkDNS work until I open the app and it instantly reconnects.
```

**Comment by ignoramous** [comment]
Tested this on my device. Still happens in `v053c`.

Moving just the webview to its own process prevents this: https://archive.is/osP0J

Looks like a relatively straightforward change: https://archive.is/hraw8

**Comment by ignoramous** [comment]
[androidx.webkit](https://developer.android.com/reference/androidx/webkit/package-summary) package looks enticing.

**Comment by ignoramous** [comment]
webview has been removed from the app in #380 

release `v053i` (1 to 2 week from now? Earlier than that?)
