### ISSUE TITLE
Version label disparity between github and f-droid builds

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1172]
A user writes,

> Is there a difference between the github and fdroid app?
>
> On github the latest app version is labeled as v0.5.5a, whereas on fdroid it is v055a. It is also v055a on the play store too.

need to ensure such disparities don't manifest in final builds.

**Comment by hussainmohd-a** [comment]
Now the label will use a common build version instead of fetching from strings.xml https://github.com/celzero/rethink-app/issues/1032
