### ISSUE TITLE
When click pause the countdown begins from 23h15

### ISSUE THREAD

**Issue by shifoc** [celzero/rethink-app#1173]
![Screenshot_20231226_013352_Rethink.png](https://github.com/celzero/rethink-app/assets/32818143/62dbd9e6-8765-40be-b2d3-42bbdd0f49e3)

**Comment by ignoramous** [comment]
Sounds wierd. The default is 15mins. Will take a look. What version are you using? Check the bottom of the "About" UI in the app.

**Comment by shifoc** [comment]
> Sounds wierd. The default is 15mins. Will take a look. What version are you using? Check the bottom of the "About" UI in the app.

V055a

**Comment by ignoramous** [comment]
The code is erroneously treating countdown timer as date/time and hence what you're seeing is really some gross misinterpretation of the countdown (complete with timezones and all).

https://github.com/celzero/rethink-app/blob/48f1f7b66d47e108ee58481a7c2260c1f315d328/app/src/full/java/com/celzero/bravedns/util/UIUtils.kt#L1030L107

We've fixed this for the next version, `v055b`. Thanks for the bug report! I wonder why others hadn't seen it. I guess `pause` isn't a popular feature.

**Comment by shifoc** [comment]
Hahaha thank you. I reported it years ago by email as well, glad it was fixed

**Comment by ignoramous** [comment]
Fixed in [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b): https://github.com/celzero/rethink-app/commit/66e42a6fdb7ea227da20002c5ac242f4981e9018
