### ISSUE TITLE
Android 14/One Ui 6: Apps not receiving internet unless opened 

### ISSUE THREAD

**Issue by shifoc** [celzero/rethink-app#1174]
Since I updated to android 14, apps are no longer receiving internet connection unless I open the app. Even apps that bypass firewall and dns have the same issue.

**Comment by ignoramous** [comment]
Yes, this is related to #1115 

Can you disable *Advanced DNS filtering* from *Configure* -> *DNS* and see if things then recover?

**Comment by shifoc** [comment]
> Yes, this seems related to #1115 which we have fixed in `v055b` (unreleased).
> 
> Can you disable *Advanced DNS filtering* from *Configure* -> *DNS* and see if things then recover?

It seems to have worked

**Comment by ignoramous** [comment]
Closing this as dup of #1115 (please let feel free to reopen if this issue is *not* fixed in the upcoming release v055b when it launches *after* enabling *Advanced DNS filtering*).
