### ISSUE TITLE
Selecting and unselecting an on-device blocklist is selecting other blocklists as well

### ISSUE THREAD

**Issue by shifoc** [celzero/rethink-app#1175]
https://github.com/celzero/rethink-app/assets/32818143/e1e3dde7-90a9-413d-adba-15f42f8f0689

**Comment by shifoc** [comment]
I am not sure if it's a bug or there are common blocklists but I thought I should report it

**Comment by ignoramous** [comment]
If "Malware" is a superset of "Spam" and "Spyware" blocklists, then they're expected to be selected automatically, and that's what is likely happening.

Will verify and get back.

**Comment by hussainmohd-a** [comment]
Some lists are common to the simple UI. When these lists are selected, the other list will be enabled automatically. In this case, Malware is a superset of both Spam and Spyware.

**Comment by ignoramous** [comment]
looks like it is working as intended. The gist is, the scam and spam group of lists are *subset* of malware group of lists.
