### ISSUE TITLE
Clicking on "info" icon in DNSCrypt screen shows a delete dialog instead

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#118]
When a custom added DNSCrypt is connected to, the delete icon changes to info icon.

But the behaviour doesn't change as tapping on info icon still shows the delete dialog instead.

![Screenshot_20201021-103138.jpg](https://user-images.githubusercontent.com/852289/96745103-651f8300-13e3-11eb-8b76-cbc514152b94.jpg)

**Comment by hussainmohd-a** [comment]
The dialog now will classify the delete and info button. Will show appropriate dialog for both. Fixed.
