### ISSUE TITLE
simplex.chat domains blocked

### ISSUE THREAD

**Issue by epoberezkin** [celzero/rethink-app#1183]
Hi!

One of our users reported that simplex.im domains we use for preset servers in SimpleX Chat (https://simplex.chat) are blocked in rethinkDNS app.

Can you please let me know why?

Thank you!

**Comment by ignoramous** [comment]
You can check the blocklists here: https://rethinkdns.com/search?q=simplex.chat

Closing since Rethink doesn't curate blocklists nor whitelist/allowlist third-party domains. Feel free to reopen this bug in case you think otherwise.

(big fan of your work, epoberezkin)

**Comment by epoberezkin** [comment]
> Users can add any domain to the allowlist / whitelist themselves.

Yep, but they usually just use the defaults...

Anyway, I've submitted the issue to the blocklists, closing here :)

Thank you, you have a great project here.

**Comment by ignoramous** [comment]
Thanks.

> I would appreciate if you consider not using any blocklists that block top level TLDs

None of these lists that block TLDs are applied by default. A user has to manually select them / these are opt-in. And when domains are blocked, Rethink also informs the user which lists blocked them, and lets users to individually allowlist/whitelist domains and TLDs.

**Comment by epoberezkin** [comment]
> None of these lists that block TLDs are applied by default.

That's good to know, thank you.

> And when domains are blocked, Rethink also informs the user which lists blocked them, and lets users to individually allowlist/whitelist domains and TLDs.

Yes, that's how I learnt about it :)
Anyway, thank you for understanding.
