### ISSUE TITLE
Can't Play Youtube Videos (Android)

### ISSUE THREAD

**Issue by luckygitt** [celzero/rethink-app#1184]
I am a new user and have been having fun(!) playing with the settings but this has totally stumped me after hours of analysis!

My previous set-up: Android phone, official Wireguard (always on) and Next DNS (Private DNS)
My current set-up: Rethink, no Apps blocked, everything proxied through the same Wireguard server, NextDNS,

However, Youtbe videos will not play (or stop after a few seconds, Firefox browser, also tried Mull)
I tried a different DNS server (Rethink, Cloudfare), so its not my DNS settings.
I tried a different Wireguard server, so it's not that.

Any ideas, is this a bug?
The only thing I see is a grey line to the left of the browser app (Logs > Network) but there is no real explanation of what this means.

Thanks.

**Comment by ignoramous** [comment]
As a workaround, you can "Exclude" the YouTube app.

The issue you're facing does sound strange. A few questions:
1. Does the YouTube app work without Rethink (as in, is it censored)?
2. Does YouTube work without WireGuard (when WireGuard is OFF but Rethink is still enabled)?
3. Make sure YouTube isn't "blocked". You can determine this from "Apps" screen (search for YouTube and tap on it. The resulting UI should show rules applied to YouTube).
4. Are you technical enough to run `adb` (android debug bridge) commands?

**Comment by luckygitt** [comment]
Thanks for your quick response, here are my answers:
1. I am not using the youtube app (uninstalled), this is watching youtube videos via a browser.
2. Yes and vidoes also play when routing everything through Wireguard via the offical WG app.
3. Not applicable - not using the Youtube app, and in any case, I disabled all app blocking when trying to debug this.
4. Yes, please advise what commands to run.

**Comment by ignoramous** [comment]
Also check if any of the "domain" rules (universal/global or browser specific) are blocking `youtube.com` or associated domain names.

> Yes, please advise what commands to run.

1. Change log level: *Configure* -> *Settings* -> *Log Level* -> *Verbose*.
2. Connect to host, then exec `adb logcat` (redirect it to a file: `adb logcat > /tmp/rdns.bug`).
3. Open browser, visit YouTube.
4. End `adb logcat`; email its output: `mz` at `celzero` dot `com`.

Thanks.

**Comment by luckygitt** [comment]
Log emailed

**Comment by luckygitt** [comment]
Seems to be fixed in 55b

**Comment by ignoramous** [comment]
Thanks for the confirmation. Closing...
