### ISSUE TITLE
[Feature Tweak] Persistent scroll position and filters

### ISSUE THREAD

**Issue by bornasalman** [celzero/rethink-app#1186]
Hi, could you potentially stop the filters from resetting when hitting Back from viewing an app? Right now the behaviour after hitting Back from an app is 1) all filters are reset and you are returned to the "All" label and 2) the list auto-scrolls all the way to the top of the app list. It would be nice if it remembered both scroll position and filters on Back.

Thank you.

**Comment by ignoramous** [comment]
For the *Apps* screen? We must do so. Please track it at #1050 (feel free to reopen this bug in case you think it isn't a dup).
