### ISSUE TITLE
Feature Request - Import DNS list

### ISSUE THREAD

**Issue by orbiterFan** [celzero/rethink-app#1188]
Hi Guys

Your app is very cool. I use it everyday.

Recently backed up my settings, then upgraded, found my custom DNS list was gone, so re-imported.

After reimport, none of my DNS addresses were added.

Would like to ask for export and import of DNS addresses only. 

Welcome your feedback.

**Comment by ignoramous** [comment]
This is a top ask. We intend to implement it, once we get to a place where the app works stable enough with WireGuard.

Closing as dups of #293 and #794. Reopen if you feel they aren't dups.
