### ISSUE TITLE
share bug reports

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#119]
Add capability where in user can share app related logs through email.

Apps can read their own logcat just fine. May be, this can be attached as a zip to be sent via email or uploaded to S3 buckets via Cloudflare Workers or some such.

Don't complicate. Simplest but friction-free impl would do. Email is not friction-free, so that's ruled out.

**Comment by ignoramous** [comment]
ACRA: https://github.com/acra/acra

Crashy: https://github.com/FunkyMuse/Crashy

Also: https://github.com/Jigsaw-Code/outline-client/issues/50#issuecomment-507390339

**Comment by hussainmohd-a** [comment]
Gathering stack-trace or tombstones from the crash is not possible if you are not system app/the device is rooted. 

One other way is to use the Runtime / ProcessBuilder to fetch the logs. 

`Runtime.getRuntime().exec("logcat -c")`

ACRA also gathering the logs by capturing the throwable and bundling them with application states. 
 `getStackTrace(msg: String?, th: Throwable?)`

Instead, we can explore the options of `ApplicationExitInfo#getTraceInputStream` introduced as part of Android 12 where we can fetch tombstones as protocol buffers.

**Comment by ignoramous** [comment]
As mentioned above, Android 12+ will feature bug report API built-in, which is what we'd use.

These 3p tools won't be used for any other Android version. Closing...
