### ISSUE TITLE
Push notifications problems on android 14

### ISSUE THREAD

**Issue by katastrophe92** [celzero/rethink-app#1190]
Hey there! First of all thank God that RethinkDNS is existing  ❣️❣️

I bought a A34 and upgraded to android 14, then the  problem with notifications started. On my old M12 no problem with notifications. Sometimes I get them: after I unlock phone, pause RDNS app, some time after the notification was sent.

I tried different block lists, disable Advanced DNS filtering, allow mtalk.google.com also but still inconsistent. Also exported all settings from old phone to new one and still nothing. Tried to delete app data and reinstall. 

App Version 055a

Enabled Lists: ![SmartSelect_20240113_142558_Rethink.jpg](https://github.com/celzero/rethink-app/assets/103950507/0b93aa54-7ac4-475b-9569-c59c7d6c7259)

**Comment by ignoramous** [comment]
Thanks.

Dup? https://github.com/celzero/rethink-app/issues/1187#issuecomment-1889556327

**Comment by luckygitt** [comment]
I have/had many "Push" problems, notably Whatsapp.
I thought I'd solved it by whitelisitng (allowing) mtalk.google.com but it seems Google Play Services also needs full access to the internet for the notifications to be reliable.
Also, "prevent DNS Leaks" (DNS settings) and "block when DNS is bypassed" (Firewall settings) also interferred with the notifications (doing further testing to confirm).

PS. I also originally had Private DNS enabled in my Android settings and notifications were never reliable with that enabled either.

**Comment by BienGudBoy** [comment]
> I have/had many "Push" problems, notably Whatsapp. I thought I'd solved it by whitelisitng (allowing) mtalk.google.com but it seems Google Play Services also needs full access to the internet for the notifications to be reliable. Also, "prevent DNS Leaks" (DNS settings) and "block when DNS is bypassed" (Firewall settings) also interferred with the notifications (doing further testing to confirm).
> 
> PS. I also originally had Private DNS enabled in my Android settings and notifications were never reliable with that enabled either.

@luckygitt take a look at https://github.com/celzero/rethink-app/issues/1187#issuecomment-1895105958 and see if you can get push notification working without whitelisting GMS?

**Comment by katastrophe92** [comment]
i installed the GitHub release version and disable Advanced DNS filtering, allow mtalk.google.com. Seams to fix itself but now it doesn't run in the background for long. I need to reconnect multiple times a day
