### ISSUE TITLE
Domain Rules - is this the correct behaviour?

### ISSUE THREAD

**Issue by luckygitt** [celzero/rethink-app#1195]
If I BLOCK an App then whitelist a domain for that app (or even whitelist it globally), then said domain is sill blocked.
Is this the intended behaviour? 
If yes, I don't see any reason for having a whitelist option, as all traffic/domains will be blocked regardless until the app is set to "allow"

PS. I am routing all apps through Wireguard, if this makes a difference?

**Comment by hussainmohd-a** [comment]
@luckygitt, when the app is set to BLOCK state, the whitelist won't take effect. You should configure the app in isolate mode instead. In isolate mode, all connections, except those from whitelisted IP addresses/domains, will be blocked.
