### ISSUE TITLE
Cannot Download Blocklists

### ISSUE THREAD

**Issue by GitteGitty** [celzero/rethink-app#1198]
Hi,
yesterday and today I cannot download blocklists on a new device. Stuck at Download...
Is it possible tjat at the moment there is a problem on your blocklist-server or do you have an advice for me? Thank you!
Great App btw!
Cheers

**Comment by test1y** [comment]
1) Reset Rethink to default and also remove Rethink icon from notification.
2) start Rethink and do not configure any settings. Click "Start" button.
3) Directly go to Download blacklist and click once and wait for Rethink to Refresh itself.
4) Your blacklist button no long showing disable.

Try this. :-)

**Comment by GitteGitty** [comment]
Works, thank you!! :)
Cheers

**Comment by hussainmohd-a** [comment]
Tracked [here](https://github.com/celzero/rethink-app/issues/952). Closing as duplicate.
