### ISSUE TITLE
"Disconnected from always-on VPN" after crash

### ISSUE THREAD

**Issue by ThreeDeeJay** [celzero/rethink-app#1200]
I'm not sure if this is a problem/limitation/quirk of RDNS or Android (13, LineageOS) but apparently if RDNS crashes (or is force closed), Android will completely disable VPN and let all apps through the internet, which defeats the purpose of the firewall.

Obviously I wouldn't kill or crash RDNS intentionally under normal conditions, but there's been a few times where I get this message and have to restart RDNS to restore the firewall because it seems RDNS just crashed out of the blue, or it was killed by battery saving logic or something (RDNS usage is unrestricted though I know [that may not be enough](https://dontkillmyapp.com/)).

Is this a major flaw or am I missing something? And more importantly, is there a way to prevent this by making android at least lock down internet if RDNS dies for whatever reason? I know there's "Block connections without VPN" but enabling that option seems to cause initial connection issues and it seems to disable Orbot proxy (which by the way should also lock down traffic if it fails to connect to Tor IMO)

**Comment by ignoramous** [comment]
> I know there's "Block connections without VPN" but enabling that option seems to cause initial connection issues and it seems to disable Orbot proxy (which by the way should also lock down traffic if it fails to connect to Tor IMO)

`Block connections without VPN` (*VPN Lockdown* mode) will accomplish what you want in cases where Rethink crashes or is killed.

In the upcoming version, `v054b` (due release any day now), this limitation that Orbot cannot be used in *VPN Lockdown* mode is going away.

> Obviously I wouldn't kill or crash RDNS intentionally under normal conditions

Rethink is *crash* prone like any other complex piece of software, though it crashes like 1% to 2% of the devices running our *beta* app (according to Play Store health metrics). In `v054b` we've tried to address as many *crash* reports folks have sent our way. If you're technical enough, you can select *Verbose* logging from *Configure* -> *Settings* -> *Log Level* and immediately (like within seconds) capture logs when you detect a crash, and then send them our way. Unfortunately, delaying even for a few seconds wipes out the generated logs including critical logs that help in root-causing the crash.

Sometimes, there's a pattern to when crashes happen:
- Every time there's a network switch (wifi -> mobile)
  - or, only when Orbot or WireGuard are enabled.
  - or, only when using *System DNS*.
- Every time there's IP protocol switch (IPv4 -> IPv6)
- Every time a particular app is used (say, Syncthing or Chromecast)
- Every time the blocklists (local or remote) are changed.

and so on...

**Comment by ThreeDeeJay** [comment]
> `Block connections without VPN` (_VPN Lockdown_ mode) will accomplish what you want in cases where Rethink crashes or is killed.
> In the upcoming version, `v054b` (due release any day now), this limitation that Orbot cannot be used in _VPN Lockdown_ mode is going away.

Glad to know! 👍 
I've been looking forward to v054b and the impatience led me to attempt [building it myself had no success](https://github.com/ThreeDeeJay/rethink-app/actions/runs/7579385544/job/20643521967#step:4:404). Any plans to upload nightly APKs to something like GitHub releases so we can use [Obtainium](https://github.com/ImranR98/Obtainium)?
By the way, would `Block connections without VPN` also prevent boot-up leaks that require something [like this](https://github.com/MuratovAS/TurnOffNetwork-magisk) for AFWall+?
and is there anything we can do about [this](https://mullvad.net/en/blog/2022/10/10/android-leaks-connectivity-check-traffic)? 

> Rethink is _crash_ prone like any other complex piece of software, though it crashes like 1% to 2% of the devices running our _beta_ app (according to Play Store health metrics). In `v054b` we've tried to address as many _crash_ reports folks have sent our way. 

Yeah, the part that bothered me isn't that RDNS crashed but that android brought down the VPN and firewall out of the blue when I wasn't even using my phone, which made me question what "always-on" really meant, and apparently it just means that it can't be switched to another VPN without user confirmation or something.

> If you're technical enough, you can select _Verbose_ logging from _Configure_ -> _Settings_ -> _Log Level_ and immediately (like within seconds) capture logs when you detect a crash, and then send them our way. Unfortunately, delaying even for a few seconds wipes out the generated logs including critical logs that help in root-causing the crash.

I installed [Scoop](https://github.com/TacoTheDank/Scoop) which posts a notification with the stack trace and it helped me track down and even fix an issue with a couple apps, so hopefully it'll catch the RDNS crash log. 🤞 
 
> Sometimes, there's a pattern to when crashes happen:
> 
>     * Every time there's a network switch (wifi -> mobile)
>       
>       * or, only when Orbot or WireGuard are enabled.
>       * or, only when using _System DNS_.
> 
>     * Every time there's IP protocol switch (IPv4 -> IPv6)
> 
>     * Every time a particular app is used (say, Syncthing or Chromecast)
> 
>     * Every time the blocklists (local or remote) are changed.
> 
> 
> and so on...

I see, I'll try those to see if it crashes and gets logged. 👌 

On a side note, any plans to make Orbot proxy also block all traffic when RDNS fails to connect? It's also pretty buggy, especially when booting with Wi-Fi disabled and I get the warning about RDNS asking me to start Orbot manually.
Also, are there any plans to make it work simultaneously with Wireguard? 
and is there a way to make SSH proxy/tunneling via [ConnectBot](https://github.com/connectbot/connectbot) + [ProxyDroid](https://github.com/madeye/proxydroid) respect/not completely bypass RDNS? That would be nice to maintain firewall rules when connecting to home routers with a [firmware that doesn't support Wireguard server](https://freshtomato.org/).

**Comment by Vasil-Todorov** [comment]
@ignoramous I am on version 0.5.5a right now and the app refuses to use the Tor proxy when in "Always on VPN" mode.

**Comment by BienGudBoy** [comment]
> @ignoramous I am on version 0.5.5a right now and the app refuses to use the Tor proxy when in "Always on VPN" mode.

"Always on VPN" seems to be working too good, preventing even localhost (127.0.0.1) connection to proxy, as I've encountered.
I tried running RethinkDNS on the main profile, and a proxy on a work profile, with "Always on VPN" enabled on the main profile, but nothing on the work profile.
RethinkDNS wasn't able to connect to the proxy with it enabled. Right upon disabling, everything works fine.

**Comment by katastrophe92** [comment]
I still don't understand this: RethinkDNS logo is still visible in the notifications bar and just the VPN key logo is missing. Then I open the RethinkDNS app and it connects itself back again. I will screen record next time

**Comment by Vasil-Todorov** [comment]
@ignoramous Apologies for the confusion, I must amend my statement. Orbot proxy is only blocked when the "Block connections without VPN" option is enabled. Perhaps because that blocks the Orbot connection as that is not in the VPN?

@BienGudBoy I have tried listening on a local port then pinging it via termux, and it worked. That is on the same profile though.

**Comment by ignoramous** [comment]
> I still don't understand this: RethinkDNS logo is still visible in the notifications bar and just the VPN key logo is missing

Yes, this is symptomatic of a recovery following a crash (see my first reply here and the discussion above).

> Perhaps because that blocks the Orbot connection as that is not in the VPN?

**Comment by ignoramous** [comment]
>  RethinkDNS app was still running in the background

You can see Rethink's uptime by tapping on the *down arrow* next to the *START* / *STOP* button on the homescreen. If the logs were "missing" for 4 hours, it is likely that the app crashed.

**Comment by Vasil-Todorov** [comment]
You can only run Termux as the owner user. Once I think of a way to test inter user localhost networking communications I will post results.

I think it is likely that android is isolating users as a security/privacy measure.
