### ISSUE TITLE
It gets frequently disconnected 

### ISSUE THREAD

**Issue by katastrophe92** [celzero/rethink-app#1202]
Hey there! I connect always to RDNS Plus and every 2-5 hours get disconnected. In the notifications bar it still shows the RethinkDNS logo but the VPN connection 🔑key logo is missing. When I open the app the VPN 🔑key logo is back again and in the logs i cann see that the connection was indeed lost. Battery management is on unrestricted and running in the background also. Anybody got this bug and know a fix?  Thanks

**Comment by katastrophe92** [comment]
Hope it can be seen good enough that approximately 4 hours logs are missing and RethinkDNS app was still running in the background. Just the VPN connection and firewall + adblock from RethinkDNS app also. I'm using samsung galaxy a34 5g android.

https://github.com/celzero/rethink-app/assets/103950507/0bc16512-7105-465b-aa83-09ec0647ba61

**Comment by ignoramous** [comment]
As mentioned in a comment elsewhere, can you please check the *uptime* at the footer of the bottomsheet that comes up when you tap on the *downward arrow* next to the `START` / `STOP` on the homescreen?

**Comment by katastrophe92** [comment]
> As mentioned in a comment elsewhere, can you please check the *uptime* at the footer of the bottomsheet that comes up when you tap on the *downward arrow* next to the `START` / `STOP` on the homescreen? 

It did the same now. Hope i Screenshoted what you asked for. 
![SmartSelect_20240206_102256_Rethink.jpg](https://github.com/celzero/rethink-app/assets/103950507/aa9919cc-e761-49fe-9390-065098fb109c)

**Comment by ignoramous** [comment]
You see "active 2 min ago" there? The app crashed and was started "2 min ago". It looks like the app is crashing a LOT on your Android. If you know how to grab a bugreport, then email it to us (`mz` at `celzero` dot `com`) and mention this github issue. Someone mentioned they use "Scoop" to capture bugreports easily, so you can use that too.

> I installed [Scoop](https://github.com/TacoTheDank/Scoop) which posts a notification with the stack trace and it helped me track down and even fix an issue with a couple apps, so hopefully it'll catch the RDNS crash log. 🤞

https://github.com/celzero/rethink-app/issues/1200#issuecomment-1912857882

**Comment by katastrophe92** [comment]
I uninstalled and installed again through Obtainium app and left the app with the stock settings and just choose some block lists. The only option I changed is turning off ''Advance DHS filtering'' because I don't get notifications when this option ON is. I do not know what was the problem that cause the disconnects.

**Comment by rohitghali** [comment]
> I uninstalled and installed again through Obtainium app and left the app with the stock settings and just choose some block lists. The only option I changed is turning off ''Advance DHS filtering'' because I don't get notifications when this option ON is. I do not know what was the problem that cause the disconnects.

Oh, so that's what's causing my notifications to stop? Wow! I was scratching my head about that issue for a few days now. Turned it off. Thanks.
