### ISSUE TITLE
VPN leak for newly installed apps.

### ISSUE THREAD

**Issue by NotMainstream** [celzero/rethink-app#1215]
So when a new app is installed it should be blocked for accessing internet until the user selects if that app should be routed directly or through one of the VPN's profiles.
To go around this right now is not possible at least in the case of some apps because they don't even appear in the list of apps that can be included or excluded from a VPN profile. Maybe if the user puts the device in airplane mode and starts the app just so the app appears in the list to be included in the VPN profile but the biggest problem is that the user has to remember each time he installs an app to add it and also many apps don't even appear in the list with their name but with a numerical code.

**Comment by ignoramous** [comment]
> To go around this right now is not possible 

This feature has been added in `v055b`, the upcoming version: #1049 

> Maybe if the user puts the device in airplane mode and starts the app just so the app appears in the list to be included in the VPN profile

You may enable *Block newly installed apps* in *Firewall* -> *Universal*.

> also many apps don't even appear in the list with their name but with a numerical code.

Are these apps installed in a different user (like *Guest*) / profile (like *Work Profile*) / cloned (*dual app*)?

**Comment by NotMainstream** [comment]
Thanks for letting me know there will be improvements. I'm in a secondary user but they are not clones, they are installed directly in the secondary User.

**Comment by ignoramous** [comment]
> I'm in a secondary user but they are not clones

That's tracked here: #150 (although, we have made *some* improvements towards identifying, or rather guessing, app information in *other* profiles / users).

---

closing this issue as dup of other issues. feel free to reopen.
