### ISSUE TITLE
~10 second delays on some queries with "Do not route Private IPs" setting

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#1221]
I've been experimenting with the experimental _Do not route Private IPs_ setting (in order to accept incoming connections over LAN), but it seems to cause noticeable delays (10+ seconds) for some DNS queries.

Turning that setting off again instantly restores faster queries after the service restarts, whereas just stopping and starting Rethink doesn't appear to improve the delay.  Changing DNS provider also doesn't affect the response time.

Two logcats with verbose logging enabled:
[16_02-19-08-42_531-exclude-private-disabled.log](https://github.com/celzero/rethink-app/files/14315132/16_02-19-08-42_531-exclude-private-disabled.log)
[16_02-19-13-54_965-exclude-private-enabled.log](https://github.com/celzero/rethink-app/files/14315133/16_02-19-13-54_965-exclude-private-enabled.log)

In both cases here I'm performing a single action -- initiating Google sign-in within an app -- during which there's a single blocked request from the app to `firebaseremoteconfig.googleapis.com`, and an allowed request from Google Services Framework to `clientauthconfig.googleapis.com`.  (I believe the other domains logged are from background apps and not part of this exchange.)

With the _Do not route Private IPs_ setting disabled (first log), the Google sign-in prompt opens in the app in a fraction of a second as expected; when enabled (second log), it takes 10 seconds to show.  Without really knowing what I'm looking for, the logs look largely the same, except the second one seems to get stuck for a bit towards the end.

**Comment by ignoramous** [comment]
> In both cases here I'm performing a single action -- initiating Google sign-in within an app

If this is happening with a particular app and not with others, then it might be app-specific. Do you see this happen across apps? If not, is there a way to test for that?

**Comment by Terrance** [comment]
It's not affecting everything (e.g. general web browsing in Firefox seems to be unaffected), but also not an isolated case.  From poking various other apps with the setting enabled, I'm wondering now if this is specific to Google authorisation -- so far I'm seeing this lag with a handful of apps utilising Google sign-in as well as Google's own apps like Docs and Sheets (affecting general use as well as explicit sign-ins, perhaps because there's Google session refreshes or similar going on in the background).

In all cases, disabling _Do not route Private IPs_ and tring again immediately resolves the lag.  I'm not immediately sure how Google sign-in would tie into this -- the endpoints aren't even consistent between them (e.g. Sheets calls `www.googleapis.com` and `drivefrontend-pa.googleapis.com` without any GSF requests.

**Comment by ignoramous** [comment]
Gotcha. Have I got the repro steps right:
- Open Google Docs and Google Sheets (and if already logged in, log out).
- Try to log in back again.
- Notice the 10s delay when *Do not route Private IPs* is enabled.

**Comment by Terrance** [comment]
I can repro it without logging out by clearing Docs' cache in the Android app info UI and force-closing the app -- this clears the thumbnails of recent files on the "last opened" screen you get when first opening the app again, and the 10 second delay is noticeable there before the thumbnails are downloaded again.

**Comment by ignoramous** [comment]
Thanks. Can you confirm settings in *Configure* -> *Network* are all at *default* except *Do not route Private IPs* and that when this delay happens, no proxies are active (either in-app or on-router)?

I cleared cache and force-stopped *Google Docs* and *Google Sheets* with *Do not route Private IPs* enabled *and* disabled... but I didn't see 10s delay on either tries. I must note though, that I am running the yet unreleased `v055b` version.

**Comment by ignoramous** [comment]
I'll try to reproduce this other devices tomorrow. I am also on Android 13.

**Comment by Terrance** [comment]
Apologies, I left my device info out: OnePlus Nord CE, Android 13.

> Choose IP version is Auto (IPv4 is the default)

I also have _Choose IP version_ set to _Auto_, but switching back to _IPv4_ removes the delay.  👀  An interesting interaction between those two settings?  (Though that doesn't match what you're seeing...)

For reference, other Network settings including _Use all available networks_ are disabled.  I'm usually behind a sing-box proxy (proxying a single IP and bypassing the rest), but have been testing with and without the proxy, no change there.

**Comment by ignoramous** [comment]
If you can, please check if this delay is gone in `v055b` (though, we haven't done anything specific to fix it... but hoping new code is free of this strange behaviour): https://github.com/celzero/rethink-app/releases/tag/v0.5.5b (note that, the F-Droid version cannot be updated to a later APK from GitHub or from [our Website](https://rethinkdns.com/download). This means, if you're using F-Droid version, you will have to manually *backup* settings from *Configure* -> *Settings* -> *Backup & restore* and restore it after you install the GitHub / Website version. Rethink does *not* backup WireGuard configurations as those contain sensitive "Private Keys" and are hence left untouched).

**Comment by Terrance** [comment]
Sorry for the delay; I didn't get around to switching from the F-Droid build, and it looks like they had some problems building `v055b`, but `v055c` has since come through -- I've re-enabled Choose IP version = Auto, and in the last day and a bit, so far so good.  From a cold boot it would sometimes take a few days before the lag kicked in, so you might want to hold off a little longer beofre considering resolved, but I'll report back if it does become a problem again.

**Comment by ignoramous** [comment]
> From a cold boot it would sometimes take a few days before the lag kicked in, so you might want to hold off a little longer beofre considering resolved, but I'll report back if it does become a problem again.

Will wait. Thanks.

**Comment by Terrance** [comment]
No lag encountered since v055c.  As far as I'm concerned, this is no longer an issue.  🙂
