### ISSUE TITLE
Logs flooded by secure DNS connections(very few DNS requests though)

### ISSUE THREAD

**Issue by xandro0777** [celzero/rethink-app#1231]
The connection log is completely clogged up with DNS connections to 10.111.222.3, several hundreds per second and enough to occasionally kill the App and make the logs completely useless.

There are comparatively very few DNS requests in the DNS logs so something is probably wrong but from the logs there is no way to figure it out.

<details>
<summary>Attaching a few screenshots</summary>
hope someone has an idea?

![Screenshot_2024-03-01-12-16-28-95_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/e5cd7140-0d05-41a5-b85c-d7d19e2c043c)
![Screenshot_2024-03-01-12-16-09-45_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/86ed106d-5034-403c-b9d2-2c0f7da765f9)
![Screenshot_2024-03-01-12-15-42-80_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/07615cbd-471d-438c-b465-428fae6c5efb)

![Screenshot_2024-03-01-12-24-48-08_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/55c5551e-89a9-4c37-80cf-1b8c58780f8d)

![Screenshot_2024-03-01-12-26-00-20_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/08a7cc4b-a125-4507-a505-91fb6a389ff3)
![Screenshot_2024-03-01-12-24-55-85_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/e3634df7-f9e5-4c1c-b670-21ee1eb10397)
</details>

**Comment by ignoramous** [comment]
> There are comparatively very few DNS requests in the DNS logs so something is probably wrong but from the logs there is no way to figure it out.

- Those `10.111.222.3` connections (on TCP `853`) are meant for some *Private DNS* endpoint. Have you set one up? 
- Is Rethink is in *VPN Lockdown* mode (*Block connections without VPN*)?
- Are you on a custom ROM?
- If you use any other DNS apart from *System DNS*, do you still see this issue?

**Comment by xandro0777** [comment]
Thanks for looking at it. I did not setup anything special regarding DNS. Sometimes I use the device as hotspot so I thought the 10.x.x.x might be related but seen from the laptop the hotspot is 192.168.x.x

Didn't set or change anything like VPN lockdown mode .. which option would it be exactly? In the Network page of settings everything is off.

Stock Realme ROM, Android 13.

Tried Google and Rethink DNS and looks exactly the same.

Used Termux/ifconfig, 10.111.222.x is the "tun0" device.

Now.. suddenly I don't see any more requests like that but will probably come again.

**Comment by ignoramous** [comment]
You might have *Private DNS* set to *Optimistic*, you may want to set it to *off*, instead. Check your *Connectivity* settings ([see](https://archive.is/az65z)). Those `10.111.222.3` requests are being sent to Android's *Private DNS* endpoint.

*VPN Lockdown* mode, if enabled, is shown in the bottomsheet that comes up when you tap on the *down arrow* right of the `STOP`/`START` button on the homescreen. You can enable *VPN Lockdown* mode by:

1. Going to *About* -> *VPN profile*
2. Select Rethink
3. Enable `Always-on VPN`
4. Then, enable `Block connections without VPN` (which is what I call the *VPN Lockdown* mode).

**Comment by ignoramous** [comment]
Btw, *Private DNS* or not, Rethink should continue to work just fine (only that, all DNS requests, when *Private DNS* is enabled is handled by Android and not Rethink, which is why these "secure-dns" entries show up in *Network* logs and not *DNS* logs).

When you see this barrage of "secure-dns" connections, does Internet not work? Does Rethink crash? If any of those happen the next time, if you're technical enough, can you:
1. Select *Verbose* in *Configure* -> *Settings* -> *Log level*.
2. Capture `adb logcat` output as the issue happens and Rethink is running.
3. Capture until you expect the app to crash, if not, stop the capture after a while.
4. Email the `logcat` output to `mz` at `celzero` dot `com` and mention this GitHub issue.

**Comment by xandro0777** [comment]
I found what triggers this problem - viewing https://www.radio-bamberg.de/blitzer-verkehr/ with https://f-droid.org/de/packages/com.stoutner.privacybrowser.standard/ (webview based browser). Normally DNS requests by Privacy Browser are visible in the logs so it must be something coming from the webview. Also the requests continue for a considerable time even if I kill Privacy Browser which confused me quite a bit.

Indeed this page doesn't work when RethinkDNS is enabled and I never figured out why. The page for some reason does not work with Fennec either.

No I didn't have VPN Lockdown mode and on my system enabling it would not work as described above. The app was most likely killed because it did not respond for some time due to me looking at the flooded logs.

**Comment by ignoramous** [comment]
Thanks.

> so it must be something coming from the webview.

More likely a bug in *Privacy Browser* than WebView. Seems like *Privacy Browser* is open source. Worth raising this anomaly with its development team.

**Comment by xandro0777** [comment]
Not a Privacy Browser bug, Chrome/Android shows exactly the same behavior. Also the requests continue for some time after the browser app is killed. Tried a few other webview based browsers but the page doesnt display at all there.

Also, why does secure DNS try to connect to an address belonging to the tun0 device?

**Comment by ignoramous** [comment]
Concerning.

> Also, why does secure DNS try to connect to an address belonging to the tun0 device?

Don't really know. This bug might be in the OS. Is your *Private DNS* Android setting set to *Optimistic*?

**Comment by xandro0777** [comment]
Private DNS is set to "auto", the other two options were off and specified DNS.

**Comment by ignoramous** [comment]
>

**Comment by ignoramous** [comment]
> Private DNS is set to "auto"

Set it to OFF, and then you shouldn't see any app attempt to connect to *Private DNS*.

**Comment by xandro0777** [comment]
Setting it to off prevents the problem with flooded logs but the page still doesn't load with zero indication in the logs what goes wrong - and turning off RethinkDNS fixes this so there is something strange going on.

Also.. should probably be a different issue asking for enhancement, in cases like this it would be tremendously helpful if nearly identical entries in the logs were grouped together (in my case they are identical except the ms timestamp) and/or could be filtered out easily.

Added a few screenshots of what I am seeing now in the logs when the page is not loading.. turning off RethinkDNS fixes that.



![Screenshot_2024-03-03-10-35-52-45_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/0a5433ef-c1ff-483e-8fc7-857208c2716a)


![Screenshot_2024-03-03-10-35-47-75_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/97006653-f8ce-4ceb-8760-fca067d07061)
![Screenshot_2024-03-03-10-35-42-32_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/e51510a0-9b32-459b-919e-acb096aa6315)
![Screenshot_2024-03-03-10-35-36-70_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/915d4745-aa3c-46e2-8244-02054ff633ae)

**Comment by xandro0777** [comment]
As often when trying to catch logs, I didn't have a crash in two days when trying..

**Comment by ignoramous** [comment]
> I didn't have a crash in two days when trying...

That's because you may have turned *Private DNS* `off` from `Automatic`, which is causing the to begin with?

**Comment by xandro0777** [comment]
I have reenabled the setting again. It makes the problem visible but even when it is set to off, the page does not load without any trace in the logs that something has been denied so there is another problem. Did not happen with Netguard.

Tried a few things with Termux, that reminds me I have also ```dig```and many other tools available in Termux.. just let me know what to try.

```
~ $ ifconfig
Warning: cannot open /proc/net/dev (Permission denied). Limited output.
ap0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.188.142  netmask 255.255.255.0  broadcast 192.168.188.255
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

ccmni2: flags=193<UP,RUNNING,NOARP>  mtu 1500
        inet 10.116.182.125  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

tun0: flags=81<UP,POINTOPOINT,RUNNING>  mtu 1500
        inet 10.111.222.1  netmask 255.255.255.0  destination 10.111.222.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)

~ $ ifconfig
Warning: cannot open /proc/net/dev (Permission denied). Limited output.
ccmni1: flags=193<UP,RUNNING,NOARP>  mtu 1500
        inet 10.124.142.180  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

tun0: flags=81<UP,POINTOPOINT,RUNNING>  mtu 1500
        inet 10.111.222.1  netmask 255.255.255.0  destination 10.111.222.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)

~ $ ping 10.111.222.1
PING 10.111.222.1 (10.111.222.1) 56(84) bytes of data.
64 bytes from 10.111.222.1: icmp_seq=1 ttl=64 time=0.158 ms
64 bytes from 10.111.222.1: icmp_seq=2 ttl=64 time=0.179 ms
64 bytes from 10.111.222.1: icmp_seq=3 ttl=64 time=0.222 ms
64 bytes from 10.111.222.1: icmp_seq=4 ttl=64 time=0.198 ms
64 bytes from 10.111.222.1: icmp_seq=5 ttl=64 time=0.167 ms
64 bytes from 10.111.222.1: icmp_seq=6 ttl=64 time=0.162 ms
^C
--- 10.111.222.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5110ms
rtt min/avg/max/mdev = 0.158/0.181/0.222/0.022 ms
~ $ ping 10.111.222.3
PING 10.111.222.3 (10.111.222.3) 56(84) bytes of data.
64 bytes from 10.111.222.3: icmp_seq=1 ttl=64 time=8.28 ms
64 bytes from 10.111.222.3: icmp_seq=2 ttl=64 time=69.4 ms
64 bytes from 10.111.222.3: icmp_seq=3 ttl=64 time=16.6 ms
64 bytes from 10.111.222.3: icmp_seq=4 ttl=64 time=11.1 ms
64 bytes from 10.111.222.3: icmp_seq=5 ttl=64 time=4.17 ms
^C
--- 10.111.222.3 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 4.176/21.935/69.430/24.090 ms
~ $ telnet 10.111.222.3 853
Trying 10.111.222.3...
Connected to 10.111.222.3.
Escape character is '^]'.

^]
telnet>
Connection closed.
~ $ telnet 10.111.222.1 853
Trying 10.111.222.1...
telnet: Unable to connect to remote host: Connection refused
~ $ telnet 10.111.222.1 853
Trying 10.111.222.1...
telnet: Unable to connect to remote host: Connection refused
~ $
~ $ telnet 10.111.222.3 853
Trying 10.111.222.3...
Connected to 10.111.222.3.
Escape character is '^]'.
hello

fghggggjh
fgyuuujuhhhghhhhdfggdfrtgvcxzetuhgghgffghggg
dffggfftyggfycthftgftfyythhhggghgggfghghhjjjj
dghchgguxurudststdifuftfxxixxttifdxtitdttidtdt
srdtdtdtftftcicyyicycycycgcyfgcycgcgcgcgcggixxj
rsduxufuxuufxxudrxtConnection closed by foreign host.
```

**Comment by xandro0777** [comment]
Got one of the crashes:

[cr.txt](https://github.com/celzero/rethink-app/files/14502443/cr.txt)

**Comment by ignoramous** [comment]
> [cr.txt](https://github.com/celzero/rethink-app/files/14502443/cr.txt)

Thanks for the log. The crash happens because Android has ran out of memory to allocate. Looks like Rethink simply can't keep up with the flood of TCP streams to `10.111.222.3:853` (going nowhere).

```
03-02 16:17:59.278 26490 26490 F DEBUG   : Abort message: 'mprotect failed on atexit array: Out of memory'
```

> the page does not load without any trace in the logs that something has been denied so there is another problem.

I assume you mean you can't visit `https://www.radio-bamberg.de/`? I am able to access the website just fine. Check if any app-level or universal domain or IP rule is blocking access to `www.radio-bamberg.de` (which is actually an alias for `welocal.cloud`, blocked by `1Hosts (Xtra)` https://archive.is/ePKLy). Rethink's *Network* logs and *DNS* logs may have clue as to what's going on, if you see any entries related to `www.radio-bamberg.eu` (tapping on entries in the *Network* logs and *DNS* logs should bring up a bottom sheet with more details about the connection entry).

**Comment by xandro0777** [comment]
Well just to be sure. I set private DNS to off, cleared App storage, reinstalled and started RethinkDNS without touching any configuration option.

The Radio-Bamberg page doesn't load in privacy browser (which one did you try?) and there is nothing shown  blocked in the logs. Works fine if I turn of RethinkDNS.
![Screenshot_2024-03-06-10-38-06-80_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/aefc8061-e66f-4e8f-809b-7e0199590a7e)
![Screenshot_2024-03-06-10-38-01-86_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/43711649/9c59f3a9-a87f-456c-b5d2-d2274314d177)

**Comment by ignoramous** [comment]
> https://www.radio-bamberg.de/blitzer-verkehr/

I tried in Firefox and Chrome. Worked on both. Privacy Browser, didn't, even with Rethink disabled. For you, the other browsers load the website, fine, even with Rethink running, correct?

<details>
<summary>network log entry</summary>
screenshot:
![Screenshot_2024-03-06-15-57-15-43_c8cbde12d3521911922be4eee6a05664~2](https://github.com/celzero/rethink-app/assets/852289/c4123689-ef64-4409-8d2c-9ba1b5d50df3)
</details>

> there is nothing shown blocked in the logs

Yeah, looks like Privacy Browser isn't able to load the website...

**Comment by xandro0777** [comment]
Privacy Browser works perfectly when I disable RethinkDNS.

Chrome sometimes works regardless but if RethinkDNS is enabled the cookie consent dialogs often go nuts.

Firefox loads something regardless of RethinkDNS but doesn't display the actual content I want to see.. probably ublock-origin. Because of this Privacy Browser was my choice for viewing the website for the last months.

**Comment by xandro0777** [comment]
I have a suspicion what is wrong. The routing tables are

```
$ ip route show table 0|grep 10.111                                                                                                                              
10.111.222.0/24 dev tun1 table 1044 proto static scope link 
10.111.222.3 dev tun1 table 1044 proto static scope link 
10.111.222.0/24 dev tun1 table 1000000044 proto static scope link 
10.111.222.3 dev tun1 table 1000000044 proto static scope link 
10.111.222.0/24 dev tun1 proto kernel scope link src 10.111.222.1 
broadcast 10.111.222.0 dev tun1 table local proto kernel scope link src 10.111.222.1 
local 10.111.222.1 dev tun0 table local proto kernel scope host src 10.111.222.1 
local 10.111.222.1 dev tun1 table local proto kernel scope host src 10.111.222.1 
broadcast 10.111.222.255 dev tun1 table local proto kernel scope link src 10.111.222.1 
```
so that Android thinks that 10.111.222.3 is the address of the VPN server. Apparently the Android DNS sometimes tries to get DNS services from the VPN server and tries to connect there. Accessing10.111.222.3 through the vpn tunnel all ports are open and a connection can be opened which does confuse the DNS.

I believe when accessed from inside the tunnel all ports on 10.111.222.3 should be closed.

**Comment by xandro0777** [comment]
>Thanks. Can you add a rule to firewall `10.111.222.3:853` and see if the flooding goes away?
>

Yes, that stopped the flooding.. one single rejected access attempt logged. However the page still didn't load in Privacy browser so I blocked port 53 as well, now the page still refuses to load, sometimes showing name not resolved,  mostly just a black page.

Note that the access attempts at 53 were not at all logged.. even though I suspect the port was accessed.

Also, there were no such issues with Netguard so there must be some subtle difference that causes this DNS confusion. If I get some time I will compare the routing tables of Netguard and this App even though routing tables aren't my strongest subject. Any other ideas?

This also looks like a missed opportunity.. imho the 10.111.222.3 end should actually catch, process and forward all DNS requests according to the rules. 

Probably all other connection attempts that don't make sense - after all the topmost priority of a firewall should should be to protect from illegal access attempts from outside!?

**Comment by ignoramous** [comment]
> Yes, that stopped the flooding.. one single rejected access attempt logged

Thanks. Tracking: https://github.com/celzero/rethink-app/issues/1265

> Note that the access attempts at 53 were not at all logged.. even though I suspect the port was accessed.

These go in the *DNS Log*s UI.

> imho the 10.111.222.3 end should actually catch, process and forward all DNS requests according to the rules

Rethink does this if *Configure* -> *DNS* -> *Prevent DNS leaks* is ON for unencrypted DNS traffic. It can't do for DoT because in TLS the queries and the endpoint (host) are encrypted and authenticated, respectively.

> Probably all other connection attempts that don't make sense - after all the topmost priority of a firewall should should be to protect from illegal access attempts from outside!?

Sorry, I don't get. But I must point out that Android, by default, blocks all *incoming* connections, it only allows *outgoing* ones.

**Comment by xandro0777** [comment]
>> Note that the access attempts at 53 were not at all logged.. even though I suspect the port was accessed.
>
>These go in the *DNS Log*s UI.

Nothing suspicious seen there, just the one expected query that did succeed.. have to look again at the DNS server in that query.

>> imho the 10.111.222.3 end should actually catch, process and forward all DNS requests according to the rules
>
>Rethink does this if *Configure* -> *DNS* -> *Prevent DNS leaks* is ON for unencrypted DNS traffic.

Ok, that setting is on, probably default, and that perhaps explains why I am not seeing any suspicious access to 53.

> It can't do for DoT because in TLS the queries and the endpoint (host) are encrypted and authenticated, respectively.

That's bizarre, it can be encrypted but I didn't think there can be a valid certificate for 10.111.222.3? So I would say it can be intercepted just as well?

>> Probably all other connection attempts that don't make sense - after all the topmost priority of a firewall should should be to protect from illegal access attempts from outside!?
>
>Sorry, I don't get. But I must point out that Android, by default, blocks all *incoming* connections, it only allows *outgoing* ones.

I have ssh and ftp servers on many Android devices so this default apparently doesn't protect much. Would be good if RethinkDNS could block or log connection attempts from outside.

**Comment by ignoramous** [comment]
> it can be encrypted but I didn't think there can be a valid certificate for 10.111.222.3? So I would say it can be intercepted just as well?

Could be, but too much work when blocking it suffices.

> Would be good if RethinkDNS could block or log connection attempts from outside.

True.

**Comment by ignoramous** [comment]
Fixed in `v055d`: https://github.com/celzero/rethink-app/commit/370995a9b70c6b388a7fab2164bd21e07c172d4a (available on Play Store and F-Droid in the coming days or so), and [on GitHub, today](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d).

Please feel free to reopen.
