### ISSUE TITLE
v055b: Local blocklists inaccessible

### ISSUE THREAD

**Issue by LovingNumbers** [celzero/rethink-app#1235]
Hello Guys 
The new update is great but i noticed that im unable to change on-device blocklists wonder if you guys have the same problem?

Edit: Also the orbot seems still to be partially broken.

**Comment by ignoramous** [comment]
Sounds concerning.

>  The new update is great but i noticed that im unable to change on-device blocklists wonder if you guys have the same problem?

What do you mean by "unable to change"?

> orbot seems still to be partially broken

**Comment by LovingNumbers** [comment]
In the last version i could easily enable and disable it right now it only is disabled with no way to change it to enabled.

With orbot i tried like 3 times before i got a connection (only worked for tcp only proxy) the other times rethinkdns said i would need to start it through orbot which also didn't work orbot just became stuck loading.

**Comment by ignoramous** [comment]
> In the last version i could easily enable and disable it right now it only is disabled with no way to change it to enabled.

I just tried on my `v055b` and I could enable / disable *on-device blocklist* just fine.

What do you see when you tap on it to "enable" it? Can you share a screen record on here, if you're comfortable doing so?

**Comment by LovingNumbers** [comment]
https://github.com/celzero/rethink-app/assets/144499593/1e88fe3f-e97f-4c05-863b-fa9ca459d251

**Comment by ignoramous** [comment]
Strangely, "Check for blocklist update" is also missing from the "Configure 195+ ..." bottomsheet. Believe there's some serious mixup in our code which is confused if the app was downloaded from the Play Store (where we disable on-device blocklists) or from F-Droid / GitHub / Website (where we don't). Can you see what version "About" reports (you'd find it version at the bottom of the Rethink's "About" UI).

**Comment by LovingNumbers** [comment]
5.5.b was the version i used even weirder right now i deleted the app and the apk and got it fresh again from github but then i was stuck with only the rethinkdns plus not being able to change and look at the other dns servers the only thing that popped up was the changing blocklist for that dns..
i solved it by using a backup i made weirdly i could change everything like normaler afterwards..

**Comment by LovingNumbers** [comment]
5.5.b was the version i used even weirder right now i deleted the app and the apk and got it fresh again from github but then i was stuck with only the rethinkdns plus not being able to change and look at the other dns servers the only thing that popped up was the changing blocklist for that dns..
i solved it by using a backup i made weirdly i could change everything like normaler afterwards..


BIG EDIT: found a temporary fix if you downgrade ( i downloaded the older version from github) and then update from the rethinkdnsapp it will lead you to the website and that version fixes the on-device blocklist problem! (so i guess the newest version on github is broken but not the one on the website tho maybe im wrong)

**Comment by ignoramous** [comment]
>  Could not change and look at the other dns servers the only thing that popped up was the changing blocklist for that Rethinkdns Plus.

That page has moved to *Configure* -> *DNS*. This UI change was made because most users asked us that they want to access blocklists *quickly* when the upstream is *RDNS*, as they don't really understand / have the desire to change other DNS-related settings. If the upstream is any other DNS, the older behaviour kicks-in (where the DNS UI is shown instead of the RDNS blocklists UI).

>  found a temporary fix if you downgrade ( i downloaded the older version from github)

*v055a github* -> *v055b github* update broke on-device blocklists for you, correct? we'll take a look at it on priority the first thing tomorrow.

**Comment by LovingNumbers** [comment]
no i had the fdroid version first so i couldn't update rethinkdns so i deleted it and then installed the newest version from github don't know if that makes a difference?

**Comment by LovingNumbers** [comment]
> Edit: Also the orbot seems still to be partially broken.


While everything is fixed Orbot still has problems.

**Comment by ignoramous** [comment]
> While everything is fixed Orbot still has problems.

Tracked here #1065 

Though, I suspect these issues have nothing to do with Rethink... but we'll take a look. Are you using the built-in Orbot integration or configuring raw SOCKS5 to point to Orbot?

**Comment by ignoramous** [comment]
> Local blocklists cant be enabled in any of the cases. 

So, no matter what you do (clean install / update from previous version), *on-device blocklists* cannot be turned ON?

**Comment by LovingNumbers** [comment]
> > While everything is fixed Orbot still has problems.
> 
> Tracked here:
> - #1065 
> 
> Though, I suspect these issues have nothing to do with Rethink... but we'll take a look. Are you using the built-in Orbot integration or configuring raw SOCKS5 to point to Orbot?

Just installed new Orbot Version and then tried to get it started through rethink http proxy doesn't work at all and tcp works after 1-2 tries though it doesn't show immediatly that it works but you can see orbot is running and after a little bit of clicking rethinkdns shows that the proxy is on :)

**Comment by LovingNumbers** [comment]
> I tried downgrading and updating via website as @LovingNumbers suggested. Still no local blocklist.

I also played a little around with the blocklist when i downgraded it so maybe that way i solved it idk (i reinstalled the blocklist) don't forget to make a backup! and load it in before you update your version! That's at least what i did to make it work.

**Comment by allmightyasian** [comment]
Same Here unable to access local Blocklist

**Comment by hussainmohd-a** [comment]
The issue occurs when a user performs a fresh install of v055b and attempts to enable the blocklist. Users from previous versions can enable/update the blocklists without any issues. There is a critical bug in how the blocklist enable click listeners are handled: when there is no blocklist, instead of prompting a download, the listener was simply skipping the step. This has been fixed now in  https://github.com/celzero/rethink-app/pull/1240/commits/63226fcffba29c0f6e17f2ac6d50140892d7ab47

**Comment by ignoramous** [comment]
It is part of a *Pull Request* waiting to be merged: https://github.com/celzero/rethink-app/pull/1240
