### ISSUE TITLE
v055b: Per-app trusted domains are ignored

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1238]
> It's seems the latest version v0.5.5b introduced a regression where per-applications trusted domains are ignored (they remain blocked) if said domains are included in a DNS blocklist :( Universally trusted domains are still honored, though.

_Originally posted by @BayLee4 in https://github.com/celzero/rethink-app/issues/1120#issuecomment-1975205541_

**Comment by ignoramous** [comment]
I can reproduce this. We'll fix this in a fast follow release.

**Comment by ignoramous** [comment]
fix: https://github.com/celzero/rethink-app/pull/1240/commits/d0c988aa37422ebd67656a54b4909e9e223baaf4

**Comment by ntnguyen1234** [comment]
Hi, I installed `v0.5.5c`. When I set a trusted domain for an app, that domain becomes trusted for other apps as well.

Steps to reproduce (I installed `0.5.5c` fresh)

1. Install `https://play.google.com/store/apps/details?id=com.facebook.orca` (`Messenger`) and `https://play.google.com/store/apps/datasafety?id=com.tflat.english.vocabulary` (`TFlat dictionary`)
2. Enable `1hosts Pro` list
3. Access `TFlat dictionary` -> `graph.facebook.com` is blocked
4. Put `graph.facebook.com` as a trusted app for `Messenger`
5. Access `TFlat dictionary` -> `graph.facebook.com` is not blocked

Sorry I haven't tested simpler apps to reproduce.

**Comment by Robert-K** [comment]
I'm still running into the issue of trusted IPs and domains getting blocked for blocked apps on [d24918c](https://github.com/celzero/rethink-app/commit/d24918c6650fb9bc3d7500bea77cb6442ff108f8).
Are you sure the fix works as intended?
Or am I misunderstanding how blocking/trusting works?

**Comment by ignoramous** [comment]
Are you on version `v055c`? Check the footer of the "About" UI for the version.

**Comment by Robert-K** [comment]
Yes I'm positive. Could confirm this behaviour on multiple devices.

**Comment by ignoramous** [comment]
Unsure what's going on. Can you see if on anyone of those devices, does a fresh install for *trust*ed domains, work?

Also, if a DNS upstream resolver (and not *on-device blocklist*) blocks a domain, Rethink won't be able unblock it. Check the DNS logs if the domain is blocked by the upstream (like `dns.adguard.com`, for example). *Trust*ed domains are guaranteed to bypass on-device blocklists but not *content-blocking* upstream resolvers (like `dns.adguard.com`).

*Trust*ing domains only fully works with *System DNS* or *RDNS* or an non-blocking upstream resolver (like, *Cloudflare* / *Quad9*).

**Comment by ignoramous** [comment]
We've fixed a related bug #1431 in `v055j` ([github](https://github.com/celzero/rethink-app/releases/tag/v0.5.5j), [website](https://rethinkdns.com/download)).

Can you let us know if you still see this issue?
