### ISSUE TITLE
v055b: DNS over WireGuard bypasses ALL rules

### ISSUE THREAD

**Issue by aviv926** [celzero/rethink-app#1249]
The application seems to have a serious security problem, and several other minor problems as detailed:

**Serious security problem:**
The DNS reveals the original IP address if it goes through Wiregurd's proxy. You can see the original IP address according to the logs in Nextdns.

In addition, when the "Block unused applications" option is activated, it first sends the request to the DNS decoder and then blocks the request (it is not clear why this is so) this is how I noticed according to the logs in Nextdns also in the application you see the request first in the DNS column and only after a few seconds in the Network.

**Bug:**
The option to download access lists does not work when the app is running (my firewall setting says block any unused app) when I disabled the app's VPN, it was able to download the block lists without a problem.

**Info**
Samsung phone android 13.
App v0.5.5c from Github [releases](https://github.com/celzero/rethink-app/releases).

**Comment by ignoramous** [comment]
> The DNS reveals the original IP address if it goes through Wiregurd's proxy.

1. Is WireGuard running in *Simple* mode or *Advanced*?
2. If *Advanced*, is it setup as *Always-on*?

If neither, then DNS is not forwarded via WireGuard.

> The option to download access lists does not work when the app is running (my firewall setting says block any unused app) when I disabled the app's VPN, it was able to download the block lists without a problem.

Tracked here: #983 

Does it not work with both *In-app downloader* (check *Configure* -> *DNS* -> *Advanced*) turned ON and OFF?

If so, in the network logs, can you search for `dl.rethinkdns.com` and tap on it to bring up a *bottomsheet*. Then, look for any error status at the footer of the bottomsheet.

**Comment by aviv926** [comment]
> 1. Is WireGuard running in _Simple_ mode or _Advanced_?
> 2. If _Advanced_, is it setup as _Always-on_?
> If neither, then DNS is not forwarded via WireGuard.

Excellent, this solved the problem when I chose advanced mode -> always on.

> > The option to download access lists does not work when the app is running (my firewall setting says block any unused app) when I disabled the app's VPN, it was able to download the block lists without a problem.
> 
> Tracked here: #1094
> 
> Does it not work with both _In-app downloader_ (check _Configure_ -> _DNS_ -> _Advanced_) turned ON and OFF?

OFF

> If so, in the network logs, can you search for `dl.rethinkdns.com` and tap on it to bring up a _bottomsheet_. Then, look for any error status at the footer of the bottomsheet.
> 
> Probably, Android's _built-in_ "downloader" is blocked by _Blocked any app not in use_, if you're using it.

I added it to exceptions, I guess it will solve the problem later, thanks!


Do you have any ideas about this additional problem I described?

In addition, when the "Block unused applications" option is activated, it first sends the request to the DNS decoder and then blocks the request (it is not clear why this is so) this is how I noticed according to the logs in Nextdns also in the application you see the request first in the DNS column and only after a few seconds in the Network.

**Comment by aviv926** [comment]
> > when the "Block unused applications" option is activated, it first sends the request to the DNS decoder and then blocks the request (it is not clear why this is so
> 
> No clue, really. This is first such report. Also, it is unclear if Rethink really sends any DNS probe at all (it shouldn't, in any case).
> 
> Can you post a video grab to show what you're describing?

See this:
https://github.com/celzero/rethink-app/assets/51673860/b1744a0b-6b1f-40d6-b84a-c22ae354af6f

**Comment by ignoramous** [comment]
Thanks. In the video, I see Google-related apps sending TCP requests (and not DNS)? Why is that unexpected?

Or, what should I be looking for in the video concerning DNS?

**Comment by aviv926** [comment]
> Thanks. In the video, I see Google-related apps sending TCP requests (and not DNS)? Why is that unexpected?
> 
> Or, what should I be looking for in the video concerning DNS?

ESET sent a DNS request (play.eset.com) that was supposed to be blocked, but according to the log in NextDns it managed to arrive.

I assume that this DNS request was also supposed to be blocked since I chose not to allow unused apps, isn't that right?

**Comment by ignoramous** [comment]
> I assume that this DNS request was also supposed to be blocked since I chose not to allow unused apps, isn't that right?

Yes, *WireGuard DNS* bypasses all rules. Probably a stupid decision on our part. We'll fix this in the upcoming version `v055b` due in a day or two.

**Comment by aviv926** [comment]
> > I assume that this DNS request was also supposed to be blocked since I chose not to allow unused apps, isn't that right?
> 
> Yes, *WireGuard DNS* bypasses all rules. Probably a stupid decision on our part. We'll fix this in the upcoming version `v055b` due in a day or two.

Thanks, in the case of this query, it was not routed with WireGuard I only configured a number of apps to run through WireGuard.

My setup works like this: 
1. Firewall - Block app not in use
2. DNS - nextdns
3. VPN - WireGuard advance - lockdown only 8 apps all other via regular IP 

Is it still because of the problem you mentioned?

**Comment by ignoramous** [comment]
> Is it still because of the problem you mentioned?

Seems like a different problem to the one I was thinking.

Is `play.eset.com` *trusted* by any app? A DNS request for something that's expected to be *blocked* is only sent if any *trust* rule for it exists.

**Comment by aviv926** [comment]
> > Is it still because of the problem you mentioned?
> 
> Seems like a different problem to the one I was thinking.
> 
> Is `play.eset.com` *trusted* by any app? A DNS request for something that's expected to be *blocked* is only sent if any *trust* rule for it exists.

For the avoidance of doubt I checked and it also happens for example on Reddit, it "allows" itself to communicate with the DNS decoder even though it should be blocked and shown as blocked.



By the way I really appreciate all your support, keep up the great work!

**Comment by aviv926** [comment]
https://github.com/celzero/rethink-app/assets/51673860/52187a83-15bf-49a0-8286-204c2232e629

**Comment by ignoramous** [comment]
Can you check if *any* app is in *Bypass DNS and Firewall* mode? If so, to support the bypassing of rules for that app, all DNS must be resolved regardless (and the DNS rules are applied at *connection* time instead).

**Comment by aviv926** [comment]
> Can you check if _any_ app is in _Bypass DNS and Firewall_ mode? If so, to support the bypassing of rules for that app, all DNS must be resolved regardless (and the DNS rules are applied at _connection_ time instead).

Yes that makes a lot of sense, I actually have some apps that bypass the firewall rules.

**Comment by ignoramous** [comment]
> Yes that makes a lot of sense, I actually have some apps that bypass the firewall rules.

Not just *Bypass firewall* but *Bypass DNS and Firewall* (specifically, wanting some apps to bypass DNS is why ALL DNS queries are always resolved).

**Comment by aviv926** [comment]
> > Yes that makes a lot of sense, I actually have some apps that bypass the firewall rules.
> 
> Not just *Bypass firewall* but *Bypass DNS and Firewall* (specifically, some apps must bypass DNS when ALL DNS queries are always resolved).

Oh so I think there is a bug because I have only Bypass firewall and not DNS and Firewall
And still, all apps can resolve DNS queries.

**Comment by ignoramous** [comment]
If I understand you right, your query is why does DNS resolve even though the app is not in use?

The reason is, ALL DNS requests on Android are sent by ... Android (and not individual apps). In other words, DNS requests are *not* sent to Rethink by apps, but by Android. And so, per-app rules cannot be applied on DNS requests.

**Comment by aviv926** [comment]
> If I understand you right, your query is why does DNS resolve even though the app is not in use?

Yes, that's exactly my question. Maybe we should edit the title accordingly (?)

> The reason is, ALL DNS requests on Android are sent by ... Android (and not individual apps). In other words, DNS requests are _not_ sent to Rethink by apps, but by Android. And so, per-app rules and app-specific universal / global rules cannot be applied on DNS requests.

Oh ok, good to know that, well that 100% solves my question

And I learned new information too, so thanks a lot for all the help, this app is great and the support is even better 🔝

**Comment by ignoramous** [comment]
Fixed in [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d) (should be live on the Play Store and F-Droid in 3 to 10 days from now).

Feel free to reopen.
