### ISSUE TITLE
Intutively handle up and back in Firewall and DNS screens v05x

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#125]
Instagram has fragments within tabs and tabs within fragments but the back and up navigation seem to match mental models just fine.

Explore.

See: https://developer.android.com/guide/navigation

**Comment by ignoramous** [comment]
see also: https://archive.is/JgMVT

**Comment by ignoramous** [comment]
I think, simply navigating to "home" when user goes "back" is enough. This is how some apps (like Swiggy) handle it and it feels intuitive enough. Easier to impl as well, without having to maintain a back-stack...

**Comment by hussainmohd-a** [comment]
Using the in-built navigation component to manage the bottom navigation view, instead of manually handling it. When the user presses the back button, the default behavior will be navigating to the Home page. Will be part of `v054b`
