### ISSUE TITLE
0.5.5c private doh

### ISSUE THREAD

**Issue by li88iioo** [celzero/rethink-app#1251]
Brothers, is there some bug in version 055C? When I use socks 5 and dns, I will be unable to connect to my private doh.

**Comment by ignoramous** [comment]
> When I use socks 5 and dns, I will be unable to connect to my private doh.

In `v055c`, DNS is proxies over SOCKS5, too. In this case, it could be that the *private doh* is not reachable over SOCKS5.

**Comment by ignoramous** [comment]
In upcoming version, we'll let users disable DNS forwarding over proxies: #1271

**Comment by ignoramous** [comment]
Fixed by https://github.com/celzero/rethink-app/commit/370995a9b70c6b388a7fab2164bd21e07c172d4a in `v055d` (live on [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d) and [Website](https://rethinkdns.com/download), pending approvals for Play Store and F-Droid).
