### ISSUE TITLE
v055b: Investigate lower WireGuard speeds

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1252]
[A user says](https://www.reddit.com/r/rethinkdns/comments/1b87o0b/upload_speed_issue_since_055b/),

> Fresh install 0.55.b and importing my wireguard config getting 1mbps upload speed
>
> Rolling back to 0.55.a fix the issue.Getting maximum speed the device is able to archive. Same wireguard config. Using 10 gbps server while testing this issue.

**Comment by jydhthrshrhty** [comment]
Hi, 

I am the user who said this, can provide 10G RAM only servers and wireguards configs. PM me your location, will provide a server near you. Yhe issue persist in 0.55.c going back to version 0.55.a

Thanks

**Comment by ignoramous** [comment]
Speed was relatively unaffected but definitely higher jitter (10ms v 1s) and latency (200ms v 1.8s) connecting to a peer in North America from India. That was due to dropped packets. Fixed.
