### ISSUE TITLE
some issues in 55c

### ISSUE THREAD

**Issue by sinjoe** [celzero/rethink-app#1255]
- opening DNS when using Rethink, it open straight to editing filter, instead of opening Main DNS menu. Using other DNS doesn't have this issue.
- If one of the wireguard has lockdown enabled, even if the wireguard profile itself is disabled. There is no internet connection.
- Can't proxy through Orbot with HTTP proxy option. Leaving proxy menu after choosing HTTP proxy will revert back to None (default). TCP-only proxy works however.

**Comment by ignoramous** [comment]
> opening DNS when using Rethink, it open straight to editing filter

Expected. This was done in response to user feedback. 

> one of the wireguard has lockdown enabled, even if the wireguard profile itself is disabled. There is no internet connection.

Expected. Lockdown means apps that are part of a WireGuard profile would only be able to connect to Internet via that profile, regardless of whether it is connected.

Unexpected if apps that aren't part of the profile also lose connection. Is that what you're seeing?

> Can't proxy through Orbot with HTTP proxy option. Leaving proxy menu after choosing HTTP proxy will revert back to None (default). 

Thanks. Will take a look. We've got multiple reports on this.

**Comment by ignoramous** [comment]
Closing this issue in favour of #1258. Feel free to reopen.

Thanks again (:
