### ISSUE TITLE
v055b post-build version check failed on F-Droid 

### ISSUE THREAD

**Issue by michaelblyons** [celzero/rethink-app#1256]
There's a version check failure after build. Expected v0.5.5b, got v055b.

Is v055c also going to have the same problem? ♥️

**Comment by ignoramous** [comment]
I think this problem happened once before and an F-Droid volunteer had to fix it themselves. I'll monitor. Thanks.

**Comment by michaelblyons** [comment]
v055c is in the F-Droid store. 🎉
