### ISSUE TITLE
Apps reappear as unnamed/untitled ("unbenannt")

### ISSUE THREAD

**Issue by sereksim** [celzero/rethink-app#1257]
A few days ago, the app started to newly register most of my installed apps as unnamed/untitled.
I enabled blocking the internet for newly installed apps so all my installed apps were blocked again. The app-list now contains the installed apps with their names like before but additionally many entries of "unnamed/untitled" apps, each being one of the already installed apps. Every rule I had for these apps is still at the old entry with its name, but does not work because it is overruled by the unnamed one.
<details>
<summary>Screenshot</summary>
(All "unbenannt" Apps were blocked initially, I unblocked some of them to be able to use them)

![signal-2024-03-09-164824](https://github.com/celzero/rethink-app/assets/74626816/b041d944-8398-4ea2-811e-e7e728fe6629)

</details>

**Comment by ignoramous** [comment]
Thanks. A bug we fixed in `v055c`. What version are you using? Check the footer of the "About" UI in the app.
