### ISSUE TITLE
v055b: Orbot HTTP CONNECT always fails

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1258]
https://github.com/celzero/rethink-app/issues/1255#issue-2176694799

**Comment by ThreeDeeJay** [comment]
I also noticed this even in v0.0.5c

By the way, Is there a way to ensure whitelisted apps _always_ use Orbot or just block connection if Tor connection fails?
Even with the v0.0.5a, Orbot mode would randomly get disabled (especially after a reboot where I've always had to manually re-enable it) which would make whitelisted apps leak into direct/non-proxied traffic.

Speaking of rebooting, doing it after enabling Block apps without VPN causes this error:
```
Warning: Rething has been deactivated
Tap to change protection setting
```
![image](https://github.com/celzero/rethink-app/assets/71472458/1dfedd25-2606-4145-aa4d-3f4535e93c7d)

Also I noticed TCP-only Proxy sometimes immediately reverts back to None (default), which I hadn't seen happening in v0.0.5a 

I know these are probably unrelated issues, but I figured I'd ask here before opening new ones 😅 

Just one last thing: what are the pros and cons of HTTP proxy vs TCP proxy? 🤔

**Comment by ignoramous** [comment]
> what are the pros and cons of HTTP proxy vs TCP proxy

None that matter. Different tunneling protocols connecting into Orbot (which is running locally on the device).

> Also I noticed TCP-only Proxy sometimes immediately reverts back to None (default), which I hadn't seen happening in v0.0.5a

This means, Rethink failed connecting to Orbot. I don't think Rethink switches to "None" otherwise, but we'll take a look: https://github.com/celzero/rethink-app/issues/1261 Do you know if it happens all the time or just randomly? Any set of steps that makes this behaviour more likely?

> Speaking of rebooting, doing it after enabling Block apps without VPN causes this error:
> ```Warning: Rething has been deactivated
Tap to change protection setting```

Yeah, I've seen this too and this happened in earlier versions as well (which we thought we fixed): #825 / #1200 etc

> By the way, Is there a way to ensure whitelisted apps always use Orbot or just block connection if Tor connection fails?

Not yet: #976

**Comment by ThreeDeeJay** [comment]
> Yeah, I've seen this too and this happened in earlier versions as well (which we thought we fixed): #825 / #1200 etc

I had never noticed it in earlier versions, tough tbf I avoided Block apps without VPN because it didn't work with Orbot. Still kinda ironic it does the exact opposite of what we'd expect 😂

**Comment by ignoramous** [comment]
> tough tbf I avoided Block apps without VPN because it didn't work with Orbot

btw, `v055b` onwards, Orbot works with *Block connections without VPN* (aka *VPN Lockdown* mode) just fine (implemented by #393)

**Comment by ThreeDeeJay** [comment]
Yeah, but what I meant is that the reason why I still don't use VPN Lockdown is that now it completely crashes/shuts down the whole VPN when rebooting, which I think lets traffic through, completely defeating the purpose of an "always-on" VPN 😅

On a side note, I noticed that when rebooting, before unlocking the lockscreen, Wi-Fi is connected but ReThink isn't active.
Does that mean that it's leaking all/some traffic, or is it just idle till unlocking? I think AFWall used to require an addon to fix a startup leak, so I wonder if ReThink is also vulnerable, especially now that I have to disable VPN lockdown 🤔

**Comment by ignoramous** [comment]
> completely crashes/shuts down the whole VPN when rebooting, which I think lets traffic through, completely defeating the purpose of an "always-on" VPN

No, it wouldn't if *Block connections without VPN* is enabled. That is, unless the VPN (Rethink in this case) routes outgoing connections, they will be blackholed by the OS.

> Does that mean that it's leaking all/some traffic, or is it just idle till unlocking

Depends on just when the OS starts the VPN service (Rethink doesn't control the timing). With *Block connections without VPN*, no traffic should leak.

**Comment by ignoramous** [comment]
Seems like there's confusion if SOCKS5 (TCP) or HTTP scheme should be set for forwarding to Orbot, when in fact HTTP is selected.

```
03-20 03:40:11.532  5642 10164 I VpnLifecycle: Initiate orbot start with type: HTTP
03-20 03:40:11.634  5642  5642 D VpnLifecycle: on pref change, key: proxy_proxyprovider
03-20 03:40:11.635  5642  5642 D VpnLifecycle: on pref change, key: proxy_proxytype
03-20 03:40:11.636  5642 16156 D VpnLifecycle: selected proxy type: HTTP, with provider as ORBOT
03-20 03:40:11.637  5642 16156 D VpnLifecycle: handle proxy change, proxy: ORBOT
03-20 03:40:11.642  5642 18802 I GoLog   : config.go:254: I proxyopt: no user() and/or pwd(0)
03-20 03:40:11.642  5642 18802 I GoLog   : multihost.go:83: D multihost: with [] => [127.0.0.1]
03-20 03:40:11.642  5642 18802 I GoLog   : socks5.go:125: D proxy: socks5: created ORBOT with clients(1), opts(,,127.0.0.1:9050)
03-20 03:40:11.642  5642 10164 I VpnLifecycle: Proxy mode set with tunnel url(ORBOT): socks5://127.0.0.1:9050, result: backend.Backend$proxyProxy@1e82d8c
03-20 03:40:11.642  5642 18802 I GoLog   : proxy.go:110: I proxy: added ORBOT/socks5/127.0.0.1:9050
03-20 03:40:11.642  5642 18802 I GoLog   : socks5.go:224: I proxy: socks5: stopped ORBOT
03-20 03:40:11.642  5642 10164 I VpnLifecycle: Socks5 mode set: 127.0.0.1,9050
03-20 03:40:11.649  5642 22507 I GoLog   : config.go:238: I proxyopt: ipport(:) is url?(not an ip:port)
03-20 03:40:11.654  5642  5642 D VpnLifecycle: on pref change, key: proxy_proxyprovider
03-20 03:40:11.658  5642  5642 D VpnLifecycle: on pref change, key: proxy_proxytype
03-20 03:40:11.659  5642 10164 D VpnLifecycle: selected proxy type: NONE, with provider as NONE
03-20 03:40:11.659  5642 10164 D VpnLifecycle: handle proxy change, proxy: NONE
03-20 03:40:11.669  5642 16156 E VpnLifecycle: error setting http proxy: unsupported proxy scheme
03-20 03:40:11.669  5642 16156 E VpnLifecycle: go.Universe$proxyerror: unsupported proxy scheme
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at backend.Backend$proxyProxies.addProxy(Native Method)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.setHttpProxyIfNeeded(GoVpnAdapter.kt:602)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.setCustomProxy(GoVpnAdapter.kt:538)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService.handleProxyChange(BraveVPNService.kt:1523)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService.access$handleProxyChange(BraveVPNService.kt:116)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onSharedPreferenceChanged$9.invokeSuspend(BraveVPNService.kt:1411)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onSharedPreferenceChanged$9.invoke(Unknown Source:8)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onSharedPreferenceChanged$9.invoke(Unknown Source:2)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$io$1.invokeSuspend(BraveVPNService.kt:2380)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
03-20 03:40:11.669  5642 16156 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
03-20 03:40:12.392  5642 16156 I VpnLifecycle: after timeout, isOrbotUp? true
```

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/commit/a7e062e54d78602aeb41b53918bc183df24aabaf

**Comment by ThreeDeeJay** [comment]
Also confirmed fixed on my end. Thanks! 👍
