### ISSUE TITLE
Routing of .onion DNS Querys diffrent as before?

### ISSUE THREAD

**Issue by M-u-m-p-i-t-z** [celzero/rethink-app#1259]
latest version c

Before upgrade I used Orbot DNS Proxy on Port 5400 and the option in RethinkDNS to route all DNS querys to the set DNS Proxy .
Ok since now with the lastest update, this doesn’t work anymore, the DNS query is routed to 127.0.01:53 and gives error send_fail in log.

This DNS query comes from mail client with a .onion adress as smtp, so it must route to Orbot to get an IP, but it doesn't anymore.

Is this the right behavior, do I have to change settings or is this behavior not wanted?

thank you

**Comment by ignoramous** [comment]
`.onion` is sent to system set DNS, as it is considered an "undelegated domain". We inherited this behaviour from [dnscrypt-proxy](https://github.com/dnscrypt-proxy/dnscrypt-proxy).

We'll fix this in the upcoming release. Thanks for reporting.
