### ISSUE TITLE
Block 853 on VPN DNS

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1265]
To prevent the OS flooding the tunnel thinking there's a genuine DoT server running at `10.111.222.3:853`, firewall packets sent to port `853`, by default.

---

I have a suspicion what is wrong. The routing tables are

```
$ ip route show table 0|grep 10.111                                                                                                                              
10.111.222.0/24 dev tun1 table 1044 proto static scope link 
10.111.222.3 dev tun1 table 1044 proto static scope link 
10.111.222.0/24 dev tun1 table 1000000044 proto static scope link 
10.111.222.3 dev tun1 table 1000000044 proto static scope link 
10.111.222.0/24 dev tun1 proto kernel scope link src 10.111.222.1 
broadcast 10.111.222.0 dev tun1 table local proto kernel scope link src 10.111.222.1 
local 10.111.222.1 dev tun0 table local proto kernel scope host src 10.111.222.1 
local 10.111.222.1 dev tun1 table local proto kernel scope host src 10.111.222.1 
broadcast 10.111.222.255 dev tun1 table local proto kernel scope link src 10.111.222.1 
```
so that Android thinks that 10.111.222.3 is the address of the VPN server. Apparently the Android DNS sometimes tries to get DNS services from the VPN server and tries to connect there. Accessing10.111.222.3 through the vpn tunnel all ports are open and a connection can be opened which does confuse the DNS.

I believe when accessed from inside the tunnel all ports on 10.111.222.3 should be closed.

https://github.com/celzero/rethink-app/issues/1231#issuecomment-1987423345

**Comment by hussainmohd-a** [comment]
Fixed: [trapVpnPrivateDns](https://github.com/celzero/rethink-app/blame/503ad490d68a2fb7d8b28b391be47f4f647001f3/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L2954)
