### ISSUE TITLE
Disable "Enable network visibility" if any Proxy is in Lockdown

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1267]
A user reports that otherwise IP leaks through (which is expected) as apps can bind to any interface other than the VPN tunnel's.

> Not use enable network visibility  
> can hide my ip

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/commit/370995a9b70c6b388a7fab2164bd21e07c172d4a
