### ISSUE TITLE
v055b: System DNS is always set to Fallback DNS

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1268]
> > Are you using it as "System DNS" or setting up a new "DNS Proxy" instance that connects to dnsmasq?

I use the system dns option. If I set my local dns via other dns there is no error show, but as it is a local dns it does not help, when I am not at home.

> > For me it seems to be a ui error
> 
> Likely. Fallback DNS is only used when user-selected DNS cannot be setup. This instance should be rare except for "System DNS".

The error with using fallback does not go away, but it works. Another thing I mention. If I start the dns/firewall service the error comes after some time. If I change the visable app to another and then back the error is show immediately.

If i change the code in app/src/full/java/com/celzero/bravedns/ui/fragment/HomeScreenFragment.kt so the error is not shown the speed of the dns server somtimes changes. I don't understand the code for the ui. Changing the timeouts does not help.

>         if (VpnController.isOn()) {
>            val status = VpnController.getDnsStatus(id)
>            // status null means the dns transport is not available / different id is usedE
>            if (status == null) {
>                if (retryCountForDnsStatus < 5) {
>                    retryCountForDnsStatus++
>                    delay(TimeUnit.SECONDS.toMillis(1), lifecycleScope) {
>                        if (isAdded) {
>                            updateUiWithDnsStates(dnsName)
>                        }
>                    }
>                }
>                //b.fhsCardDnsLatency.visibility = View.VISIBLE
>                //b.fhsCardDnsFailure.visibility = View.GONE
>                b.fhsCardDnsLatency.visibility = View.GONE
>                b.fhsCardDnsFailure.visibility = View.VISIBLE
>                b.fhsCardDnsFailure.text = getString(R.string.failed_using_default)
>                b.fhsCardDnsLatency.isSelected = true
>            } else {
>                b.fhsCardDnsLatency.visibility = View.VISIBLE
>                b.fhsCardDnsFailure.visibility = View.GONE
>            }
>        }

Also if the error with fallback dns is shown, disable and reenable the dns/firewall does not help. Only changing the dns to not be system dns works (also to custom dns which ist the ip of the system dns). 

Regardless of the status in ui the system dns seems to work.

_Originally posted by @celle1234 in https://github.com/celzero/rethink-app/issues/1253#issuecomment-1988154180_

**Comment by celle1234** [comment]
It seems to be fixed in v055d.

**Comment by hussainmohd-a** [comment]
Thanks for the confirmation, Fix: https://github.com/celzero/rethink-app/commit/4176b8e20b02d09981e48eac4615c789bafb92df
