### ISSUE TITLE
v055b: Exclude apps from Proxies

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1270]
A user says,

> Can someone clarify a few things please?
> 
> 1. How to add new apps automaticly to the VPN profile.
> 2. How to permanently exclude some apps from the VPN profile.
> 3. How to be sure that the DNS traffic will always go through the VPN?

**Comment by weedy** [comment]
This is exactly what I was looking for. I'd like to enable always on in setting of advanced WG tunnels and exclude a few apps.
(Banking, LAN scanner, etc)

**Comment by ignoramous** [comment]
> LAN scanner

You probably want to *Exclude* LAN/P2P apps altogether from Rethink. This setting only "bypasses" all active proxies for this app's connections.

**Comment by ignoramous** [comment]
Impl in [`v055l`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5l) in *Configure* -> *Apps* -> (search for app, tap on its entry) -> turn ON *Bypass app from all proxies*
