### ISSUE TITLE
v055c breaking some DNS servers

### ISSUE THREAD

**Issue by Artim96** [celzero/rethink-app#1275]
It seems that v055c breaks some DNS servers. I have no trouble using e.g. Cloudflare or Google - though only DoH - but e.g. the build in Quad9 DoH, Cloudflare and Google DoT or custom servers like dns.digitale-gesellschaft.ch/dns-query (for DoH) or dns.digitale-gesellschaft.ch and dns3.digitalcourage.de (for DoT) just don't work. Besides the fact that after switching the server, disabling Rethink and enabling it, it keeps saying "waiting" and no web page would load. Didn't have that issue with v055a (never used v055b though).

Bug report from the app is attached.

[rethinkdns.bugreport.zip](https://github.com/celzero/rethink-app/files/14575580/rethinkdns.bugreport.zip)

Edit: DNSCrypt Quad9 works like a charm, ODoH Cloudflare on the other hand doesn't even though it shows protected quite quickly.

**Comment by ignoramous** [comment]
Starting `v055c`, Rethink uses "fallback DNS" (which is really a badly named "default" DNS) to resolve hostnames for its own self.

You'll spot entries in the *DNS Log* UI with "*resolved x mins ago by `rethink.`address*" for queries resolved by "fallback" DNS.

![Screenshot_2024-03-13-01-23-18-09_c8cbde12d3521911922be4eee6a05664~2](https://github.com/celzero/rethink-app/assets/852289/977419d2-798f-45aa-bc3f-6fba1abcf719)

In *Configure* -> *Network*, what is *Choose fallback DNS* set to? If `None`, it uses network/OS provided DNS (aka `System DNS`). If set to Google, Cloudflare, or Rethink, then it uses one of those resolvers.

**Comment by ignoramous** [comment]
> Ah, thanks. It was set to Google. I switched to None and now it works again

Is Google DNS blocked in your network?

> What is it used for

"fallback" DNS is used by Rethink but not exclusively. Rethink may use "fallback" in case there are no other active / legit user-preferred DNS transports (usually only happens for DNSCrypt where, say, the periodic cert validation done in background fails).

**Comment by Artim96** [comment]
No, Google should not be blocked. I tried with both my home WiFi that's already set to use DoT and with mobile network. It doesn't make sense that this causes errors, especially considering that not all DNS servers are broken. But at least the fix - even if it's just a stopgap solution - is easy enough.

**Comment by ignoramous** [comment]
> No, Google should not be blocked. 

Interesting:

> > What error do you see in *DNS Log*s UI (the final error msg is shown at the footer of the bottomsheet that comes up when you tap on individual entries)?

**Comment by Artim96** [comment]
> What error do you see in _DNS Log_s UI (the final error msg is shown at the footer of the bottomsheet that comes up when you tap on individual entries) when Google is selected as "fallback" DNS?

Where exactly do I see that? In the Logs in the DNS tab there are no entries added at all after switching to Google as fallback DNS.

**Comment by ignoramous** [comment]
> In the Logs in the DNS tab there are no entries added at all after switching to Google as fallback DNS.

Gotcha. I can reproduce this in `v055c` (I was on some other commit which didn't have this issue). We're fixing this in multiple places so this wouldn't happen.

**Comment by ignoramous** [comment]
Fixed in [`v055d`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d) (should be live on Play Store within this week, and F-Droid within the week after this one).

Feel free to reopen if that isn't the case.
