### ISSUE TITLE
v055c: Always-on WireGuard leaks conns when phone is restarted

### ISSUE THREAD

**Issue by 8itlew7r** [celzero/rethink-app#1277]
Possible bugs based on experience:

- It says "PROTECTED WITH WIREGUARD" even though it doesn't redirect connections to the VPN server.

- Happened to me twice.

- Auto-start on power up is dissabled.

**Comment by ignoramous** [comment]
> It says "PROTECTED WITH WIREGUARD" even though it doesn't redirect connections to the VPN server

A few questions: 
- Was the WireGuard config not *active*?
   - What was its status (failing, connected, starting)?
- Was WireGuard in *Simple* mode or *Advanced* mode?
   - If in *Advanced* mode: Was the WireGuard config *Lockdown*?
- Is *Configure* -> *Network* -> *Enable network visibility* turned ON?

**Comment by 8itlew7r** [comment]
> - Was the WireGuard config not *active*?
There are 2 configs, one is active and the other is not.

>    - What was its status (failing, connected, starting)?
Unfortunately, I didn't notice. But I will let you know if it happens again.

> - Was WireGuard in *Simple* mode or *Advanced* mode?
Advanced mode.

>    - If in *Advanced* mode: Was the WireGuard config *Lockdown*?
Yep. And always on.

> - Is *Configure* -> *Network* -> *Enable network visibility* turned ON?
Nope. It is disabled because the RethinkDNS application is in lockdown mode.

---

I can't reproduce the bug. Maybe because I removed the second inactive config and changed something. Just be aware that this bug is still lurking.

**Comment by 8itlew7r** [comment]
Also I had to press the stop and start button to fix the VPN leak.

**Comment by ignoramous** [comment]
Thanks.

Rethink should never leak connections of "Always-on" is turned ON.

> says "PROTECTED WITH WIREGUARD" even though it doesn't redirect connections to the VPN server.

How did you verify the leaks? By looking at the *Network Log*s? Or, verifying it externally at router / access point / server?

**Comment by 8itlew7r** [comment]
> How did you verify the leaks? By looking at the *Network Log*s? Or, verifying it externally at router / access point / server?

Yeah, by looking at the network logs, there is no label that says "proxied", and also by checking my IP address in ipwho.de

**Comment by 8itlew7r** [comment]
> There are 2 configs, one is active and the other is not.

The bug happened again.

The label of 3 proxy says "Failing" even though RDNS says "PROTECTED WITH WIREGUARD".

Do you have a Proton Mail account? I can send you the bug report there, or I'll just send it encrypted.

**Comment by ignoramous** [comment]
> The label of 3 proxy says "Failing" even though RDNS says "PROTECTED WITH WIREGUARD". Do you have a Proton Mail account? I can send you the bug report there, or I'll just send it encrypted.

This is a separate issue and since it is reprodcible pretty readily, we've since fixed it, too. Thanks for the report.

**Comment by 8itlew7r** [comment]
> separate issue

I assume you're talking about the VPN leak.

**Comment by ignoramous** [comment]
> assume you're talking about the VPN leak

Two scenarios:
- If WireGuard is *failing* it shouldn't leak traffic. If it does, that's a separate bug to this (which is about leaks when Android is restarted).
- Today, WireGuard shows *failing* even when it is really *idling*. Next version will distinctly identify *idle but connected* WireGuards.

**Comment by 8itlew7r** [comment]
I had trouble connecting to a website on all three of my configurations. Also, I noticed a VPN leak (without rebooting) on one of them, even though the 'always on' setting was enabled. However, switching to simple mode fixed both issues. It seems that the bug only affects the advanced setting.

**Comment by ignoramous** [comment]
Yeah, we've since fixed these leaks. Expect a release in a day or so. Things are looking up in tests (as of today).

**Comment by 8itlew7r** [comment]
> There are spurious packet drops #515  Unsure if that's what's affecting your configs, too. If you're technical enough, what do you see in `adb logcat` (turn ON *Verbose* mode from *Configure* -> *Settings* -> *Log Level*)?

I mean absolutely no internet connection, with no data packets being transmitted. Previously, only 2/3 of the Wireguard configurations would work, followed by 1/3, and then none would allow me to connect to the internet. However, the simple mode not only resolves this issue, but also improves connection speed.

**Comment by ignoramous** [comment]
Released fixes for this issue in [`v055e`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e). Please feel free to reopen if that's not the case.

> I mean absolutely no internet connection, with no data packets being transmitted. Previously, only 2/3 of the Wireguard configurations would work, followed by 1/3, and then none would allow me to connect to the internet.

As a workaround, try tapping on `Refresh` button at the top right hand corner in *Configure* -> *Proxy* UI the next time this happens, and see if WireGuard (advanced) recovers.

We are tracking a fix for connection drops related to device waking up from deep sleep here:
- #1368

**Comment by ignoramous** [comment]
https://github.com/celzero/rethink-app/commit/370995a9b70c6b388a7fab2164bd21e07c172d4a
