### ISSUE TITLE
v055b: WireGuard frequent reconnects?

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1279]
A user says,

> for example some forum, opening a thread page often takes 5+ or 10+ seconds, even that DNS logs are showing less than 5ms. On the other hand, sometimes it's instantly, so I thought WireGuard might be dropping a connection and reconnecting again, hence why a slow loading

https://github.com/celzero/rethink-app/issues/1276#issuecomment-1992646624

**Comment by ignoramous** [comment]
From [`v055d`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d), only attempt a refresh ("reconnect") if the *active* network (WireGuard sockets are bound to) changes: https://github.com/celzero/rethink-app/commit/370995a9b70c6b388a7fab2164bd21e07c172d4a

https://github.com/celzero/rethink-app/blob/10dd9d517e88bd8635bb43febb6895e237b85593/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L1919-L1925

**Comment by Magicrafter13** [comment]
> From [`v055d`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d), only attempt a refresh ("reconnect") if the _active_ network (WireGuard sockets are bound to) changes

Could this be made into a toggle? I use ProtonVPN through the wireguard interface of rethink, and it frequently has issues requiring me to turn it off and back on, which aside from being annoying, also means I can't keep my apps proxied (even if only for <1 second).

**Comment by ignoramous** [comment]
>  use ProtonVPN through the wireguard interface of rethink, and it frequently has issues requiring me to turn it off and back on, which aside from being annoying

You can opt to set *Persistent KeepAlive* to any value, ideally between 30s to 2m.
