### ISSUE TITLE
After Restart Rethinkdns stopped working

### ISSUE THREAD

**Issue by LovingNumbers** [celzero/rethink-app#1281]
Has been solved. Keeping it open for the others.

**Comment by ihatemakinganaccount** [comment]
Looks like the servers are down today

**Comment by DINKIN** [comment]
Had to uninstall & remove VPN profile

Everything failing

Wireguard sessions not even working

**Comment by LovingNumbers** [comment]
> Had to uninstall & remove VPN profile
> 
> Everything failing
> 
> Wireguard sessions not even working

yeah something weird is happening rn hope it's nothing too bad

**Comment by Imold** [comment]
> `max.rethinkdns.com` is up (and also serving `sky.rethinkdns.com` traffic, right now).
Any way you could use `max.rethinkdns.com` to let us download the blocklist?

**Comment by ignoramous** [comment]
> Any way you could use max.rethinkdns.com to let us download the blocklist?

On `dl.rethinkdns.com` (where the blocklists are hosted on), egress (downloads) is *free*. on Fly.io (where `max.rethinkdns.com` runs) is expensive for hosting file downloads.
