### ISSUE TITLE
Unsolicited DNS Servers Shown on DNS Leak Test Results!?

### ISSUE THREAD

**Issue by SevenFactors** [celzero/rethink-app#1282]
Tested on Rethink App ver 0.55a (fdroid) & now ver 0.5.5c (github) both on regular android 10 and GrapheneOS (latest)

**Issue**

While testing for DNS leaks I came to notice some odd results. Besides my custom set DoH (NextDNS), I get a bunch of Google DNS results all from a different city/state. The only local result is my set DoH provider. 

The only result I should be getting is NextDNS or whatever DNS provider I set sans any other DNS provider IPs but for some reason this is happening.

// _**Is this happening to anybody else?**_   //

**Things to Note**

- I tested same NextDNS profile on said devices sans Rethink app and the results I got only showed the expected NextDNS IP, server name etc.

- I have Rethink-App's Fall Back DNS to None

- Tested with and without "Block Connection without VPN"

- I've tested with Cloudflare DoH/DNScrypt and also got the same results.

- Quad9 yielded the same results but after lots of tests results are from Quad9 (Woodynet)

- I don't want to keep running back to back test as I don't want to run into issues with mullvad.

- I also ran some "extended" tests at dnsleaktest.com but these only yield my set DoH IP.

**Comment by ignoramous** [comment]
Do you have *Configure* -> *DNS* -> *Show website icon in DNS logs* enabled?

Which website are you using to test DNS leaks?

**Comment by YellowRoseCx** [comment]
Check to make sure your browser settings and your phone connection settings isn't using a Google DNS server or else it will use both as you're experiencing
Also, I like to check with https://ipleak.net

**Comment by ignoramous** [comment]
Disable that and then test for "leaks"? I usually use, `browserleaks.com/dns`. Thanks.

**Comment by SevenFactors** [comment]
> Disable `Show website icon in DNS logs` (turn it OFF) and then test for "leaks"? I usually use, `browserleaks.com/dns`. Thanks.

With the option disabled there is no issue. I will just leave it off for now. After all, it is in a experimental stage.

**Comment by ignoramous** [comment]
> After all, it is in a experimental stage.

To be clear, turning it ON doesn't leak DNS. It confuses the remote server attempting to detect "leaks".

**Comment by brookzee** [comment]
> > After all, it is in a experimental stage.
> 
> To be clear, turning `Show website icon in DNS logs` ON doesn't leak DNS. It confuses the remote server attempting to detect "leaks".

Issue should remain open.

This is not true, atleast on my device build.  I can confirm after weeks trying to figure out where the Google LLC leaks were coming from (same as OP's issue) Including testing various DNS providers, auth methods, and Firefox about:config settings, simply turning this setting OFF fixed the leaks.

The leaks were only visible on browserleaks.com/ip
Using dnsleaktest.com or ipleak.net did not detect them FYI with the setting ON

user-agent: Mozilla/5.0 (Linux; Android 14; Mobile; rv:12 7.0) Gecko/127.0 Firefox/127.0
app-version:0.5.5e

Can provide more device debug info if required.

**Comment by ignoramous** [comment]
> This is not true

Wev services like `dnsleaktest.com` etc don't really test for "leaks" (they can't), but rather test for something adjacent to a "leak". What they classify a leak needn't be one.

There are many open source versions of these "leak tests", one of which you can find here: https://github.com/redirect2me/which-dns?tab=readme-ov-file

**Comment by brookzee** [comment]
Okay good to know but The Google LLC leak as shown and same as OP issue was
from browserleaks.com check. Again turing OFF show icons fixed the issue.
Maybe the function of it has a bug or there was some favicon surveillance
plant file downloaded somehow in that storage location that was able to
call out.

**Comment by okcprime** [comment]
its not DNS leak . NextDNS has Their Assigned Servers hosted in differrent Cloud platform some of themare Hosted using GCP and thats what shows GOOGLE LLC ( ISP )
