### ISSUE TITLE
Proxy app must now be manually granted internet access

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#1288]
("Regression" since `v055a`; not sure if this is intentional or not as I couldn't find an obvious associated change in the commit list.)

I'm using sing-box as a SOCKS5 proxy in Rethink (configured to route certain internal IPs via an SSH tunnel, and bypass the rest), but after upgrading to `v055c`, connections were being blocked.  sing-box was in _Isolate_ state with no rules -- previously the proxy app automatically bypassed the firewall, but that doesn't seem to be the case any more.  For setting up a new proxy, it's not exactly obvious that you need to give it unrestricted access, in order to handle all requests being handed to it.  If not granted internet access, the home screen status seems to change repeatedly between _Protected with SOCKS proxy_ and _No connection_.

Relatedly, proxy app requests now appear in the log -- while I'd say in general more complete logs are better, it means every request is duplicated in the log: the source app with associated domain and 🗝 icon, and the proxy without either (because DNS happened outside the proxy, it just connects direct to an IP).  For typical use, I think keeping them hidden would make the log more usable.

**Comment by ignoramous** [comment]
> connections were being blocked. sing-box was in Isolate state with no rules

Set sing-box so as to allow connections?

> previously the proxy app automatically bypassed the firewall, but that doesn't seem to be the case any more

Yeah previously, such apps had to be "excluded" from the VPN tunnel altogether (which meant these apps essentially bypassed DNS and Firewall). In `v055b`+, such apps are kept within the tunnel, and so these apps can be monitored with the Firewall, just like any other app.

> not sure if this is intentional or not as I couldn't find an obvious associated change in the commit list

Were a series of commits over 3+ months (not documented in a single place) addressing #393

> For typical use, I think keeping them hidden would make the log more usable

Perhaps. Will think about how to best to filter these out to a separate screen. It isn't trivial, so we may not get around to doing it for a long time.

**Comment by Terrance** [comment]
Ah yes, putting sing-box into _Bypass_ mode is effectively the old behaviour of requests not being logged because they run outside of Rethink.  That said:

> In `v055b+`, such apps are kept within the tunnel, and so can be monitored with the Firewall, just like any other app.

This is cool and the extra visibility is ultimately a win (e.g. if your proxying app makes nefarious requests of its own that end up needing _Block_ rules), so I'll be keeping it in _Allow_.

> Will think about how to best to filter these out to a separate screen. It isn't trivial, so we may not get around to doing it for a long time.

I can at least get a proxy-free log by filtering to Allowed > Proxied (as everything is proxied except for the proxy traffic itself), and a separate Blocked filter (which never reach the proxy), so that's good enough for now.

**Comment by ignoramous** [comment]
Yeah, routing those apps within Rethink is superior. But I really wonder for your battery life using Rethink and Sing Box together ;)

> For typical use, I think keeping them hidden would make the log more usable

Noted: https://github.com/celzero/rethink-app/issues/1247#issuecomment-2001845648

Thanks.
