### ISSUE TITLE
Geoblocking

### ISSUE THREAD

**Issue by iulko** [celzero/rethink-app#1291]
(just an idea, not a piority at all, maybe for like version 0.85)

As rethink already have database of IP-Country, maybe we could use that database to block our phone from contacting specific country IPs

**Comment by ignoramous** [comment]
Thanks.

The geoip db (from `db-ip.com`) Rethink uses is not that high quality (as it is the free version).

But this request isn't new. Please track at: #590 

(closing. feel free to reopen if #590 doesn't cover the request here)
