### ISSUE TITLE
v055c: After Loopback, Rethink shows as "blocked" in Apps

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1292]
When Loopback is enabled, Rethink appears as any other installed app. Today, firewall and DNS rules do not apply to Rethink. The UI controls are disabled. Though the label shown "blocked" can be changed to something more indicative of why users can't change rules for Rethink.

<details>
<summary>screenshot</summary>
after loopback is enabled:

![rinr](https://github.com/celzero/rethink-app/assets/852289/36d23e6d-078e-4f44-bbe2-36fbdf2eb2ec)
</details>

([*source*](https://www.reddit.com/r/rethinkdns/comments/1bgw28h/blocked/))

**Comment by hussainmohd-a** [comment]
Internally, no firewall rules will be applicable for Rethink. This was an UI issue, which has now been fixed. You can find the fix here: https://github.com/celzero/rethink-app/pull/1301/commits/2187896eae9f6e4d481a840f01782a1ad58aa514. Now Rethink will be shown as _Allowed_
