### ISSUE TITLE
Chaining proxies

### ISSUE THREAD

**Issue by plkonbklo** [celzero/rethink-app#1296]
Is it possible to chain the proxies?
E.g. setup two wireguard connections wg1 and wg2 and configure Rethink to route wg2 over wg1?

**Comment by ignoramous** [comment]
Don't think WireGuard in WireGuard is possible without co-ordination from Peers (endpoints). Tor in WireGuard or SOCKS5 in WireGuard must be possible, with I imagine some terrible performance.

If you're interested in proxies, check out [Nekohasekai's Sing Box](https://github.com/SagerNet/sing-box) or [eycorsican's Leaf](https://github.com/eycorsican/leaf).

**Comment by plkonbklo** [comment]
Thank you for your suggestion, I didn't think about using Rethink+sing-box.
I'll try to configure the sing-box with chained proxies and socks5/wg server on localhost and then connect the Rethink to this local proxy. I'll report back with the results.
Also does SOCKS5 client in Rethink support proxying UDP traffic?
I've found this completed issue:
https://github.com/celzero/rethink-app/issues/421
That seems to imply that UPD over SOCKS5 support was implemented but it's not mentioned specifically.

**Comment by ignoramous** [comment]
> Also does SOCKS5 client in Rethink support proxying UDP traffic?

Yes, it does. Unsure if it works perfectly, though ;)

**Comment by plkonbklo** [comment]
I've tested rethink + sing-box and it work just as I wanted it to.
Example sing-box config for those who are interested in this:
```
{
    "inbounds": [
        {
            "type": "socks",
            "tag": "socks-in",
            "listen": "127.0.0.1",
            "listen_port": 2080,
            "users": [
              {
                "username": "rethink",
                "password": "somepassword"
              }
            ]
        }
    ],
    "outbounds": [
        {
          "type": "wireguard",
          "tag": "wg-out0",

          "server": "1.2.3.4",
          "server_port": 12345,
          "local_address": [
            "10.1.1.2/32"
          ],
          "private_key": "X",
          "peer_public_key": "X",
          "pre_shared_key": "X"
       },
        {
          "type": "wireguard",
          "tag": "wg-out1",

          "server": "1.2.3.4.6",
          "server_port": 123456,
          "local_address": [
            "10.1.2.2/32"
          ],
          "private_key": "X",
          "peer_public_key": "X",
          "pre_shared_key": "X",
          "detour": "wg-out0"
        }
    ],
    "route": {
        "final": "wg-out1"
    }
}
```
