### ISSUE TITLE
Separate ABIs for F-Droid

### ISSUE THREAD

**Issue by shuvashish76** [celzero/rethink-app#1299]
Currently the universal apk size on F-Droid is bit heavy (~60MB), request to split it by their architecture.

**Comment by ignoramous** [comment]
Does F-Droid support [multi APK builds](https://developer.android.com/build/configure-apk-splits)?
- #526

**Comment by shuvashish76** [comment]
Yes for example see [KOReader](https://f-droid.org/en/packages/org.koreader.launcher.fdroid/), [Seal](https://f-droid.org/en/packages/com.junkfood.seal/), [SchildiChat](https://f-droid.org/en/packages/de.spiritcroc.riotx/),  etc.. For each specific version they've multiple apks  (x86, x86_64, armeabi-v7a, arm64-v8a)

**Comment by ignoramous** [comment]
Gotcha. Please track at #47 (I've moved your comments there).
