### ISSUE TITLE
DNS log filters (ui)

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#13]
Currently, there's no way to filter just the blocked traffic on the app. Provide a way to filter blocked traffic vs all traffic on the DNS log page. 

Add an indicator to the entry against blocked DNS traffic (with a "red" border or some such) to distinguish it from allowed DNS traffic.

**Comment by ignoramous** [comment]
Some more filter ideas:

1. Country?
2. DNSCrypt / DoH / Proxy?
3. Blocklist?
4. Failed resolutions?

**Comment by hussainmohd-a** [comment]
Filtering of logs has options to filter out blocked connections as part of V053, Will add the more filters in the later releases.

**Comment by ignoramous** [comment]
Current filters allow one to view just *all*, *allowed*, or *blocked* queries. There's a search bar that can filter on IPs and domain names.

Probably only missing a *query type* (`A`/`AAAA`/`SVCB`/`MX`/`TXT`) etc.
