### ISSUE TITLE
cannot add DNSCrypt server; long stamps push "Add" offscreen

### ISSUE THREAD

**Issue by ftobin** [celzero/rethink-app#130]
On more compact devices, the dialogue for adding a new dnscrypt resolver does not allow one to add stamp information and then hit "Add", because stamps are long and modal dialogue is not scrollable.

![Screenshot_20201109-181056](https://user-images.githubusercontent.com/3298600/98617425-f8562500-22cc-11eb-89fd-af7f9a61ef57.jpg)

**Comment by ignoramous** [comment]
I think you might have enabled large or extra-large font-size on your device. Can you please check if setting the font-size to "normal" or "medium" lets you add the resolver?

We'd, either ways, fix this layout issue but really unexpected with as common a stock UI component as a dialog box. Thanks for bringing it to our attention.

**Comment by ftobin** [comment]
Decreasing my font size temporarily does allow me to work around this issue.
