### ISSUE TITLE
On-device blocklists skipped for all apps when any app is Bypassed 

### ISSUE THREAD

**Issue by ZenzoK90** [celzero/rethink-app#1300]
Have been facing an issue with dns level adblocking with RethinkDns app. On-device blocklist didn't seem to be effective for for adblocking using with different dns servers. Only RethinkDns dns servers and ads filtering dns servers are working. This happens in latest version I think, as the previous version was working fine.

**Comment by diegol88** [comment]
The same happening to me on the latest version. Some additional information:

- I am using wireguard + ODoH (CloudFlare) + On-Device blocklist.
- If I set Wireguard as simple, I can see the blocklist working however in the logs it shows as "maybe blocked" . Anyways the blocks is working indeed;
- If I set Wireguard as Advanced, the on-device blocklist is bypassed and doesn't work;
- Removing cache + storage from Android and starting from scratch seems to fix the issue, however, if I try to restore a backup, the issue re-appears;

**Comment by ZenzoK90** [comment]
Clearing cache and data or reinstalling didn't even work for me. Moreover, when switching to Rethink dns server,  DNS section from homepage took me directly to blocklist configure instead. Have to go through configure and DNS section for any changes.

**Comment by ignoramous** [comment]
> DNS section from homepage took me directly to blocklist configure instead. Have to go through configure and DNS section for any changes to make

This is expected. Many users asked us that they wanted quick access to RDNS blocklists, and so when RDNS is selected, it takes users straight to its configuration page, now.

> Clearing cache and data or reinstalling didn't even work for me.

This is strange but not the first report we've got. Unfortunately, if folks don't share logs, there's nothing we can do except guess as this issue isn't reproducible on Androids we use.

**Comment by diegol88** [comment]
> This is strange but not the first report we've got. Unfortunately, if folks don't share logs, there's nothing we can do except guess as this issue isn't reproducible on Androids we use.

I'm happy to provide the logs, I just don't know what logs are you looking for. If you can provide some guidance I can try to help.

**Comment by ignoramous** [comment]
Thanks.

0. Turn OFF on-device blocklists.

1. Turn on `Verbose` from *Configure* -> *Settings* -> *Log level*
2. Capture logs: `adb logcat -s <package_name>:*`
3. Turn ON on-device blocklists.
4. Select "Recommended" from the Privacy section, if it isn't already.
5. Visit websites that should be blocked (if none of the apps are in `Bypass DNS and Firewall` mode) like `segment.com` or `segment.io` (provided these domains are not `Trust`ed by any app or by *Universal* (global) rules).
6. Stop log capture. Email me the results, if you're comfortable doing so: `mz` at `celzero` dot `com` (please do mention this github issue)

**Comment by diegol88** [comment]
> 6. Stop log capture. Email me the results, if you're comfortable doing so: `mz` at `celzero` dot `com` (please do mention this github issue)

Done, hopefully I have sent the correct logs.

**Comment by ZenzoK90** [comment]
> Have been facing an issue with dns level adblocking with RethinkDns app. On-device blocklist didn't seem to be effective for for adblocking using with different dns servers. Only RethinkDns dns servers and ads filtering dns servers are working. This happens in latest version I think, as the previous version was working fine.

Okay..untill this issue is fix in next update I found a temporary solution for this unexpected error in latest version. Adding any apps to Bypass DNS and Firewall Rules (which suppose to work best in RethinkDns only), causing On-device blocklist to stop working. What makes me surprised is that, when this issue starts Cloudflare dns servers gets leak during the dns leak test, and its all because of enabling dns booster. 
Hopefully, this issues will get fix soon.

**Comment by ignoramous** [comment]
> And yes, the blocking of ads perfectly works now if I don't add any app to Bypass DNS and Firewall Rules.

When *any* app is set *Bypass DNS and Firewall* then all rules (IP and DNS/domain) are applied at connection time (that is, you'd not find any "blocked" domains in *DNS* logs but instead will find "blocked" domains in *Network* logs).

**Comment by ZenzoK90** [comment]
> > And yes, the blocking of ads perfectly works now if I don't add any app to Bypass DNS and Firewall Rules.
> 
> When _any_ app is set _Bypass DNS and Firewall_ then all rules (IP and DNS/domain) are applied at connection time (that is, you'd not find any "blocked" domains in _DNS_ logs but instead will find "blocked" domains in _Network_ logs).

It's not what I meant, what I mean is that once I trigger Bypass DNS and Firewall Rules by adding any single app to it, the blocking doesn't work at all for whole system. When there's no app added to that particular Firewall Rules, only then the on-device blocking works. Its like triggering this issue when I touch Bypass DNS and Firewall Rules option.

**Comment by diegol88** [comment]
> It's not what I meant, what I mean is that once I trigger Bypass DNS and Firewall Rules by adding any single app to it, the blocking doesn't work at all for whole system. When there's no app added to that particular Firewall Rules, only then the on-device blocking works. Its like triggering this issue when I touch Bypass DNS and Firewall Rules option

This. I have the same problem and removing all apps hat I have previously added to Bypass DNS and Firewall fix the issue. Thanks for the workaround.

**Comment by hussainmohd-a** [comment]
Multiple fixes have been implemented in v055d (available on [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d) and [Website](https://rethinkdns.com/download)). Please feel free to reopen the issue if you encounter it again.
