### ISSUE TITLE
Manually import blocklists

### ISSUE THREAD

**Issue by croteco** [celzero/rethink-app#1303]
The DOWNLOAD BLOCKLISTS button appears unresponsive, this may not be a bug since I am in a region with network censorship. It would be nice if there's an option to manually download and import blocklists.

**Comment by ignoramous** [comment]
> It would be nice if there's an option to manually download and import blocklists.

dup: #293 (please track there).

> The DOWNLOAD BLOCKLISTS button appears unresponsive

toggle the *Use in-app downloader* (if it is ON turn it OFF, if it is OFF turn it ON) and see if the download then works?

You can also turn OFF Rethink and then attempt a download.
