### ISSUE TITLE
v055c: Wireguard tries to use an old IP for the peer

### ISSUE THREAD

**Issue by michaelolbrich** [celzero/rethink-app#1305]
The Wireguard peer is configured with a hostname in the endpoint field in the configuration. That's necessary because the IP for that host changes regularly.

It works just fine until the IP changes. At that point, no traffic reaches the endpoint. Stopping and starting the wireguard proxy does not help. I've used 'adb logcat' and there I see:
```
I GoLog   : wgconn.go:90: I wg: bind: new endpoint <new-ip>:<port>
I GoLog   : wgconn.go:90: I wg: bind: new endpoint <old-ip>:<port>
```
If I force close the app then it works again and both lines contain the new IP.

The previous version (v055a according to f-droid) did not have the problem. I often needed to reconnect the proxy after the IP change (but not always) and that worked reliably.

**Comment by ignoramous** [comment]
> The previous version (v055a according to f-droid) did not have the problem. I often needed to reconnect the proxy after the IP change (but not always) and that worked reliably.

Gotcha.

This is using hostname for a *Peer.endpoint*, correct?

WireGuard, starting `v055b`, uses the same DNS cache as the rest of the app. This cache is refreshed if connections error out (for TCP, catching errors are straight-forward; but for UDP, I guess, we don't handle it as we should) or kept as-is until the app is restarted.

**Comment by michaelolbrich** [comment]
> This is using hostname for a _Peer.endpoint_, correct?

Correct.

**Comment by ignoramous** [comment]
Thanks. Fixed this rather annoying bug.

Caches are dropped when:
- Tapping the "Refresh" icon in either:
    - *Configure* -> *Proxy* at the top right-hand corner (https://github.com/celzero/firestack/commit/a0e568d5098bad5266cf1747fc3e82c7be28d8ee).
    - *Configure* -> *DNS* at the top right-hand corner (https://github.com/celzero/firestack/commit/6233231086711c15f9f8a7dd05bc31d9631fc414).
- The VPN goes through a `STOP`/`START` cycle (https://github.com/celzero/firestack/commit/2526bcf558ab5a44b7e09f240fca7d1808e79998).
- Network changes (https://github.com/celzero/firestack/commit/ab5ca79aeff799f4c9012e83b2953623561339ea).

Should be part of a new release in two days or so.

**Comment by ignoramous** [comment]
Released in [`v055e`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e). Feel free to reopen if this issue isn't fixed for you.
