### ISSUE TITLE
Can't packet capture to Downloads, manage all files permission unavailable

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#1309]
If I try to enable Settings > Packet capture > Output to the Downloads folder, I'm taken into app settings to grant the _Allow access to manage all files_ permission, but it's greyed out:

<img src="https://github.com/celzero/rethink-app/assets/4025899/2a87cb95-ceb3-4357-abd0-9d61c2840d4a" width="300">

Possibly missing a declaration in `AndroidManifest.xml`?

Device: OnePlus Nord CE, Android 13 (stock OxygenOS)

**Comment by ignoramous** [comment]
I've got a Nord but don't see what you're seeing (as in, the toggle isn't grayed out). Strange.

**Comment by Terrance** [comment]
Is the all files permission actually needed here?  My limited understanding of the modern Android storage permissions is that Download, Documents, Pictures etc. are 'standard' folders with their own individual permissions / access routes now, though I'm not sure how that ties into supporting older Android versions.

**Comment by ignoramous** [comment]
> Is the all files permission actually needed here? 

Unsure, but from what I remember, no other permission worked (as in the `golang` layer that wants to write packet captures to this file was not able to). Welcome pull requests if anyone has the bandwidth to figure this out (which is a power user feature unlikely to be used by many, anyway)

**Comment by Lanius-collaris** [comment]
@ignoramous  I think Storage Access Framework is better, it doesn't require permissions.

1. Get a URI via SAF
2. Open the URI with `getBaseContext().getContentResolver().openFileDescriptor()`
3. Use `ParcelFileDescriptor.detachFd()` or `ParcelFileDescriptor.getFd()` to get a file descriptor
4. Pass the file descriptor to the `golang` layer.

**Comment by ignoramous** [comment]
The `fd` SAF gave us didn't work from `golang` (again, it could be we did something wrong when prototyping the feature... but given this feature is unlikely to be used by most of the regular users, what's currently baked in is good enough; though, will accept PR if anyone can make it work with SAF on ALL Android versions 6+).

**Comment by Lanius-collaris** [comment]
@ignoramous I have not tested calling from a different process. [unix#PidfdGetfd](https://pkg.go.dev/golang.org/x/sys/unix#PidfdGetfd) may help?

**Comment by hussainmohd-a** [comment]
Somehow, the declaration was mistakenly removed in this latest release, causing this issue. It has been fixed in https://github.com/celzero/rethink-app/pull/1301/commits/260d89e90b3c37ccfd61bb5676f12a1bba89ecae.

**Comment by ghostersk** [comment]
> Somehow, the declaration was mistakenly removed in this latest release, causing this issue. It has been fixed in [260d89e](https://github.com/celzero/rethink-app/commit/260d89e90b3c37ccfd61bb5676f12a1bba89ecae).

So this should be fixed with next update?
As I got Pixel with Graphene OS, I also have greyed out the full permissions, but I gave it Storage permission for Downloads folder (Btw i can save backup just ok) and still cannot do PCAP to device.

**Comment by ignoramous** [comment]
> should be fixed with next update?

Yes, it should.

> Downloads folder (Btw i can save backup just ok

Different mechanisms. pcap is written to by the network engine, and it needs the permission (though, ideally, it wouldn't and work just like backups work).

**Comment by hussainmohd-a** [comment]
v055d has been released. Closing the issue. Please feel free to reopen if the error persists in the latest versions.

**Comment by Terrance** [comment]
Can confirm the _All files access_ setting is now available, and logs are successfully captured to `/Download/Rethink`.

**Comment by ghostersk** [comment]
I assume this update is only for self install right, as I have not seen any update on F-droid

**Comment by Terrance** [comment]
F-Droid [updated yesteday](https://f-droid.org/packages/com.celzero.bravedns/#latest) with v055d.

**Comment by ghostersk** [comment]
> F-Droid [updated yesteday](https://f-droid.org/packages/com.celzero.bravedns/#latest) with v055d.

Yes, thank you. I tested it now.
Usually I get prompt asking me to update it manually, this time it seems like it updated automatically.
It works :}
