### ISSUE TITLE
v055c: WireGuard field DNS blank ("Auto") fails

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1314]
> I found a similar issue while trying to edit the MTU in a Wireguard Config - you cannot leave the DNS blank ("Auto") -
> <details><summary> it fails with an error (see screenshot)</summary>
> screenshot:
>
> ![wireguard](https://github.com/celzero/rethink-app/assets/150080223/932e64b8-bbe8-425e-9e04-9119f9455a3f)
> </details>

_Originally posted by @luckygitt in https://github.com/celzero/rethink-app/issues/1311#issuecomment-2019845376_

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/pull/1301/commits/98f92ea335394451e633fb66ca71ef3c5fea9444
