### ISSUE TITLE
MyJio App doesn't work with Rethink app at all

### ISSUE THREAD

**Issue by ghost** [celzero/rethink-app#1326]
Hello! I tried MyJio app just after fresh install of rethink dns with all default settings with some apps blocked via firewall including play service, but always shows no internet connection. I tried to switch to only DNS mode and only Firewall mode but same results. DNS logs shows that app tries to make some connections and some of them are blocked by DNS, I tried to allow those connections but still same result. It works fine without any firewall tho.

**Comment by ignoramous** [comment]
It could be that the app is trying to contact domains/IPs that are blocked by *RDNS Default* (guessing that you're using *RDNS Default*). Try switching to "System DNS" from *Configure* -> *DNS* or to either *Google* or *Cloudflare* in "Other DNS".

Or: *Exclude* MyJio app from *Configure* -> *Apps* (search for it in search box).

I don't use MyJio to test this myself, so I'll need more input. If you're technical enough:
- Look in *DNS Logs* what domains are blocked when you open MyJio app.
   - *Trust* the domains that are being blocked, if any.
- Look in *Netowkr Logs* to see if MyJio is struggling to connect.
   - Check if any connections MyJio is trying to make are *blocked* at all. These show up with red colourd left-hand side border in *Network Logs*.
   - As in: Entries against MyJio with `0b` upload / `0b` download.
   - If you spot such `0b` entries, tap on them to reveal a *bottomsheet* which shows the final status of the connection. This status is shown at the footer of that bottomsheet.

**Comment by ignoramous** [comment]
> although now there's nothing getting blocked in DNS and no entry with 0b in Network logs either.

Are there any entries from MyJio app at all in *Network Logs*? Make sure to *unexclude* the app (*excluded* apps would not show up in *Network Logs*).

> I do not understand where can i find the final status of connection, if you could share a screenshot of it, it would be appreciate

Tap on any entry that's *not* active in Network Log (that is, there's no *green* dot: 🟢). *Active* connections won't have a "final" status message. A *bottomsheet* should come up. The *footer* of the *bottomsheet* should show the final status of the connection.

<details>
<summary>screenshot</summary>
1. white highlight shows active connections; these won't have final status just yet.
2. red highlight shows time of the connection and total data transfer for the connection.
3. yellow highlight shows the final status message from the connection.
 
![Screenshot_2024-04-03-15-23-36-55_c8cbde12d3521911922be4eee6a05664~2](https://github.com/celzero/rethink-app/assets/852289/3c3b8df9-b86d-4ed1-a97a-94159e428a61)
</details>

> What could be possible problem

No clue as of yet.

- Have you changed any setting from whatever was the default in *Configure* -> *Network*? If so, which ones?
- Is *Advanced DNS filtering* turned ON in *Configure* -> *DNS*? Keep it OFF (which is the default).
- Are you running Rethink in *DNS + Firewall* mode? Check this by tapping on the *downward* arrow next to the `START`/`STOP` button on Rethink's homescreen.
- Are you running WireGuard or any other proxy?
   - If WireGuard: Have you setup any WireGuard profile as *Lockdown*? Or added *MyJio* to any of the WireGuard profiles which are not currently *running*?

**Comment by ignoramous** [comment]
Thanks.

> there are entries in Network and DNS log but nothing is blocked in either DNS or Network log.

If there are entries in Network Log, what is the final connection status shown in those for the MyJio apo?
