### ISSUE TITLE
Excessive Battery Usage

### ISSUE THREAD

**Issue by Sinestr0** [celzero/rethink-app#1328]
I am using Rethink-app with configuration below since release of v055c in my main user profile (also in work profile and other user profile as well with variation of blocked apps in firewall (of course different apps in different profile) and whitelisted domains) on android with always on VPN option turned on for Rethink-app.

> I am on android 8.1 (stock) which does not support setting up custom DNS natively. I configured Rethink app with on-device blocklist with marking some domains/websites as "trusted" in Firewall-IP&Ports rules (using RethinkDNS Plus), mode set as DNS and Firewall (default) mode, blocked internet access for many apps in firewall, IP version as Auto.

On average, this app uses 35-40% of battery of single charge with average 4 hours of screen ON time and medium usage of phone, for main user profile. Surprisingly, it is using very very low battery for other user profile and work profile.

I tried to uninstall the app completely and reconfigured as above (without restoring backups), but still issue persists for main profile.

I set same configuration for app for all profiles and still, main profile has very high battery usage and others have very low usage. 

I have completely switched to netguard and checked for battery usage for average day usage, it shows very low battery usage for main profile.

Turning on/off battery optimization seems to have almost no effect on results either for netguard or rethink-app. So usually keep battery optimization on.

I sent relevant screenshots to @ignoramous by email.

**Comment by ignoramous** [comment]
> sent relevant screenshots to @ignoramous by email.

Haven't got any screenshots in my email. My address is `mz` at `celzero` dot `com`.

> 40%

I'd like to note that the battery use on my Android barely crosses 2%.

<details>
<summary>screenshot</summary>
battery use:

![Screenshot_2024-04-03-14-53-43-21_0ba066473b79d6e213a1f6f52505e2ee~2](https://github.com/celzero/rethink-app/assets/852289/c0abfa66-af72-44c0-be0b-36d4bb4ea69a)
</details>

**Comment by ignoramous** [comment]
btw, are you using DNSCrypt or any other Proxy (like WireGuard)?

**Comment by ignoramous** [comment]
Hm, can you disable *On-device blocklists* and see if the situation improves. This is just a guess since I use it, but never cross 5% on my Android.

Also:
1. Do you have any app in `Bypass DNS & Firewall` mode? 
2. Have you enabled `Block any app not in-use` in *Universal* (global) firewall?

**Comment by ignoramous** [comment]
I block 400+ apps and usage is 2% right now.

Something definitely weird going on, on your Android. May be some bug in Rethink which is only triggered given some set of conditions.

Can you observe `com.celzero.bravedns` CPU usage in for a few minutes?

```
adb shell

# once inside shell, exec:
top

# if CPU use is too high...
# grab the pid from "top":
# usually, the first column against 
# process name, "com.celzero.bravedns",
# (which appears in the last column).

top -B -h -p <pid>
```

**Comment by ignoramous** [comment]
> top -B -h -p is not working, it says "top : unknown option B".

Ah, it is `top -b -H -p` (note the uppercase `-H`).

> com.celzero.brave jumps from 4% to 36-60% and stays for few seconds then return to around 10% and stays there while video is still playing. Is it expected behavior?

Yeah, that checks out. Rethink should only consume resources (network and CPU) when other apps (being routed through Rethink) are in-use. I am mostly worried about the 40% drain solely due to a bug in Rethink (say, some never ending task running forever in background aimlessly and needlessly).

**Comment by ignoramous** [comment]
> What should be "normal" battery usage with wireguard enabled?

Depends on just how much traffic is pumped through WireGuard. Generally, *without* WireGuard, it shouldn't cross 5% to 10%. With WireGuard, my assumption is, it shouldn't add more than 10% on top of the *baseline* usage.

**Comment by ignoramous** [comment]
Some pointers: https://github.com/tailscale/tailscale/issues/3363

**Comment by ignoramous** [comment]
Strange. (if you're comfortable revealing) From which version to which?

It shouldn't be that older Android version consume disproportionately more battery. May be your new Android doesn't have apps that don't hammer away at Rethink as much?

Thanks for closing the loop on this. We still haven't done much battery profiling (we should)... but glad that the consistent drain you saw isn't any longer a concern.

**Comment by Teophrast** [comment]
I am not sure if anyone will be reading this, but "block internet for newly installed apps" setting also causes huge battery drain.

**Comment by HideMyUsername1** [comment]
> I am not sure if anyone will be reading this, but "block internet for newly installed apps" setting also causes huge battery drain.

The v0.5.5y version is using significantly more battery than the previous few versions. I think it has a lot to do with the errors showing up in the logs. If you don't want the app to have a network connection at all, you should block it at the OS level. This uses almost no battery.

**Comment by ignoramous** [comment]
> The v0.5.5y version is using significantly more battery than the previous few versions. 

This shouldn't be the case. Versions since `v055v` have seen several improvements with respect to resource use.

What % battery use does your Android show against Rethink? Mine never is usually about 3% and I have 5 active WireGuards and 30+ blocklists turned on.

- *About -> Proc* shows the current memory usage by the app and the network engine. If you tap on the "Threads / Proc / Mem" tab, you'd see all top active threads across Rethink's entire process (including the network engine).

- *About -> Stacktrace* shows all alive threads (for the UI/Kotlin parts, viz. "JVM stack"), goroutines (for the network engine, viz. "Go stack"), and their execution context.

These two should most likely reveal what's causing heavy battery drain. You can copy and paste the output from those here (there's a "Copy" button at the footer in both those UIs) or chat about it with a capable LLM of your choice.

>  think it has a lot to do with the errors showing up in the logs

What kind of errors and which logs? *About -> App Logs*?

**Comment by Teophrast** [comment]
> > I am not sure if anyone will be reading this, but "block internet for newly installed apps" setting also causes huge battery drain.
> 
> The v0.5.5y version is using significantly more battery than the previous few versions. I think it has a lot to do with the errors showing up in the logs. If you don't want the app to have a network connection at all, you should block it at the OS level. This uses almost no battery.

I personally wasnt complaining. My usage is for yesterday is 0.4% in 24 hours. I just said that enabling setting to block newly installed apps raises the usage of battery. As if rethink dns constantly monitors if there is app being installed and that process eats all of the ram, and consumption jumps to 30% or so.

**Comment by HideMyUsername1** [comment]
> > The v0.5.5y version is using significantly more battery than the previous few versions.
> 
> This shouldn't be the case. Versions since `v055v` have seen several improvements with respect to resource use.
> 
> What % battery use does your Android show against Rethink? Mine never is usually about 3% and I have 5 active WireGuards and 30+ blocklists turned on.
> 
>     * _About -> Proc_ shows the current memory usage by the app and the network engine. If you tap on the "Threads / Proc / Mem" tab, you'd see all top active threads across Rethink's entire process (including the network engine).
> 
>     * _About -> Stacktrace_ shows all alive threads (for the UI/Kotlin parts, viz. "JVM stack"), goroutines (for the network engine, viz. "Go stack"), and their execution context.
> 
> 
> These two should most likely reveal what's causing heavy battery drain. You can copy and paste the output from those here (there's a "Copy" button at the footer in both those UIs) or chat about it with a capable LLM of your choice.
> 
> > think it has a lot to do with the errors showing up in the logs
> 
> What kind of errors and which logs? _About -> App Logs_?

I think it's fine for one app to account for 39% of my battery usage.
The main error in the logs is:  spammy...alg: ptr: in 5 msgs; dropped? true

**Comment by ignoramous** [comment]
> block newly installed apps raises the usage of battery. As if rethink dns constantly monitors if there is app being installed and that process eats all of the ram, and consumption jumps to 30% or so.

I have *Block newly installed apps* turned on, but don't see the high battery use you're seeing. Likely it is a combination of settings. *Block any app not in use* is a resource drain (Rethink relies on *Accessibility Service* to identify foreground apps, which is expensive).

As mentioned above, whenever you hit 30% or something absurd next time (for `v055v`+ anything beyond 15% is totally unexpected; 3% to 5% is typical for normal use; 5% to 15% for heavy use, in my experience), will you "Copy" output from:

(*copy pasting from a comment above*)

* _About -> Proc_ shows the current memory usage by the app and the network engine. If you tap on the "Threads / Proc / Mem" tab, you'd see all top active threads across Rethink's entire process (including the network engine).

* _About -> Stacktrace_ shows all alive threads (for the UI/Kotlin parts, viz. "JVM stack"), goroutines (for the network engine, viz. "Go stack"), and their execution context.

* _About -> General_ shows current network engine state and various other settings and diagnostic messages from subcomponents, if any.

---

> think it's fine for one app to account for 39% of my battery usage

Yikes, 39% is super high. What settings do you have turned on? You can share screenshots of *Configure -> Settings*, *Configure -> Network*, *Configure -> Firewall -> Universal firewall rules*, & *Homescreen*, if you're comfortable? If not, you can also "Copy" (look for that button in the *footer*) output from *About -> General* privately with me (mz at celzero dot com; please do leave a link to this GitHub issue in the body or subject of the email).

In addition, as above, output from *About -> Proc* (there's two tabs in this UI) and *About -> Stacktrace* will also help.
