### ISSUE TITLE
[0.5.5c] SEND_FAIL

### ISSUE THREAD

**Issue by woj-tek** [celzero/rethink-app#1335]
Recently I'm getting `SEND_FAIL` error with timeout of ~5s (500x ms) and error:

`resuelto Hace 0 min por system.212.166.128.202:53`

From what I can see it's my (current) mobile operator - Vodafone Spain (https://ipinfo.io/212.166.128.202). But it works just fine when I disable RethinkDNS

I'm on `0.5.5c` from f-droid

**Comment by ignoramous** [comment]
Have you changed any setting in *Configure* -> *Network*? *Use all available networks* for example can cause what you're seeing (which we have fixed in `v055d`).

**Comment by ignoramous** [comment]
> It only happens for certain apps/domains

**Comment by ignoramous** [comment]
> Before that the domains were... random - big and small sites (looks like DNS blocking and not network issue because disabling R-DNS fixed the issue immediately without moving a bit / disconnecting mobile network)

Can you tap on one of those entries in *DNS Log* (for `one.one.one.one`) which succeeded immediately next to the ones that failed and post a screenshot? It seems to me like `System DNS` is reachable over IPv6 but not `IPv4` (Rethink retains these logs for 7 days).

**Comment by ignoramous** [comment]
Thanks.

Are you using *Auto* in *Configure* -> *Network* -> *Choose IP version*?

From the screenshots you shared, looks like a valid `System DNS` server `100.100.1.1` is *unreachable*. This can happen if Rethink goes looking for it on the "wrong" network (for example, trying to connect to WiFi's DNS server over the Mobile network). We've fixed this bug in [`v055e`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e), can you check and let us know if this happens in that new version?

**Comment by ignoramous** [comment]
>  And indeed the issue seems to be gone (I rarely notice that something is not missing) but the errors for one.one.one.one were from today.

Sorry, is the issue gone or is it present (or you mean, just not as severely as in `v055c`)?

**Comment by ignoramous** [comment]
(closing this report then; please feel free to reopen. `v055f` lands in a day or so, which should also improve things a little bit).
