### ISSUE TITLE
v055d: Nekobox SOCKS5 does not work

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1337]
> I'm not sure if this needs it's own issue, but I have problems with Nekobox SOCKS5 proxy in `v0.5.5d` too. Rethink doesn't seem to route any traffic to it as it has been in `v0.5.5c`. When I try to check my IP with the same setup I've had before update it shows me my real IP instead of my proxy's, and all of my ISP's blocklists apply too.
>
> - I have Rethink in Always-on VPN mode
> - Nekobox in proxy mode, port 1234 for SOCKS5, port 6450 for DNS proxy
> - I set up SOCKS5 proxy in Rethink to 127.0.0.1:1234 - Nekobox
> - DNS proxy to 127.0.0.1:6450 - Nekobox
Nekobox is excluded from dns and firewall rules.
>
> It all *did* use to work before update, I haven't changed anything.

_Originally posted by @vertuk in https://github.com/celzero/rethink-app/issues/1323#issuecomment-2037893147_

**Comment by vertuk** [comment]
> Strange. Is SOCKS5 generally working for other such apps (like with [ShadowRocket](https://github.com/Pawdroid/shadowrocket_for_android) or [Orbot](https://github.com/guardianproject/orbot) or [SingBox](https://github.com/SagerNet/sing-box-for-android) for example)?

I reinstalled Rethink `v0.5.5d`, restored settings from backup and it started to work again. And it works for Orbot too (via SOCKS5 proxy). Nevermind then, sorry...

**Comment by ignoramous** [comment]
Thanks for that confirmation. Closing... feel free to re-open in case this happens again.
