### ISSUE TITLE
v055d: RDNS DoT (max) blocked but DoH (sky) works

### ISSUE THREAD

**Issue by Amir2367** [celzero/rethink-app#1340]
Hello again, I was able to find a very interesting point.
It doesn't work when we connect to RDNS DEFAULT normally, but when we copy the same address and create a new DOH in OTHER DOH with RDNS DEFAULT address, it connects amazingly.
You can see the video below
@ignoramous

https://github.com/celzero/rethink-app/assets/83357422/e5eeb3f6-411b-4e07-ae35-9f9472d628f5

**Comment by ignoramous** [comment]
`Max` in *RDNS* uses DNS-over-TLS (DoT). Is it blocked where you are? One way to check would be to add `rec.max.rethinkdns.com` in Android' [*Private DNS*](https://archive.is/az65z) to see if it works? If it doesn't, the DoT is being blocked by either the ISP or the network you're on.

**Comment by Amir2367** [comment]
> `Max` in _RDNS_ uses DNS-over-TLS (DoT). Is it blocked where you are? One way to check would be to add `rec.max.rethinkdns.com` in Android' [_Private DNS_](https://archive.is/az65z) to see if it works? If it doesn't, the DoT is being blocked by either the ISP or the network you're on.

I tested, yes, it does not load any website or app.
If it is blocked according to your statement, why does it connect to the same network in normal mode in version 0.5.5a and upload all websites and apps at a good speed?

**Comment by ignoramous** [comment]
>  If it is blocked according to your statement, why does it connect to the same network in normal mode in version 0.5.5a and load all websites and apps at a good speed?

On `v055a`, both `sky` and `max` use DNS-over-HTTPS (DoH). In `v055b`+ `sky` uses DoH, but `max` uses DoT.

**Comment by Amir2367** [comment]
> On `v055a`, both `sky` and `max` use DNS-over-HTTPS (DoH). In `v055b`+ `sky` uses DoH, but `max` uses DoT.

Can't you revert this to version 0.5.5a?
What was the need to change it?
I'm just asking out of curiosity

**Comment by ignoramous** [comment]
> Can't you revert this to version 0.5.5a? What was the need to change it?

Will stick to DoT for `Max` as it is cheaper for us run. We're paying more than $2000/mo for our DNS services and want to cut down costs wherever we can.

**Comment by Amir2367** [comment]
> > Can't you revert this to version 0.5.5a? What was the need to change it?
> 
> Will stick to DoT for `Max` as it is cheaper for us run. We're paying more than $2000/mo for our DNS services and want to cut down costs wherever we can.

Yes I understood

**Comment by ignoramous** [comment]
We have switched `max` to DoH in `v055e`.

**Comment by Amir2367** [comment]
> We have switched `max` to DoH in `v055e`.

Very good, thank you to your good team for considering the audience's suggestion❤️
