### ISSUE TITLE
Bug: Unamed apps not the same as "Unknown" apps

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#135]
Apps (or really, UIDs) that do not have any names shouldn't be shown as "unknown" especially since there's a universal firewall rule that lets users block "unknown" connections (which are connections for which an owner UID/app couldn't be determined).

Perhaps these UIDs without names need to be labelled "Unnamed" to avoid confusion.

**Comment by hussainmohd-a** [comment]
The requests which are missing the UID's are blocked based on the universal firewall settings. All the other request which are having UID's but missing package name are treated as Unnamed(UID).
