### ISSUE TITLE
How can I add a custom blocklist?

### ISSUE THREAD

**Issue by mtxadmin** [celzero/rethink-app#1354]
In the manual there are only link to rethinkdns.com/configure and some default lists. How can I add my own list? And at least to be able to quickly block several new domains, right from the device in the field.

Maybe, some small local DNS with adblocking/filtering functions? Don't understand why does the app need some external service (rethinkdns.com) for it.

**Comment by mtxadmin** [comment]
Thanks, it seems that covers quick blocking of several domains. And what about custom blocklists?

**Comment by ignoramous** [comment]
> And what about custom blocklists?

Importing lists isn't straightforward.  Think, we'll get around to implementing it (please track at: #237) after we've fixed other high priority issues.

**Comment by noe-578** [comment]
@ignoramous could you please consider reopening this? Usecase: I want to curate my own list and add it as an URL when blocklists are downloaded and used locally. Similar to how ublock origin lets you add them. 

<img height="120" alt="Image" src="https://github.com/user-attachments/assets/af7ed5ce-d98a-4087-b218-44deb1ac111b" />

**Comment by ignoramous** [comment]
Please track 
- https://github.com/celzero/rethink-app/issues/237
