### ISSUE TITLE
v055c: Unable to share file through termux python over http.server over LAN

### ISSUE THREAD

**Issue by barkoder** [celzero/rethink-app#1356]
Steps to reproduce:

0. Install ReThink v0.5.5c

1. Install and open Termux.

2. Install python in termux -  `pkg install python`

3. `echo test > test.file` in termux.

4. Start http-server - `python3 -m http.server 12345`

5. `curl -O http://<LOCAL_IP_ADDRESS_OF_YOUR_ANDROID_DEVICE>:12345/test.file` on a different computer on your local network. This step fails unless you turn off Rethink altogether. Switching to DNS only or Firewall only mode in ReThink doesn't work. 

6. Also the Network log and DNS Log on ReThink shows nothing regarding this request.

-------

I remember an older version of ReThink used to work on Step 5.

Thanks.

**Comment by ignoramous** [comment]
Thanks. In general, we haven't checked if *unconnected* UDP sockets and *server* TCP sockets work in all scenarios as at least running TCP servers is a very uncommon thing to do (*unconnected* UDP sockets are slightly more common but apps don't rely on it solely so it never manifests as a bug, except in cases where it does: #1323).

Two ways to work around this problem:
1. `Exclude` Termux (from *Configure* -> *Apps*) from Rethink
2. Turn ON *Do not route Private IPs* (from *Configure* -> *Network*).

**Comment by barkoder** [comment]
Thanks @ignoramous . That works!

It would help if the Network log showed that it was being blocked and also why it was being blocked.

**Comment by ignoramous** [comment]
> It would help if the Network log showed that it was being blocked and also why it was being blocked

It isn't blocked. I believe Android doesn't even send us the packets for server TCP sockets. I might be wrong. As mentioned above, we haven't really dug in this.

**Comment by ignoramous** [comment]
In `v055j` ([github](https://github.com/celzero/rethink-app/releases/v0.5.5j), [website](https://rethinkdns.com/download)), we've brought back the previous behaviour of "excluding" proxy-running apps like Termux. Please test on `v055j` and let us know.

To toggle this behaviour, go to turn ON/OFF *Configure* -> *Network* -> *Loopback proxy forwarder apps* (to be clear, in this case, OFF is what would "exclude" Termux and hopefully make it work).

**Comment by ignoramous** [comment]
`v055j` is on now [f-droid](https://f-droid.org/en/packages/com.celzero/bravedns) too (closing this issue, feel free to reopen) if it hasn't fixed for you.
