### ISSUE TITLE
Spring-clean blocklist

### ISSUE THREAD

**Issue by gnu1dea** [celzero/rethink-app#1359]
Currently there are some filter lists in "advanced" that are either discontinued (like _Fanboy's Enhanced Tracking List_, _AdRules China (Cats Team)_, …) or miscounted as having 0 rules (like _Malware (RPi)_, _Child Protection (RPi),_ …).
It's just seems to be a good time to review/update them all.

**Comment by ignoramous** [comment]
Yeah, we should. Thanks.

**Comment by LovingNumbers** [comment]
Already reported these a while ago https://github.com/serverless-dns/blocklists/issues/168
