### ISSUE TITLE
v055e: Rethink is now intercepting queries from DNS proxy apps(?)

### ISSUE THREAD

**Issue by Rhys-T** [celzero/rethink-app#1360]
I've been combining Rethink with personalDNSfilter, mostly as a workaround for #316.
DNS type: Other DNS > DNS 53
Proxy settings:
> personalDNSfilter
> App name: personalDNSfilter
> IP address: 127.0.0.1
> Port number: 5300

I just updated Rethink to v055e, and noticed that it didn't think I had an Internet connection - but the connection worked fine when Rethink was stopped. I did some testing, and discovered that:
- DNS queries are making it to personalDNSfilter.
- Domains with custom IP addresses set in pDNSf resolve correctly.
- The connection works if I switch Rethink's upstream/proxy DNS server from pDNSf to Google DNS, but fails when I switch back.
- I tried recreating the proxy setup for pDNSf in Rethink, but it failed the same way.
- If I set pDNSf to 'exclude', everything works fine.

It's acting like pDNSf's own queries are now getting intercepted by Rethink, even though it's set as the DNS proxy app. Any idea what might be causing this?

**Edit**: Also, I tried to get a packet capture so I could try and confirm what was going on, but for some reason it's now producing broken `.pcap` files that can't be recognized by Wireshark, or even by the `file` command. I can open another issue for that if you want.

**Comment by ignoramous** [comment]
> Any idea what might be causing this?

See if turning *Prevent DNS leaks* OFF helps (in *Configure* -> *DNS*).

> It's acting like pDNSf's own queries are now getting intercepted by Rethink, even though it's set as the DNS proxy app. Any idea what might be causing this?
>
> If I set pDNSf to 'exclude', everything works fine.

Ah, this *could* be caused by #393.

> `.pcap`

https://github.com/celzero/rethink-app/issues/1361

Can you confirm whether both *Downloads folder* & *Logcat* did not work?

**Comment by Rhys-T** [comment]
> See if turning _Prevent DNS leaks_ OFF helps (in _Configure_ -> _DNS_).

Yes, turning that off causes the connection to work even with pDNSf set back to the normal 'allow' mode.

> Ah, this _could_ be caused by #393.

Hmm - I was thinking I had been on at least v055b (where that was added) without having this issue, but I'm no longer sure, because of [the problem I had with F-Droid not giving me notifications](https://github.com/celzero/rethink-app/issues/1005#issuecomment-2050241475). It's possible I actually skipped over those. Unfortunately I didn't think to check my current version before updating Rethink.

> #1361
> 
>     * Can you confirm whether both _Downloads folder_ & _Logcat_ did not work?
> 
>     * For _Downloads folder_, make sure Rethink has been _granted_ access to write to the external storage.

I'm working on putting together a reply on that issue.

**Comment by ignoramous** [comment]
> this is desirable when rethink is under vpn lockdown mode though

Certainly, but apps running servers (listening on some port) won't work with Rethink (I am out of ideas on how to make them work, given port forwarding isn't possible on Android as both the VPN app, that is Rethink, and the server app, here pDNSf, run in the same network namespaces; on top, Android doesn't let VPN apps creat `raw` sockets, either). 

Such apps will have to be *excluded*.

That said, you can still choose to loopback these server apps into Rethink (but they won't work) by turning ON *Configure* -> *Network* -> *Loopback proxy forwarder apps*.
