### ISSUE TITLE
v055e: packet capture to file broken

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1361]
A user writes,

> I tried to get a packet capture so I could try and confirm what was going on, but for some reason it's now producing broken `.pcap` files that can't be recognized by Wireshark, or even by the file command. I can open another issue for that if you want.

From: https://github.com/celzero/rethink-app/issues/1360#issue-2238363626

**Comment by Rhys-T** [comment]
> * Can you confirm whether both _Downloads folder_ & _Logcat_ did not work?

The 'Logcat' option seems to work fine. The 'Downloads folder' option creates a file successfully -  the file just isn't correctly formatted.

> * For _Downloads folder_, make sure Rethink has been _granted_ access to write to the external storage.

The first time I tried it, it prompted me to grant that, and I did. I wondered whether the header had been lost as a result of that somehow, but I tried it a second time with the permission already granted, and it failed the same way.

---

I've had a chance to examine the broken files more closely. It looks like they're missing the initial [global header][], and instead begin with the first [packet header][]. (Enough network activity happens in the background that I don't know whether any actual packets from the beginning are being lost or not.) I don't see any sign of the global header (`D4C3B2A1` etc.) anywhere else in the file - it seems to just be missing.

[global header]: https://wiki.wireshark.org/Development/LibpcapFileFormat#global-header
[packet header]: https://wiki.wireshark.org/Development/LibpcapFileFormat#record-packet-header

**Comment by ignoramous** [comment]
This is helpful. I think the ongoing "improvements" we are making where we [never](https://github.com/celzero/firestack/commit/0e5fce46fbc83cb10c62b77f7e139bf9f0cff050) [restart](https://github.com/celzero/firestack/commit/c3b11d641c68386b61ee1cd3692470f1ef507fc0) the network engine (regardless of whether [the VPN service is restarted](https://github.com/celzero/rethink-app/blob/e40ae417434ee8c7a645a6b59251db1f4035f101/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L1739-L1784)) might have caused this.

**Comment by Rhys-T** [comment]
Could be. I also noticed that one of the test files kept getting written to for a long time after I thought I had stopped it, ending up over 2 GiB. I had convinced myself that I just missed stopping the capture somehow, but I just did some more testing, and it seems like once I start capturing (to either a file or logcat), it keeps going even after I turn it back off. Turning Rethink off and back on seems to stop the capture.

**Comment by ignoramous** [comment]
> I just did some more testing, and it seems like once I start capturing (to either a file or logcat), it keeps going even after I turn it back off. Turning Rethink off and back on seems to stop the capture.

Yikes.

https://github.com/celzero/rethink-app/blob/02eda856d129d5b64adb1f5c7e876eccfcae11db/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L1714-L1722

Network engine (`vpnAdapter`) must be instructed to *stop* capturing before the `return` on line 1718.

**Comment by hussainmohd-a** [comment]
Fix: https://github.com/celzero/rethink-app/pull/1351/commits/378857765998f14a13daaae026ed7c7e11744415

**Comment by Rhys-T** [comment]
Just got 055g through F-Droid, and this seems to be fixed. I've tested both Logcat and Downloads folder modes, and they both seem to stop immediately when I change the setting again. Thanks!

**Comment by ignoramous** [comment]
Thanks for confirming. The pcap file isn't malformed anymore, is it?

**Comment by Rhys-T** [comment]
🤦 Sorry, I think perhaps I wasn't quite fully awake yet when I posted that, because I completely forgot to check on the thing this issue was originally about. But I can confirm that the new .pcap files seem to have the proper header, and are loaded correctly by Wireshark.
