### ISSUE TITLE
request: Show Network Speed in Status Bar

### ISSUE THREAD

**Issue by ppittle** [celzero/rethink-app#1363]
**Feature Request:** Show the current data usage in the Status Bar

Similar to #235 

Some versions Android include an option to display network data usage in the status bar, but [not all do as it's not a feature in AOSP](https://discuss.grapheneos.org/d/2041-network-speed-monitor-in-status-bar).

Rethink currently displays network speed on the home page above the pause button.  I'd like the option to have this data displayed in the android status bar.

My current work around is to use a separate app ([DataMonitor](https://github.com/itsdrnoob/DataMonitor)) for this, but for battery, performance, privacy, etc I'd prefer to not have an extra app monitoring data usage.

**Comment by ignoramous** [comment]
Thanks.

Dup: #1225 (feel free to reopen if it isn't a dup).
