### ISSUE TITLE
[Request] Adding  a function Holding browser cache on memory to this app.

### ISSUE THREAD

**Issue by yutayu** [celzero/rethink-app#1366]
I want use android without disk as possible as we can :P

**Comment by ignoramous** [comment]
Sorry, I don't understand your request. Can you elaborate a bit more?

**Comment by yutayu** [comment]
Dns cache holds dns queries on memory a while.
Data cache holds datas on memory like it.

Firefox holds data cache on disk , that is not fast.

**Comment by yutayu** [comment]
sorry ,That is to complicated lol.
 I shall close.
