### ISSUE TITLE
Wireguard Connection Fails If Screen Locked for a long time

### ISSUE THREAD

**Issue by anxiouslelimo** [celzero/rethink-app#1368]
I have two wireguard connections. WG1 is set for all apps except browser with Lockdown Mode + Always On turned on. WG2 is just for browser with Lockdown Mode On. However if phone is locked for a long time, WG2 even though showing connected in wireguard menu never connects to internet. Have to toggle ON/OFF to reconnect. Tried with _Configure-Network-Loopback_ toggled ON/OFF. No issues with WG1.

**Comment by ignoramous** [comment]
We are aware of this, and are unsure why WireGuard enters such a state. See if these couple changes help:
- Set `KeepAlive` to a value between `30s` & `3600s` (1 hour). Higher values would be kinder on the battery.
- Tap on the `Refresh` button at the top right-hand corner of *Configure* -> *Proxy* UI and see if connection recovers (of course, too tedious to keep doing it every time Android comes up from deep sleep).

I expect a "fix" to land in the next version, `v055f`, in the coming days.

**Comment by nomisma-qt** [comment]
Not sure at all if related, but in Android 14 Developer options, there is a "Mobile data always active" switch, with the explanation:

"Always keep mobile data active, even when Wi-Fi is active (for fast network switching)"

Again, i have no idea if related, but i've been trying to find settings that would help with this, in related to #1367 and this issue. Hope it can be fixed.

**Comment by ignoramous** [comment]
> but in Android 14 Developer options, there is a "Mobile data always active" switch

Unrelated. Rethink can use both mobile and wifi if you want it to; turn ON *Configure* -> *Network* -> *Use all available networks*

**Comment by ignoramous** [comment]
Can you confirm if this issue still persists in [`v055i`](https://github.com/celzero/rethink-app/releases) or later versions?
