### ISSUE TITLE
Vivaldi: name not resolved

### ISSUE THREAD

**Issue by bohwaz** [celzero/rethink-app#1369]
When using Rethink DNS Plus and Vivaldi configured to use a custom DNS provider, Vivaldi cannot resolve any domain name, with a DNS error.

You need to go to Settings > Privacy and Security > Use secure DNS, and switch back to "Use default provider", or if it still doesn't work, disable secure DNS, as this is handled by Rethink anyway.

Just letting this here in case anyone needs it :)

**Comment by ignoramous** [comment]
Thanks!
