### ISSUE TITLE
v055e: WireGuard with multiple DNS entries 

### ISSUE THREAD

**Issue by nomisma-qt** [celzero/rethink-app#1372]
> I think I found the issue: at least if you have a custom DNS specified as I have, the Fritzbox Wireguard config for the client contains these two lines specifying the DNS:
>```
> DNS = 192.168.178.199,192.168.178.1
> DNS = fritz.box
>```

I do not know if this is according to the Wireguard spec or if the implementation from AVM is faulty, but there are two differences between the official Wireguard client and RethinkDNS:
- the Wireguard client gracefully combines both DNS entries into one, while ReThink only displays the first line and seems to ignore the second one
- with my setup, only the first DNS entry "192.168.178.199" is valid, and RethinkDNS does not seem to use that one, but Wireguard does. I am however unsure if that was simply bad luck or something caused by the implementation.

As soon as I delete the DNS entry in ReThink and replace it with only the correct DNS entry, the connection works.

_Originally posted by @Braintoe in https://github.com/celzero/rethink-app/issues/1298#issuecomment-2016905913_

**Comment by ignoramous** [comment]
A user says,

> I run my own WG peer on a VPS (trailofbits/algo project.) It provides a QR code for setup. That QR code includes the default DNS server configured in the settings on the VPS server, with both ipv4 and ipv6 addresses. If i use that QR code to set up my android phone to use WG for example with the "WG Tunnel" app by Zane Schepke, found on F-Droid, then the VPN tunnel works fine.
>
> In rethink, DNS does not work by default. In 'wg3' edit mode, where i edit the name, private key, public key, peer addresses and DNS servers, there are two addresses for the DNS, ipv4 and ipv6.
> 
> I have to remove the ipv6 address after the comma.

**Comment by ignoramous** [comment]
> I have to remove the ipv6 address after the comma.

See: #1483

**Comment by ignoramous** [comment]
We fixed this issue but it caused a bunch of other issues... But this one has been fixed.
