### ISSUE TITLE
Wireguard DNS for Specific Applications

### ISSUE THREAD

**Issue by anxiouslelimo** [celzero/rethink-app#1378]
In the current implementation, Simple mode doesn't let you select specific applications and in Advanced mode, Wireguard DNS is not used. In Proton Wireguard configuration, I noticed that the connection is noticeably faster in Simple mode. But currently in scenarios where Wireguard is required only for selected applications, there is a shortcoming where one can't select the DNS preference.

**Comment by ignoramous** [comment]
For *Simple* mode, we won't add any more knobs such as excluding apps; as it won't be *Simple* anymore.

> I noticed that the connection is noticeably faster in Simple mode

Unlikely that this holds true across network conditions / setups. Both modes use the same WireGuard impl underneath.

>  Simple mode doesn't let you select specific applications

We intend to bring `Bypass from Proxy` as a per-app setting: #1270 (closing; feel free to re-open)
