### ISSUE TITLE
add a root mode and a normal mode during first setup

### ISSUE THREAD

**Issue by rajarshikhatua100** [celzero/rethink-app#1380]
so add a different root mode support for enhanced experience for these who have root. I suggest add it during first setup of the app something like what adaway does

**Comment by yoshimo** [comment]
What could he improved with the additional power?

**Comment by yoshimo** [comment]
I know but since the app can also connect to a VPN, it isn't a deal breaker.

**Comment by ignoramous** [comment]
As mentioned above, Rethink does support connecting to WireGuard, SOCKS5, and HTTP upstreams, even if it occupies the only VPN slot on Android.

For root specifically, please track:
- #78 
- #66
