### ISSUE TITLE
v055e: WireGuard drops connection after airplane mode

### ISSUE THREAD

**Issue by Ypot** [celzero/rethink-app#1381]
RethinkDNS 055e with Wireguard proxy active. 
First, activate airplane mode. 
Deactivate airplane mode. 
Instead of resuming anonymous connection, the connection is direct (Wireguard says "failing"), there is no proxy and no notification that the IP is public.

**Comment by ignoramous** [comment]
- Are you using WireGuard in *Advanced* mode or *Simple* mode?
    - If in *Advanced* mode, have you enabled *Always-on* or *Lockdown* on any of the *active* WireGuard configs?
- What do you mean when you say "resuming anonymous connection"?
    - Where are you testing for public IP leak?
    - And is that app that's testing it, added to the *failing* WireGuard config (described above)?
    - What do the entries in Rethink's Network Log for the app which you used to test IP leaks show (tap on the entries, a *bottomsheet* should come up. The top right-hand corner of that *bottomsheet* should show whether the connection was proxied or not; while the footer of the *bottomsheet* should show the final status of the connection if it has *closed* and isn't "active").

**Comment by Ypot** [comment]
Updated to 55h. Same problem:

> * Are you using WireGuard in _Advanced_ mode or _Simple_ mode?
>   
Advanced mode.
>   * If in _Advanced_ mode, have you enabled _Always-on_ or _Lockdown_ on any of the _active_ WireGuard configs?
No
> * What do you mean when you say "resuming anonymous connection"?
>   
Resuming using Wireguard IP 
>   * Where are you testing for public IP leak?
Here: 
https://duckduckgo.com/?q=what%27s+my+IP&t=ofa&ia=answer
>   * And is that app that's testing it, added to the _failing_ WireGuard config (described above)?
The app is opera, no exception with it in the Wireguard config.
>   * What do the entries in Rethink's Network Log for the app which you used to test IP leaks show (tap on the entries, a _bottomsheet_ should come up. The top right-hand corner of that _bottomsheet_ should show whether the connection was proxied or not; while the footer of the _bottomsheet_ should show the final status of the connection if it has _closed_ and isn't "active").

[img]https://i.imgur.com/tPm9HFJ.jpeg[/img]

**Comment by ignoramous** [comment]
> Updated to 055h. Same problem:

Do I understand your problem right:
- After airplane mode, WireGuard (in *Advanced* mode, but not *Lockdown*) is *active* (and not *failing* or *disabled*)
- Opera, which is added to the WireGuard, stops being sent over WireGuard.

Can you check what status that WireGuard is in after airplane mode is deactivated? Is it showing *disabled* or *active*?

Putting *Advanced* WireGuard in *Lockdown* will make sure that apps (here, Opera) would always be sent over WireGuard regardless of whether it is *active* or *disabled*.

**Comment by Ypot** [comment]
It's working perfectly now. 
Thanks!!

**Comment by ignoramous** [comment]
@Ypot nice, but how did you fix it?

**Comment by Ypot** [comment]
I thought that selected apps where excluded from Wireguard, and it's just the opposite. 
I miss a lot to have big documentation for each option.
