### ISSUE TITLE
Unable to use On-device blocklist 

### ISSUE THREAD

**Issue by ZenzoK90** [celzero/rethink-app#1388]
Hello Rethink developer team, I'm here again to report an issue that comes up with the new and latest version 0.5.5f. Whenever an update comes, there's always in some way the small issue pops up, as I'm experiencing these from the past few updates. 
This time again, it's about On-device blocklist where I'm not able to open or configure blocklist anymore. 
When I try to enable blocklist it shows "Start Rethink to Proceed " even if the service is started and still running and protected. I mean, it didn't let me in to configure and start or enable blocking. 
Try to re-install and start over but in vain.
![Uploading Screenshot_20240426-000703_Rethink.jpg…]()

**Comment by hussainmohd-a** [comment]
@ZenzoK90, this is a known issue in v055f, which has been fixed in v055g. You can download the updated release from [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5g).
