### ISSUE TITLE
v055g: SOCKS5 via Termux, Not working

### ISSUE THREAD

**Issue by Amir2367** [celzero/rethink-app#1399]
when from the SETUP SOCKS5 PROXY section
To connect, we choose the TERMUX program, no connection is made while the connection is made with Other programs.

**Comment by ignoramous** [comment]
1. Go to *Apps* and search for *Termux*.
2. Tap on its entry.
3. Exclude *Termux*.

Similar: #1356

**Comment by Amir2367** [comment]
> 1. Go to _Apps_ and search for _Termux_.
> 2. Tap on its entry.
> 3. Exclude _Termux_.
> 
> Similar: #1356

I did all the steps according to your instructions, but it still didn't connect.

https://github.com/celzero/rethink-app/assets/83357422/2bf091aa-44eb-4020-b673-038d6d41fa8d

**Comment by Amir2367** [comment]
> 1. Go to _Apps_ and search for _Termux_.
> 2. Tap on its entry.
> 3. Exclude _Termux_.
> 
> Similar: #1356

I did all the steps according to your instructions, but it still didn't connect.

https://github.com/celzero/rethink-app/assets/83357422/859562c1-581d-4c04-aef6-4315b7ac2342

**Comment by ignoramous** [comment]
> did all the steps according to your instructions, but it still didn't connect

No, you haven't.

*Exclude* Termux.

**Comment by Amir2367** [comment]
> > did all the steps according to your instructions, but it still didn't connect
> 
> No, you haven't.
> 
> _Exclude_ Termux.

Isn't it like this?
It was the same in the video
![Screenshot_2024-04-28-23-53-48-633_com celzero bravedns](https://github.com/celzero/rethink-app/assets/83357422/513616c8-0124-4eba-9ac7-e936b2cda00f)

**Comment by Amir2367** [comment]
> > did all the steps according to your instructions, but it still didn't connect
> 
> No, you haven't.
> 
> _Exclude_ Termux.

Isn't it like this?
It was the same in the video
![IMG_20240428_235529](https://github.com/celzero/rethink-app/assets/83357422/c461bb9b-e1ba-4f28-9da1-3a012c89727d)

**Comment by Amir2367** [comment]
> > did all the steps according to your instructions, but it still didn't connect
> 
> No, you haven't.
> 
> _Exclude_ Termux.

Wow, I was able to connect, thank you for your help❤️
