### ISSUE TITLE
Notify users when automatically switching DNS servers

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#140]
DNS server switches to the default (RethinkDNS Basic) at least in one case today where none of the selected DNSCrypt servers could be connected to. This can happen due to several reason, the most common one is when DNSCrypt server certs couldn't be downloaded / refreshed (which needs to be done periodically).

When doing so, notify the user of the change as default server is something they may not trust.

Alternatively, should we let user choose a default DNS over HTTPS server they trust?

**Comment by obeho** [comment]
> should we let user choose a default DNS over HTTPS server they trust?

That's better

**Comment by ignoramous** [comment]
We are leaning towards letting users select a fallback / default / secondary DNS endpoint. May be show a notification when the failover happens?

Track progress here #211
