### ISSUE TITLE
Unexpected Google DNS Usage Despite Configuration for NextDNS

### ISSUE THREAD

**Issue by Vildnex** [celzero/rethink-app#1406]
**Rethink DNS version:** v0.5.5h
**Phone:** Huawei P40
**Custom DNS:** NextDNS

<details><summary>When I am trying to setup my `Rethink DNS` to use my `NextDNS` link via the **Other DNS** option I will do as fallow</summary>
image:

![image](https://github.com/celzero/rethink-app/assets/10352059/a12663be-f37e-467f-960e-3322d8163da0)
</details>

<details><summary>Also my DNS setting is set to off on my **Private DNS** settings:</summary>
image2:

![Screenshot from 2024-04-30 12-07-15_v2](https://github.com/celzero/rethink-app/assets/10352059/6a286f98-5274-4d52-85b5-0447c5cc59fc)
</details>

### **The Problem:**

<details><summary>Now with this setup I am expecting to use only my DNS from the NextDNS, but in reality... I am using Google DNS from some reason:</summary>
image3:

![Screenshot_20240430_121329_com celzero bravedns](https://github.com/celzero/rethink-app/assets/10352059/4fc5ca51-67a1-416f-b330-c0d29eb93c5d)
</details>

<details><summary>Also on my NextDNS application is going to tell me that the Google DNS is used instead of mine:</summary>
image4:

![Screenshot_20240430_121335_com doubleangels nextdnsmanagement](https://github.com/celzero/rethink-app/assets/10352059/05b04032-a35a-4b22-8e0c-1f6588ce36d0)
</details>

### **Workaround:**
The only workaround that I could find in order to use my DNS is to setup the Rethink DNS to use the **System DNS** instead of **Other DNS** and the all the traffic will go to my `NexDNS`, but if I will do that I will not have the option to enter into the **DNS**  section of **Rethink DNS**
<details><summary>next time because of this error:</summary>
image5:

![Screenshot_20240430_122822_com celzero bravedns](https://github.com/celzero/rethink-app/assets/10352059/d079d133-fe45-4c4c-aec2-4ad9106412bc)
</details>

### **Question:**

This is 100% reproducible every single time, did I make some mistakes in terms of configuration or this is an issue? Or this is how it was intended to be from the beginning?

**Comment by ignoramous** [comment]
I just setup DoT to `dns.nextdns.io` and https://which.nameserve.rs/ and https://browserleaks.com/dns both show NextDNS as the upstream.

Can you check?

**Comment by Vildnex** [comment]
Regarding the first check, I have to add that after some time this problem it as change. Not even if I still have the Google DNS 8.8.8.8 everywhere in my logs. When I am trying to use those 2 links you provide me I will get my DNS from my home network displayed instead of either Google or NextDNS.

![Screenshot_20240506_133618_org mozilla fennec_fdroid](https://github.com/celzero/rethink-app/assets/10352059/5a02e1d9-089f-4570-9ffd-6fc1c87da800)
![Screenshot_20240506_133636_org mozilla fennec_fdroid](https://github.com/celzero/rethink-app/assets/10352059/df05db4d-2eeb-45cd-a206-bfd56484ecc4)

**Comment by ignoramous** [comment]
> Not even if I still have the Google DNS 8.8.8.8 everywhere in my logs ... Also, I had already the Prevent DNS leaks checked from the beginning, with or without it (I've tried it both ways) I will always get the same DNS calls to Google.

Entries of `8.8.8.8` in *Network Logs* doesn't mean Rethink is using Google DNS. Please follow this and let me know what you see:

> > These redirect DNS requests would show up with a white coloured left-hand side border (and if you tap on its entry, the bottomsheet that would come up should show in the top right-hand corner a chip that goes DNS Proxied).

> The only exception to this is when I will set the DNS to be at the system level instead.

See if your browser app (Firefox?) is "Excluded" from Rethink's tunnel (from *Configure* -> *Apps*). If so, un-Exclude it. You can also try enabling Android's *Always-on VPN* and *Block connections without VPN* and then check what `dnsleaktest.com` or `browserleaks.com/dns` or `which.nameserve.rs` report.

**Comment by Vildnex** [comment]
Also, I've just updated my rethink app to version `v0.5.5i`, but the issue persists.

**Comment by ignoramous** [comment]
> I can confirm that the DNS leak issue occurs in version 0.5.5h (obtained from F-Droid). I have identified it as a DNS leak by repeatedly accessing https://browserleaks.com/dns using various browsers, where version 0.5.5h consistently reveals the IP addresses of my system resolver.

Can you confirm if you setup *Block connections without VPN* and the leaks persisted?

Either the browsers are doing their own DNS (for example, Chrome has "Secure DNS", Firefox has "Trusted Recursive Resolver"), or something with Rethink's setup has gone whack.

Unfortunately, we are unable to reproduce these leaks, nor has anyone else reported it. If you're technical enough, go to *Configure* -> *Settings* -> *Log level* and set it to *Verbose*, then will you please capture and email `adb logcat` ([ref](https://www.xda-developers.com/how-to-take-logs-android/)) output to `mz` at `celzero` dot `com` (do mention this github issue)?

> Despite attempting to toggle the website favicon setting on and off, the leak persists.

These website-based "DNS leak" tests aren't a fool-proof. Turning ON website favicon download in Rethink doesn't *leak* DNS, but instead confuses these services in thinking there is one.

>  Upon uninstalling version 0.5.5h and reinstalling version 0.5.4c, the leak ceased; however, version 0.5.4c lacks the ability to set the fallback DNS to None.

In the latest versions, setting *Fallback DNS* to *None* is equivalent to setting it to *System DNS*.

**Comment by ignoramous** [comment]
> because the fallback DNS is "none" and the app notification still shows "protected" and "connected to DNS", they may not realize that they are actually using system DNS.

*Fallback DNS* is used in 2 scenarios:
1. If Fallback DNS replaces a permanently unconnectable user-preferred DNS, then Rethink's homescreen would show "using fallback dns".
2. For domains that Rethink itself needs to resolve.

> Is there a way to disable all fallbacks even if the user-preferred DNS fails?
