### ISSUE TITLE
Bepass flavour Wireguard

### ISSUE THREAD

**Issue by Amir2367** [celzero/rethink-app#1408]
Hello to the hardworking Rethink team, I have a request from your development team, if possible, use Wireguard Go in addition to Wireguard core or replace Wireguard core. We are users in the area that is blocked by Wireguard. Only Wireguard Go responds.
The reason for the importance of the core of Wireguard Go is the download and upload of this core, thank you.

Wireguard Go project links:
https://github.com/WireGuard/wireguard-go
https://github.com/bepass-org/warp-plus

**Comment by Lanius-collaris** [comment]
bepass-org/warp-plus 's wireguard tricks:
https://github.com/bepass-org/warp-plus/blob/4dc2259edc59577b664717a40ec409e68cee611f/wireguard/device/send.go#L90-L116

https://github.com/bepass-org/warp-plus/blob/4dc2259edc59577b664717a40ec409e68cee611f/wireguard/device/send.go#L122-L126

https://github.com/bepass-org/warp-plus/blob/4dc2259edc59577b664717a40ec409e68cee611f/wireguard/device/send.go#L161-L165

**Comment by Amir2367** [comment]
> bepass-org/warp-plus 's wireguard tricks: https://github.com/bepass-org/warp-plus/blob/4dc2259edc59577b664717a40ec409e68cee611f/wireguard/device/send.go#L90-L116
> 
> https://github.com/bepass-org/warp-plus/blob/4dc2259edc59577b664717a40ec409e68cee611f/wireguard/device/send.go#L122-L126
> 
> https://github.com/bepass-org/warp-plus/blob/4dc2259edc59577b664717a40ec409e68cee611f/wireguard/device/send.go#L161-L165

@ignoramous

**Comment by ignoramous** [comment]
> bepass-org/warp-plus 's wireguard tricks:
https://github.com/bepass-org/warp-plus/blob/4dc2259edc59577b664717a40ec409e68cee611f/wireguard/device/send.go#L90-L116

Interesting. Similar (but less qualitative) than Mullvad's DAITA: https://github.com/mullvad/wireguard-go/commit/f4bc3aefeb6c6ae50567a4bfc177593337eb9cba

**Comment by ignoramous** [comment]
Thanks for the code pointers.

Implemented. Will be available in `v055o` (due a release soon-ish pending a few ongoing tests).
