### ISSUE TITLE
SOCKS5 / HTTP tunnels through Shadowrocket does not work

### ISSUE THREAD

**Issue by 29ru** [celzero/rethink-app#1417]
Hello!
In the latest versions, the previously fixed problem with tunneling will reappear.
[https://github.com/celzero/rethink-app/issues/1017]
Please correct.

**Comment by ignoramous** [comment]
Try *Excluding* Shadowrocket and see if it works?

1. From *Configure* -> *Apps*
2. Search for *Shadowrocket* -> tap on its entry
3. Look for *Exclude* -> tap on its icon

**Comment by 29ru** [comment]
Thank you, but this setting was set previously. Why did she fold? Will the settings be lost when updating versions?

**Comment by ignoramous** [comment]
> Thank you, but this setting was set previously.

We made changes to route external proxy apps within Rethink's local tunnel as part of #393. This may break some of the proxy apps; see:
- #1356 
- #1360

>  Why did she fold?

We're considering rolling back to `v055a` behaviour.

> Will the settings be lost when updating versions?

When updating Rethink? Slim chances, yes.

(closing this issue as it a dup of the ones mentioned above; feel free to re-open).
