### ISSUE TITLE
Rethink crashes when there is no network or if there is no network and I click on stop

### ISSUE THREAD

**Issue by shifoc** [celzero/rethink-app#1427]

**Comment by shifoc** [comment]
https://github.com/celzero/rethink-app/assets/32818143/dc874529-4090-4b31-94ff-0c627781987a

**Comment by hussainmohd-a** [comment]
@shifoc Please provide details on the Rethink version you're using. Additionally, could you share the logs for further analysis?

**Comment by shifoc** [comment]
V0.5.5i

How do I get the logs?

**Comment by hussainmohd-a** [comment]
Please follow these steps to capture logs for further analysis:

1. Go to Configure -> Settings -> Log level and set it to Verbose.
2. Reproduce the issue you're experiencing.
3. Use `adb logcat` to capture logs. You can refer to [this guide](https://www.xda-developers.com/how-to-take-logs-android/) for assistance.
4. Email the captured logs to md@celzero.com and mention the GitHub issue related to this matter.

**Comment by PikaGamer8** [comment]
I don't know if this helps but I used LogFox to get this error. It seems to happen randomly but mostly when I switch from mobile data to WiFi.


*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a53xue/a53x:14/UP1A.231005.007/A536U1UES8DXD7:user/release-keys'
Revision: '9'
ABI: 'arm64'
Processor: '0'
Timestamp: 2024-05-11 10:39:23.406458942-0400
Process uptime: 4s
Cmdline: com.celzero.bravedns
pid: 2900, tid: 2960, name: Thread-27  >>> com.celzero.bravedns <<<
uid: 10432
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0  0000000000000000  x1  0000000000000b90  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000001  x5  0000000000000001  x6  0000000000000000  x7  000000000000000a
    x8  0000000000000083  x9  0000000000000035  x10 000000000000001e  x11 0000007b60661042
    x12 0000000000000001  x13 0000000000000000  x14 0000000000000002  x15 0000000000000003
    x16 0000007b1092d340  x17 0000007b10a247f0  x18 0000007b0ec28000  x19 0000000000000b54
    x20 0000007b10a24690  x21 0000004000180808  x22 0000007d69708d50  x23 0000000000000000
    x24 000000005aea82e8  x25 0000000012ffdfa8  x26 0000000000000000  x27 0000000000000010
    x28 0000004000093500  x29 0000004000073ad8
    lr  0000007b5fef1924  sp  0000004000073ae0  pc  0000007b5ff106f8  pst 0000000080001000
1 total frames
backtrace:
      #00 pc 00000000002f76f8  /data/app/~~lY_j6e-XWNFJkbv2GpsRYA==/com.celzero.bravedns-d6V19q-nUD5BNtO0_bulcA==/base.apk (offset 0x33c000)

**Comment by ignoramous** [comment]
The fix is to add the following to the app's `Android manifest.xml` ([ref](https://archive.ph/OF5K8)).

```diff
+  <application android:allowNativeHeapPointerTagging="false">
  ...
  </application>
```

instead of:

https://github.com/celzero/rethink-app/blob/825d27bbf30522b41d5698e457cd02e6ded61279/app/src/main/AndroidManifest.xml#L39

**Comment by shifoc** [comment]
![Screenshot_20240518_233144_Rethink.png](https://github.com/celzero/rethink-app/assets/32818143/bae2bf03-53b9-4ee1-b380-481fcea0f962)

I don't know if it's considered fixed or not but it's not crashing anymore
