### ISSUE TITLE
Enabling Block connection without VPN in Android

### ISSUE THREAD

**Issue by sankhababu** [celzero/rethink-app#1429]
Sir
I'm using Rethinkdns app in android. It's really a dream project. 👌👏

🔸I use it with system dns enabled (as I using adguard in private dns).
🔸I enabled WireGuard proxy with Proton.
🔸Have Excluded, Blocked & Allowed apps.
🔸In Android's vpn setting I've enabled 'Always on' for Rethink app.

❓With this configuration my quarry is - can I enable 'Block connections without VPN' ?

In Netguard app it is not allowed, as notification pop-ups 'do not enable this setting'. With Rrthink app I did not see such.

Will this work rightly with my other settings of Rethink app as expected ?

Regards

**Comment by hussainmohd-a** [comment]
@sankhababu, the app works as expected when the "Block connections without VPN" setting is turned on. This setting restricts internet access for excluded apps. Therefore, we will not exclude any apps when this setting is enabled. Feel free to opt out of excluding apps when activating this setting.
