### ISSUE TITLE
Logs for Domains and network contradict each other

### ISSUE THREAD

**Issue by shifoc** [celzero/rethink-app#1431]
<details><summary>Even though it should be blocked since the domain is blocked, it wasn't blocked</summary>
image1:

![Screenshot_20240510_034151_Rethink.png](https://github.com/celzero/rethink-app/assets/32818143/edc4383a-5797-4bea-a43e-04c85485c6b4)

image2:
![Screenshot_20240510_034134_Rethink.png](https://github.com/celzero/rethink-app/assets/32818143/d97598c3-c39a-4f5f-9a77-97fad35b28bd)
</details>

**Comment by ignoramous** [comment]
Thanks. We can reproduce this. This happens when back-to-back DNS requests (for the same domain but different query-type (`a` vs `aaaa` vs `https` vs `svcb`) override our internal blocklists cache.

**Comment by ignoramous** [comment]
This has been fixed in `v055j` ([github](https://github.com/celzero/rethink-app/releases/tag/v0.5.5j), [website](https://rethinkdns.com/download)). F-Droid and Play Store pending approvals.
