### ISSUE TITLE
VPN always on gets disconnected after some phone idle time

### ISSUE THREAD

**Issue by nu111** [celzero/rethink-app#1434]
Hi, on Android 13 and rethinkdns 0.5.5i,
I have setted the VPN as "always on".

Frequently I receive the notification of VPN disconnected 🔑.
Expanding the notification shows a button to launch rethinkdns app again, this fix the connection.

This never happened while activily using the phones, it happens after some time without unlocking the screen.

**Comment by ignoramous** [comment]
What version of Android are you on?

Are you on a Pixel or using GrapheneOS?

Are you technical enough to grab `adb logcat` output? 

```sh
# make sure Rethink is at "Verbose" in 
# Configure -> Settings -> Log level

# note the current size; the default is usually 256kb
adb logcat -g

# increase log buffer size to 16mb
adb logcat -G 16M

# see if it switched to 16mb
adb logcat -g

# now, at some later time, when Rethink "freezes", capture logs
adb logcat > /path/to/file

# compress it
gzip -k /path/to/file

# email the gz file
```

**Comment by ignoramous** [comment]
> I am on Pixel 4a and i am running stock OS.

If so, it might be related to #1427

> Later I'll try to retrieve that log!

Please do. You can alternatively capture logs from tapping on "Bug report" button at the top of the *About* page in the app.

**Comment by nu111** [comment]
> Please do. You can alternatively capture logs from tapping on "Bug report" button at the top of the About page in the app.

Yes, I am sorry for being late on this.
Meanwhile I tried to set the battery usage as "without limits"
![Screenshot_20240516-205931](https://github.com/celzero/rethink-app/assets/1246989/4c546a4a-db26-4799-902f-abf447053220)

It seems that after this the issue is less frequent.

**Comment by ignoramous** [comment]
> It seems that after this the issue is less frequent.

**Comment by nu111** [comment]
To add more details: now it seems to happen only after the phone recovers from "do not disturb" mode. BTW I have sent a log of one of this events.

Thanks!

**Comment by xa4hf8** [comment]
It seems like there is some kind of power management issue here: when awakening from a deep sleep/hibernate state (not sure which level), Rethink stops working and no internet traffic passes until i select the app from Android Task Manager.  I then see a message at screen bottom which says `WAITING` or `NO INTERNET`.  This message disappears immediately and it starts working again (Status = `PROTECTED`). Battery preference for Rethink is set to "Unrestricted".

Pixel 3 with OEM Android (API = 31, Total RAM = 3579 MB)

i may need to capture some more data, but this might be relevant
[Rethink.log](https://github.com/user-attachments/files/21125059/Rethink.log)

The following was logged at wake from a shallow hibernate or doze mode:
[wake.log](https://github.com/user-attachments/files/21127135/wake.log)

**Comment by xa4hf8** [comment]
> Are you technical enough to grab `adb logcat` output?

For reference, some related logcat tools:

**Android**
https://f-droid.org/en/packages/com.f0x1d.logfox/
https://f-droid.org/en/packages/com.dp.logcatapp/
https://f-droid.org/en/packages/com.tortel.syslog/

Unless rooted, permission is required to read logs
(one-time configuration via `adb`)

`>` `adb shell pm grant [APP ID] android.permission.READ_LOGS`
___
**Desktop terminal app**
https://github.com/flxo/rogcat
