### ISSUE TITLE
[Question] Possible to let Doh/Dot to not go trough wireguard proxy?

### ISSUE THREAD

**Issue by Gontier-Julien** [celzero/rethink-app#1439]
As the title says i wonder if it is possible to let Doh/Dot to not go trough a wireguard proxy?

Reasoning: reducing latency

**Comment by Gontier-Julien** [comment]
Also others question is to know if it is possible to enable the proxy only when enabling the dns/firewall option

**Comment by ignoramous** [comment]
> wonder if it is possible to let Doh/Dot to not go trough a wireguard proxy?

Yes, enable *Never proxy DNS* in *Configure* -> *DNS*.

> possible to enable the proxy only when enabling the dns/firewall option

No. Though, using proxy requires *Firewall-only* or *DNS + Firewall* mode. It won't work in *DNS-only* mode.

Please ask questions in our [telegram group](https://t.me/rethinkdns), [subreddit](https://reddit.com/r/rethinkdns), or [discussions](https://github.com/celzero/rethink-app/discussions).
