### ISSUE TITLE
Is it possible to use RethinkDNS strictly as a local DNS filtering solution?

### ISSUE THREAD

**Issue by cold-nagai** [celzero/rethink-app#1442]
I want to avoid using RethinkDNS DNS servers and use the VPN's provided DNS server instead because of the fingerprinting concerns. Is it even possible?

**Comment by ignoramous** [comment]
Yes, download and enable *On-device blocklists* in *Configure* -> *DNS* (available only on [F-Droid](https://f-droid.org/packages/com.celzero.bravedns) and [Website](https://rethinkdns.com/download) flavours).

Please ask questions in our [telegram group](https://t.me/rethinkdns), [subreddit](https://reddit.com/r/rethinkdns), or [discussions](https://github.com/celzero/rethink-app/discussions).
