### ISSUE TITLE
Help to know if there is DNS leak

### ISSUE THREAD

**Issue by Ypot** [celzero/rethink-app#1445]
Hi

Reading your documentation I have found this website: 
https://dnsleaktest.com/results.html

How should be used that data to know if we have a DNS leak? Is it easy for just a RethinkDNS user?

**Comment by ignoramous** [comment]
Rethink doesn't "leak" DNS and these websites are a rough heuristic but not always right about "leaks".

The appropriate way to check for "leaks" is to do it in a networking setup you can control and monitor, but that is only for technically adept and power users.

There exist tools with simpler output (like [browserleaks.com/dns](https://browserleaks.com/dns) and [which.nameserve.rs](https://which.nameserve.rs)) that can *detect* the current DNS resolver in-use by the client visiting respective webpages.

Please ask questions in our [telegram group](https://t.me/rethinkdns), [subreddit](https://reddit.com/r/rethinkdns), or [discussions](https://github.com/celzero/rethink-app/discussions), *GitHub Issues* is not the place for it.
