### ISSUE TITLE
No throughput on Wireguard with 0.5.5k

### ISSUE THREAD

**Issue by GoonerM466** [celzero/rethink-app#1463]
Updated to the new version but now it's only resolving DNS requests, and any data that should be going through the Wireguard tunnel fails to connect. 

Had no issues on "j" so I've rolled back, but had no luck at all with "k". 

It looks as though every connection is blocked by the firewall perhaps, even though the apps are set to exclude/bypass and they all work fine ok "k". 

No amount of tinkering would get it to work.

**Comment by ignoramous** [comment]
Yes, I messed up. ICMP connections end up blocking the network engine for 10s to 25s per ICMP request. We've since fixed this and releasing a new version right away.

Reconnecting WireGuard seems to block in a similar way, too. Need to undo this commit: https://github.com/celzero/rethink-app/commit/6b77b2fc4cb1c280e85e8614049ff771c095023f

**Comment by GoonerM466** [comment]
> Yes, I messed up. ICMP connections end up blocking the network engine for 10s to 25s per ICMP request. We've since fixed this and releasing a new version right away.
> 
> Reconnecting WireGuard seems to block in a similar way, too. Need to undo this commit: [6b77b2f](https://github.com/celzero/rethink-app/commit/6b77b2fc4cb1c280e85e8614049ff771c095023f), [c8e1784](https://github.com/celzero/rethink-app/commit/c8e178461764adb90ca318e7f52f1d3210859adb)

Well I'm glad it wasn't just a issue my end! 

I'll test out the new version when it's up and reports back.

**Comment by ignoramous** [comment]
> I'll test out the new version when it's up and reports back.

**Comment by GoonerM466** [comment]
All fixed thank you!

**Comment by weedy** [comment]
I'm using CloudFlare Warp, still can't use WG with 0.5.5.L

**Comment by ignoramous** [comment]
> using CloudFlare Warp, still can't use WG with 0.5.5.L

1. Are you able to import Warp configuration?
2. If so, does it not start?
3. If it doesn't, any error you see in the UI?
4. If not, are you technical enough to send us a bugreport? 

```bash
# note the current size; the default is usually 256kb
adb logcat -g


# increase log buffer size to 16mb
adb logcat -G 16M


# see if it switched to 16mb
adb logcat -g


# now, at some later time, when apps see significant delay, capture logs
# make sure Rethink is at "Very Verbose" in Configure -> Settings -> Log level


# capture logs
# ref: https://www.xda-developers.com/how-to-take-logs-android/
adb logcat > /path/to/file


# compress with gzip
# the command below creates /path/to/file.gz
gzip -k /path/to/file 


# email mz at celzero dot com
# and mention this GitHub issue
```

**Comment by weedy** [comment]
Did you see my email?

**Comment by ignoramous** [comment]
> Did you see my email?

Yes. Try removing ipv6 address from "Peer" *Endpoint* and the domain name too `engage.cloudflareclient...` and see if warp then works?

- #1483

**Comment by weedy** [comment]
Yeah that's the bug, it doesn't fall back anymore

**Comment by ignoramous** [comment]
> Yeah that's the bug, it doesn't fall back anymore

WireGuard itself doesn't and prefer v4 over v6 (Rethink does the reverse). We'll see what we can do short of changing WireGuard itself.

**Comment by weedy** [comment]
Fixed in N
