### ISSUE TITLE
Local .lan domains still do not get resolved while using rethinkdns on 0.5.5j

### ISSUE THREAD

**Issue by RodoMa92** [celzero/rethink-app#1466]
Setting the DNS resolver to system will immediately forward it correctly to my local DNS box on my wireguard VPN setup making them work correctly, but they still will get forwarded to rethinkdns when it's not the default, even with the do not route private IP enabled in the settings.

Resolving local ip directly works perfectly fine with no issues, just local domain names seem to be failing.

Is this an expected issue? AFAICR this has been fixed recently a couple of revisions ago.

**Comment by ignoramous** [comment]
Released in [`v055k`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5k)+.
