### ISSUE TITLE
Whitelist reverts to default on occassion

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#147]
Users have reported that the whitelist (in the Universal page of the Firewall screen) removes the apps they have added and instead reverts to the default whitelist (which is all "system components", that is, `uid`s not in the "app range" as defined by [android_filesystem_config.h](https://cs.android.com/android/platform/superproject/+/master:system/core/libcutils/include/private/android_filesystem_config.h?q=android_filesystem_config.h)).

**Comment by hussainmohd-a** [comment]
[https://github.com/celzero/rethink-app/commit/faa1ecd71fa256b758daccf7ca1d6043e1bd457f](url)

Found a case where the System components are added to whitelist by default. Modified the behaviour. Whitelisted values will remain same during the application database refresh/reload.
