### ISSUE TITLE
General firewall: Allow apps to internet when proxy is ON

### ISSUE THREAD

**Issue by freebrowser1** [celzero/rethink-app#1474]
Awesome app, but it would be nice that the 'general firewall' has an option that apps which are not allowed on the internet, are allowed when the proxy (e.g. the Wireguard VPN) is enabled with a simple switch. 
This allows use of internet on public wifi access points which is insecure when not using a VPN or proxy. So the user enables 'rethink', connects to the public wifi and enables the wireguard VPN or proxy, which only then allows internet access.

**Comment by ignoramous** [comment]
> Awesome app

Thanks.

> but it would be nice that the 'general firewall' has an option that apps which are not allowed on the internet, are allowed when the proxy (e.g. the Wireguard VPN) is enabled with a simple switch.

This is already possible. Designate a *WireGuard* (in *Advanced* mode) as *Lockdown* and *add* the app in question to route via it. You'd find that when *WireGuard* is *not* active, the app has no connectivity, and vice versa.

- dup: #976

(closing a dup, feel free to re-open if we're mistaken)

**Comment by freebrowser1** [comment]
That is nice, but for each wg vpn a separate app whitelist should be made.
Can this be combined as a general whitelist for all wg vpns ?

**Comment by ignoramous** [comment]
Yes, but unfortunately there are other pressing issues that demand our attention.
