### ISSUE TITLE
Block internet access when not in use/locked on app level

### ISSUE THREAD

**Issue by HKADSV** [celzero/rethink-app#1475]
Hi,
it would be very useful to have the above mentioned firewall settings on an app level.
Say I want to install some meta app, but refuse to let that one access the internet 24/7.
Sure I can block and unblock it, but it would be times easier to have the universal setting for each app available.

**Comment by ignoramous** [comment]
>  it would be very useful to have the above mentioned firewall settings on an app level.

This is planned (unfortunately, it isn't trivial to implement, so it won't happen anytime soon): #720 

(closing as dup, feel free to re-open if #720 does not cover this feature request).
