### ISSUE TITLE
Rethink DNS App Accessibility Settings Blocked on Android 13

### ISSUE THREAD

**Issue by OX-AK** [celzero/rethink-app#1478]
Issue:
After updating, on Android 13, the Rethink DNS app is unable to access the Accessibility settings. The app previously had Accessibility permissions enabled, but now it shows that due to security reasons, the Accessibility settings cannot be enabled.

Expected Behavior:
The Rethink DNS app should be able to access the Accessibility settings, as it did before the update, in order to function properly. Actual Behavior:
The Rethink DNS app is unable to access the Accessibility settings, and the settings show a message indicating that it cannot be enabled due to security reasons

 Impact:
The inability to access the Accessibility settings prevents the Rethink DNS app from functioning as intended, as the app relies on these permissions to operate correctly. Severity:
High, as the app is unable to perform its core functionality due to the issue.

**Comment by ignoramous** [comment]
Related? #1260

**Comment by Domy81** [comment]
It doesn't work on Android 15. There is no three dots menu available! 😤
Any solution?
