### ISSUE TITLE
Application rules do not disappear on uninstallation of app

### ISSUE THREAD

**Issue by cybgh7** [celzero/rethink-app#1485]
When having firewall rules for an application and uninstalling that application, the firewall rules persist.

I am expecting the firewall rules to disappear, because they are referencing an app which is not existing anymore on that device.

Restarting RethinkDNS does not change anything, the rules still do not disappear.

When rebooting the device, the rules actually disappear. They should be removed directly after uninstalling an app.

**Comment by ignoramous** [comment]
Some users have said they desire rules to be persisted for some time to handle scenarios where they uninstall and reinstall the same app:
- #978 

For a related bug, see:
- #951
