### ISSUE TITLE
Per-app logs older than 7 days

### ISSUE THREAD

**Issue by opk12** [celzero/rethink-app#1487]
A recent update added `1 hr - 24 hr - 7 day` in the per-app logs. The recent logs can show that an app did something weird. It would be convenient to also see have the logs since the installation, as it was before, to prove that an app did **not** do weird things long-term.

**Comment by hussainmohd-a** [comment]
@opk12, Rethink always stores network and DNS logs for no more than 7 days to avoid handling large amounts of data, both in the UI and during the backup and restore process. The current segregation of logs into 1-hour, 24-hour, and 7-day periods is designed to make navigation easier. Navigating through 7 days of data is similar to handling the complete logs as before.

**Comment by ignoramous** [comment]
> logs since the installation, as it was before, to prove that an app did not do weird things long-term

Various dependencies we use (LiveData, Room, UI components, etc) cannot handle data that large out-of-the-box. And so, we restrict logs and stats to 7 days.

**Comment by opk12** [comment]
Sorry, I did not realize that the max was already 7 days. Then it makes sense to distinguish `1 hr - 24 hr - 7 day`.
