### ISSUE TITLE
Clicking on Action required should open the app page

### ISSUE THREAD

**Issue by opk12** [celzero/rethink-app#1488]
- Install an app.
- Click on Rethink's "Action required" notification.
- Rethink opens its homepage or its list of apps.
- The details page for that app should be opened instead.

**Comment by hussainmohd-a** [comment]
@opk12, Is this action required due to the app being blocked by the universal firewall rule "Block newly installed apps"? If so, there is an action button to Allow or Deny. Is it not useful?

**Comment by ignoramous** [comment]
dup (please track #883):
- #883 

related:
- #1409
