### ISSUE TITLE
Virtual Hosts File

### ISSUE THREAD

**Issue by fatbob1024** [celzero/rethink-app#1489]
Unusual case perhaps but would it be possible to add entries for a virtual hosts file to allow a user to add entries for servers running with self signed certs and no actual registered Domain. 

I'm sure there are other use cases like if there is a total global dns failure and you wish to still resolve some critical services.

**Comment by ignoramous** [comment]
> add entries for servers running with self signed certs 

Self-signed is a bit of a hassle, instead when adding a new DoH, ODoH, or DoT server, turn ON `Do not validate server TLS certificates`.

> you wish to still resolve some critical services.

Dup:
- #316 

(feel free to re-open this issue if #316 and "Do not validate..." does not cover the usecases mentioned here)
