### ISSUE TITLE
App keeps stopping 

### ISSUE THREAD

**Issue by michaelblyons** [celzero/rethink-app#1492]
This has been happening for a long time now. Maybe since 055a. Once or twice a day, the VPN icon goes away. The Rethink tile thinks it's still running, but I have to click once or twice to get it back on.

I don't think it's a RAM problem, unless it's a transient one. The phone doesn't seem to be memory-constrained. Rethink is not subject to battery throttling. I'm just puzzled. It is most likely to happen overnight when plugged in, but that's not the only occurrence.

I know you folks have been pushing versions right and left. I'm not quite up to date with 055m. (Currently 055l.) If you have any guesses, I'm all ears.

**Comment by ignoramous** [comment]
If it isn't the battery optimizer, it is likely the app is crashing.

We are aware of stability issues and have included Crashlytics (#1455) (much to our chagrin) to track those down as we've found that most are *not* able to figure out how to share crash logs (even the ones who take pains to open a GitHub account just report issues).

Even then, Crashlytics wouldn't capture crashes in our network engine (which is where we believe most of the crashes are). And so, eventually we are left with implementing our own crash reporter.

---

> I'm just puzzled. It is most likely to happen overnight when plugged in, but that's not the only occurrence.

If you can increase the logsize to 16m, and then immediately when you spot a crash, go to *About* (in Rethink) and email us the bug report.

```
# note the current size; the default is usually 256kb
adb logcat -g


# increase log buffer size to 16mb
adb logcat -G 16M


# see if it switched to 16mb
adb logcat -g


# now, at some later time, when the app crashes, capture logs
# make sure Rethink is at "Debug" in Configure -> Settings -> Log level


##### either do 1 or 2, 1 is preferred.

# 1. capture logs
# ref: https://www.xda-developers.com/how-to-take-logs-android/
adb logcat > /path/to/file
# compress with gzip
# the command below creates /path/to/file.gz
gzip -k /path/to/file 

# 2. Go to About, tap on bug report

# email mz at celzero dot com
# and mention this GitHub issue
```

**Comment by ignoramous** [comment]
The problem mentioned in #1539 can happen regardless of WireGuard/Firewall (may be it is rarer without it).

**Comment by michaelblyons** [comment]
Never mind. It still happens with just DNS. 😭

**Comment by ignoramous** [comment]
I'll close this issue as dup of #1539 then. Hopefully, the change we're making  in `v055o` to request Android to *not* perform address sanitization works.

Please follow #1539.
