### ISSUE TITLE
User feedback: Whitelists for Universal Firewall

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#15]
User's want a whitelist feature for universal firewall, that is, they want to exclude certain apps from it. A decent ask. Requires a UI change, probably, even moving the Universal Firewall to its own window, separate from the current lone "Firewall" window.

**Comment by ignoramous** [comment]
Instead of blocking all apps in the app `uid` range #65 may be apps that don't have a `category_launcher` should be spared and added by default to the whitelist, and probably all system apps to should be flagged so as to prompt users to add them to the whitelist?

**Comment by hussainmohd-a** [comment]
Introduced application whitelist for firewall. Applications which are added 
to whitelist will not be part of any firewall rules. 
Created new Dialog activity in UniversalFragment class, which will show the list
of applications to whitelist. 
By default, all the system components are added to whitelist.
