### ISSUE TITLE
V055m: bug can't stop or start the vpn

### ISSUE THREAD

**Issue by shifoc** [celzero/rethink-app#1501]
I think it happens sometimes when I click on the quick tile. https://github.com/celzero/rethink-app/assets/32818143/3a951403-25dd-4669-98cb-c889954b6f9f

**Comment by ignoramous** [comment]
Concerning. We'll take a look.

- Do you know how you entered this state?
- Did it happen just the once or keeps happening every now and then?
- Can you fetch us `adb logcat` after putting Rethink in `Very Verbose` mode in *Configure* -> *Settings* -> *Log Level*?

**Comment by shifoc** [comment]
It happened multiple times, mostly when I click on the quick tile.

I don't have access to a laptop for the next few weeks.

**Comment by hussainmohd-a** [comment]
Closing as the above mentioned commit will fix this issue. Feel free to reopen if you encounter the issue again.

**Comment by shifoc** [comment]
Hello, I still have the issuehttps://github.com/user-attachments/assets/912dc4a2-207c-44be-94be-ec6c2268f091
