### ISSUE TITLE
App "KDEConnect" cannot be allowed/bypassed

### ISSUE THREAD

**Issue by marscher** [celzero/rethink-app#1507]
App ["KDEConnect"](https://f-droid.org/en/packages/org.kde.kdeconnect_tp/) cannot be allowed/bypassed in Rethink.

Symptoms:
- No connection possible on a local and trusted (within KDEConnect) wifi.
- "Bypass Universal" + "Bypass app from all Proxies" does not make it possible to connect.
- "Bypass DNS & Firewall" + "Bypass app from all Proxies" does not make it possible to connect.
- Adding a "universal firewall" rule to allow (bypass) broadcast traffic to 255.255.255.255

Solution/Workaround:
pause or disable Rethink seamlessly works until re-activation of the firewall.

Desired:
Do not stop/pause the firewall to make local connections.

**Comment by ignoramous** [comment]
KDE Connect likely uses P2P/LAN? If so, try enabling:
- Either: *Configure* -> *Network* -> *Do not route Private IPs*.
- Or: *Configure* -> *Apps* -> (search for KDE Connect, tap on it) -> Choose `Exclude`.

**Comment by marscher** [comment]
Thanks, excluding private IPs did do the trick.

**Comment by alexanderadam** [comment]
I think that there should be some FOSS apps which should be on the exclude list by default or have at least some rules to have them working by default.

What do you think?

**Comment by alexanderadam** [comment]
> The ones who use apps like KDE Connect or Syncthing already know enough to look for and understand the workarounds, imo.

I didn't and I guess the others in this issue as well in #577 or #1159 did neither.


How about a middle ground where the first blocked request of a well-known FOSS app that's logged will cause a notification saying something like "_Hey, it looks like you're using $app and we blocked the request for you which will lead to some functions not working._" and then having two options "Allow request for $app" "Dismiss and don't ask again".
