### ISSUE TITLE
[Enhancement request] No way to filter/see partly-allowed/blocked apps

### ISSUE THREAD

**Issue by puelp** [celzero/rethink-app#1516]
I block all apps by default, and only allow Internet access to a select few apps.

If I allow an app access to both Wi-Fi and mobile data, it will show up under the [Allowed] filter, which is great.

But if I allow an app access only to Wi-Fi or only to mobile data, it doesn't show up under [Allowed]!

Please make it so that partly-allowed apps show up under [Allowed], or have a new filter section called [Partly allowed].

Thank you very much in advance.

**Comment by pandadeepimpact** [comment]
I agree that having a filter to see those that only allow Wi-Fi or Mobile Data would be useful, though not when they're mixed together. How about having a separate filter of "Allowed on Unmetered" (Wi-Fi) and "Allowed on Metered" (Mobile Data) instead?

**Comment by vovodroid** [comment]
Probably defining default mode (allow or block) and just showing changed apps first would be simple approach.

**Comment by ignoramous** [comment]
> - When apps are allowed to connect on the cellular (metered) network but not on wifi networks the GUI Home tab shows all apps are blocked.
> <details><summary>Suggest GUI be modified to show how many apps are allowed by network type?</summary>
> img0:
>
> ![Screenshot_20240621-131221_1](https://github.com/celzero/rethink-app/assets/35378689/11ae377f-fc19-4ac7-adb3-a85145176bd8)
> </details>
>
> - On the firewall's apps GUI itself there is no way to view a list of allowed apps if they are only allowed on the cellular (metered) network. The 'allowed' list only shows apps if they are allowed on both cellular and wifi networks.
> <details><summary>Suggest filters be added to show each apps blocked/allowed status by network type.</summary>
> img1:
>
> ![Screenshot_20240621-140114_1](https://github.com/celzero/rethink-app/assets/35378689/0091dbcb-8d3d-456f-bfc9-3150a4e8b94b)
> </details>

By @raven9nine from https://github.com/celzero/rethink-app/issues/1564#issue-2367107182
