### ISSUE TITLE
Copycat in Galaxy store

### ISSUE THREAD

**Issue by howlettwv** [celzero/rethink-app#1525]
<details><summary>screenshots:</summary>
image0:

![e38716f4-3603-4a3e-9d07-052130f3083b](https://github.com/celzero/rethink-app/assets/143527216/814b2b79-1ffd-4349-8bff-3be279473a6e)

image1:
![dc45f3e5-897a-4511-9375-ebc277b7a0ad](https://github.com/celzero/rethink-app/assets/143527216/3cd93b44-db8e-4ec2-bfaa-f6be5fa3dc3e)

image2:
![833c5355-f55b-43eb-8582-2428d0016584](https://github.com/celzero/rethink-app/assets/143527216/a973ac0c-d240-474e-adfc-1277fa692551)
</details>

There is a similar application on the Galaxy store with slight modification in the GUI.

The link is
https://apps.samsung.com/appquery/appDetail.as?appId=com.celzero.bravedns

**Comment by alaa9jo** [comment]
I was about to report the same issue, it started this morning with Samsung Store started to suggests updating the app with the one from their store and if its not working I should uninstall the one I have and install the one from Samsung store

**Comment by ignoramous** [comment]
We don't see a "report abuse" button on their Store. If you folks do, do report abuse.

I am not sure what else could be done with such squatters.

**Comment by alaa9jo** [comment]
Reported and now it's gone, hopefully for good, you can close the issue

**Comment by ignoramous** [comment]
Thank you 🙏
