### ISSUE TITLE
Typo in AdGuard DoT description 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1536]
![is-the-adguard-under-dot-of-rethink-use-cloudflares-dns-or-v0-j4iyvxdt836d1](https://github.com/celzero/rethink-app/assets/852289/93046d5d-1ed5-44bb-a0fe-afe4461f5b3f)

From: https://www.reddit.com/r/rethinkdns/comments/1de0c16/is_the_adguard_under_dot_of_rethink_use/

**Comment by hussainmohd-a** [comment]
Fix: https://github.com/celzero/rethink-app/pull/1581/commits/35e43fa9a85d65060f881e1c685ee86079d086e3
