### ISSUE TITLE
How add a new personal Dns blocklist

### ISSUE THREAD

**Issue by freeburn12** [celzero/rethink-app#1541]
How can we add or import a personal DNS blocklist in the application ? 

I don't find this option.
That's almost just what's missing in your excellent app

I sugger you to add this very good list who assembly a lot of other and block over 462 000 rules.

She is disponible in multiple format for Pc, Android,  in Format hosts 0.0.0.0,  hostname... :   `[](https://sebsauvage.net/wiki/doku.php?id=dns-blocklist-en)`

Thanks you for your interest in better protection

**Comment by ignoramous** [comment]
Thanks. This isn't trivial to build and it isn't priority, among other open bug reports and feature requests.

Please track at: 
- #237
