### ISSUE TITLE
Question:  Maybe Issue?  Is there a setting for inbound ip addresses on local network?

### ISSUE THREAD

**Issue by SteveTinkers** [celzero/rethink-app#1562]
I have a file manager that can host a webserver for transferring files on the local network, say http://192.168.1.1:1111.

I can access the file manager's webserver from a browser on my android device, but I cannot access the webserver from a browser running on my laptop (on the same network).

I've tried enabling wifi for my file manager, enabling and disabling universal: udp, source app unknown, dns bypassed, and port 80....   The only way I can get it to work is to EXCLUDE my file manager under app rules.

I didn't see any settings for inbound...anything.  What do I need to investigate to make it work?

Bonus question:
I'm a NetGuard convert and it looks Rethink can do everything NetGuard can do and more!
NetGuard used to warn about possible increased battery usage with extra logging and filtering... rethink is even more granular and offers more options.  Am I exposing my device to increased battery use?  Has anyone compared the battery use between the two apps?

**Comment by Lanius-collaris** [comment]
Configure -> Network -> Do not route Private IPs

Could you try turning it ON?

**Comment by SteveTinkers** [comment]
> Configure -> Network -> Do not route Private IPs
> 
> Could you try turning it ON?

Bingo! Thank you.  I thought it might have been something dumb and I forgot that the network section even exists and focused on the firewall!!   Thanks!!
