### ISSUE TITLE
Two Firewall GUI Issues

### ISSUE THREAD

**Issue by raven9nine** [celzero/rethink-app#1564]
1) When apps are allowed to connect on the cellular (metered) network but not on wifi networks the GUI Home tab shows all apps are blocked.
Suggest GUI be modified to show how many apps are allowed by network type?
![Screenshot_20240621-131221_1](https://github.com/celzero/rethink-app/assets/35378689/11ae377f-fc19-4ac7-adb3-a85145176bd8)

2) On the firewall's apps GUI itself there is no way to view a list of allowed apps if they are only allowed on the cellular (metered) network. The 'allowed' list only shows apps if they are allowed on both cellular and wifi networks.
Suggest filters be added to show each apps blocked/allowed status by network type.
![Screenshot_20240621-140114_1](https://github.com/celzero/rethink-app/assets/35378689/0091dbcb-8d3d-456f-bfc9-3150a4e8b94b)

**Comment by ignoramous** [comment]
dupe?
- #1516 

(noted; feel free to re-open incase #1516 isn't a duplicate)
