### ISSUE TITLE
Rethink displays itself as "Blocked" under firewall rules

### ISSUE THREAD

**Issue by FLAGEL** [celzero/rethink-app#1571]
In v055n, it seems that Rethink has categorized itself ("Rethink") under firewall rule "Blocked" (Navigate to "Configure" > "Apps" > Toggle "Blocked"). At the same time the subtitle says "allowed" and sometimes the left colour bar is green, while at other times it is red. The option to configure Unmetered, Metered, Isolate, etc (as with regular apps) is not available. DNS resolution and other functionality seems to be unaffected and works as intended.

Screenshot:
https://ibb.co/XbX7Ng9

**Comment by ignoramous** [comment]
Seems like a UI quirk. Thanks. Will fix.

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/pull/1581/commits/0ade1c79d4b61f639a698890071c15713ea7de27
