### ISSUE TITLE
Fails to download blocklists

### ISSUE THREAD

**Issue by JohnnyBrav0Sr** [celzero/rethink-app#1576]
Hi

I have downloaded the RethinkDNS Android app from Github. I'm running Android 14 on a Pixel 6a. 

I have configured the app to use Proton free VPN using the Wireguard VPN protocol. The VPN seems to be working well. However, when I try to download the DNS block lists, the app fails to download any block lists. 

It appears to be downloading blocklists, but it never achieves to do so. It just says 'downloading blocklists', but nothing happens.

Is this a bug, or have I missed an important step in the app configuration?

![Screenshot_20240627-120855](https://github.com/celzero/rethink-app/assets/167346664/1253b736-bc7e-42df-a117-719bdde59204)

**Comment by hussainmohd-a** [comment]
Does toggling the _'Use in-app downloader'_ setting help?

**Comment by JohnnyBrav0Sr** [comment]
Thank you, problem solved!
