### ISSUE TITLE
How to whitelist (or blacklist) domains?

### ISSUE THREAD

**Issue by JohnnyBrav0Sr** [celzero/rethink-app#1577]
Hi

Is there a way to whitelist (or blacklist) specific domains in this app? I have been looking for this, but I can't find it. Thanks!

I'm using local DNS blocklists with Wireguard VPN.

**Comment by hussainmohd-a** [comment]
Manage domain rules in the following ways:

**Firewall Settings:**

- Go to Firewall -> IP & Port Rules.
- Click on the Domain tab.
- Add domains to block or whitelist.

**Logs Screen:**

- Navigate to the Logs screen.
- Click on the specific connection.
- There is an option to block or whitelist the domain.

**Apps Screen:**

- Go to the Apps screen.
- Select an app.
- Click on Domain Rules.
- Add domains to block or whitelist.

**Comment by JohnnyBrav0Sr** [comment]
Wow, 3 ways to do so! Thank you!
