### ISSUE TITLE
Option to set "system" DNS as fallback

### ISSUE THREAD

**Issue by rmskhen** [celzero/rethink-app#1580]
Thanks for developing the app! It’s very useful and I keep it on all the time. One small suggestion:
- It’d be great to have the option to choose “system” DNS in **Settings > Network > Choose fallback DNS**.
- This would be helpful in situations where, for example, users don’t have a Wi-Fi connection, don’t have a cellular data plan, and are prevented by their carriers from connecting to any domain, including any DNS providers (Cloudflare, Google, and Rethink, etc.) other than the default provider that only resolves specific “whitelisted” domains, like domains for WhatsApp or Facebook Messenger (usually to let users use these services even when they don't have a cellular data plan).
- That way, users won't have to go to **Settings > DNS** and switch to "System DNS" every time these situations happen just to get DNS back up and get access to services like WhatsApp and Facebook Messenger, and then switch back to their preferred DNS again when they get back online.

**Comment by ignoramous** [comment]
> It’d be great to have the option to choose “system” DNS in Settings > Network > Choose fallback DNS.

*None* is *System DNS*. We should have worded it better.

> That way, users won't have to go to Settings > DNS and switch to "System DNS" every time these situations happen just to get DNS back up and get access to services like WhatsApp and Facebook Messenger, and then switch back to their preferred DNS again when they get back online.

That's not the purpose of *Fallback DNS*. It is used as bootstrap DNS, that is, to help Rethink connect to other DNSes. 

DNS maps IPs to a domain name. If the DNS server itself is a domain name (which is the case for DNS over HTTPS / DNS over TLS / Oblivious DNS over HTTPS endpoints), Rethink uses this *Fallback* to map them to IPs.

*Fallback* should really be reworded to *Bootstrap*.

What you're perhaps looking for is *Secondary* DNS? #1025

**Comment by mvevitsis** [comment]
Please add the ability to enter a custom bootstrap DNS (since rethink cannot work with private DNS on).

**Comment by ignoramous** [comment]
> Please add the ability to enter a custom bootstrap DNS (since rethink cannot work with private DNS on).

*Private DNS* has no bearing on whether Rethink can work or not, and also totally unrelated to fallback / bootstrap DNS upstream.
