### ISSUE TITLE
WireGuard advanced mode apps list shows applications that are not installed

### ISSUE THREAD

**Issue by LightWayUp** [celzero/rethink-app#1587]
In advanced mode of WireGuard configs, apps can be selected to be routed through VPN of a configuration. The apps list shows apps that aren't installed, such as Candy Crush Saga and Bixby Service.

The regression is from [commit `0446dfa` - update db in assets folder](https://github.com/celzero/rethink-app/commit/0446dfa115f0561050a992c6b7a15515bb159db2), affecting v0.5.5l and later versions. The `ProxyApplicationMapping` table should be empty, but contains records that seem to be exported from a real device.

**Comment by hussainmohd-a** [comment]
@LightWayUp Thank you, we will look into it. In the meantime, does the refresh button at the top of the app list in the proxy screen help?

**Comment by LightWayUp** [comment]
Apologies for the late reply. It does indeed refresh the app list and remove erroneous entries, thanks for the tip!
