### ISSUE TITLE
[Feature] Second backup mode

### ISSUE THREAD

**Issue by MichaelZ4714** [celzero/rethink-app#1594]
I would like to have a second backup mode. In this mode the settings of dns and global firewall and apps such as block, isolated, filter addresses and names etc. are included with a reference to app.id and not uid. This would allow to restore the important data when reinstalling custom rom or changing device.

**Comment by ignoramous** [comment]
The current backup/restore should already work across devices. Is that not the case when you tried?

- #757 

If so, can you put Rethink in *Verbose* mode from *Configure* -> *Settings* -> *Log level* and then restore the backup and email the resulting logs captured via `adb logcat` to `mz` at `celzero` dot `com`?

Currently, Rethink doesn't backup encrypted data like *Proxy* configurations.

- #1280

**Comment by MichaelZ4714** [comment]
Have many thanks for the info!
I did ask because in the dialog to create a backup or do a restore it says (I have german language set):
Funktioniert nicht über App-Versionen oder Geräte hinweg
(about: Doesn't work across app-versions oder devices)
I just made a short test and it looks good. Issue may be closed.

**Comment by ignoramous** [comment]
> funktioniert nicht über app-versionen oder geräte hinweg (probably in english: Doesn't work across app-versions or devices)

It says that because we aren't sure cross device restore will work in ALL cases.

> just made a short test and it looks good. Issue may be closed

Thanks for confirming. Closing...
