### ISSUE TITLE
Implement persistence for app after low memory kill

### ISSUE THREAD

**Issue by 8itlew7r** [celzero/rethink-app#1596]
Please implement a method to make Rethink app persist or restart automatically after it's been killed due to low memory conditions.

Currently, the app terminates completely when the system kills it to free up memory.

This is especially important for me because I can't manually restart the app on someone else phones conveniently. The solution needs to work automatically without user intervention.

**Comment by ignoramous** [comment]
> Please implement a method to make Rethink app persist or restart automatically after it's been killed due to low memory conditions.

On Android 10+, you can already do this by setting up Rethink as *Always-on VPN*.

1. Open Rethink.
2. Go to the *About* UI.
3. Scroll down and tap on *VPN Profile*.
4. Tap on the ℹ️ or ⚙️ icon next to Rethink's entry.
5. Select *Always-on VPN*
6. Optionally, enable *Block connections without VPN* (aka *VPN Lockdown* mode) right below it, to make sure no installed app can connect to the Internet when Rethink isn't running.

This method, supported by Android OS itself, will always be better than anything we can implement in-app: #95 

(closing this as dup of #95, feel free to reopen)
