### ISSUE TITLE
WireGuard: DNS leak with advanced configuration

### ISSUE THREAD

**Issue by OrkoGrayskull** [celzero/rethink-app#1597]
A WireGuard tunnel offers two options:
- Simple
- Advanced

If you use the "simple" configuration, each app is routed through the tunnel and the DNS server of the VPN provider is used. 

If you use the advanced configuration, you can select individual apps to be tunnelled through the VPN tunnel. In this case, however, the DNS server stored in RethinkDNS is used instead of the VPN provider's DNS server. Is this a bug or is it intentional? Is it also possible to use the DNS server of the VPN provider in the advanced configuration?

I use RethinkDNS version v0.5.5n.

**Comment by ignoramous** [comment]
> Is this a bug or is it intentional? 

Intentional. The small text label in WireGuard's *Advanced* configuration UI should go: *DNS is forwarded to `<some user-preferred DNS upstream>`...*.

> Is it also possible to use the DNS server of the VPN provider in the advanced configuration

Not currently, no.

- #1510

(closing this as dup of #1510, feel free to reopen)
