### ISSUE TITLE
Upload RethinkDNS to Accrescent?

### ISSUE THREAD

**Issue by Nairou** [celzero/rethink-app#1605]
(Disclaimer: I have no affiliation with Accrescent, I just support their cause.)

RethinkDNS is one of the few apps I installed from GitHub rather than an app store. And although it has an update notification, I only see that if I happen to open RethinkDNS for some reason.

Accrescent is a new open-source app store being developed, which I think shows a lot of promise. Would you consider uploading RethinkDNS there, as an alternative method of downloading the app and keeping it updated?

Info: https://accrescent.app
Dev console: https://dev.accrescent.app

**Comment by ignoramous** [comment]
Rethink does not meet some their requirements: https://accrescent.app/docs/guide/appendix/requirements.html

Doesn't look like we will ever publish this app to Accrescent. Sorry.

**Comment by ignoramous** [comment]
Rethink doesn't meet the guidelines below. Also: we do not have the necessary bandwidth to engage with their review process or make changes to comply with their guidelines.

> The [android:usesCleartextTraffic](https://developer.android.com/guide/topics/manifest/application-element%23usesCleartextTraffic) attribute in the Android manifest must not be "true". This check may move to manual review in the future.
>
> The MANAGE_EXTERNAL_STORAGE permission may only be requested for one or more of the following use cases:
> - file management, such as for a file manager app
>
> [android.accessibilityservice.AccessibilityService](https://archive.is/3sgct#androidaccessibilityserviceaccessibilityservice)
Accessibility services are highly invasive, presenting a security and privacy risk to users. As such, they are heavily restricted on Accrescent and may only be used to help users with disabilities interact with the device.
>
> [android.net.VpnService](https://archive.is/3sgct#androidnetvpnservice)
VPN services may only be used by apps that have a VPN as their core functionality.
