### ISSUE TITLE
Aditional app filter request

### ISSUE THREAD

**Issue by FireNinja7365** [celzero/rethink-app#1606]
Add a filter to hide apps that don't have the "have full network access" and related permissions, since apps without these permissions don't use the internet anyways

**Comment by ignoramous** [comment]
An app update can add those permissions back though, without the user even noticing.

**Comment by ignoramous** [comment]
More at #1612 (please track there).

Currently, we dim out entries of apps without the `INTERNET` permission (to make them stand out).
