### ISSUE TITLE
App is mega broken

### ISSUE THREAD

**Issue by A20N** [celzero/rethink-app#1611]
Hi,
Sorry can't really describe it any way else.
I receive dozens of network related app notifications hours later often not at all.

Excluding an app has no effect whatsoever.
Examples:
WhatsApp 
Tesla
Gmail
The list goes on ...

When I try to download the on device blocklist nothing happens, when exiting back to the home screen and disabling rethink, the my download manager explodes.
_rd.txt, _basicconfig.json, bla bla bla.

So yeah the app apparently blocks its own downloads??
Even after the downloads have finished, after turning it off of course, the app is not aware of the files and tries to download _again_ which also fails _again_.

What has happened to the app?

If used it for years and everything was fine up until the start of the year. Since then it has become unusable.

**Comment by ignoramous** [comment]
Please track at:

- #983 
- #952 
- #564 
- #593

Feel feel free to reopen if reported issue isn't covered by one of the above. Thanks
