### ISSUE TITLE
Bug, Wireguard app list shows nonexistent Samsung Apps

### ISSUE THREAD

**Issue by boredsquirrel** [celzero/rethink-app#1613]
I am on GrapheneOS where the only Samsung app is `com.samsung.slsi.telephony.oemril.OemRilApp`.

But the list when setting up per-app Wireguard filtering shows a bunch of Samsung apps that simply do not exist.

The other lists dont show these apps, just the "add apps to proxy" one in the setup.

Using the latest release of RethinkDNS.

**Comment by hussainmohd-a** [comment]
Fixed. Will be part of the next release v055o. Ref: https://github.com/celzero/rethink-app/issues/1587

As a work around, refresh button at the top of the app list in the proxy screen

**Comment by boredsquirrel** [comment]
awesome, thanks!
