### ISSUE TITLE
Bug: Orbot connection fail may lead to fallback to unproxied

### ISSUE THREAD

**Issue by boredsquirrel** [celzero/rethink-app#1614]
This is pretty critical. When using RethinkDNS with Orbot, the app starts but doesnt find a connection, RethinkDNS may fallback to using no proxy.

This is very dangerous. 

Used was the latest Release with GrapheneOS.

**Comment by hussainmohd-a** [comment]
@boredsquirrel, When configuring the Orbot proxy, does it fallback to none when Orbot hasn't established a connection?

If this happens, ensure that Orbot has an established connection in power user mode. In Rethink settings, select the apps that need to be forwarded via Orbot and choose either HTTP or TCP mode.

**Comment by ignoramous** [comment]
Thanks. Dup:

- #976

(feel free to reopen in case it isn't)
