### ISSUE TITLE
FR: allow to exclude apps from HTTP block

### ISSUE THREAD

**Issue by boredsquirrel** [celzero/rethink-app#1615]
Browsers can block HTTP themselves but allow opt-in with a warning.

This is way better UX than needing to manually allowlist a website.

Excluding the browser from the "universal" blocking didnt work.

**Comment by ignoramous** [comment]
> Excluding the browser from the "universal" blocking didnt work.

You mean *Bypass Universal* did not work (as in bypass the *block HTTP on port 80* universal firewall rule)? That's a bug.

If so, after the browser apps have been *Bypass Universal*: 
1. Does it not work ever (as in, the connection to port 80 remains blocked across app and device restarts, for example)?
2. Does it not work with other browser apps (you may have installed) or just the one you use as the default?

**Comment by boredsquirrel** [comment]
I used Mull and tried to open httpforever.com

I had the "block HTTP" as my only rule of that category. 

The "Bypass Universal" still didnt allow me to open the HTTP site, while turning the rule off entirely did.

**Comment by boredsquirrel** [comment]
strange, could not reproduce.

Previously, I think:
- used system DNS (assuming that was the one advertized by DHCP by the VPN server)
- had "block HTTP" as only firewall rule
- had 2 wiregurard VPNs, some apps bypass, some apps in one, the other apps in the other

Now I have the same but also use a local filterlist, while using Quad9 DNSCrypt. And cant reproduce currently.

**Comment by ignoramous** [comment]
Thanks. Seems like it was a one-off.

For next time, check *Network Log* entries for Mull (or any other app you suspect isn't working as expected) for why its connection don't worke (either firewalled or simply failed). When you tap on the entries shown in *Network Log*, a *bottomsheet* with more information about the connection should show up. For finished connections (connections not currently ongoing / active), the footer of the *bottomsheet* shows diagnostic messages (final status of the connections).
