### ISSUE TITLE
Blocked apps on LTE only dont appear in Allowed category

### ISSUE THREAD

**Issue by iulko** [celzero/rethink-app#1641]
If you "Allow" an app like Chrome, but only for Mobile or Wifi than it dissapears from "Allowed" category and only appear in "All" and "Blocked". 
I think if you "block" only one of Wifi/LTE than app should appear in both "Allowed" and "Blocked" so you can easy see it in both.

**Comment by ignoramous** [comment]
Believe it is a dup?

- #941
- #949

(closing... pls feel free to reopen if I am mistaken)
