### ISSUE TITLE
Making ReThink play well with local network apps like Syncthing/plex/local NAS/NextCloud while in VPN in lockdown mode

### ISSUE THREAD

**Issue by XingShelly** [celzero/rethink-app#1660]
When in VPN Lockdown mode, ReThink blocks all local network connections, and there's no way to turn them back on. ReThink is already bad at recording local network connections and allowing them, as most of them don't even show up. When in lockdown mode, these apps become useless. I do not know if this is possible to fix or not, but being able too let certain local connections through or having an option to let all local connections through even in VPN lockdown mode would make using rethink a lot more viable for a FOSS user.
I really enjoy this app, and it solves so many important issues in android that big Tech did not solve. I just just wanted to express my gratitude.

**Comment by ignoramous** [comment]
Not ideal but you could either "Exclude" these apps from Rethink (from *Configure* -> *Apps*) or turn ON *Do not route Private IPs* (from *Configure* -> *Network*).

To make P2P / LAN apps works, we need to make a bunch of changes, but unsure if we'll ever complete that work. See dups (closing this issue):
- #577 
- #1507
- #1562
- #1589 
- #1618 
- #1661
- etc.
