### ISSUE TITLE
UI: Bigger 'enable' button for WireGuard

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1665]
> Also, can you make the hit target of the enablebutton bigger? Because I mistakenly press it a lot and enter the information page instead.
>
> Can you just make it a certain percentage of the whole button from the right (Something around 15% of the whole button). I imagine there are a lot of people like me who keep accidentally entering the information instead, and I believe this could be a nice UX improvement.

_Originally posted by @XingShelly in https://github.com/celzero/rethink-app/issues/1662#issuecomment-2316408452_

**Comment by ignoramous** [comment]
> Could I add on adding a refresh button directly in the Wireguard menu? I'll make a new issue if not. Thank you.

**Comment by XingShelly** [comment]
It is still small. I am all, and I still accidentally enter the edit mode. Please make 20% of all of the right of the button pressable.
