### ISSUE TITLE
Can't access .onion sites when a TOR ProtonVPN Wireguard profile is used

### ISSUE THREAD

**Issue by turbamulta** [celzero/rethink-app#1668]
ProtonVPN has some servers that can be used to go through / to the TOR network. 

ProtonVPN Android app:
1) Connect to any TOR enabled server
2) Connect to any clearnet site. It loads. You have a TOR exit node ip.
3) Connect to a .onion site. It loads. 

RethinkDNS Android app
1) Generate a Wireguard profile of any TOR enabled ProtonVPN server
2) Load the profile in RethinkDNS and connect.
3) Connect to any clearnet site. It loads. You have a TOR exit node ip.
4) Connect to a .onion site. It doesn't load, can't connect.

**Comment by ignoramous** [comment]
Are you running WireGuard in *Simple* mode or *Advanced* mode? If the latter, see:
- #1510

**Comment by turbamulta** [comment]
Correct, I'm using advanced mode. 

I've read the thread, makes sense. I'll try again when you have that per-app DNS feature, sounds quite tough. 

I'm closing this issue since you already working on it. Thanks for the hard work you put on this.
