### ISSUE TITLE
Wireguard Uses Different DNS in Simple / Advanced mode

### ISSUE THREAD

**Issue by luckygitt** [celzero/rethink-app#1674]
If I set Wireguard in Simple mode the Rethink (home screen) shows as "Wireguard"
If I change Wireguard to Advanced mode, it shows my DNS as the selected one (in my case NextDNS).

Second conundrum: In Simple mode the Lockdown (found in advanced Tab) still works - is this correct? If yes, it should be in the Simple tab and not hidden in the Advanced tab.

**Comment by ignoramous** [comment]
The fact that *Advanced* mode WireGuard DNS *won't* be used is mentioned in the app. It is due to an Android limitation. Please track dup at:
- #1597
