### ISSUE TITLE
After doing a search in the app list, pressing on a certain app and going back, removes the searched list and takes you back to the main menu. Even though the search query is still written. results

### ISSUE THREAD

**Issue by XingShelly** [celzero/rethink-app#1676]
As per the title, when I do a search in the app list, and I list, press on it and try to go back to the searched apps list, the search results disappear and the app pretends that there is no search query even though the search query is still clearly written in the text box.

**Comment by ignoramous** [comment]
Annoying! I know...

Please track at:
- #1517 

(*closing... but feel free to reopen*)
