### ISSUE TITLE
Blocklist download stuck

### ISSUE THREAD

**Issue by imedjendoubi** [celzero/rethink-app#1680]
![Screenshot_2024_0902_113449.jpg](https://github.com/user-attachments/assets/f3692564-528e-4cb3-82cd-b80223a620f0)

**Comment by hussainmohd-a** [comment]
@imedjendoubi, Could you try toggling the 'Use in-app downloader' setting to see if that resolves the issue?

**Comment by imedjendoubi** [comment]
The button was the issue, it is showing "Downloading Blocklists" but it is not downloading

Clicking multiple times on the button, solved the issue.

Thank @hussainmohd-a
