### ISSUE TITLE
Please add rules.

### ISSUE THREAD

**Issue by biange200** [celzero/rethink-app#1681]
http://rssv.cn/adguard/

https://github.com/TG-Twilight/AWAvenue-Ads-Rule
    https://flowus.cn/share/f5b48261-8aed-49a2-bdd2-9b75b20f6ba9

https://ghproxy.net/https://raw.githubusercontent.com/qq5460168/666/master/dns.txt

**Comment by ignoramous** [comment]
Thanks. Please track: 
- https://github.com/serverless-dns/blocklists/issues/177
