### ISSUE TITLE
Make ReThink play well with work profiles

### ISSUE THREAD

**Issue by XingShelly** [celzero/rethink-app#1685]
I use rethink in both the main profile and in the work profile. The main one seems to work perfectly fine, no problem. But the work profile one keeps giving me grief all the time when connecting to wire guard proxies.
The connection keeps dropping or not connecting at all, both in simple and in advanced mode.

To give you an idea about my environment, I use both the work profile and the main profile in Lockdown mode.
I use GraphineOS which has much stronger separation between profiles. So this also could be part of the issue.  I encounter fewer issues in the work profile on other devices. I hope you would do some testing on GraphineOS.
I connect mostly to Proton VPN.

You probably need way more information than this to figure out the issues and if you want I can help but please fix this issue.

**Comment by ignoramous** [comment]
Dup:
- #150

**Comment by XingShelly** [comment]
> > Dup:
> > 
> > * [Android Work Profile and RethinkDNS #150](https://github.com/celzero/rethink-app/issues
> Just for reference, I have been running shelter on my Pixel 8 Pro since around January this year with the RethinkDNS app set up in both the main/admin/normal profile and then another instance of it in the shelter/work profile - both are running on the same NextDNS DoH server(with nametag to distinguish the requests on nextdns) but each have a separate Mullvad wireguard connection/endpoint/locale and I have had next to no issues with this setup, no dns leaks etc and I check using dnscheck.tools regularly also to be sure.
>

I don't have much issue as well when I use an external DNS provider. I am talking about using RethinkDNS on Rethink.
Because, at least to me, that is the main benefit of using Rethink. Otherwise, I would just use a VPN plus NextDNS, which is actually what I have reverted to doing right now as Rethink has become very much unreliable lately, and connections keep dropping, in addition to previous issues like not working in the work profile, not working with my university's Wi-Fi  etc.

Using an external DNS filter plus a VPN does come with its own problems. For example, I cannot set an app-specific rules, like Rethink. And when I switch to a whole other user, the rules of the admin user still apply, which causes a lot of conflict and issues.

I really wish they would make this work and and fix other critical issues in Rethink because right now it's unusable for me. I really wish I can use it. I desperately need something like that.
