### ISSUE TITLE
App not working anymore when connected to mobile network in private profile only, work profile still functional

### ISSUE THREAD

**Issue by roteiro** [celzero/rethink-app#1699]
Device: Fairphone 5
OS: IodéOS 5.4 Iodé is a LineageOS derivate)
RDNS-Version: v0.5.5n

I have a private profile and a work profile set up via Shelter, RDNS is installed in both profies. 

Until a few weeks ago, the RethinkDNS App (Firewall+DNS mode) was working without issues, both when connected via WiFi and via Mobile Network. 

Now, within the private profile, I'm not able to use the app anymore  when connected via Mobile Network, while it's still working without issues when connected via WiFi.  Pressing START results in "DNS error" 
There was no app update and I didn't change settings. Maybe there was an OS update, I'm not sure about this.  It's mabye similar to this issue: 
https://reddit.com/r/rethinkdns/comments/1c18xa2/rethink_cannot_use_mobile_data_when_wifi/

Neither STOPing & STARTing nor a reboot helps. I played around with the settings, but so far to no avail. It seems that RDNS is completely missing my mobile connection in the private profile. RDNS in work profile is still fully functional, even when on mobile data.

I tried to backup the settings in the work profile and restoring them in the private profile, but the issue persists. 
Sorry for the unspecific issue report, whats the best way to debug this? I can provide adb logcat data if needed.

**Comment by roteiro** [comment]
I fiddled around with the Android App settings (Delete Cache, Permissions etc), RDNS is fully functional again. Unfortunately, I cannot reproduce the described behaviour anymore, therefore closing the issue

**Comment by ignoramous** [comment]
Thanks for confirming that it might have been a one-off issue (which are harder to debug but of times, easier to fix, once it can be reproduced with some consistency).
