### ISSUE TITLE
Feature Request: automatically invalidate catchAllAppConfigCache periodically 

### ISSUE THREAD

**Issue by CodingManiacCyborg** [celzero/rethink-app#1706]
Given the goal of this project: "Rethink is not an anonymity tool: It helps users tackle unabated censorship and surveillance..." would it make sense to add a feature to periodically clear the catchAllAppConfigCache? The idea here would be to add a bunch of wg configs and have it randomly choose between them. Ideally it would clear after a certain period of inactivity. This would help with avoiding surveillance.

**Comment by ignoramous** [comment]
Makes sense.

v055o will pin a proxy (WireGuard, SOCKS5, HTTP) to a (uid,ip,port) tuple for 30s.
