### ISSUE TITLE
Block list misinterpretation results in overblocking

### ISSUE THREAD

**Issue by boernsen-development** [celzero/rethink-app#1713]
Reproduce:
- RethinkDNS 0.5.5n (fdroid)
- Android 14 (GrapheneOS)
- Enable blocklist: [EasyPrivacy](https://easylist-downloads.adblockplus.org/easyprivacy.txt)
- Open (just an example): www.wetteronline.de/wetterradar/berlin

Expected:
- Website loads, rain radar is shown
- Tried this with Mull + uBlock Origin + the EasyPrivacy block list from above imported into uBlock (while the same block list was disabled in RethinkDNS) and the website fully loads

Actual:
- Website doesn't load. In the log you can see several `*.wo-cloud.com` requests getting blocked.
- To confirm: This happens once I enable the EasyPrivacy block list in RethinkDNS and does not if it is deactivated (even when using the exact same block list in uBlock Origin)

Presumed reason:
The block list includes only one related entry:
- `||wo-cloud.com^$ping`

I assume the `ping` option of this entry is misinterpreted and incorrectly blocks the entire domain.

Workaround:
Trusting the individual domains sometimes helps, but sometimes doesn't. Sometimes the request appears in the log as `maybe blocked`, which I don't know the meaning of.

I'm not familiar with block list syntax, but the related ping type option is described here: https://help.adblockplus.org/hc/en-us/articles/360062733293-How-to-write-filters#type-options

Suggested change:
- Preferably correct block list's options interpretation (if at all possible, I'm not familiar with this)
- Alternatively remove domains with such options from blocking to avoid overblocking

Maybe someone with experience can add to this. I am very happy to answer any questions as I love the idea of RethinkDNS and would like to support it!

**Comment by ignoramous** [comment]
Thanks for the detailed bug report.

Rethink uses `adp` rules for just DNS-based content blocking. It doesn't yet implement HTTPS interception (like AdGuard does via either plugins or firewalls) to apply `abp` rules.

Also, the conversion of `abp` rules to domain rules is not fool-proof: https://github.com/serverless-dns/blocklists/issues/48

In short, we prefer using `domains`/`hosts` files not `abp`

**Comment by boernsen-development** [comment]
Thanks for your reply!

So, this is already in your pipeline :)
I didn't find the issue linked by you when researching prior to posting this. Sorry about that. I'm gonna close this issue as duplicate then.
