### ISSUE TITLE
UI: Bypassed filter option doesn't show apps bypassing proxies

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1714]
A user [says](https://www.reddit.com/r/rethinkdns/comments/1foh08j/apps_bypass_for_all_proxie_doesnt_show_in/)...

<details>
<summary>screenshots</summary>
img0:

![Screenshot-20240924-123524](https://github.com/user-attachments/assets/2f108957-9ac0-4cde-a3f9-d741f5eac852)

img1:
![Screenshot-20240924-123506](https://github.com/user-attachments/assets/e9ea6872-40ce-4b02-9c1a-45320d1c3470)
</details>

**Comment by NoPlagiarism** [comment]
Issue was closed, but [commit was added to hussainmohd-a fork](https://github.com/hussainmohd-a/rethink-app/commit/8d374f9fd9e3f037099e2866c813dfcb0f74fafd)

And was not merged into main, but issue is closed

Am I missing something here?

**Comment by hussainmohd-a** [comment]
Added in [v055o](https://github.com/celzero/rethink-app/pull/1581); this will be merged into the main branch during the release.

**Comment by NoPlagiarism** [comment]
Yep. sorry about this, didn't notice this PR
