### ISSUE TITLE
Randomly Select from my Wireguard Proxys

### ISSUE THREAD

**Issue by flushedface** [celzero/rethink-app#1716]
There is no funcionalty to randomly turn on a Wireguard proxy from the imported proxy list.

**Comment by ignoramous** [comment]
In *Advanced* mode, Rethink already load balances among multiple *Always-on* WireGuards. 
- #1477

As for *Simple* mode, see:
- #1683

(closing this as dup of the above 2 issues; if they don't address what you're requesting here, please feel free to reopen)
