### ISSUE TITLE
Can't download or update local/remote rethink dns blocklist

### ISSUE THREAD

**Issue by Tyxiel** [celzero/rethink-app#1721]
Already tried all possible rethink config, but none seem to work. It worked in the past but now it isn't.

**Comment by hussainmohd-a** [comment]
@Tyxiel , Could you try toggling the 'Use in-app downloader' setting to see if that resolves the issue?

**Comment by Tyxiel** [comment]
<details><summary>Didn't work, i already try using mobile data as well</summary>

![Screenshot_20240929-064414](https://github.com/user-attachments/assets/06e1d943-2252-41da-8a9f-2fbabf0487ee)
</details>

Version: 0.5.5n

**Comment by hussainmohd-a** [comment]
> Didn't work, i already try using mobile data aswell ![Screenshot_20240929-064414](https://private-user-images.githubusercontent.com/128870773/371843229-06e1d943-2252-41da-8a9f-2fbabf0487ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MTUzNTQsIm5iZiI6MTcyNzYxNTA1NCwicGF0aCI6Ii8xMjg4NzA3NzMvMzcxODQzMjI5LTA2ZTFkOTQzLTIyNTItNDFkYS04YTlmLTJmYmFiZjA0ODdlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMzA0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmJiN2I5Mzg0MDljZDMyN2EwOTk1NDU4MmVlMzZhNTE4YjkzZTgxMjg5YTVmYjE2ZWExNmE4MGI5MmNjNDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PCcSNAm14w65kH8gd20ZFZHiE4DM210PLr-udA63rq8)
> 
> Version: 0.5.5n

Looking into it.

**Comment by Tyxiel** [comment]
If that helps, it downloads 4 files then fails:
"_td.txt"
"_rd.txt"
"_filetag.json"
"basicconfig.json"

**Comment by ignoramous** [comment]
If you get the time, can you folks confirm if the new blocklist (`2024/1727819766546`) update works? Thanks.

**Comment by LovingNumbers** [comment]
worked for me :^)

**Comment by piotr-kiszka** [comment]
Working now, thanks :+1:

**Comment by Tyxiel** [comment]
It is working, thank you.

Closing the issue as it is solved, thanks you guys for your help!

**Comment by mooglestiltzkin** [comment]
https://www.reddit.com/r/rethinkdns/comments/1fs1mmk/comment/lpvhisi/

not working for me when trying to update the blocklist.

using latest 0.5.5n downloaded from this github. using with a samsung s24 ultra running one ui 8.0
