### ISSUE TITLE
HTTP Proxy on Android 6+

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1734]
A user says,

> I've installed the app in a mobile phone and it works fine but when I use it on an android tv the "Proxy HTTP" feature is not visible.
>
> Why? Same network and same app version (0.5.5n).

The "new" http proxy implementation should work on Android 6+ (while the previous implementation only worked on Android 8+).

**Comment by hussainmohd-a** [comment]
Fix: [6a6b0305](https://github.com/celzero/rethink-app/pull/1581/commits/6a6b03059a891938b44df56367e8038049347cc7)
