### ISSUE TITLE
[Feature request] Logs for settings

### ISSUE THREAD

**Issue by pawlosck** [celzero/rethink-app#1738]
Could you add screen with info, what user changed. For example:
Date/Time: Screen XXX, Setting: YYY, Previous: ZZZ, Current: AAA
2024.10.09, 20:00:00: Screen DNS log, Setting: domain example.com Previous: no rules, Current: blocked

Generally, I am blocking everything, except apps I am using, so sometimes I block too much. The biggest problem is with notification (push). Sometimes, result appear after few days, so I don't remember, what I changed.
Theoretically, screens "network logs" and DNS should solve any problem, but it doesn't work. For example, log show me, that everything should work, but some app don't show me notification, or can't connect to Internet.

**Comment by ignoramous** [comment]
Thanks.

Has been suggested before:
- #1452 

(closing as dup)
