### ISSUE TITLE
Blocked DNS queries do not reveal the blocklists anymore

### ISSUE THREAD

**Issue by tlartaud** [celzero/rethink-app#1749]
Hello there,

I am running the android app v0.5.5e.
Since this version (released on april 2024), which introduced Wireguard compatibility that I activated, I am not able anymore to see the blocklists which blocked a specific DNS request.

Prior to that version, I was able to check which blocklist blcoked a specific DNS query by clicking the DNS tab, then clicking a blocked DNS query, then clicking the "blocked" tag on the top right corner:
Prior to that version, a popup was opening, and I was able to know which specific bocklist blocked that query, which was super useful.

From v0.5.5e, this feature seems to have been removed, and it is now a real pain to manage the blocklists (almost impossible).

Do you plan to reintroduce this feature?

---

Also, as I can see from this Git repository, there are new versions available, but they do not seem to be available from the play store. What is going on? Should we expect to receive updates from the play store? I am personally stuck at v0.5.5e without any update from months.

Anyway, thank you for this wonderful app!

Regards.

**Comment by ignoramous** [comment]
Please track at:

- https://github.com/celzero/rethink-app/issues/1702

> Also, as I can see from this Git repository, there are new versions available, but they do not seem to be available from the play store. What is going on? 

```
After v055b, we hit numerous bugs (and unbelievably difficult ones) in our WireGuard integration. Released v055c and subsequent versions to fix the most annoying bugs among them.

We paused Play Store builds at v055e because each new version since has had its own glaringly annoying bugs (that were of course fixed in the subsequent versions). Why? Play Store brings in the most number of Rethink users (per our estimate), and we decided to halt publishing there until we can figure out how to stablize Rethink's feature-set affected by WireGuard.

Pausing roll-out like this is a one-off.

Typically, you can expect all flavours (GitHub / Website / Play Store & F-Droid) to be at the same version.

If you're feeling particularly adventurous: You can temporairly seamlessly update (without having to reinstall) to the GitHub / Website version if you're currently using Rethink installed from the Play Store. And then later, when Play Store catches up, update from Play Store again.
```

From: https://www.reddit.com/r/rethinkdns/comments/1f7ydjo/git_vs_fdroid_google_play_app_version/ / https://archive.md/dviiZ
