### ISSUE TITLE
Variety of questions regarding Rethink's functions

### ISSUE THREAD

**Issue by DomainUser0** [celzero/rethink-app#1756]
### Discussed in https://github.com/celzero/rethink-app/discussions/1752

<div type='discussions-op-text'>

<sup>Originally posted by **DomainUser0** October 26, 2024</sup>
Hello, I have a few questions regarding some functions and interactions Rethink may have. If some these have been referenced before I apologize. I have sifted through many discussions but have found it difficult to get a seamless answer.  It may do well to have these all accumulated in one thread and answered by those qualified, that can base their answer on various factors.

DNS:

Does 'DNS booster' wipe cache when toggled off, then back on?

When 'Never proxy DNS' is enabled, do DNS requests get sent to the underlying DNS server? ie: Your ISP, if you have a wireguard connection active, with DNS being proxied through that?

Is 'Block when DNS is bypassed' redundant with 'Prevent DNS leaks' enabled? Would enabling this prevent DNS being bypassed by user apps?

Firewall:

Is 'Block when DNS is bypassed' necessary for consistently routing through DNS set through Rethink? ie: Syncthing will have thousands of requests blocked for bypassing DNS, per the relay function (via TCP on port 22067). Are these requests connecting directly to IP, with DNS not in use at all, if not, are these requests be sent with the underlying DNS of your ISP if the firewall rule isn't set?

Proxy:

ICMP traffic isn't routed, is this Rethink specific or do all android VPN services function this way? What traffic isn't routed that would be encompassed in a standalone wireguard app?

Network:

What services or apps are affected by 'Loopback proxy forwarder apps'?

Why is 'Loopback' dependent on 'Use all available networks'? will it be directed through Wi-Fi by default? Under what circumstances will it route via cellular? (as they are both now active)

If 'Choose fallback DNS' is not set, will the packet be dropped or will it route through a DNS set outside of Rethink? ie: ISP default
</div>

**Comment by ignoramous** [comment]
Answered in the discussion thread. Sorry it took long.
