### ISSUE TITLE
Network logs screen stuck midway

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#176]
See screenshot. This is happening only since v053.

Some users reported that they inadvertently click on the universal firewall toggles when swiping the screen as an unintended side effect.

![IMG_20201221_124820_490](https://user-images.githubusercontent.com/852289/102749979-fb900680-438a-11eb-9be5-e795905d2b0b.jpg)

**Comment by hussainmohd-a** [comment]
The view pager has now migrated from viewPager2 to viewPager1 which solved this issue. 
(commit https://github.com/celzero/rethink-app/commit/7798087)
There is a known issue in viewpager2 (https://github.com/material-components/material-components-android/issues/500) is the 
reason we migrated from viewpager2 to viewpager which solved this issue
