### ISSUE TITLE
v055j: Combined apps

### ISSUE THREAD

**Issue by Kamika242** [celzero/rethink-app#1761]
I have Firefox and Firefox-Beta installed, I would like to tunnel Firefox-Beta through Orbot and Firefox should regularly connect to the internet. When I'm trying to select Firefox-Beta for Orbot, a popup tell's me that the connection would be valid for both Firefoxes, it's not possible to choose only one of them, why?

Before questions are coming up, I use v055j on my tablet and v055a on my phone, in both scenarios the follow-up versions of Rethink have to much bugs. I don't think that this problem doesn't exist anymore in later versions.

**Comment by ignoramous** [comment]
> Firefox-Beta for Orbot, a popup tell's me that the connection would be valid for both Firefoxes, it's not possible to choose only one of them, why?

Both apps share the same signing keys and *uid*, which means, except for 2 "apks" that can be installed/uninstalled separately, the app is one & the same.

There's nothing Rethink can do to fix this, unfortunately. You could try other Firefox builds (debug?), perhaps?

**Comment by Kamika242** [comment]
Ah, what a pity! I need plugin-capable browsers and there aren't a lot for Android. Used Mull (Firefox based) from F-Droid for a long time now, but it has a security gab and no updates to fix it, same with Fennec (also Firefox based) and Kiwi-Browser (Chrome based). Chrome itself I don't want to use, because its pure Google spyware.

**Comment by ignoramous** [comment]
I'll close this issue as Rethink is helpless. It cannot distinguish Firefox from Firefox (Beta) as long they share the same *uid* (which they don't have to!).

> Chrome itself I don't want to use, because its pure Google spyware.

In case you aren't aware (unlikely), you might want to give Vandaium a try. They base off of Chromium (?) (which is afaik is a de-Googled Chrome distribution made by Google themselves) and have had content blocking support built-in for a long while now: https://github.com/GrapheneOS/Vanadium/issues/10

**Comment by Kamika242** [comment]
Thanks a lot! I heard that Vanadium Browser is only for GrapheneOS and I don't have GrapheneOS.
I have to live with it and will tunnel both Firefoxes through Orbot, it's necessary only on one device, fortunately.
