### ISSUE TITLE
Unable to restore .rbk files

### ISSUE THREAD

**Issue by antoinepirlot** [celzero/rethink-app#1762]
Hello, I encounter an issue with backup.

I backed up data from my phone (Pixel 7 Android 15) as rbk file and would like to restore it on my tablet (Galaxy S8 Android 14) but the rbk file can't be selected by the document selector.

I use the version v0.5.5n on both devices

**Comment by ignoramous** [comment]
Grant permissions to Rethink to access media? You can go to "About" -> "App info" (in Rethink) and check if it has all requisite permissions.
