### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by Ypot** [celzero/rethink-app#1781]
Hi

I see no updates lately. Just in case, I would like to let you know that you're doing a great work. I have been using 0.5.5n and I love the privacy it brings, of course some thing could be better, but it works and it was not easy to have all that functionality. 

THANKS!

**Comment by ignoramous** [comment]
Why thank you.

v055o will arrive soon-ish. It has been ready for a few months now but we always keep hitting some weird edge case or the other. It will also have #946, testing which is another thing that delays the release.

  

You can track the work we do on the app on the dev branches:
- https://github.com/hussmohd-a/rethink-app
- https://github.com/celzero/firestack/tree/n2
