### ISSUE TITLE
More DNSCrypt Relays and UX change

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#181]
Move anonymous relay selection into a modal dialog (similar to the one used in v053 for _Exclude apps from DNS and Firewall_) via a button next to the drop-down at the top of the _Configure_ tab of the _DNS_ page.

Add at least one relay per country, if not multiple cities in the same country.

List: https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/relays.md

See also: #157

**Comment by hussainmohd-a** [comment]
In contrast to the previous user interface, the separation of DNSCrypt and relays into two different screens now makes it simpler for users to add the resolvers and relays of their choice. Now, user has five predefined resolvers and relays.
