### ISSUE TITLE
Plain App dont work with Rethink Firewall

### ISSUE THREAD

**Issue by mauserk98grenaderifle** [celzero/rethink-app#1816]
Plain App works with Rethink DNS but I cant configure it with Firewall. PlainApp uses http://192.168.1.2:8080 to access files from phone to web browser. It works well without the Firewall. I have also difficulty in adding this app to firewall.  im using v.0.5.5N

**Comment by ignoramous** [comment]
> PlainApp uses http://192.168.1.2:8080/ to access files

Currently, Rethink doesn't work well for LAN connections. Many prev requests such as:
- #1618 
- #1704 
- #1725 
- etc.

(closing as dup of those; feel free to reopen if I am mistaken about your usecase)

You can choose to:

- Either: "Exclude" *Plain App* from Rethink (from *Configure* -> *Apps* -> search for "Plain App" -> tap on it and in the screen that shows up, select "Exclude").
- Or: Turn ON *Configure* -> *Network* -> *Do not route Private IPs*.

For both those options to work, you'd have to make sure that the VPN (Rethink) is NOT in *Lockdown mode* (aka *Block connections without VPN* mode).
