### ISSUE TITLE
Rotating Proxies

### ISSUE THREAD

**Issue by harvest316** [celzero/rethink-app#1828]
# Request
We already have the facility to add multiple wireguard proxies, but I'd like to extend this facility to allow more than one of these to be selected, and Rethink cycles through these proxies automatically.

# Method
Methods for cycling through proxies could be any/all of:
- assigning each new session to a new proxy
- assigning each new app to a new proxy
- changing proxies for all apps every X minutes

# Benefit
This lowers the risk of being identified by the VPN provider, thereby reducing the need to trust one single VPN provider.

**Comment by ignoramous** [comment]
This isn't going to be any more private than using a single VPN. In fact, it is less private as the browsing data is now distributed across multiple providers.

Regardless, `v055o`, the upcoming version implements this sort of *load balancing* across all active *Always-on* (Advanced) WireGuards:

- #1477 

For Simple mode WireGuard, please track:

- #1683
