### ISSUE TITLE
Move dangling ui strings from code to strings.xml

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#195]
Need to do move those strings anyway for i18n.

Too many strings code-rotting right now.

**Comment by hussainmohd-a** [comment]
dda0f9958a6bd9cc4de57d69b5e478ea0ec47287, 2a3dec70e153facb60f8f5e6818db48bb87d2e93, ff2b39409cf29bc7be72dce62748d87de451cc89.
