### ISSUE TITLE
Set accessibility service description

### ISSUE THREAD

**Issue by Ch4t4r** [celzero/rethink-app#196]
Google started banning devs for using the `AccessbilityService` for other uses than accessibility in 2017. It quickly changed that stance, but now requires devs to set a proper description in the manifest, as well as reasonably disclose the usage of it to the user before he grants the permission: https://www.androidpolice.com/2017/12/07/google-pauses-accessibility-app-ban-considers-responsible-innovative-uses-accessibility-services/. Some internet sources claim you should also mention this in the play store description, I couldn't find anything official though.

As far as I can see RethinkDNS does not yet have this description in the manifest; I did not check for the disclosure.

**Comment by ignoramous** [comment]
Nice catch. 

We do show users a dialog when they enable "Block any app not in use" Firewall setting informing why accessibility permissions are required.

Re: description: is this what Google looks for?

https://github.com/celzero/rethink-app/blob/9a29879d49952583cf5085a262905f7b8e2ea77c/app/src/main/res/values/strings.xml#L26

**Comment by Ch4t4r** [comment]
Most likely, although in the end noone knows what Google really wants.

**Comment by hussainmohd-a** [comment]
Description added as mentioned above.
