### ISSUE TITLE
Guava and failureaccess dependencies

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#198]
The library for the guava android and the failureaccess are loaded from the libs folder. Need to remove from the libs.

**Comment by hussainmohd-a** [comment]
Maybe take a look at the link [Duplicate class issue](https://stackoverflow.com/questions/56639529/duplicate-class-com-google-common-util-concurrent-listenablefuture-found-in-modu)

**Comment by ignoramous** [comment]
These have been moved to be fetched from `maven` now. #210
