### ISSUE TITLE
Traffic allowed from a blocked app

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#199]
For a system app, albeit a very aggressive one, traffic was allowed even though the app was on the deny list. There were no crashes subsequently or before this happened, and only seemed to have happened in case of this one app. 

The user confirmed that the connections from the app did go through because they saw notification related to the app, so this wasn't a case of UI incorrectly logging a blocked-request; the request was indeed allowed.

Run through the code to see why and when can this happen.

This has been reported twice by the same user.

**Comment by ignoramous** [comment]
Likely when the firewall sees any `Exception` at all, it errs on the side of allowing traffic:

https://github.com/celzero/rethink-app/blob/aee7df7703ca42310f08671c04851ac1206fa410/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L148-L283

May be it should err on the side of disallowing traffic?

**Comment by hussainmohd-a** [comment]
Returning the blocked as true for all the block call from GO with exceptions.
The apps which are hit in exceptions will have the response sent as blocked(true)
after a delayed amount of time.
