### ISSUE TITLE
Remove the AppMode global

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#200]
Per Daniel,

- `VpnController` has a static field `braveVpnService`. This is not an important fix because it is set to null with `stop()`. If the service is killed by the system it is pulled from memory entirely, so no reason to do cleanup.
- `HomeScreenActivity` leaks `AppMode`, which references Context and multiple DAOs. It is used extensively across the app. It is fixable, but I'm not sure whether I'd mess up the logic behind it.
- `GoVpnAdapter` has a non-static `AsyncTask`. It potentially leaks `Context` through this as it is an inner-class. It also is fixable, but requires refactor (also, IntelliSense doesn't work in this class for me).

https://github.com/celzero/rethink-app/pull/188#issuecomment-751393885

**Comment by hussainmohd-a** [comment]
Remove some of the inconsistent methods from the Persistentstate. 
eg., - modifyAllowedWifi(), getConnectedDNS()

**Comment by ignoramous** [comment]
https://github.com/celzero/rethink-app/pull/282/files#r645294634

**Comment by ignoramous** [comment]
1. `VpnController` is likely to remain as-is, as it is extensively used throughout the code-base and doesn't seem critical.
2. `AppMode` is still a global, but it kind of acts like a `DatabaseManager` at this point, though not quite. In a limbo.
3. GoVpnAdapter's use of `AsyncTask` has been replaced with Kotlin Coroutines. #240
