### ISSUE TITLE
Block any app not in use issues part xvii

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#202]
In production builds of v053, _Block any app not in use_ feature is hilariously broken.

1. It doesn't work as intended from get to.
2. Sometimes it enters this endless loop or grant/re-grant permissions after a crash. Additionally, clicking on "deny" in the permission dialog during a permission re-grant still toggle enables the functionality in the app, when it shouldn't (like in the permission grant ui flow).

Do not block apps when accessibility service isn't even running... if nothing, that check need to go in, pronto.

**Comment by hussainmohd-a** [comment]
_Block any app not in use_ various fixes are added as part of v053b and v53c. 
Analyzing code if there are any improvements required in this.

**Comment by ignoramous** [comment]
Some more improvements went-in as part of #228 

Some issues may remain in which case a *new* bug (rather than this one) would be opened to track those.
