### ISSUE TITLE
"Check for Update" issues

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#207]
clicking on "update" in v052 (app downloaded from the PlayStore) did nothing (didn't take the user to PlayStore). And after that, started showing the "download from website" dialog, incorrectly (this dialog should never be shown on an app downloaded from the PlayStore).

and despite clicking on "Remind me later" button on that dialog, it showed up multiple times when navigating the homescreen.

**Comment by hussainmohd-a** [comment]
aff0b1d6b3dbdda71e66dcef29b67ed5f31122e9
