### ISSUE TITLE
DNS Settings keeps on resetting

### ISSUE THREAD

**Issue by w4tadrag** [celzero/rethink-app#209]
I installed the app yesterday on my Pixel 4a 5g and have been using the RethinkDNS Plus with some filters turned on. Since yesterday my configuration changed to Rethink DNS basic twice already and I lost all my previous configuration. I am not sure why it does this, but it gets annoying to renable the filters I previously had. Could you please fix the issue? Thanks

**Comment by ignoramous** [comment]
Hi there, a few users reported this to us during our alpha tests as well but weren't able to reproduce this at all and so we did try to make some fixes by _shooting in the dark_, as it were. See #170 

1. Can you please confirm you're using v053? Check the footer of the app's about page in case you're not sure.
2. If so, did you upgrade from v052 / earlier version, or was this a fresh install?

Thanks.

**Comment by w4tadrag** [comment]
1. I am using v 0.5.3
2. Downloaded the version that was in the play store yesterday for the first time, so maybe the latest version.

**Comment by ignoramous** [comment]
We have not been able to reproduce the issue you've reported with a fresh `v053` install on a _vanilla_ Android. Can you please fetch logs from your device and send them to `mz at celzero dot com`, if you're comfortable doing so?

If Pixel supports taking bugreports on-device, you do so from `Settings` -> `System` -> `Advanced` -> `Developer Options` -> `Bug Report`.

Or, on all phones, if you've already setup the android-debug-bridge, then `adb bugreport` would work too.

Also, can you please confirm if you're using the stock ROM? Thanks.

**Comment by ignoramous** [comment]
Dup: #170 

Also: Likely fixed too as a result of refactor that was undertaken with #282
