### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by woodholly** [celzero/rethink-app#210]
Make app more popular by adding visible link to github and emphasize it at the top of www.bravedns.com page.
Without this link www.bravedns.com looks like commercial closed-source project.

**Comment by woodholly** [comment]
2) Add this project to F-Droid (catalogue of open-source android applications)

**Comment by ignoramous** [comment]
Re F-Droid: the apps uses a bit of Google closed source APIs that F-Droid won't accept, so until we work around that (create a separate build for F-Droid excluding closed source code), this can't happen.

Re: Website: good point. We probably need to redesign the current pages, I've been told by a few others too that it doesn't really _inspire_ trust.

Thanks for your inputs. Appreciate it.

**Comment by Ch4t4r** [comment]
Regarding F-Droid: https://github.com/celzero/rethink-app/pull/212

**Comment by Ch4t4r** [comment]
When the necessary changes have been made:
 - Create an issue here: https://gitlab.com/fdroid/rfp/-/issues
   - An example for a complex config file: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/chat.rocket.android.yml#L136 (the highlighted line would be the build type F-Droid would create, 'fdroidRelease' most likely in this case)

**Comment by michaelblyons** [comment]
If this app becomes available on F-Droid, I would try it out. Currently using [DNS66](https://github.com/julian-klode/dns66) which does pi-holing, but not DoT/DoH.

**Comment by ignoramous** [comment]
Only if building for F-Droid wasn't such a pain for polyglot apps, this would already be a reality...a man can dream. Currently, F Droid builds are blocked by:

1. #215 
2. A server with crazy amount of RAM, CPU, and disk. 

Of course, outside contributions to have F Droid builds is always welcome. Save that, one can build debug builds by cloning the source into Android Studio.

**Comment by michaelblyons** [comment]
1. Thanks for the #215 link.
2. What's the server for? I thought F-Droid does the builds on their infrastructure.

> Only if building for F-Droid wasn't such a pain for polyglot apps, &hellip;

Heavy +1 to that.

**Comment by ignoramous** [comment]
> 2. What's the server for? I thought F-Droid does the builds on their infrastructure.

Not sure, never tried after glancing at this ominous article: https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by michaelblyons** [comment]
That article is indeed ominous, but looking through the referenced [`CONTRIBUTING.md`](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md), I think it's a one-time thing to create the "recipe," after which you can clean up the resources.

Doing it in a VM just makes the cleanup easier. I suppose one might want to keep the VM around to debug build failures in future versions (if you ever have any), but I'm sure you can keep the VM in cold storage.

I haven't verified this myself, but that's my read of the walkthrough.

**Comment by howtologinquickwiththirtyninecharacters** [comment]
@michaelblyons while you wait for Rethink on F-Droid, if you want pi-holing and DoH, [personalDNSfilter](https://f-droid.org/en/packages/dnsfilter.android/) can do both (it's on F-Droid).

**Comment by ignoramous** [comment]
IzzyDroid builds: https://gitlab.com/fdroid/rfp/-/issues/1552

**Comment by afonari** [comment]
> @michaelblyons while you wait for Rethink on F-Droid, if you want pi-holing and DoH, [personalDNSfilter](https://f-droid.org/en/packages/dnsfilter.android/) can do both (it's on F-Droid).

Sorry for the ofttop. I was using personalDNSfilter, it is pretty good and light. However it lacks firewall option (blocking apps from the internet connectivity), this is the main reason I'm trying now rethinkdns.

**Comment by ignoramous** [comment]
Okay, we don't need to muck with git submodules. Publishing a hard-fork of the `outline-go-tun2socks` firewall/doh network-engine dubbed [`firestack`](https://github.com/celzero/firestack/tree/1947dac1888e) to [`jitpack.io`](https://jitpack.io/#celzero/firestack/1947dac188) now.

**Comment by ignoramous** [comment]
Next step, upstream RethinkDNS's build "metadata" to F-Droid ([ref](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.tailscale.ipn.yml)).

**Comment by ignoramous** [comment]
App submitted for review: [fdroid/data/merge-requests/8559](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8559/diffs)

**Comment by ignoramous** [comment]
@woodholly The website has been re-designed (by @amithm7). The resolver website (for-profit but FOSS) is at [rethinkdns.com](https://rethinkdns.com/) and the app's website (F[L]OSS) is at: [rethinkfirewall.com](https://rethinkfirewall.com/).

F-Droid RFP (request for packaging) has been merged yesterday: [gitlab/fdroid/fdroiddata/merge-request/8605](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8605) It may take up to 5 days to show up though: [gitlab/fdroid/wiki/FAQ#how-long](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client)

**Comment by ignoramous** [comment]
Many thanks to @Ch4t4r as well. They put wind in the sails of this initiative! :pray: And @hussainmohd-a who did bulk of remaining work.

**Comment by ignoramous** [comment]
@michaelblyons this is for you! (:

**Comment by ignoramous** [comment]
[Live on F-Droid](https://f-droid.org/packages/com.celzero.bravedns).
