### ISSUE TITLE
If PlayServices are missing or install-source isn't PlayStore, use NonStoreUpdater

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#214]
I guess we need to check for presence of Play Services too (which, if absent, would skip update-checks and show an error toast on Play flavoured builds): 

https://github.com/googlesamples/google-services/blob/7cbe0486697a/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MainActivity.java#L103-L117

_Originally posted by @ignoramous in https://github.com/celzero/rethink-app/pull/212#discussion_r550801837_

**Comment by Ch4t4r** [comment]
The title and body currently have conflicting information. Should it fall back to the NonStoreUpdater or show the error?

**Comment by ignoramous** [comment]
Yikes. Good catch. Falling back to non store updater is strictly better than erroring out :)

**Comment by ignoramous** [comment]
Ref:

https://github.com/googlesamples/google-services/blob/7cbe0486697a/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MainActivity.java#L103-L117

**Comment by ignoramous** [comment]
Daniel implemented this for us in one of his commits.
