### ISSUE TITLE
Move outline-go-tun2socks to a git submodule

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#215]
> > ```
> > 2. Move `outline-go-tun2socks` in as a `git submodule`.
> > ```
> 
> Would having a monorepo (subfolder/module for tun2socks) also be fine for you? That would be simpler and we could just depend on it using pure gradle (and wouldn't have to init/pull the submodule all the time).
> I'm not sure whether Android projects can have non-Android modules though.

We are going to include WireGuard in this project at some point, too: Prefer that it comes in as a git-module. I am mostly basing it off of on how Orchid handles external but critical (security sensitive) cross langauge deps: https://github.com/OrchidTechnologies/orchid/blob/master/.gitmodules

I take, your concern is that gradle process won't be straight-forward? That is, Android Studio build integration would be convoluted more than necessary?

_Originally posted by @ignoramous in https://github.com/celzero/rethink-app/issues/212#issuecomment-753441429_

**Comment by michaelblyons** [comment]
You guys are going to add WireGuard? 🤩

**Comment by ignoramous** [comment]
`git submodules` plan is defunct because a couple of folks scared me from using it.

Instead, the [go-dependencies](https://github.com/celzero/firestack) for RethinkDNS are built from source and published as an Android Archive (`firestack.aar`) to [`jitpack.io`](https://jitpack.io/#celzero/firestack).
