### ISSUE TITLE
Resuming Always-on VPN

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#221]
RethinkDNS doesn't start when it is in fact "Always-on VPN" but instead shows a pop-up that "Always-on VPN" is enabled.

Apparently, according to one user, this isn't the behaviour they see with other android VPN apps, and that those are able to start stop just fine in this case. "Tracker control can't start when I toggle start button but when I restart TrackerControl it automatically started."

Investigate.

**Comment by ignoramous** [comment]
1. Start Always-on VPN for RethinkDNS.
2. Force Stop RethinkDNS.
3. Open RethinkDNS.
4. Notice it doesn't connect.

**Comment by hussainmohd-a** [comment]
f3f97a2745cc118a14776259a702f11999c9ebda
