### ISSUE TITLE
Track VPN mode changes

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#225]
From a quick glance at AOSP code, it looks like we can fully expect [`ConnectivityManager.NetworkCallback#onCapabilitiesChange`](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onCapabilitiesChanged(android.net.Network,%20android.net.NetworkCapabilities)) to trigger whenever the VPN goes in and out of the `lockdown` ("Block connections without VPN") mode.

Check for [`VpnService#isLockdownEnabled`](https://developer.android.com/reference/android/net/VpnService#isLockdownEnabled()) then when the callback triggers and rebuild the VPN as required (enabling *exclude-apps* and allowing *VPN bypass* when VPN **not** locked down, for example).

See: #178, #39, #224

**Comment by ignoramous** [comment]
So, it looks like neither `onCapabilitiesChanged` nor `onLinkPropertiesChanged` can be relied upon to be called when VPN switches to `lockdown` mode.

**Comment by ignoramous** [comment]
Or, wait, may be we were doing it incorrectly, ref: [com.android.cts.vpnfirewall.ReflectorVpnService](https://cs.android.com/android/platform/superproject/+/master:cts/apps/VpnApp/src/com/android/cts/vpnfirewall/ReflectorVpnService.java;l=117-132;drc=master).

```
        final NetworkRequest request = new NetworkRequest.Builder()
            .addTransportType(NetworkCapabilities.TRANSPORT_VPN)
            .removeCapability(NetworkCapabilities.NET_CAPABILITY_NOT_VPN)
            .removeCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
            .build();
        mNetworkCallback = new ConnectivityManager.NetworkCallback() {
                @Override
                public void onAvailable(final Network net) {
                    final Intent intent = new Intent(ACTION_VPN_IS_UP);
                    intent.setPackage(DEVICE_AND_PROFILE_OWNER_PACKAGE);
                    intent.putExtra(EXTRA_ALWAYS_ON, isAlwaysOn());
                    intent.putExtra(EXTRA_LOCKDOWN, isLockdownEnabled());
                    sendBroadcast(intent);
                    ensureNetworkCallbackUnregistered();
                }
            };
```

**Comment by ignoramous** [comment]
The above callback works only when "Always-on VPN" is toggled but not for "Block connections without VPN".

One approach to consider now is, to check [`VpnService#isLockdownEnabled`](https://developer.android.com/reference/android/net/VpnService#isLockdownEnabled()) atmost once every 30s on every firewall decision in [`BraveVpnService#block`](https://github.com/celzero/rethink-app/blob/1bb47828e08791ff76d7d4d223864a22447ff03f/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L132).

**Comment by hussainmohd-a** [comment]
As of now, work around is introduced to check for the lockdown mode. Callbacks for the "Block Connection without VPN" is not
available. Need to figure out a better way to track the lockdown mode. 
Closing this issue. New issue #257

**Comment by ignoramous** [comment]
So, `BraveVPNService#checkLockdown` is called on every `protect.Blocker.block` call which happens once per connection / flow.

https://github.com/celzero/rethink-app/commit/0a18f65b8869c74a84daff08cca550838706c2d8
