### ISSUE TITLE
Split Tunnel for Proxies

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#229]
Outgoing SOCKS5 and WireGuard conns can be split tunneled. That is not every app has to be tunneled through WireGuard and/or SOCKS5.

This would mean another list in addition to the existing allowlist (exclude app from firewall), denylist (block all conns from app), and exclude-list (exclude app from VPN).

Requires implementation in both Golang and Kotlin layers.

See also #52 #51

**Comment by ignoramous** [comment]
From user feedback

```
btw network logging page and DNS resolution page are very useful to write custom V2Ray routing configs
```

So, each TCP/UDP connection could be split-tunneled.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
nice2have routes like:
TCP => SOCKS5
UDP => WireGuard 

 App that bans VPN/proxy, Whitelist directly connectivity.

**Comment by ignoramous** [comment]
Go / network engine changes (yet to be thoroughly tested): https://github.com/celzero/firestack/commit/456491ac0ac884481f5bc14431fdfcc0f0aaec9c

**Comment by ignoramous** [comment]
Per-app split-tunnel (this bug) for proxies is fully implemented in `v055` ([released yesterday](https://github.com/celzero/rethink-app/releases/tag/v0.5.5)).

Split-tunneling based on protocols (ex: TCP to Tor + UDP to WireGuard), is possible but there's no UI for it. Also, providing settings like these is likely to confuse users more, so we need to think a bit about how to best make a UI for it.
