### ISSUE TITLE
 Webview soft crash

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#238]
To reproduce:

1. Go to DNS Configure page, click on Configure against RethinkDNS Plus
2. Set a couple of blocklists. and press Done.
3. Observe the soft crash (see below) from the logs.

```
02-17 15:44:07.485  9202  9202 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
02-17 15:44:07.493   911   911 E BufferQueueConsumer: disconnect by : /system/bin/surfaceflinger my_pid = 911
02-17 15:44:07.496  9202  9202 E chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (29792) crash detected (code -1).
02-17 15:44:07.496  9202 18188 E GoLog   : [ERROR:aw_browser_terminator.cc(125)] Renderer process (29792) crash detected (code -1).
```

**Comment by hussainmohd-a** [comment]
[Reference](https://stackoverflow.com/questions/51971241/webview-crashing-my-app-with-validation-error-deserialization-failed)

**Comment by ignoramous** [comment]
webview has been removed from configuring rethinkdns+ in #380 

release? `v053i`.
