### ISSUE TITLE
Light mode doesn't show "send fail" icon in DNS logs

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#247]
![WhatsApp Image 2021-03-19 at 10 20 37 AM](https://user-images.githubusercontent.com/852289/111785097-2df5c500-88e2-11eb-98c8-d24f26efb874.jpeg)
![WhatsApp Image 2021-03-19 at 10 29 10 AM(1)](https://user-images.githubusercontent.com/852289/111785108-2fbf8880-88e2-11eb-9102-a135b60a4f62.jpeg)
![WhatsApp Image 2021-03-19 at 10 29 10 AM](https://user-images.githubusercontent.com/852289/111785112-30581f00-88e2-11eb-9fc7-d278dae6ae4e.jpeg)

**Comment by hussainmohd-a** [comment]
Fixed - 74ebc5847be42d08db0ba3eb32daa98be8985347
