### ISSUE TITLE
Redirect to other important Android Settings

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#249]
1. To RethinkDNS' own "App Info" page.
2. To Android's VPN Setting's page for RethinkDNS.
3. To Notification Settings page for RethinkDNS.

May be these can be accommodated in the current `Settings` page under `General`?

**Comment by hussainmohd-a** [comment]
The App Info, VPN settings and notifcation settings page redirect is added as part of 584c334443601557391817ba1f1cba9f0027a872. 
As of now, the above is added in About screen under "System" section.
