### ISSUE TITLE
Improvements on blocklist(local & remote)

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#256]
Now the local blocklist is using the download manager to download 
and the workers are monitoring the download status. 

Need to do this for 
1) Remote blocklist
2) Apk download.

**Comment by ignoramous** [comment]
Download Manager is in production with  v053c release, but a lot of users have reported unable to download the lists at all. 

Possibly related: https://github.com/AdguardTeam/AdguardForAndroid/issues/3355

**Comment by ignoramous** [comment]
#314 will add a custom downloader. Built-in download-manager works nicely on most devices, but not all.
