### ISSUE TITLE
Eager fetch favico

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#271]
Fetch favico at the time when a DNS transaction is recorded and never after. Ref: https://github.com/bumptech/glide/issues/2523

https://github.com/bumptech/glide/blob/e86fd41e16/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrSearchActivity.java#L313

Do not just-in-time fetch favico from remote when scrolling through the list-view as done today; but instead fetch it from the [cache-only](https://bumptech.github.io/glide/doc/caching.html#loading-only-from-cache).

#105

**Comment by hussainmohd-a** [comment]
https://github.com/celzero/rethink-app/commit/06e76747ed48d1924ed137f57ab1c6e1d2f0e477

**Comment by ignoramous** [comment]
Fixed.
