### ISSUE TITLE
Stop/Start should work in Always-on VPN mode too

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#275]
This shouldn't be a restriction.

May be allow users to stop it with a dialog box ("vpn settings", "dismiss", "stop app") asking them to confirm their intention when "Always-on VPN" is enabled.

For when the VPN is in the lockdown mode, also warn users that they'd lose all internet connectivity, but still let them disable it.

**Comment by ignoramous** [comment]
Also, when the VPN is always-on, we should let user stop it, with a pop-up

"Always-on VPN is enabled. Are you sure you want to stop RethinkDNS anyway?"

If the VPN is in lockdown mode:

"RethinkDNS is running VPN in _lockdown_ mode. Stopping it would result in loss of Internet connectivity on this user profile. Do you want to continue anyway?"

button3: Settings (should open VPN settings)

button2: Cancel

button1: Stop

**Comment by hussainmohd-a** [comment]
[Reference]( https://github.com/celzero/rethink-app/commit/10512e06e6059fa88b439844370d0b97700217bf#diff-be99af92b41cf0b259ec2cda1adaaf2dfb085db2b604cdf2b7926d5c77ad73ab)

**Comment by ignoramous** [comment]
Works.
