### ISSUE TITLE
Notification bar action-button options

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#276]
Some users have reported annoyance at the "STOP" button shown with the notification. #104 

They'd like to remove it. So, what we could do is, let users control what button is shown to them:

1. STOP 
2. PAUSE / RESUME (this need to be implemented) #204 
3. DNS / DNS + FIREWALL (modes)
4. NONE

**Comment by hussainmohd-a** [comment]
Introduced the action button STOP, DNS / DNS + Firewall, NONE. [Commit](https://github.com/celzero/rethink-app/pull/282/commits/de2171c0407ac4922a4f7e2e0d00211e8fd26454)
Implementation pending for #204.

**Comment by ignoramous** [comment]
Implemented in #282 1, 3, and 4. 2 is tracked by #204 of course.

release imminent.
