### ISSUE TITLE
integrate an option to unblock blocked queries.

### ISSUE THREAD

**Issue by chris-tian78** [celzero/rethink-app#279]
At the moment you have no possibility to manually unblock individual queries blocked by filter lists. This is problematic because you have to whitelist the entire app every time. Please change.

**Comment by ignoramous** [comment]
This is coming in the upcoming release, planned for May 1st week, but might be delayed given the pandemic rearing its ugly head.

**Comment by ignoramous** [comment]
Releasing in a day or two or three.

<details>
<summary>screenshot</summary>
block or allow domains:

![Screenshot_2023-03-04-14-40-19-12_c8cbde12d3521911922be4eee6a05664-01](https://user-images.githubusercontent.com/852289/222929545-0f8c623b-e2d6-47ae-91d9-e595b7ef0a5f.jpeg)
</details>
