### ISSUE TITLE
Block app not in use blocks connections of apps in Whitelists?

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#281]
At least one user has reported that in `v053e`, when *Block any app not in use* is enabled, the whitelisted apps (Signal and WhatsApp, specifically) stop receiving connections when the device is locked.

Nothing in the network logs, either. This problem goes away when the user disables *Block any app not in use* setting.

Strange.

**Comment by ignoramous** [comment]
We have improved _Block any app not in use_ behaviour. Let's see if this report comes back.

**Comment by error-reporting** [comment]
@ignoramous in v055t also when Block any app not in use is enabled, the whitelisted apps (Invizible pro specifically) stop receiving connections when the whitelisted app is in background
