### ISSUE TITLE
Network Log Map, and HTTP Proxy

### ISSUE THREAD

**Issue by abakasam** [celzero/rethink-app#283]
Got DNS and Firewall...

1. Map of Network Log
2. List for HTTP proxies without SSL possible

Sam

**Comment by ignoramous** [comment]
I didn't quite get your feature request. Can you please elaborate further?

**Comment by abakasam** [comment]
1. A threat map

Using: 
![Screenshot_20210515-103958](https://user-images.githubusercontent.com/58202540/118369681-edc16480-b569-11eb-9382-e38f7c63df91.jpg)

Create: https://threatmap.checkpoint.com/

Then add as: 
![Screenshot_20210515-104049__01](https://user-images.githubusercontent.com/58202540/118369722-1a757c00-b56a-11eb-92df-1078bc48f598.jpg)

To: 
![Screenshot_20210515-104049__01](https://user-images.githubusercontent.com/58202540/118369739-23664d80-b56a-11eb-8f4f-7e4c50ff2ae3.jpg)

2. Like proxify...

As: 
![Screenshot_20210515-104241__01](https://user-images.githubusercontent.com/58202540/118369804-72ac7e00-b56a-11eb-9ed3-3ec32bf940fd.jpg)

Sam

**Comment by ignoramous** [comment]
Gotcha. Will keep in mind. See also: #54

**Comment by abakasam** [comment]
https://sayfer.io/blog/how-to-set-up-a-proxy-in-android-using-mitm-proxydroid/

**Comment by abakasam** [comment]
https://github.com/abakasam/redns
