### ISSUE TITLE
Move to a better place

### ISSUE THREAD

**Issue by soheilkhanalipur** [celzero/rethink-app#286]
Unfortunately, I have to say that you have put this program in a bad place! GitHub!
This app deserves places like: Codeberg, Gitea, GitLab (Instances), and wherever better…
GitHub boycotts users, removes apps, and actually says "Whatever I want is going to be saved and whatever I don't need Is going to be deleted." The app has not paid attention to users' requests for RTL support for years, and says this is not a priority!
Free software should be free somewhere, which GitHub does not have!
Aren't these enough to leave GitHub?

**Comment by ignoramous** [comment]
Yes, they are. Unless we start making money, we cannot switch to using our own instances to host software.

You make valid points. Codeberg and Gitea look enticing. Right now, tooling for some of the (`golang` and `JavaScript`) packages _require_ GitHub or _GitLab_, but that can be overhauled. Let's see.
