### ISSUE TITLE
Naming conventions as per Android's style. 

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#290]
Android's style is to not capitalize abbrv, go through the files and modify those changes. 

Example.,
VPN -> Vpn
XML -> Xml
HTTP -> Http
... and so on

**Comment by ignoramous** [comment]
https://developer.android.com/kotlin/style-guide

**Comment by ignoramous** [comment]
Styling has been applied for the entire code-base in a yet-to-be-merged review. As for renames, that will have to happen over time.
