### ISSUE TITLE
Ordering of application names - Alphabetical

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#292]
The ordering of the application names now takes precedence of Capital letters followed by alphabetical order. 
Make the ordering as Alphabetical order.

**Comment by hussainmohd-a** [comment]
Reference - ![WhatsApp Image 2021-05-17 at 12 52 11 AM](https://user-images.githubusercontent.com/56958445/118717541-d2917600-b843-11eb-9720-e7233aed31f3.jpeg)

**Comment by hussainmohd-a** [comment]
[Ref](https://stackoverflow.com/questions/2413427/how-to-use-sql-order-by-statement-to-sort-results-case-insensitive)

**Comment by ignoramous** [comment]
Implemented with refactor in #282
