### ISSUE TITLE
[Enhancement] Option to add host filter

### ISSUE THREAD

**Issue by leogbar** [celzero/rethink-app#299]
First of all, this is a great app.

Second, can be good include a option to add host filters, own filters o another's filters. Thanks for your work!

Leonardo

**Comment by ignoramous** [comment]
Thanks for your kind words.

Yes, this is planned but isn't likely to ship until September given other high priority items in the backlog. :)

**Comment by ignoramous** [comment]
@leogbar see also: `blocklists` bundled with the app are open to community input here: https://github.com/serverless-dns/blocklists.

**Comment by ignoramous** [comment]
Dup: #293
