### ISSUE TITLE
ConnTrack

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#3]
Track and log an app's incoming and outgoing connections, show consolidated reports to the user.

ConnTrack for DNS UDP would be a heuristic:
1. Track DNS queries and answers.
2. See if any app within the next 400ms or so makes a connection to an IP answered by DNS.
3. If so, it is _likely_ (not certainly) that app sent the DNS request in the first place.

Need a new alerts screen? This is likely going involve adding a new screen and so, see also: [Refactor the current Firewall screen to rid of two different app lists and possibly merge them into one single list](https://github.com/celzero/brave-android-app/issues/4).

**Comment by hussainmohd-a** [comment]
Connection Tracking:
* Introduced new screen to track all the app connections.
* isBlock method invocation from tunnel2socks will have the details of the connections. Those connections are added to the connection tracking screen.
* Conn Tracking Screen will have the details of the app, timestamp, IP, port, type of connection, and flag.
* Pending - -DNS UDP connection to an IP address.

**Comment by ignoramous** [comment]
ConnTrack (not backed by a database yet) has been impl in #354

**Comment by ignoramous** [comment]
See also how Orbot translates IPv4 to IPv6 using clever DNS and packet rewrite tricks: #310
