### ISSUE TITLE
Remove isScreenOff from PersistentState

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#304]
isScreenOff doesn't need to be persisted. It should be an in-memory state, because whenever the app recovers from a crash (or is restarted), it doesn't need to know if screen is off, it only needs to know if a connection should be blocked, if so, what is the set user preference (which needs to be persisted) and what is the current device state. The current device state should be set once when the vpn restarts, and again whenever the receivers trigger. Use IPC like Messenger or IntentService to communicate state.

**Comment by ignoramous** [comment]
The implementation has changed drastically in a yet-to-be-merged pull-request, making this tech-debt obsolete.
