### ISSUE TITLE
[Bug] Mobile Networks keep restarting in a fast iteration.

### ISSUE THREAD

**Issue by amithm7** [celzero/rethink-app#307]
<table>
<tr>
	<td>Device
	<td>Mi A1
<tr>
	<td>Android Version
	<td>9
<tr>
	<td>App Version
	<td>v053c, v053d, v053f
</table>

After leaving rethinkDNS ON for 12-24 hours or unlocking the phone after sometime (not sure which one),
_Mobile networks keep restarting in fast iteration_ (i.e. cross icon appears on mobile tower signal icons - usually indicates no internet).

This also bloats the RAM, as a consequence, phone slows down.

Likely introduced in v053c (See e210771d8d6cc14ad0b0962d420ef03628a35cef)

Have tested that this doesn't appear in prior version (v053b).

Network restarts iteration intensity had slowed (observed visually), after removing a particular app (spotify, which appeared to be crashing in logs). Phone stills slows down (have to restart phone after stopping rethinkDNS, to regain proper functionality).

**Comment by ignoramous** [comment]
Your diagnosis was correct. We removed report-network-connectivity calls to test and it works as expected (that is, network restarts do not happen as they did before the fix). A yet-to-be-merged pull-request has the fix which is due a merge in upcoming days...

See also #277
