### ISSUE TITLE
Custom downloader

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#314]
Right now, Android's download manager is used to download on-device blocklists.

A *lot* of users have reported that it simply doesn't work and endlessly keeping spinning without any progress. Some root-causes as to why this happens is known:

1. The DownloadManager is firewalled.
2. UDP connections are blocked.
3. VPN is in "lockdown mode" (that is, "Block connections without VPN" from Android VPN Settings is enabled).

That said, there are likely other issues, either with RethinkDNS' use of download manager APIs or with custom ROMs or with de-googled devices or with download manager implementation itself.

And so, we must consider if a custom downloader is apt in this case with the download manager acting as a fallback. One glaring change from the current user-experience would be the custom downloader must happen in a foreground service, with a modal UI on top, right, and center of the app.

**Comment by mbjd05** [comment]
Hello, does anyone have a status update on this?

**Comment by modestderp** [comment]
I would like to know if there are any updates to this as well.
