### ISSUE TITLE
HTTP proxy(orbot) is not an http Proxy

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [celzero/rethink-app#317]
> Then, I activated Orbot integration inside your app. Rethink said all traffic is now routed over Tor.
> 
> The problem is all other apps! can connect to internet, not just Browser if HTTP proxy is enabled (orbot activated) Firewall is completely unusable.
> 
> When I disable orbot link, rethink block app's internet connection as advertised.
> 
> conclusion: if the HTTP proxy(orbot) is active, your app is ignoring firewall rules silently

#313 @strongok 
Couldn't answer on parent issue. Image says more than thousand words.

![059b5c04-895f-4782-a1d8-d984c8d7dbca.jpg](https://user-images.githubusercontent.com/46166740/122639469-587e3680-d0fa-11eb-906e-1f2d1e569e05.jpg)

**Comment by ignoramous** [comment]
Yes, we merely set it #44, and Android implements the rest (which is a HTTP `CONNECT` tunnel instead of a HTTP proxy).

http/1.1 proxies are trivial to implement; it is the http/2 that is problematic here.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
>  it is http/2 that is problematic here: https://github.com/celzero/rethink-app/issues/45#issuecomment-695347020

That may not work for any pinned certificates anyway. But it's not needed, The http tunnel port works fine for https and as https proxy. As far I know, Https over http proxy uses http connect.

> http/1.1 proxies are trivial to implement;

Previously orbot shipped with polipo http proxy with socks5 as it's parent proxy.

This option causes likely all apps including system Chrome Browser to access http:
![IMG_20210624_170430.jpg](https://user-images.githubusercontent.com/46166740/123287263-e7ca8600-d50e-11eb-801d-99ae030a3a90.jpg)

While TCP forward mode works as expected.
![IMG_20210624_170430.jpg](https://user-images.githubusercontent.com/46166740/123287517-10528000-d50f-11eb-91c7-1b20ca4a685e.jpg)

The combinations or use as http proxy works for everything than http itself. 
![6b2ae5c6-37db-4701-ba75-6d7b72e9923c.jpg](https://user-images.githubusercontent.com/46166740/123287543-15173400-d50f-11eb-9e1e-c2c1003149ed.jpg)

**Comment by ignoramous** [comment]
https://github.com/elazarl/goproxy to rescue. Attempting an impl...

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> https://github.com/elazarl/goproxy to rescue. Attempting an impl...

Good choice. I checked out https://github.com/elazarl/goproxy as HTTP/S=>SOCKS5 Upstream standalone, and it works quite well for this purpose.

**Comment by ignoramous** [comment]
> I guess since `7734c45` this issue could be closed?

We haven't integrated it in the app... (:

**Comment by ignoramous** [comment]
In [`v055`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5), we implement just the HTTP/S CONNECT tunnel and not HTTP/S Proxy per se. Please test it out and let us know if it works as intended; feel free to reopen if it doesn't. Thanks (:
