### ISSUE TITLE
please, add min_sdk 21 (android 5.0) support

### ISSUE THREAD

**Issue by DI555** [celzero/rethink-app#318]
please, add min_sdk 21 (android 5.0) support !
we have a huge amount of devices with this os ..
or, if not possible, then at least support min_sdk 22 (android 5.1) ..
many thanks in advance !!!

**Comment by ignoramous** [comment]
I think the `androidx` open source library that we use supports `6`+ only. Targetting `5` is going to be very hard to do. @hussainmohd-a ?

**Comment by DI555** [comment]
according to my info , there in library should be support for minimal sdk 21 , so i hope for it !!!

**Comment by DI555** [comment]
or, may be, just min_sdk22 (android5.1) there support now exist only.. this should be great in RT either!!!

**Comment by ignoramous** [comment]
It is unlikely we ever support Android 5. We tried but quite simply too many `androidx` (core libs) simply don't work on Android 5 as-is and need a bunch of re-organzing existing code-base. Given Android 6+ is close to 95% of all Androids ([ref](https://www.androidpolice.com/googles-latest-android-version-distribution-numbers-show-11-in-dead-heat-with-10/)), there's simply too much work to be done for the remaining 3% or so on Android 5 / 5.1 :(

That said, we're open to merging pull requests from anyone else willing to spend time on migrating Rethink to Android 5.
