### ISSUE TITLE
Rewrite of GoVpnAdapter - v055

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#321]
GoVpnAdpater requires a re-write which will be part of v055. 
eg., As of now the app fallback on an unmaintained url.

**Comment by hussainmohd-a** [comment]
"STOP + Failing" or should the app flip to "START + Not protected"?? Line: 521

**Comment by ignoramous** [comment]
Ref: https://github.com/celzero/rethink-app/pull/282/files/2e87fcfe40433e846d8eb25a309c9d694a4f7911..ff1eb73d3d248914bc282618637af8076c819197#r645636367

**Comment by ignoramous** [comment]
> "STOP + Failing" or should the app flip to "START + Not protected"?? Line: 521

Implemented in #282 in `BraveVpnService#handleAdapterChange`, but it shows `failing` for now when a `tunnel` couldn't be established. Re: showing other states (possibly, `offline`): #294

**Comment by ignoramous** [comment]
Most of the rewrite is well and truly done.
