### ISSUE TITLE
Usage of isDarkThemeOn in code. 

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#324]
When the app’s theme changes (either through the system setting or AppCompat) it triggers a `uiMode` configuration change. This means that Activities will be automatically recreated. This happens for the activities alone. For the fragments we are using the Utilities. Still these can be improvised more with `configChanges` property.

**Comment by ignoramous** [comment]
a very specific limited-scope tech debt, likely will be addressed over a period of time.
