### ISSUE TITLE
Vpn allowBypass conundrum 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#33]
For a VPN masking as a firewall, it is suicidal to let apps bypass it: [BraveVPNService.kt#L178](https://github.com/celzero/brave-android-app/blob/master/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L178).

- May be provide an "Advanced Setting" to let users to not allow bypass?
- May be never allow bypass when the device is locked and the universal firewall rule is set?
- May be never allow bypass at all at the risk of breaking web-rtc apps?

**Comment by ignoramous** [comment]
The part that's left to implement: If  `Allow Bypass` has been enabled, prompt user and disable when the VPN is put in "lockdown mode" (that is, `Block connection without VPN` is enabled).

**Comment by hussainmohd-a** [comment]
when the Block connections without VPN is enabled in VPN settings, then  Allow-bypass in Settings Fragmentwill be disabled and the allow-bypass will be set to false regardless of the settings in the SettingsFragment while creating the VPN Builder. The description text will be modified in the settings screen.
