### ISSUE TITLE
Auto enable after user-defined minutes 

### ISSUE THREAD

**Issue by mxte** [celzero/rethink-app#338]
Create an option at Settings/General after pressing the stop button on the notification auto enable it after user-defined minutes.

**Comment by ignoramous** [comment]
[Android no longer lets apps start a foreground service arbitrarily](https://developer.android.com/about/versions/12/foreground-services), even if through [JobScheduler/WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager). I guess, we could implement a *dummy* VPN that stops all the filtering, and resume it back again after a set time. That'd be similar to what we want to do for #204

**Comment by mxte** [comment]
Yes, this is it.
