### ISSUE TITLE
Icons for Settings 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#346]
On-device blocklists: https://iconduck.com/icons/89978/list-status (Apache)
Favicon: https://iconduck.com/icons/84323/diamond (MIT)
Exclude: https://iconduck.com/icons/117863/logout-exit (MIT)
Bypass: https://iconduck.com/icons/7224/circle-two-line (Apache)
SOCKS5: https://iconduck.com/icons/58302/git-network-sharp (MIT)
HttpProxy: https://iconduck.com/icons/57061/spinner-alt (Apache)
MultiNetwork: https://iconduck.com/icons/9531/network-3 (Apache)
Logs: https://iconduck.com/icons/58726/pulse-sharp (MIT)
Theme: https://iconduck.com/icons/9336/image (Apache)
Update: https://iconduck.com/icons/29775/system-update-alt (Apache)
Notification: https://iconduck.com/icons/69983/notification (MIT)
AutoStart: https://iconduck.com/icons/75175/rocket-launch (MIT)
KillApp: https://iconduck.com/icons/9014/clean (MIT)
Tor: https://iconduck.com/emojis/42933/onion (CC by SA)
AppInfo: https://iconduck.com/icons/75229/squares-four (MIT)

---

Whitelist: https://iconduck.com/icons/12468/exit-right (Unlicense)

**Comment by hussainmohd-a** [comment]
More icons: 
Minus: https://iconduck.com/icons/86309/minus-circle (MIT)
Pause: https://iconduck.com/icons/7494/pause (Apache)
Plus: https://iconduck.com/icons/100296/plus-circle (Apache)
Stop: https://iconduck.com/icons/9828/stop-filled (Apache)
WiFi: https://iconduck.com/icons/117952/wifi-connection (MIT)
WiFi_off: https://iconduck.com/icons/117953/wifi-off-connection (MIT)
Network: https://iconduck.com/icons/90419/network-strength-4 (Apache)
Network_off: https://iconduck.com/icons/90421/network-strength-off (Apache)
Sort icon: https://iconduck.com/icons/91550/sort-variant (Apache)
Sort icon reverse: https://iconduck.com/icons/91546/sort-reverse-variant (Apache)
Back arrow: https://iconduck.com/icons/113404/arrow-left (MIT)
Arrow: https://iconduck.com/icons/34340/arrow-back (Apache)
Copy Icon: https://iconduck.com/icons/67122/copy
Configure Icon: https://iconduck.com/icons/39768/configure
Sort: https://iconduck.com/icons/73848/sort-ascending (MIT)
Edit: https://iconduck.com/icons/100921/note-edit-line (MIT)***
Cross: https://iconduck.com/icons/12452/cross-circle (Unlicense)
Tick: https://iconduck.com/icons/8995/checkmark-outline (Apache)
Search: https://iconduck.com/icons/9755/search (Apache)
Metered (Universal): https://iconduck.com/icons/9477/meter-alt (Apache)
Backup and restore: https://iconduck.com/icons/29558/settings-backup-restore (Apache)
Backup: https://iconduck.com/icons/88379/database-arrow-down-outline (Apache)
Restore: https://iconduck.com/icons/88411/database-refresh (Apache)
Authors: https://iconduck.com/icons/72135/code (MIT)
Global lockdown: https://iconduck.com/icons/34872/vpn-lock (Apache)
Lockdown: https://iconduck.com/icons/91774/table-lock (Apache)
Blocklist update: https://iconduck.com/icons/88040/clock-time-three-outline (Apache)
Translate: https://iconduck.com/icons/109091/translate (MIT)
Privacy policy: https://iconduck.com/icons/9650/policy (Apache)
Firewall allow: https://iconduck.com/icons/117791/cloud (MIT)
Statistics screen: https://iconduck.com/icons/39966/line-chart (Apache)
Exclude icon: https://iconduck.com/icons/145495/exclude-row (Apache)
Bypass icon: https://iconduck.com/icons/166828/bird (MIT)
IP rule icon: https://iconduck.com/icons/124775/ip-address (MIT)
App lock icon: https://iconduck.com/icons/28889/fingerprint (Apache)
Trust IP: https://iconduck.com/icons/113163/double-check (Apache)
Bypass dns & firewall: https://iconduck.com/icons/125139/security-pass (MIT)
adv dns filtering: https://iconduck.com/icons/33050/filter-tilt-shift (Apache)
Pcap: https://iconduck.com/icons/84209/capture (MIT)
fallback dns: https://iconduck.com/icons/150045/go-back-2 (MIT)
proxy: https://iconduck.com/icons/154458/proxy (MIT)
other settings: https://iconduck.com/icons/34062/miscellaneous-services (Apache)
dns cache: https://iconduck.com/icons/88531/dns-outline (Apache)
private network: https://iconduck.com/icons/10009/virtual-private-cloud-alt (Apache)
Network (tunnel): https://iconduck.com/icons/9532/network-4 (Apache)
Save icon: https://iconduck.com/icons/257634/floppy-disk-save# (MIT)
Wireguard icon: https://iconduck.com/icons/245558/wireguard (Apache)
QR code: https://iconduck.com/icons/30995/qr-code-scanner (Apache)
Import: https://iconduck.com/icons/9161/document-import (Apache)
New warp conf (wg): https://iconduck.com/illustrations/108520/project-create-new-sm (MIT)
Connectivity checks: https://iconduck.com/icons/134657/check-circle (ISC)
Firebase: https://iconduck.com/icons/85574/firebase (MIT)
Reddit: https://iconduck.com/icons/58495/logo-reddit (MIT)
Mastodon: https://iconduck.com/icons/244791/mastodon (Apache)
Element: https://iconduck.com/icons/244416/element (Apache)
Share: https://iconduck.com/icons/192400/share-classic (MIT)
info: https://iconduck.com/icons/58379/information-circle-outline (MIT)
plus: https://iconduck.com/icons/7688/plus (Apache)
camera: https://iconduck.com/icons/75473/camera (MIT)
microphone: https://iconduck.com/icons/12717/microphone (MIT)
loop back: https://iconduck.com/icons/57060/spin (Apache)
sponsor: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:favorite:FILL@1;wght@400;GRAD@0;opsz@48&icon.query=heart&icon.size=256&icon.color=%23e8eaed&icon.platform=web (Apache)
rethink plus: https://iconduck.com/icons/68045/premium (MIT)
edit: https://iconduck.com/icons/167416/pencil-ui-circle (MIT)
created: https://iconduck.com/icons/108689/history (MIT)
expiry: https://iconduck.com/icons/108875/time-out (MIT)
fail open on no network: https://icones.js.org/collection/all?s=network&icon=carbon:network-admin-control (Apache)
idle timeout: https://icones.js.org/collection/all?s=loading&icon=icon-park-outline:loading-one (Apache)
tcp kep alive: https://icones.js.org/collection/all?s=hour&icon=fluent:hourglass-three-quarter-16-regular (MIT)
split dns: https://icones.js.org/collection/all?s=split&icon=ic:round-call-split (Apache)
meter only mobile nws: https://icones.js.org/collection/all?s=meter&icon=ion:md-speedometer (Apache)
tun-nw policy: https://icones.js.org/collection/all?s=settings&icon=mdi:cog-clockwise (Apache)
use fallback to bypass: https://icones.js.org/collection/all?s=route&icon=circum:route (Mozilla)

----------------------------------
v055u
tombstone: https://icones.js.org/collection/all?s=tomb&icon=game-icons:tombstone (CC by 3.0)
accept incoming wg: https://icones.js.org/collection/all?s=incom&icon=icon-park-twotone:incoming (Apache)
battery: https://icones.js.org/collection/all?s=battery&icon=material-symbols:battery-0-bar (Apache)
bandwidth booster: https://icones.js.org/collection/all?s=width&icon=fluent:auto-fit-width-20-regular (MIT)
allow metered: https://icones.js.org/collection/all?s=metered&icon=carbon:power-enterprise-pools-metered-capacity-integration (Apache)

-----------------------------------------

v055v

DNS recordtype filter: https://icones.js.org/collection/all?s=dns&icon=carbon:dns-services (Apache)
Flight recorder https://icons.getbootstrap.com/icons/airplane (MIT)
Proc icon https://uxwing.com/processor-icon (Apache)
RPN Auto icon: https://uxwing.com/crown-jewel-icon (Apache)
Stacktrace: https://uxwing.com/activity-log-icon (Apache)
Flood wireguard: https://uxwing.com/valve-outline-icon (Apache)
Socket buffer size: https://uxwing.com/technology-icon (Apache)

-----------------------------------------

v055z
Sponsor badge: https://icones.js.org/collection/all?s=sponsor&icon=octicon:sponsor-tiers-16 (MIT)
Profile Memory: https://icones.js.org/collection/all?s=profiler&icon=gcp:profiler (Apache)


---------------------------------------

v057

Perform protocol translation: https://icones.js.org/collection/all?s=convert&icon=fluent:convert-range-24-regular (MIT)


---------------------------------------

Illustrations
Download illustration: https://undraw.co/license

**Comment by ignoramous** [comment]
Impl in #354
