### ISSUE TITLE
[FEATURE REQUEST] Resolved IPs in network log

### ISSUE THREAD

**Issue by 0xlne** [celzero/rethink-app#348]
As a user, I want to be able to recognize hostnames in the network log to block.
IPs do not mean much to a human.
Resolved hostnames would make the process of blocking/whitelisting more user-friendly & less time-consuming.

**Comment by ignoramous** [comment]
We already show the domain names in a separate DNS logs screen. Though, we ideally would like to show unified logs, we haven't yet been able to figure out what the UI should look like.

As for blocking domain names (as opposed to what the app supports today, which is blocking IPs) is a priority item: #208 

So: Are you looking for _unified_ logs (both DNS and Network logs in the same screen) or #208?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Duplicate #301 or no?

**Comment by 0xlne** [comment]
Indeed, my request is a dupe of #301 & I apologize for my inadequate acquaintance with the backlog.
However, now that you bring it up, #208 also makes sense, but since my request is already documented in existing issues, I'll close this one & follow the aforementioned.
Thank you for taking the time to respond.

**Comment by ignoramous** [comment]
We have a preliminary implementation up in #354 (which resolved #3 but not quite #301)

We do not do `PTR` lookups, but instead simply map the outgoing connection to approp resolved DNS name (within the `TTL`), kind of like a `reverseDomainToIP` lookup. Of course, this is fraught with errors, especially when a single IP may host several domains (like CDNs / VirtualHosts), but this is a work-in-progress. Ideally, we'd avoid DNS `PTR` lookups altogether, but instead rely on something more fancier like DNS ALG that we are looking to implement #270
