### ISSUE TITLE
Webview's JSInterface not working for signed apk

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#352]
When using JSInterface with Webview, the app works fine with debug build but with the signed APK the JS calls are not returning to the application. 

https://stackoverflow.com/questions/36233328/webview-loadurl-works-fine-when-i-debug-the-app-but-when-i-generate-a-signed-ap

One of the approach to fix the issue is adding fully qualified name in **progaurd-rules.pro**

```
If your project uses WebView with JS, uncomment the following
and specify the fully qualified class name to the JavaScript interface
class:
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
  public *;
}
```

One more approach is modifying the **build.gradle** file 
`release {
minifyEnabled false
...
}`

**Comment by hussainmohd-a** [comment]
As of now, `minifyEnabled` is changed to false.

**Comment by ignoramous** [comment]
Flip the minify setting now that the use of webview has been eliminated from the app?

**Comment by ignoramous** [comment]
Enabled: https://github.com/celzero/rethink-app/blob/91523b633ee03873dce36374e720ebc9995b4f95/app/build.gradle#L47
