### ISSUE TITLE
Allow udp DNS proxies

### ISSUE THREAD

**Issue by DUOLabs333** [celzero/rethink-app#353]
I'm trying to connect personalDNSfilter to ReThink, but when I do, DNS queries don't show up in pDNf. This may be because it launches its proxy over udp, instead of tcp.

**Comment by ignoramous** [comment]
I am able to forward connections to pdnsf just fine.

Are you selecting _pdnsf_ from the dropdown against _App_ (by default, it is set to `Nobody`) when adding a new _DNS Proxy_ entry?

**Comment by DUOLabs333** [comment]
Sorry, yeah, I found the way to do it: go to DNS, disable server discovery, put your IP address in brackets and put the port after two colons.
