### ISSUE TITLE
Allow use of default network DNS

### ISSUE THREAD

**Issue by BayLee4** [celzero/rethink-app#355]
Hi,
As fas as I know, there is currently no option not to use a custom DNS. It would be great to be able to use the default network DNS, as it complements very well the on-device blocklist feature and give users more control over their setup. Thanks for the great app.

**Comment by ignoramous** [comment]
Thanks. Just using the _Firewall_ mode would make the VPN use network / os-provided DNS.

I can also see why one'd want to use it even in _DNS_ mode. Shouldn't be too hard to add this, it is only a matter of how do we expose it as a UI setting to the user. May be in a drop-down in the _Configure_ page of the _DNS_ screen as the fourth option (below the first three: _DNS over HTTPS_, _DNSCrypt_, _DNS Proxy_) / as an option within in _DNS Proxy_ screen itself.

**Comment by BayLee4** [comment]
Thank you !

Not directly related to the issue, so excuse me if this is not the right place to ask, but does the project accept donation (via Paypal for instance) ? I saw on the website that there should be a paid support coming this month, and I probably won't use it but I still want to support the project.

**Comment by ignoramous** [comment]
We do not accept donations right now (not sure if we ever will). Paid plans are planned for end of this month (may be, it spills over to the next).

**Comment by BayLee4** [comment]
Oh too bad, is there any specific reason not to ? I mean there's quite a lot of options : Github Sponsor, Paypal, Bitcoin, Monero, each of them having their strength and weakness. Anyway, if by chance you change your mind, I'll happily donate to the project.

**Comment by ignoramous** [comment]
Donations are known to not sustain FOSS projects. Even the most popular ones barely get a trickle. RethinkDNS + Firewall is a full-time effort, and it is likely donations will never get close to footing the bills of involved engineers. And so, we would like to be able to sell the software and services around it rather than fallback on donations. Given our plans to commercialize this FOSS project, it is also a bit disingenuous to solicit sponsorships in form of donations, I feel.

If the product falters and for one reason or the other, the engineers could not work on it full-time, then it might make sense for whoever takes over the project's maintenance to revisit accepting donations.

Thanks for your support, btw. Appreciate it.

**Comment by BayLee4** [comment]
This is very understandable. My only concern about using the paid plan was that, depending on the implementation, it could lead to a weakened privacy if storing uniquely identifying information such as licence key or email. After seeing a [particular](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8536) thread, it looks like you take such issue seriously, and that the actual implementation will likely not have that weakness. But I'll really need more detail on the implementation to feel 100% comfortable, on how it effectively does not 'track' users in any way. This is especially true as I'm not sure I'll use any of the features included in the paid plan, so I really don't want to take any 'risk'.

This is why I was asking if there was a donation option in supplement, as this way I'm sure it would not be linked to the application on my phone, and thus could be used to identify me. But if opting for the paid support is done in such way that it does not leak any information compared to the freemium plan, then a donation option effectively makes little sense and I would happily take the paid plan instead.

Voila, you now have the full reason behind my request for donation, hope it does not sound too 'paranoid' :')

**Comment by ignoramous** [comment]
A user says,

> I use VOXI in the UK (www.voxi.co.uk) and get free data on certain websites. I've been told by their support team I need to use their DNS for this feature to work

**Comment by pleiozc** [comment]
It'd be excellent to be able to use ISP provided DNS and still be able to use tracking feature from this app.

By adding forth option:
  1) DNS over HTTPS, 
  2) DNSCrypt, 
  3) DNS Proxy,
  4) **No DNS or ISP provided DNS**

Could it be possible? Is there a place for that on roadmap ?

**Comment by ignoramous** [comment]
Yes, this is do-able, and we will implement this by end of this month / next (Oct).

**Comment by ignoramous** [comment]
Read: https://github.com/tailscale/tailscale/issues/2116#issuecomment-946319795

**Comment by ignoramous** [comment]
Impl done in #380 and https://github.com/celzero/firestack/commit/775d8f0ca2853b1f9b752a593298b2b371a1359c

Releasing in `v053i`.
