### ISSUE TITLE
Allow to whitelist/blacklist DNS entry

### ISSUE THREAD

**Issue by BayLee4** [celzero/rethink-app#356]
Hi, currently it's not possible to blacklist an entry (in the LOGS menu, when clicking on an entry it only show its IP address), or to whitelist an entry (it only shows which blocklist(s) have blocked it).
It would be great to have an "Allow/Block" button when clicking on an entry in the LOGS menu, as there may be false positives, or conversely unwanted entries not being blocked.

**Comment by ignoramous** [comment]
Thanks. Planned in the upcoming v054 release #18

**Comment by BayLee4** [comment]
Oops sorry, I didn't see that there was already an issue open. Thanks !
