### ISSUE TITLE
oisd blocklist is updating from a mirror instead of the official site

### ISSUE THREAD

**Issue by user8446** [celzero/rethink-app#358]
Hello,

Currently the oisd list is updating from https://github.com/ookangzheng/dbl-oisd-nl instead of from https://oisd.nl/downloads. Although it's great that someone has done a mirror there have been instances where the repo stopped updating. I think it would be wise to update directly... the maintainer says the site is behind cloudflare so bandwidth is not an issue.

**Comment by ignoramous** [comment]
Thanks for pointing it out. Will address this.

**Comment by ignoramous** [comment]
Tracking at serverless-dns/blocklists#15

**Comment by ignoramous** [comment]
Done: https://github.com/serverless-dns/blocklists/commit/ad5de34581b780190d6538c97af7099dc469d593#diff-33d39a7c412af4f80d8d30358a34bba88cb4d1b6e0d988994b4f5b1a29c23933
