### ISSUE TITLE
Browser is bypassing firewall

### ISSUE THREAD

**Issue by raven9nine** [celzero/rethink-app#364]
Android 10. Privacy Browser (frontend for the system webview). In the RethinkDNS firewall I blocked all apps including all system apps. I unchecked all the whitelisted apps so the Rethink DNS firewall says,

296 apps blocked
0 whitelisted, 0 excluded

But I am still using the browser to submit this report.

**Comment by ignoramous** [comment]
Yikes. Which browser is that and on what OS/Phone?

Can you please confirm if you have, set a _HTTP(S) Proxy_ from within RethinkDNS (the current impl bypasses the firewall: #317). 

Can you check if browser can still connect after you enable "Block connections without VPN" from Android's VPN Setttings ([ref](https://archive.is/cd2kn))?

**Comment by raven9nine** [comment]
Privacy browser that is a front end for the stock webview. Android 10 Phone. I dont use a proxy. All user installed apps are blocked in the firewall. The whitelisted apps are the default list.

**Comment by raven9nine** [comment]
Privacy browser that is a front end for the stock webview. Android 10 Phone. I dont use a proxy. All user installed apps are blocked in the firewall. The whitelisted apps are the default list.

**Comment by raven9nine** [comment]
I enabled 'block connections without VPN' in the VPN settings, but I believe the browser is still connecting through the rethinkdns VPN because the rethink DNS log shows the browser connections are being allowed. I uploaded 2 screenshots one to show all apps are blocked the other shows the browser is being allowed through the firewall because it has no red line beside it.

![Screenshot_20210726-181916](https://user-images.githubusercontent.com/35378689/132263072-c06649e1-73e3-4481-8bd5-71e0c96001e9.png)
![Screenshot_20210726-181935](https://user-images.githubusercontent.com/35378689/132263084-b2d921b1-0feb-4373-a986-4b80b6793b84.png)

**Comment by raven9nine** [comment]
I enabled 'block connections without dns'.
Here is 2 screenshots.
One shows all apps are blocked the other shows browser is being allowed through the firewall and it has no red line beside it to signify it was blocked.
![Screenshot_20210906-170238](https://user-images.githubusercontent.com/35378689/132263774-b548e402-34d4-4cd3-b6fc-615f793ac2e6.png)
![Screenshot_20210906-171157](https://user-images.githubusercontent.com/35378689/132263811-8e4e6af3-1ab1-4360-8c38-e2743e441004.png)

**Comment by ignoramous** [comment]
Thank you this is helpful.

Can you _tap_ on one of those Privacy Browser entries, and share the screenshot?

Also, from the search bar in _All Apps_ tab, search for _Privacy Browser_ to confirm if it is indeed blocked.

Btw, how did you enable _Block connections without DNS_? That setting has not been released to any of the app stores...

**Comment by ignoramous** [comment]
I think there might be issue with blocking recently apps installed. Looking into it...

**Comment by raven9nine** [comment]
Sorry I meant I enabled 'block connections without vpn' in android vpn settings. 

All apps shows all apps are blocked including browser. Here is screenshot tapping browser entry in the log shows firewall allows it.


![Screenshot_20210907-020248](https://user-images.githubusercontent.com/35378689/132301635-d6f319c7-acdd-4ec5-9617-a7cc4eaa249c.png)

**Comment by ignoramous** [comment]
What happens when you tap against `Rule #1` against _Privacy Browser_? Does it show _Cannot block the app_? If yes, we are looking to fix what you're seeing.

**Comment by raven9nine** [comment]
App is V.0.5.3e (2)
When I clicked against rule #1, yes is showed cannot block the app.

**Comment by raven9nine** [comment]
Another observation. I still have all apps blocked, zero whitelisted. So the firewall log shows my f-droid app was blocked but I find it is bypassing that block and connecting to the f-droid site regardless. This must be what Android permissions means by apps can use the browser and other apps for network access.

**Comment by ignoramous** [comment]
>  When I clicked against rule #1, yes is showed cannot block the app.

We do not know what _caused_ the issue you're seeing but have identified a potential _bug_ which we have since fixed (to be released in a week or two with `v053g`) that _may_ fix it.

Can you see if after tapping the _refresh_ button on _All Apps_ tab, you're then able to block _Privacy Browser_? 

>  I find it is bypassing that block and connecting to the f-droid site regardless. 

F-Droid app itself? It may be loading things from cache. Try downloading / installing an app. Shouldn't work.

> This must be what Android permissions means by apps can use the browser and other apps for network access.

Not really. Apps can use browser (WebView) but it won't help them bypass the Firewall as impl by RethinkDNS. Apps can use Android's built-in _Download Manager_ to bypass user-space firewall (which RethinkDNS is) restrictions, but _Download Manager_ itself is blockable by user-space firewalls. There are other ways app can exfiltrate data out of the phone even when firewalled, but I firmly believe, firewall should be viewed from the lenses of blocking IPs / domains rather than blocking apps.

I wrote more on the topic in a comment at the [degoogle sub-reddit](https://www.reddit.com/r/degoogle/comments/p4uxwq/best_root_solution_to_block_apps_connection_to/h960rmk/).

**Comment by raven9nine** [comment]
I refreshed the apps but I am still using the browser even though it is supposed to be blocked. The log still shows browser is being allowed through the firewall while all other apps are blocked.

**Comment by ignoramous** [comment]
No WebView is not whitelisted in code. What you are seeing is a bug where there is a mismatch between what's installed and apps tracked by RethinkDNS. _Clear data_ should fix this (be warned that you'd lose all your RethinkDNS settings and config)

**Comment by ignoramous** [comment]
#354 fixes this. _Hopefully_. @raven9nine see if _clear data_ fixes the issue for you on `v053e (3)`.

Thanks for your patience and this report (which comes just at the right time to allow us to fix it for an imminent release). Such a nasty bug, this one.

**Comment by ignoramous** [comment]
@raven9nine can you confirm if clear-data (on `v053e`) and then attempting to block the browser works?

We've since fixed this issue in a yet-to-release `v053g`, otherwise.

**Comment by ignoramous** [comment]
[`v053g`](https://github.com/celzero/rethink-app/releases/tag/v0.5.3g) is a go. Please test to see if you still experience the issue reported here. Thanks.

**Comment by raven9nine** [comment]
Yes the the issue is fixed in v053g. Good work, thankyou.
