### ISSUE TITLE
Continued Issues With archive.is

### ISSUE THREAD

**Issue by raven9nine** [celzero/rethink-app#371]
NX Domain response while using RethinkDNS but archive.is loads fine when I disconnect RethinkDNS to use my regular provider dns.
![Screenshot_20210908-110404](https://user-images.githubusercontent.com/35378689/132957204-b865c191-89d4-47d1-9a76-6a67c3f5b99f.png)

**Comment by ignoramous** [comment]
Unfortunately, `archive.is` refuses to work with DNS resolvers that do not share a part of client's IP with them (specifically, the `EDNS Client Subnet`).

Ref #361 for possible mitigations we plan to implement.

**Comment by raven9nine** [comment]
Are you saying the website gets to decide which DNS servers have their ip address?

**Comment by ignoramous** [comment]
archive.is likely runs their own nameservers (or configures them so as) to deny responding to DNS requests that do not send it the client-subnet. 

See: https://news.ycombinator.com/item?id=19828317

**Comment by raven9nine** [comment]
Ok but why does it resolve the address sometimes and not others?
![Screenshot_20210913-101828](https://user-images.githubusercontent.com/35378689/133112356-31ff9caa-6ae1-4c40-84c6-a0fa307c1551.png)

**Comment by ignoramous** [comment]
Not sure how it happened but that one is an incorrect resolution (`archive.is` -> `1.1.1.1`) anyway (`1.1.1.1` is a Cloudflare IP)

**Comment by raven9nine** [comment]
Hmmmm yes now that is weird because the archive.is site did open in the browser.  Would you agree that the only way the archive.is site could open in my browser without the ip address being correctly resolved is if that was a fake archive.is ?

**Comment by ignoramous** [comment]
>  Would you agree that the only way the archive.is site could open in my browser without the ip address being correctly resolved is if that was a fake archive.is

Not really. TLS v1.2+ cannot be MiTMd (man-in-the-middle) just like that. The browsers warn you of MiTM when visting `https` (TLS) websites. Of course, always possible that archive.is you saw was MiTMd through any number of compromises (like bogus certificates) even when on `https`. With `http`, you can be _sure_ you'd be MiTMd to oblivion.

**Comment by raven9nine** [comment]
Cloudfare is the mitm.

**Comment by ignoramous** [comment]
Cloudflare is a reverse proxy. MiTM is a bit of a stretch, but sure.

**Comment by ignoramous** [comment]
Tracking this in #361 Please feel free to reopen this issue if you'd like to continue to the discussion here instead (:
