### ISSUE TITLE
Home Page Reports Incorrect  DNS Config After DNS Connection Error

### ISSUE THREAD

**Issue by raven9nine** [celzero/rethink-app#372]
Attempt to configure RethinkDNS to use DNSCrypt, Quad9, LA Relay, returned DNS connection error, 'Error Connecting to DNS Server'. RethinkDNS defaulted back to DNS over HTTPS but Homepage still shows DNSCrypt.

**Comment by ignoramous** [comment]
Thanks. Which version are you on (check the footer of the app's About page)?

**Comment by raven9nine** [comment]
Version 0.5.3e (2)

**Comment by ignoramous** [comment]
This has been fixed in #354 hopefully landing sometime this week.
