### ISSUE TITLE
v0.5.3g "Setup SOCKS5 (TCP) Proxy)" - option disabled after upgrade.

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [celzero/rethink-app#381]
upgraded from v0.5.3e to v0.5.3g through fdroid. As much improvements the new release contains, sadly 
found out that my "Setup SOCKS5 (TCP) Proxy)" settings was kept, but the option itself was disabled afterwards. That's perhaps not the expected behavior? Effectively leaking all apps instead proxifying.

**Comment by ignoramous** [comment]
Hi again (:

That one is strange. App disables the SOCKS5 setting when:

1. Connected to Orbot
2. App not in DNS + Firewall mode
3. "Block connections without VPN" is set from Android's VPN Settings page.

Do you see any prompts on why the app chose to disable the setting? If not, can you share a screenshot of the Settings page, if you're comfortable doing so?

> found out that my "Setup SOCKS5 (TCP) Proxy)" settings was kept, but the option itself was disabled afterwards

Does this mean the app is not forwarding connections despite having *set* and enabled SOCKS5?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Sorry, It must be case #3!

Than it migth have been my fault and this is not and issue and I will close. Because I remember switching "Block connections without VPN" on before upgrade but than need to use androids „airplane mode“ anyway. The configured proxy was still set, but the option was actually disabled.

Thanks for explanation.

**Comment by ignoramous** [comment]
thanks.

It is probably a usability bug if VPN continues to respect SOCKS5 settings while the UI is disabled. Here's the offending code: https://github.com/celzero/rethink-app/blob/46f08da505e234c098626208682f2b12dce21920/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L619-L630

What do you think is the right thing to do here? Allow forwarding SOCKS5 and HTTP via proxy even when user has chosen to _block all connections without VPN_? If the proxies themselves are not running on localhost (`127.0.0.1`) then may be we could honor the proxy settings to forward connections to any other LAN / WAN address.
