### ISSUE TITLE
Always-on dialog not functional on Lineage OS 7.1

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#383]
User reported: 

```
Toggle of START/STOP button showing incorrect dialog on Lineage OS 7.1

https://t.me/rethinkdns/21242
https://t.me/rethinkdns/21309
```

**Comment by hussainmohd-a** [comment]
Reference link for creating emulator to test the issue.

[Run lineageOS](https://www.reddit.com/r/LineageOS/comments/8b25i0/can_i_run_lineageos_in_an_emulator_and_if_so_how/)

[Build](https://stackoverflow.com/questions/60943250/can-i-build-emulator-version-of-lineageos)

**Comment by ignoramous** [comment]
@hussainmohd-a I believe this is fixed? If not, reopen.

Dup? #427
