### ISSUE TITLE
Check for uuid in generated domains

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#385]
Check if the auto generated domain names contains a uuid in it. 

https://github.com/hussainmohd-a/rethink-app/blob/46f08da505e234c098626208682f2b12dce21920/app/src/main/java/com/celzero/bravedns/service/DNSLogTracker.kt#L234

```
Eg.,

  ~7a8754ab-3e4e-402b-9019-b4bc1fb2998f.which.nameserve.rs 

 49db5bdc-bde4-4700-aa8f-9d843756357b.test.dnsleaktest.com
```

**Comment by hussainmohd-a** [comment]
Now the fqdn's which has uuids are considered as auto-generated. Fixed as part of v054.

**Comment by ignoramous** [comment]
#380
