### ISSUE TITLE
ActiveNetwork maybe VPN?

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#398]
Confirm if `ActiveNetwork` is indeed not the VPN itself!

https://github.com/celzero/rethink-app/blob/46f08da505e234c098626208682f2b12dce21920/app/src/main/java/com/celzero/bravedns/service/ConnectionMonitor.kt#L166

also: #355 (shouldn't set a VPN's DNS as the network DNS which would be the case when `ActiveNetwork` is VPN itself)

**Comment by hussainmohd-a** [comment]
There is a check for active network not VPN. 
https://github.com/celzero/rethink-app/blob/161674b1cdbdd72fefee5edd953179a637e00f6f/app/src/main/java/com/celzero/bravedns/service/ConnectionMonitor.kt#L253
