### ISSUE TITLE
"Nobody" in proxy dialogs 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#400]
A user wrote that they were uber confused with what "`Nobody`" mean in the proxy dialogs (DNS and SOCKS5). We need either an `i`nformational icon like we have in Orbot screen explaining what those fields are, or a new label to denote "`Nobody`".

**Comment by ignoramous** [comment]
Probably just change the label to `None`.

**Comment by hussainmohd-a** [comment]
Fixed: 8013e22076e31f521949e8d626e93d8abf2886b2
