### ISSUE TITLE
WebView Zoom

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#401]
The webview that shows [rethinkdns.configure](https://rethinkdns.com/configure) to let users configure blocklists disables zoom'ing. Enable it since sometimes, the text is rendered too small (like the webpages showing the raw hostfile entries).

```
webview.getSettings().setBuiltInZoomControls(true);
webview.getSettings().setDisplayZoomControls(false);
```

per: https://stackoverflow.com/a/32587047

**Comment by hussainmohd-a** [comment]
Enabled built in zoom controls of webview.
