### ISSUE TITLE
Room dispatchers

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#407]
Room has its own dispatchers that run off of the main-thread. https://archive.is/hRdJv

Simply decorating the functions with suspend is enough. In fact, they recommend not adding withContext on any Room transactions or queries. non-suspending Room functions need dispatchers, but those should only be supplied from a view-model.

**Comment by hussainmohd-a** [comment]
Also see: https://archive.is/prxe9

A FlowObservable to observe events from LiveData via ChannelFlow without leaking the ChannelFlow.

**Comment by ignoramous** [comment]
Fixed in #380
