### ISSUE TITLE
Handle Android 9 and Android 10 Private DNS behaviour differently

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#408]
A user says,

> When Android's Private DNS is set to Automatic, DNS logs can't be viewed. Automatic  mode is default I believe, where Android wants to upgrade to DoT opportunistically. This seems to be affecting only Andorid 9 (Pie), in which Private DNS doesn't affect VPNs.

> Assuming this is a bug, may be a check here and here if getPrivateDnsServerName() is not null too should fix it? 

[Only since Android 10](https://github.com/aosp-mirror/platform_frameworks_base/commit/f98611062c9cf175d3c31d0650af3ae6873ed21d#diff-3992263f882eea44ac9d5e611e713966), does DNS traffic get sent to Private DNS instead of a VPN's DNS servers. So, the checks around `Protected with Private DNS` need to be done only for Android 10 or above.

See also: #25 and #390

**Comment by amithm7** [comment]
Seeing this issue in Android 11 too!

**Comment by ignoramous** [comment]
Thanks.

On Android 9, the issue is, rdns should _show_ DNS pages regardles of private DNS status, since private DNS is overriden by VPN DNS anyway. This isn't the case for Android 10 and above.

For Android 10 and above, rdns needs to detect if the current DNS servers in a link change event are "private" and act accordingly (not just rely on whether private DNS setting is enabled or not but that the private DNS servers are actually in-use).

**Comment by ignoramous** [comment]
> When Android's Private DNS is set to Automatic, DNS logs can't be viewed.

Fixed this in the latest development builds.

> On Android 9, the issue is, rdns should show DNS pages regardles of private DNS status, since private DNS is overriden by VPN DNS anyway.

Fixing this in https://github.com/celzero/rethink-app/pull/380

**Comment by ignoramous** [comment]
Release: `v053i`.
