### ISSUE TITLE
User feedback: Auto-start behaviour and VPN state

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#41]
On a restart, BraveDNS starts-up to resume VPN services, but it so happens that on ocassion another app takes the VPN over and BraveDNS continues to show "protected/waiting" ("running"), when in fact it wasn't.

Also, add ability for end-users to choose whether BraveDNS must auto-start on reboots.

**Comment by hussainmohd-a** [comment]
Auto start feature is disabled for this release. Will introduce settings for auto start application during reboot in future release.

**Comment by ignoramous** [comment]
There's an "auto start on device restart" option in the "Settings" page of the app.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> 
> 
> There's an "auto start on device restart" option in the "Settings" page of the app since the release v052 (Nov, 2020).

I enabled this, but found out my rethink-app Ops had autostart disabled in apps permission. Make sure the user gives the rethink-app the autostart permission together with enabled autostart option.

**Comment by ignoramous** [comment]
> > There's an "auto start on device restart" option in the "Settings" page of the app since the release v052 (Nov, 2020).
> 
> I enabled this, but found out my rethink-app Ops had autostart disabled in apps permission. Make sure the user gives the rethink-app the autostart permission together with enabled autostart option.

That's a first. A user using app ops :)

Would you know if there is an api available to apps to find out app ops rules an app is subject to?
