### ISSUE TITLE
Feature request: Support asterisks in DNS host blocklists

### ISSUE THREAD

**Issue by mtxadmin** [celzero/rethink-app#411]
Hello.

Is there any plans to support asterisk(s) in blocklists?

It could drastically reduce RAM footprint and battery consumption. Some time ago in https://github.com/julian-klode/dns66/issues/423, I wrote an example for doubleclick.net subdomains. But now it is possible to fully estimate the difference for all marketing and other subdomains

Two blocklists (compiled from the strictly same sources): first is traditional one
https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt - **29.7 MB**
And the second is using asterisks (for using in [Blokada](https://github.com/blokadaorg/blokada/))
https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts_blokada.txt - **2.94 MB**

In addition, using of asterisks can block all the new subdomains automatically.

**Comment by ignoramous** [comment]
The blocklists wildcard support for RethinkDNS is tracked here: serverless-dns/blocklists#9

But: do you mean wildcard support in
- custom wildcard entries #18 
- custom blocklist import #36 

Then, yes, we intend to support it.

Btw, wildcard or not, it doesn't in terms of perf for RethinkDNS. Of course reduction in size is important but that's secondary concern as RethinkDNS already compresses the included blocklists six ways from Sunday.

**Comment by ignoramous** [comment]
Closing as dup of https://github.com/serverless-dns/blocklists/issues/9

Re-open if you think that was a mistake. Thanks.
