### ISSUE TITLE
"Back" button behavior from Settings

### ISSUE THREAD

**Issue by michaelblyons** [celzero/rethink-app#412]
Please make the system "back" button go to the main Rethink screen from your Settings screen. Right now it closes the app, and I find that moderately irritating.

I know there's an in-app "back" button consisting of a house in the bottom-left, but my brain always wants to click the universal "back" button at the bottom of the screen to do it.

**Comment by ignoramous** [comment]
Thanks. In my defense, that's the _default_ Android behaviour for the [bottom-navigation Material Design component](https://material.io/components/bottom-navigation)... We can change it of course, but then it'd be even more confusing...? or less? Though, I see where you're coming from too, and I am personally in favour of fixing the back button and replacing its 'up' like behaviour.

Dup? 
- #125
