### ISSUE TITLE
[Feature Request] Bootstrap DNS over HTTPS with "host file", then fallback to global DNS.

### ISSUE THREAD

**Issue by DUOLabs333** [celzero/rethink-app#417]
Can you give the option for the DNS-over-HTTPS resolver to be resolved by "hosts-file" like mapping first, then reverting to a global DNS server to find the IP address if it fails?

**Comment by ignoramous** [comment]
Ah, yeah planned: #94

Currently, all built-in DoH servers come with bootstrapped IPs.

(closing it as dup, re-open if you think #94 is different to this).
