### ISSUE TITLE
Block HTTP connections

### ISSUE THREAD

**Issue by Horizonbli** [celzero/rethink-app#418]
Hello,

For some time now that I see chrome trying a connection to HTTP instead of HTTPS (one of those gvt1). Currently, the only workaround is to simply block connections to the respective IP address, which then forces chrome to connect to HTTPS, which it can't because the IP is blocked.
But, other services/web sites still don't make use of HTTPS, and I also noticed that, for whatever reason, previous versions of chrome failed to block access to HTTP, even though I had the flag to block them enabled. So, it would be great if rethinkdns app firewall could have a general setting to block connections to HTTP. This is one situation where redundancy is more than welcome.

Thanks!

**Comment by ignoramous** [comment]
Makes sense. 

See also #50
