### ISSUE TITLE
Firewall suggestions

### ISSUE THREAD

**Issue by Horizonbli** [celzero/rethink-app#420]
Not sure whether or not it would be possible, but imagine that we block all connections, except what's whitelisted. Say, we use Gmail app and Play Store. Not only we need to whitelist the respective apps, but also Google Backup Transport.

My question is: would it be possible to have a future version of RethinkDNS to allow us to whitelist, in my example, Google Backup Transport, but only for Gmail and Play Store and block it for everything else?

Also, in the firewall log I believe we should also be able to find for domains and port/protocols as well, not only apps and IPs.

Thanks!

**Comment by ignoramous** [comment]
Thanks.

> Google Backup Transport, but only for Gmail and Play Store and block it for everything else?

I don't see how we can ever do this without actually peeking into the actual content of the traffic. Not that it isn't do-able, but also super error prone and very much not safe at all.

> Also, in the firewall log I believe we should also be able to find for domains and port/protocols as well, not only apps and IPs.

Yeah, we should. See also #149

**Comment by Horizonbli** [comment]
Thanks for explaining the firewall doubt that I had.

Now, I'd like to know one more thing, and this is something that just occurred to me after having some connectivity issues with dnscrypt servers/relays that I manually added, and that for whatever reason made me lose connectivity because I have the firewall set to block connections when DNS is bypassed. That said, I am wondering if we could have it reveal where DNS queries are being made to? Just to be clear, I lost connectivity (until I switched dnscrypt servers/relays again) between 7:42:06 and 7:48:25 PM. The firewall logs reveal that connectivity was blocked due to DNS being bypassed. Unfortunaly, there are simply no DNS queries logged within the same period of time. So, just wondering if we could have the DNS queries revealed (with future releases) or if it is just the way it works. I suppose this is more related to the DNS component rather than the firewall itself, but since it goes blank about those DNS bypasses, I'm wondering if its possible to know where DNS queries are going to, by having the firewall reveal it perhaps?

Thank you!

**Comment by ignoramous** [comment]
>  I suppose this is more related to the DNS component rather than the firewall itself, but since it goes blank about those DNS bypasses, I'm wondering if its possible to know where DNS queries are going to, by having the firewall reveal it perhaps?

I have to think more about it, but I don't think this is possible at all. The app "bypassed" the DNS, and hence the DNS queries themselves are not known. But, the connections made by the app that's bypassing the DNS should almost always appear in the Firewall logs. Right now, Firewall can only "guess" whether or not DNS was bypassed, but it cannot really know for what DNS query, specifically.

> and that for whatever reason made me lose connectivity because I have the firewall set to block connections when DNS is bypassed.

Find the app that's bypassing the DNS and "whitelist" it under Firewall's "Universal" tab. You don't have to blanket disable the setting, fwiw. Of course, if this setting breaks Internet for too many apps, then you might as well choose to keep it disabled.

**Comment by Horizonbli** [comment]
OK. It would be interesting if could be possible to know where DNS queries are going to in such situations.
No need to disable DNS bypass protection, at all. I'm actually glad it works as it should. Not complaining about it. :)

**Comment by ignoramous** [comment]
> OK. It would be interesting if could be possible to know where DNS queries are going to in such situations.

Monitor progress here: #270 

> Not sure whether or not it would be possible, but imagine that we block all connections, except what's whitelisted. Say, we use Gmail app and Play Store. Not only we need to whitelist the respective apps, but also Google Backup Transport.

This is not do-able (or rather, I know of no way to do it in the VPN layer that RethinkDNS app operates in).

Feel free to re-open this bug, if you think there were queries / requests left unanswered.
