### ISSUE TITLE
Forward all DNS over SOCKS5

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#421]
Let users choose if DNS providers should also be hit through upstream SOCKS5. 

That is, forward DoH, DNSCrypt, plain DNS conns over SOCKS5 endpoint.

See also: https://github.com/celzero/rethink-app/issues/284

**Comment by FLAGEL** [comment]
Would love to see this. As a note, "Every Proxy" app supports both TCP and UDP over its SOCKS5 proxy, so there are use cases.

**Comment by ignoramous** [comment]
Impl in `v055b`: https://github.com/celzero/rethink-app/releases/tag/v0.5.5b

https://github.com/celzero/rethink-app/blob/02c16a99764b82bd4fbcc53187134cf944c47931/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L2436-L2442
