### ISSUE TITLE
May you please add an option to rethink app to upgrade all http requests to https?

### ISSUE THREAD

**Issue by rustforfuture** [celzero/rethink-app#422]
Hello

May you please add an option to rethink app to upgrade all http requests to https?

I think you can put it in buttom or show a red warning that doing if it cause problems for user?

It's used case is that having this option for whole apps and OS will be great specially in hostile networks.

That way we can be sure no http request will go outside of our phone.

Also if may another option to block http request if that website didn't had https version (after trying to upgrade the request) will ve great.

Thank you very much

(although chromium and Firefox have it, having this option for whole OS will be by far great.)

Thank you very much

Also a related issue:

https://github.com/celzero/rethink-app/issues/418

**Comment by ignoramous** [comment]
I'd have to check if something like this is possible. It could be, but the effort must be worth it... esp since the _latest_ Chrome / Firefox default to HTTPS for _all_ websites a user visits.

**Comment by rustforfuture** [comment]
Thank you.
Yes, i can understand.

When I thought about it, it will be really hard to implement and may be a waste of time for you.

I think if you provide that http blocking option, it will be great and enough

Thank you very much ♥️

Best wishes.

**Comment by ignoramous** [comment]
Sure.

> I think if you provide that http blocking option, it will be great and enough

That's on our radar, see #50
