### ISSUE TITLE
Internet does'nt work

### ISSUE THREAD

**Issue by free-tinker** [celzero/rethink-app#423]
I used the firewall mode. When I ran browser, It couldn't reach the website, like disconnected.
And then I whitelisted and unblocked all the apps, but nothing was change.
I tried it on custom rom by the way.

**Comment by ignoramous** [comment]
Check if the DNS blocklists are blocking the websites you're trying to visit? Tap on _DNS_ on the homescreen and the real-time running logs should give you clues to what blocked which domain.

Custom allowlist/denylist is coming in the next version #18

**Comment by free-tinker** [comment]
I'm sorry. My bad explanation.
What I actually meant that the internet blocked all apps not only the browser.

I was following your advice to see the log information.
There is an app, which undetected by rethinkdns (shown as unknown app), trying to connect somewhere.
I don't know what it is, but maybe need the allowlist/denylist feature (I assumed that the problem caused by this app).

**Comment by ignoramous** [comment]
>  There is an app, which undetected by rethinkdns (shown as unknown app), trying to connect somewhere.

What's the protocol for the "unknown" entry? Tap on the relevant network log entry, and the protocol information would show up _left-hand_ top-corner as `blocked on udp/53332 5 min. ago`, for example.

Usually _some_ (not all) UDP connections are marked "unknown", as Android doesn't return an owner for those.

**Comment by free-tinker** [comment]
It used https protocol.
I'm using all blocking options. My other 2 phones (one of them using custom rom and stock rom on the other one) are fine with that config.

I just found anomaly in the app. The word under start/stop button only shows starting and failing, never shows protected.

**Comment by ignoramous** [comment]
> The word under start/stop button only shows starting and failing, never shows protected.

If RethinkDNS app is in `DNS + Firewall` mode, then:  `Starting` means the app isn't seeing any _new_ DNS queries. `Failing` means RethinkDNS isn't able to answer DNS queries (likely no internet access / DNS resolver endpoints in-use are being firewalled at the router or by the ISP).
