### ISSUE TITLE
DNSCrypt + Tor?

### ISSUE THREAD

**Issue by Horizonbli** [celzero/rethink-app#425]
Sorry if it has been discussed before, but couldn't find anything similar.

I was wondering if it would be possible to have rethinkdns app encrypt DNS queries with dnscrypt (or doh as well), and then go through Tor (using orbot)? How could it be achieved? Isn't possible at all, or the way things are implemented now doesn't allow it?

Thanks

**Comment by ignoramous** [comment]
Hi, do you mean tunnel DNSCrypt and DoH within Tor?

**Comment by Horizonbli** [comment]
Yes, tunnel it. I was lacking a better term for it.
That is exactly what I meant.

**Comment by ignoramous** [comment]
Thanks.

Impl is already in the works. I'll leave this issue open to track its release.

**Comment by ignoramous** [comment]
dup: #421
