### ISSUE TITLE
RethinkDNS app didn't request connection, can't proceed to enable DNS.

### ISSUE THREAD

**Issue by PeterDaveHello** [celzero/rethink-app#427]
Tested RethinkDNS on Google Pixel 3 with Android 12, though there was a dialog to let me cancel or proceed, however, no further permission asking or VPN setup dialog coming after:

![image](https://user-images.githubusercontent.com/3691490/146771173-18a35288-e47d-40aa-a6d5-1dd4653fdffe.png)

I can confirm that the VPN connection request dialog will show up on another device with and older Android version, not sure if it's because Android 12. The permission in the app info shows no permissions requested.

**Comment by ignoramous** [comment]
Thanks! @hussainmohd-a is on it.

**Comment by hussainmohd-a** [comment]
Can able to reproduce this issue in **Android 12 (API level 32)** but the same is not happening in API level 31 emulator. Fix will be part of upcoming release. 

_Happens only if another application has Always-on enabled._ 

- **Issue:** In Android S+, there is no way to find if some other application has Always-on enabled. Prior to Android S, Android Secure Settings will provide this details.

- **Fix:** Show a toast/snack bar/dialog message to user that there is something wrong in creating a vpn profile for the application and intimate them to check if there is some other application has Always-on enabled. Note: Android will return the same error code when the user clicks on cancel button in the android create vpn profile dialog.

**Comment by hussainmohd-a** [comment]
@PeterDaveHello Let us know if the issue you are experiencing is not the same one already mentioned above.

**Comment by ignoramous** [comment]
Fixed in #380 

Releasing with `v053i` (1 week?)
