### ISSUE TITLE
Overruling blocklist

### ISSUE THREAD

**Issue by TobyEU** [celzero/rethink-app#429]
Hi all,

first of all thanks for your great work and the good app. I'm using it since several days and have an idea/feature request.
I've enabled a lot of block list and sometime facing the issue, that 
- I would block a specific URL which isn't yet part of any blocklist (and would never be part, because there are personal reasons for blocking it) (button already available)
- I would allow a specific URL which is part of one or more blocklist.

It would be nice, if there would be a button to block or allow the specific URL in the DNS log. The button for blocking is already there, but without any functionality. The allow button would be the perfect counterpart and make the feature complete.

Thanks

**Comment by ignoramous** [comment]
Duplicates:

1. #208
2. #279 

Impl underway (:
