### ISSUE TITLE
User feedback: Exclude apps from the VPN tunnel

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#43]
Users want to be able to exclude apps from the VPN.

I guess we need to create a separate "settings" screen for this and other related VPN settings...?

**Comment by hussainmohd-a** [comment]
Now user can choose applications not be part of firewall and DNS. 
Introduced new Dialog activity in SettingsFragment, where the list of applications
can be added to exclude from firewall and DNS.
The packages which are added as part of excluded list will be disallowed in VPNBuilder.
Textview in settings screen will have information of number of applications which 
are part of Excluded app list.

**Comment by AXEN-hub** [comment]
I agree! Unfortunately, some apps don't work even when using "exclude." For example, "AttaPoll" doesn't work with a VPN, so the only way to get it to work is to stop or pause RethinksDNS. A separate feature is needed that allows you to exclude a specific app not only from firewall rules but also from the VPN so that it can run without disabling RethinkDNS.

**Comment by ignoramous** [comment]
> Unfortunately, some apps don't work even when using "exclude." For example, "AttaPoll" doesn't work with a VPN, so the only way to get it to work is to stop or pause RethinksDNS. A separate feature is needed that allows you to exclude a specific app not only from firewall rules but also from the VPN so that it can run without disabling RethinkDNS.

"Exclude" does really keep the said app outside Rethink's VPN tunnel. As for the app still complaining about VPN, you could consider getting in touch with the developer / organization and explain to them that they're doing something wrong when it comes to detecting whether the app is being *routed* through the VPN (instead of merely checking if a VPN is enabled or not).
