### ISSUE TITLE
Compatibility with Dnsdist?

### ISSUE THREAD

**Issue by logicReasoner** [celzero/rethink-app#432]
On Android, I tried to use RethinkDNS with a self hosted dnsdist server: added a new entry in DNS->Configure->DNS over HTTPS. The url is of the form: `https://.../dns-query`.
RethinkDNS says `connected` below the newly ticked entry, but then no websites are getting DNS resolved in Chrome browser (Error: `DNS_PROBE_STARTED`) or at all.
When I select the `Cloudflare` entry, everything seems to work fine, so I am wondering what may be the issue. Is RethinkDNS just incompatible with dnsdist?
Just to add, the dnsdist server uses a self signed certificate whose ca.crt has been imported into Android. Perhaps I need to import the ca.cert into RethinkDNS itself or does it already ask the Android OS for verification?

**Comment by ignoramous** [comment]
If the certs are installed in Android's ca-store, the app shouldn't have trouble trusting it. Unless, Go (our underlying DoH impl) is doing something funky with it ([it is known to do so in the past](https://github.com/golang/go/issues/31791)).

I haven't tested this scenario at all, but from your experience, it seems like user-ca aren't picked up for root of trust.

> Perhaps I need to import the ca.cert into RethinkDNS itself or does it already ask the Android OS for verification?

I don't think anything you'd do would make this work. This is on us to investigate (and fix). Thanks for the bugreport.

**Comment by logicReasoner** [comment]
> I haven't tested this scenario at all, but from your experience, it seems like user-ca aren't picked up to determine chain of trust.
Yeah, it seems like that's what is going on. The user's self-signed CA certificate is listed in `Trusted credentials` on Android and the installed Google Chrome browser actually picks it up and properly validates any connections to the DOH url. 
Mobile Firefox and the RethinkDNS app OTOH seem to ignore the existence of the user CA. Some sort of certificate pinning by the underlying DoH implementation perhaps?

Another option could be that dnsdist handles DNS queries differently from CF and Google's DNS servers. See [https://github.com/PowerDNS/pdns/issues/7809#issuecomment-491612215](https://github.com/PowerDNS/pdns/issues/7809#issuecomment-491612215) for reference

**Comment by ignoramous** [comment]
Curious: Why close this? Our intention is to support user-supplied certs.

**Comment by logicReasoner** [comment]
Ah, I guess that you need to have the issue open for tracking purposes.
Reopening it.
BTW, this may be the wrong place to ask but could RethinkDNS's firewall be made to work (perhaps in the future) alongside an already established wireguard connection? I really like the current firewall capabilities but I understand that they could only work while the app presents itself as a (dummy) VPN to the underlying Android OS and given that Android only supports a single VPN connection...

**Comment by ignoramous** [comment]
> BTW, this may be the wrong place to ask but could RethinkDNS's firewall be made to work (perhaps in the future) alongside an already established wireguard connection?

This can be done: #52 

Though, doing it in a efficient way is where we are stuck, right now. In short, with userspace wireguard and firewall, we would be forced to run essentially two 'vpn's... as if, one 'vpn' wasn't already enough to send the batteries drowning.

**Comment by logicReasoner** [comment]
Well, at least RethinkDNS's "dummy" VPN seems to be relatively lightweight as in I haven't noticed it draining too much battery for the job it does. In fact, having most of the apps blocked from accessing the Internet keeps the smartphone running longer.

**Comment by ignoramous** [comment]
Don't tempt fate... ;) btw, battery drain isn't uncommon. We get a lot of (friendly) complaints, like these #409 all the time

**Comment by ignoramous** [comment]
`v055` will let users bypass strict WebPKI validation for DoH endpoints: https://github.com/celzero/firestack/commit/1dfc167ca0778ac218229c9ed264b27be7e84ef1
