### ISSUE TITLE
Feature request: custom dns records/resolves

### ISSUE THREAD

**Issue by luckcolors** [celzero/rethink-app#434]
Hello.

I've just started to use this app and it works pretty well.

It would be cool if it was possible to add custom domain ip mappings, like the etc/hosts file found on normal OS.

I don't need specifically for the feature to be implemented exactly as a hosts file, just the ability to add custom AAAA/AA records.

I think this issue is similar to #416 but was closed by the author.

**Comment by ignoramous** [comment]
#316 dup?

**Comment by luckcolors** [comment]
It's similar.
I think mine is more in scope of just adding a simple domain list.
But if full support for other records is added i don't mind.

**Comment by ignoramous** [comment]
Understood. So, also similar to #293 then.

**Comment by luckcolors** [comment]
Closed in favour of #293.
