### ISSUE TITLE
Bug, compatability problem with kiwi browser 98.0.4758

### ISSUE THREAD

**Issue by sojudu** [celzero/rethink-app#436]
Hi, I get connection errors, I use rethink dns, and have whitelisted kiwi browser, when block connections, when dns is bypassed, is turned on, despite having white-listed the kiwi app, connections fail, I cannot connect to Web pages or YouTube from kiwi browser, kindly fix the compatability problem, thank you

**Comment by hussainmohd-a** [comment]
Hi, Can you please share more details or screenshot of the network logs of Kiwi app to analyze further more on this issue?

**Comment by sojudu** [comment]
![Screenshot_2022-01-12-10-39-08-48_c8cbde12d3521911922be4eee6a05664](https://user-images.githubusercontent.com/95345118/149068140-e1ac39e0-bd26-4493-aff6-81949dfcae81.jpg)
![Screenshot_2022-01-12-10-39-21-50_c8cbde12d3521911922be4eee6a05664](https://user-images.githubusercontent.com/95345118/149068155-7e9b61b9-df63-4938-bcf5-3c47c4bb9e83.jpg)

**Comment by sojudu** [comment]
![Screenshot_2022-01-12-10-37-45-05_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/95345118/149068270-b494cbc3-ed88-4a92-9af7-90a243f62090.jpg)
![Uploading Screenshot_2022-01-12-10-37-51-29_4d38fce200f96aeac5e860e739312e76.jpg…]()

**Comment by ignoramous** [comment]
Hm, can you confurm if you've **not** added any of these lists in your DNS blocklists?

https://rethinkdns.com/search?q=youtube.com

https://rethinkdns.com/search?q=ablinks.mail.hinge.co

**Comment by sojudu** [comment]
I confirm, the bug exists, and remember even if the app is white listed or VPN paused the problem remains, thank you

**Comment by ignoramous** [comment]
Whitelisting an app doesn't exclude it from DNS rules. Whitelists (allowlist) is *only* for firewall rules.

Let me test this on kiwi browser. Can you share your RethinkDNS blocklist URL? It should look something like: `https://basic.rethinkdns.com/1:8J_-P38A___6_6CdNpCAAeRyIABAoQ==`

**Comment by sojudu** [comment]
https://basic.rethinkdns.com/1:8N8B2ADg_wP______3____u___Pp_3Ao

**Comment by sojudu** [comment]
Rethink dns is also incompatible with 'okcupid app' on android and 'the hindhu app' as well, kindly check em out

**Comment by ignoramous** [comment]
Hi, can you please check again? Both `basic.rethinkdns.com` and `basic.bravedns.com` are now running shiny new code that's (supposedly) more stable.

**Comment by sojudu** [comment]
YouTube.Com on kiwi browser , and okcupid are working, thank you
