### ISSUE TITLE
Any plans to add a feature to block custom requests? 

### ISSUE THREAD

**Issue by L1VEWIR3** [celzero/rethink-app#438]
I think it would be extremely helpful to block custom domains as some block lists might not have the domain you wish to block. 
Thank you for your work

**Comment by hussainmohd-a** [comment]
Yes we do have this added to our pipeline. 

Below are the issues to track that:

1. https://github.com/celzero/rethink-app/issues/18
2. https://github.com/celzero/rethink-app/issues/279
3. https://github.com/celzero/rethink-app/issues/208
