### ISSUE TITLE
Rethink dns incompatible with all chromium based browsers

### ISSUE THREAD

**Issue by sojudu** [celzero/rethink-app#439]
Hi, rethink dns is incompatible with all   chromium based browsers such as kiwi,Microsoft edge , sites like YouTube.com fails, even when the said browsers are white-listed, the only solution is to have rethink dns turned off, thank you.

**Comment by ignoramous** [comment]
Hi, thanks for the bug report.

Would this issue be the same as #436 reported two weeks ago?

**Comment by sojudu** [comment]
More or less the same, thank you

**Comment by ignoramous** [comment]
Hi, can you check again? We deploy far toooooo many stability improvements to the RethinkDNS DNS resolver (both `basic.rethinkdns.com` and `basic.bravedns.com`) just today (after a gap of two months!), among which we hoped to have fixed issues with these browsers too.

**Comment by sojudu** [comment]
Thank you, its up
