### ISSUE TITLE
Support DoT (DNS-over-TLS) in the app?

### ISSUE THREAD

**Issue by PeterDaveHello** [celzero/rethink-app#441]
Currently, there're only three types of DNS supported in the app(Screenshot took from RethinkApp v053g):

- DNS over HTTPS
- DNSCrypt
- DNS Proxy

<details>
<summary>screenshot</summary>
rdns dns config:

![RethinkApp v053g Screenshot](https://user-images.githubusercontent.com/3691490/151756302-39eb5b1c-8a2e-474c-896e-eee5b27bf980.jpg)
</details>
Just wondering if there's any plan to support DNS over TLS in the App? Thanks!

**Comment by ignoramous** [comment]
Hm, we can, but it isn't priority over implementing ODoH and DNS over Tor; unless there are use-cases specifically only DoT can address. Thoughts?

**Comment by PeterDaveHello** [comment]
I'm no expert of DoT or DoH, didn't know any something only DoT can address yet, DoH might be even harder to be blocked, which is good.

Just one small weakness I think that DoH has but DoT might not: the HTTP user-agent header. I saw that the RethinkDNS app will send the user agent string: `Intra`, though it doesn't contain any personal information, it'll be part of fingerprinting and user profiling, would be great if you'll like to set it to an empty string, currently, iOS and Firefox seems to do so ;)

**Comment by ignoramous** [comment]
Makes sense: We should remove the user-agent.

DoT doesn't add anything worthwhile (but does add an overhead for us to then maintain the codebase): Of course, DoT it is absent of metadata that HTTP may add, but that really is made up by, as you point out, its ability to pretty much get past firewalls.

**Comment by ignoramous** [comment]
The code may not build as it is in a midst of a rewrite that I abandoned midway (will resume soon), but feel free to make that change and send a PR: https://github.com/celzero/firestack/blob/dd39240f8f176476684a0ffa60c226b05fb4250a/intra/doh/doh.go#L357 (:

**Comment by ignoramous** [comment]
DoT impl is in firestack: https://github.com/celzero/firestack/commit/d72558727bfb394c9c7646557f31abaddbc991ab

UI pending.

**Comment by ignoramous** [comment]
UI done impl `v055b`: https://github.com/celzero/rethink-app/releases/tag/v0.5.5b
