### ISSUE TITLE
Unable to download on-device blocklists

### ISSUE THREAD

**Issue by modestderp** [celzero/rethink-app#444]
Installed the latest version on F-Droid and trying to download on-device blocklists with no success. Tried numerous times but the lists won't download. This only happens to a specific device (Pixel 3), as it doesn't occur on others (e.g. Samsung S10, Pixel 4). 

The only difference between the affected device and others is that the affected device have unlocked bootloader. The unlocked device was previously unlocked on Android 11 but got upgraded to Android 12 by accident and lost root. Tried to factory reset under Android 12 and reinstall and download blocklists again to solve this issue with no success.

Device: Pixel 3, unlocked bootloader
OS: Android 12
Build: 053h

**Comment by ignoramous** [comment]
Thanks for the bug report. This isn't uncommon though we have no clue why this happens as we use Android's built-in download manager (which we presumed to be more robust... Alas).

We are going to rollout our own (poor man's) download manager in one of imminent updates: #314

If you are comfortable sharing logs (`adb logcat`) from when this fails, can you either telegram / email me, please? `mz` at `celzero` dot `com` | [t.me](https://t.me/murtaza.aliakbar).

**Comment by modestderp** [comment]
I'll see what I can do.

Any estimation on when the new download manager will be released?

**Comment by ignoramous** [comment]
> Any estimation on when the new download manager will be released?

@hussainmohd-a should have an answer to that. May be by the end of the next month?

**Comment by hussainmohd-a** [comment]
Yes. Will be released by that time.

**Comment by ignoramous** [comment]
custom downloader impl done in https://github.com/celzero/rethink-app/pull/380

See #314
