### ISSUE TITLE
Allow to setup DNS without start the VPN service.

### ISSUE THREAD

**Issue by PeterDaveHello** [celzero/rethink-app#446]
It looks like we must start it, which means if we want to change the DNS server, we must use the unwanted DNS/config first, as currently there is no support for network specified config, would be really nice if we can change the configuration before starting it, just like the local block list.

**Comment by ignoramous** [comment]
cc: @hussainmohd-a

**Comment by ignoramous** [comment]
> as currently there is no support for network specified config

`v053i` has added support for System / Network DNS (#355).

> ...would be really nice if we can change the configuration before starting it, just like the local block list.

Our code is much simpler if we never have to show those configuration options when DNS / app itself is not functional. That said, I see why such a feature makes sense, even if it isn't likely a priority for us (given the complexity it'd add to the existing code-base).

**Comment by hussainmohd-a** [comment]
Now, app navigation is possible even before starting the VPN. User can make all the necessary configurations before clicking on Start/Stop button.
