### ISSUE TITLE
Add these lists please

### ISSUE THREAD

**Issue by sojudu** [celzero/rethink-app#448]
1) https://community.blokada.org/t/introducing-spam404-blocklist/10766

2) https://community.blokada.org/t/introducing-duckduckgo-tracker-radar-to-blokada/469

3) https://phishing.army/index.html

4) https://community.blokada.org/t/introducing-urlhaus-blocklist/13289

5) https://community.blokada.org/t/introducing-exodus-privacy-to-blokada/7358

**Comment by ignoramous** [comment]
Blokada's lists are GPLd (if I am not mistaken), which is incompatible with the more permissive license (Apache) we use.

**Comment by MicroBeast** [comment]
> Blokada's lists are GPLd (if I am not mistaken), which is incompatible with the more permissive license (Apache) we use.

As far I understand, those 5 each not owned nor maintained by Blokada. Each of them got their own license (which another story). Blokada entire list of lists maybe you mean as GPLed?

**Comment by ignoramous** [comment]
> As far I understand, those 5 each not owned nor maintained by Blokada. 

The links you're pointing to are of blocklists parsed and then re-generated by blokada with the entries from their own _whitelists_ (_allowlist_) removed from the final blocklist output.

> Blokada entire list of lists maybe you mean as GPLed?

From what little I know, GPLs do not make sense ([may even be unenforceable](https://github.com/bongochong/CombinedPrivacyBlockLists/issues/14)) for documents (like blocklists), but blokada does GPL them.

**Comment by ignoramous** [comment]
There's no clarity on the license Blokada uses for those blocklists: https://github.com/blokadaorg/landing-github-pages/blob/master/blocklists/exodusprivacy/standard/hosts.txt

The repository also is void of any license file: https://github.com/blokadaorg/landing-github-pages

I don't think we could use those in our FOSS project. You may want to engage with them to see if they are sport to adding an appropriate license for those lists. Thanks.
