### ISSUE TITLE
Shortcut for logs pages

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#454]
A user says

> Thanks for the replies. Well, I prefer blocking any app not in foreground.  When testing new apps with my configuration, it's just too many clicks to go check log files. For example, it took a bit of digging to figure out the 'social media' list was blocking Discord from connecting. I thought a simple widget of a running log to see blocked connections would be great. Or at least a shortcut to access logs quickly?

> Not sure that would be most efficient... but sure. Or how about, a one-click to access logs from Rethink's persistent notification dropdown options?  Stop -- Pause -- Logs?

> I would say a link to just FW logs is best for less clutter.

**Comment by hussainmohd-a** [comment]
Beginning with v053m, the chip on the Home screen may now be used to reach the logs screen.
Additionally, some app statistics have been added, allowing users to access the logs screen with an IP address or domain filter.

**Comment by ignoramous** [comment]
We could show a "Logs" button in the notifications that takes users to firewall logs or dns logs (in case the app's in DNS-only mode).

**Comment by ignoramous** [comment]
> We could show a "Logs" button in the notifications that takes users to firewall logs or dns logs (in case the app's in DNS-only mode).

Husain is of the opinion that "logs" isn't really an "action" to show as part of the persistent notification. So, for the sake of consistency (only showing "actionable" buttons), this is a no-go. The other changes are in, though, where "dns logs" and "network logs" chips are now shown prominently on the homescreen. There's a "Stats" UI accessible from the homescreen how too that's more digestible than a real-time running log of (internet) *connections* or (dns) *queries*:  https://github.com/celzero/rethink-app/issues/98#issuecomment-1380377147
