### ISSUE TITLE
WebView state lost after device rotation

### ISSUE THREAD

**Issue by mmc20520** [celzero/rethink-app#455]
Click "Enable RethinkDNS+" and tick some settings. But all the state will get lost after rotating screen

Before rotation:
<img width="290" alt="Screen Shot 2022-03-04 at 6 40 46 PM" src="https://user-images.githubusercontent.com/100833575/156748894-5dc71ea4-deab-4441-a3f3-a23d9b2f8654.png">

After rotation:
<img width="283" alt="Screen Shot 2022-03-04 at 6 41 00 PM" src="https://user-images.githubusercontent.com/100833575/156748912-7366ca17-0826-4669-ba7c-61dea42ae84d.png">

I was testing on v0.5.3h on Android 10

**Comment by ignoramous** [comment]
Thanks for the bug. Just a note: WebView is going away in the next version due in a month...

**Comment by ignoramous** [comment]
webview is a goner: https://github.com/celzero/rethink-app/pull/380

releasing with `v053i`.
