### ISSUE TITLE
Custom OTA Channel

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#46]
When the app is downloaded from the website, it should then be okay to update the app by checking with the server periodically.

For a variation of this refer: [Gedsh/InviZible/pan/alexander/tordnscrypt/update/UpdateService.java](https://github.com/Gedsh/InviZible/blob/63e8eea20c12debc0ac0e5d3036830fa7e22294f/tordnscrypt/src/main/java/pan/alexander/tordnscrypt/update/UpdateService.java) (GPL v3).

**Comment by ignoramous** [comment]
See also: #47

**Comment by ignoramous** [comment]
Violates Google PlayStore policies: [googleplay/android-developer/answer/9888379](https://support.google.com/googleplay/android-developer/answer/9888379/).

**Comment by k4n30** [comment]
Have you considered releasing through f-droid.org ?

**Comment by ignoramous** [comment]
> Have you considered releasing through f-droid.org ?

@k4n30 Yes, but haven't gotten around to figuring out how, yet.

**Comment by ignoramous** [comment]
Implemented in v052. If an update is available the user is either directed to the PlayStore (if the app was downloaded from there), if not, the user is taken to the website).
