### ISSUE TITLE
Button to stop on device block lists downloading/updating, or allow editing during the process

### ISSUE THREAD

**Issue by PeterDaveHello** [celzero/rethink-app#466]
![Screenshot_20220329-150723831.jpg](https://user-images.githubusercontent.com/3691490/160554553-7e48cbd7-3961-4adb-9d7f-0f2b0e2e6cea.jpg)

Sometimes the on device block list downloading process hangs, maybe the network or the data source is not stable enough, but it makes me unable to do any other change to the list, which is frustrating when you need to disable a list. Don't even know how long I need to wait(maybe another UX issue).

A button to stop the process, or allowing editing during the process may help, what do you think? Thanks.

**Comment by ignoramous** [comment]
This UI no longer exists since `v053i` (Sep 2022).

A *Cancel* button since `v053k` (Oct 2022).

Let us know if it works to your liking, @PeterDaveHello, whenever you get the chance! (:
