### ISSUE TITLE
Issue: always-on disconnected dialog's positive button not working

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#469]
Steps to Reproduce:

Enable always-on for RethinkDns.
Stop RethinkDns. 
Android System will show dialog "Can't connect to always-on VPN"
Click on "Open App"

Expected: This should open RethinkDns app. 
Result: Toast showing can't open RethinkDns.

**Comment by hussainmohd-a** [comment]
In some cases, the intent used to register the VPN service does not open the application (from Android settings). This happens in some of the Android versions. 

`VpnService.prepare()` is now registered with `requireContext()` instead of `context`.

**Comment by ignoramous** [comment]
Dup? #427
