### ISSUE TITLE
RethinkDNS | Wrong Country Flags in Network Log

### ISSUE THREAD

**Issue by salmanaligeek** [celzero/rethink-app#470]
Hi,

I don't know how you fetch country flags of IPs or which Geo IP database you use, most of the time country flags are correct but sometimes they are not. For example, **216.58.220.106** located in Japan but Indian flag is shown in your app, take a look at the screenshot. You can also verify that **216.58.220.106** is located in Japan here https://ipinfo.io/216.58.220.106

![Screenshot_20220508-110746](https://user-images.githubusercontent.com/5575504/167284520-c09f67ce-d9a9-4d33-b1c0-77c6396879cf.png)

**Comment by ignoramous** [comment]
Yeah, we get our geo-ip data from free-to-use dumps by `db-ip.com`. Not accurate at all. That said, we haven't updated the dump in a year or so. Leaving this task open to track that. Thanks for the bug report, btw (:

**Comment by salmanaligeek** [comment]
Waiting for you to use latest DB

**Comment by ignoramous** [comment]
We've implemented to syncing DB from our servers... but some users may not like that (and indeed, it is one other thing for us to maintain), but the server-side work is done. App-side work pending.

**Comment by ignoramous** [comment]
Please track progress at #222
