### ISSUE TITLE
Make proxy selectively applicable to apps.

### ISSUE THREAD

**Issue by tzugen** [celzero/rethink-app#476]
There are numerous texts advising against routing all traffic indiscriminately through Tor.
I would like to be able to apply the Tor proxy to specific but not all Apps.

**Comment by ignoramous** [comment]
per-app proxy (and per-app DNS #270) is a work-in-progress, yes! Expect it to release with `v055` (2 months, may be 3?).

**Comment by ignoramous** [comment]
Please track progress here: #229 (thanks).
