### ISSUE TITLE
"Why is [insert domain here] blocked" tool

### ISSUE THREAD

**Issue by inspector71** [celzero/rethink-app#481]
I see the logs confirming a domain is blocked. I have to dig into the app to find it though which is non-ideal.

What I do not see is why.

If I do not have any blocklists enabled, why would a site like `news.ycombinator.com` be blocked?

Could the log be adjusted to answer why, instead of just stating the block happened?

**Comment by ignoramous** [comment]
<detail>
<summary>here is the screenshot</summary>
https://user-images.githubusercontent.com/852289/179747712-d9df75d4-1027-4f9c-8582-b92efba1280f.jpg
</detail>

**Comment by ignoramous** [comment]
> Well, it may be that I'm not using local blocklists but I do not get that 'chip' at all. It's just a blank space there.

You should be shown that chip with RethinkDNS+. If you aren't it is likely a bug you're hitting (we fixed a related bunch of bugs just recently; release due soon-ish)...

**Comment by ignoramous** [comment]
`v053i` was released today ([website link](https://rethinkdns.com/download)) (expect it to roll-out via Play Store and F-Droid in the next 5 days), which fixes some 2+ bugs related to "showing RethinkDNS-enabled blocklists that blocked a domain". Re-open if that's not the case.
