### ISSUE TITLE
[Suggestion] SOCKS5 Proxy option should remember App/Hostname/Port

### ISSUE THREAD

**Issue by MasterKia** [celzero/rethink-app#484]
Hi, this is a brief suggestion.
Let's say I go to settings and enable "Setup SOCKS5 Proxy" and select the app/port.
Then if after I'm done, I disable the "SOCKS5 Proxy" option, the next time I'd have to reselect the app/port.
Can RethinkDNS save the app and the port somewhere so that I don't have to enter it everytime?

**Comment by ignoramous** [comment]
Makes sense.

The UI around proxies is changing ... One would be able to add, save, and connect to multiple SOCKS5 proxies at once.

**Comment by MasterKia** [comment]
Thank you for the explanation @ignoramous.

On that note, can RethinkDNS detect when the local SOCKS (i.g. V2RayNG) is active/enabled so that it only routes traffic through it when it's enabled?

So this way I don't have to keep toggling the SOCKS5 option in RethinkDNS when I enable/disable the local SOCKS app (V2Ray).

**Comment by MasterKia** [comment]
It seems to have been fixed without any update.
Maybe a bug on my side?

**Comment by MasterKia** [comment]
> cosmic rays flipping the bits

^^^
This xD



> Thanks for reporting back!

Thank you for creating and maintaining this awesome application.

**Comment by MasterKia** [comment]
Btw, may I ask did Mozilla explicitly told you to choose the MPL license or was it your choice?

**Comment by ignoramous** [comment]
Mozilla didn't ask anything. They only provided immense *help* for the plans we already had. That's about it.

As for Apache, we inherited it from Intra and chose to keep it, since I like what the Apache License stands for:
