### ISSUE TITLE
Firewall lockdown mode

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#486]
New app-specific firewall setting, `Lockdown`: An app can only connect to IPs that are in the allowlist / whitelist.

**Comment by ignoramous** [comment]
Or may be, this *network lockdown* mode could be a universal firewall setting, instead? Easier to reason about.

**Comment by hussainmohd-a** [comment]
App specific lockdown mode, where user can block all the traffic other than the IPs added as part of bypass app rules. 

Also introduced global lockdown mode, where all the apps other than bypass universal (previously whitelist) will be blocked. 

Commit: 03aee5b4609dc2ffa4394d569741390ccbb2a72d
