### ISSUE TITLE
Notification icon is black

### ISSUE THREAD

**Issue by mxmilkiib** [celzero/rethink-app#487]
Which is not that user friendly. Have checked the settings and tried all themes. Couldn't see an existing issue.

![Screenshot_20220720-221332_Firefox](https://user-images.githubusercontent.com/108225/180083454-7bee8b59-18f5-4de1-89a6-9a58969e1906.png)
![Screenshot_20220720-221350_Nova7](https://user-images.githubusercontent.com/108225/180083459-678f6f74-709b-47df-958a-a11d0ad2e8a0.png)

**Comment by mxmilkiib** [comment]
I'd guess an invert colours filter action in Inkscape could be enough?

**Comment by ignoramous** [comment]
Invert colours invert the background (which is white) to black. I guess, what we need is only for the shield and the word "dns" to be colour-inverted?

**Comment by ignoramous** [comment]
Good folks at privacyguides.org have one for us, but need to confirm if they're okay if we use our logo with their edits: https://www.privacyguides.org/assets/img/android/rethinkdns-dark.svg

**Comment by ignoramous** [comment]
@hussainmohd-a tells me we have since fixed this in [`v053i`](https://github.com/celzero/rethink-app/releases/tag/v0.5.3i). Which version are you on, @mxmilkiib?

**Comment by ignoramous** [comment]
Closing since all indications are we have since fixed this behaviour in `v053i`+

Please, don't hesitate to reopen this issue, in case you think it was closed in error. Thanks.

**Comment by ignoramous** [comment]
It isn't black on my A12 OxygenOS device. What Android ROM do you use?

**Comment by ignoramous** [comment]
Resolving...
