### ISSUE TITLE
Notification height

### ISSUE THREAD

**Issue by mxmilkiib** [celzero/rethink-app#488]
I have the notification in my silent notifications area, but it's still the full height, rather than the more compact format that is available, as with the Quasseldroid or Hue Essentials apps ([demo](https://youtube.com/shorts/6n40oBAYrvI)).

Could the narrower format be a possibility?

**Comment by ignoramous** [comment]
I don't see why not. cc: @hussainmohd-a

**Comment by ignoramous** [comment]
Okay, it seems like removing both title and text make the notification a one-liner, but it isn't quite the one-liner in the demo video you shared (which really is a notification with `importance_min` flag set). Android doesn't allow *foreground services* (like VPNs) to use that flag. Ref: https://stackoverflow.com/questions/50676819

**Comment by ignoramous** [comment]
As noted above, when one sets `Choose Notification Action` to `None` (from the app's *Settings* page), you'd see only the title (and no action buttons nor sub-labels and sub-texts).

That's the best that a VPN app can do, given restrictions imposed by Android on the priority of 'foreground service' notifications.
