### ISSUE TITLE
Why there are no new releases?

### ISSUE THREAD

**Issue by sanatg** [celzero/rethink-app#489]
Hi, 
I noticed something the code is being updated regularly but there aren't any new releases from past almost 1 year.since I don't know how to compile the application and really like this app I was curious about it.

**Comment by ignoramous** [comment]
There's one now `v053i`, see: [rethinkdns.com/download](https://rethinkdns.com/download).

Should show up on Google PlayStore and F-Droid in another 5 to 7 working days. GitHub release in a few hours. The lead developer forgot to do so.

Let me know if you have anymore questions. Feel free to re-open this bug in case your query was misunderstood.

**Comment by ignoramous** [comment]
Compiling the app is straight-forward btw. One way to do this:

1. Clone this github repository to your PC.
2. Open the cloned repository in Android Studio (install if you don't have it already).
3. Connect your Android (with *Developer Options* enabled) to the PC.
4. Click the Play button (this should install the latest and buggiest RethinkDNS app on your Android).
