### ISSUE TITLE
DNS forwarding option

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [celzero/rethink-app#492]
Enabled:

- Block all UDP traffic except DNS and NTP
- Prevent DNS leaks (forward to user-set DNS endpoint)

Result:

- blocked on UDP/53 UDP blocked
 A user-set firewall rule blocked this UDP connection.

Expected Result:
forward to user-set DNS endpoint

[v0.5.3i](https://github.com/celzero/rethink-app/releases/tag/v0.5.3i)

**Comment by ignoramous** [comment]
Ah, nice edge-case! Rethink should allow DNS traffic proxied to user-set endpoint... Thanks. Assigning to Husain for him to take a look.

**Comment by ignoramous** [comment]
Fixed in https://github.com/celzero/rethink-app/pull/525

Releasing by this week's end.

Btw, v053i also broke Orbot / SOCKS5 forwarding (#456)... which has also been fixed in #525

**Comment by ignoramous** [comment]
Btw, thanks a tonne for your bug report(s)! Appreciate it (:

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
After upgrading to  v053k 

- #573 

I unfortunate see the described issue of blocking instead of force forwarding to use set endpoint again.

![IMG](https://user-images.githubusercontent.com/46166740/199313556-bfc70a1d-8f40-40a8-906c-e2fc8c26cf8b.jpg)
![IMG](https://user-images.githubusercontent.com/46166740/199313565-a639a7c9-a26f-4e07-9d70-c65103ea9918.jpg)
![IMG](https://user-images.githubusercontent.com/46166740/199313574-a9dcee2c-5c44-4b5b-aadb-9e07fdf51aab.jpg)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
After upgrading to  v053k 

- #573 

I unfortunate see the described issue of blocking instead of force forwarding to use set endpoint again.

![IMG](https://user-images.githubusercontent.com/46166740/199313556-bfc70a1d-8f40-40a8-906c-e2fc8c26cf8b.jpg)
![IMG](https://user-images.githubusercontent.com/46166740/199313565-a639a7c9-a26f-4e07-9d70-c65103ea9918.jpg)
![IMG](https://user-images.githubusercontent.com/46166740/199313574-a9dcee2c-5c44-4b5b-aadb-9e07fdf51aab.jpg)

**Comment by ignoramous** [comment]
https://github.com/celzero/rethink-app/blob/76f1091e398e7feda40cebe710958ea5b4b2b616/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L386-L397

Yeah, we changed the behaviour because some folks thought the firewall was leaky when `8.8.8.8` on `53` was let through despite being in their block rules.

I am still thinking what's the best way to communicate that if DNS is proxied, then it isn't a leak... May be we should change the IP address shown in the network log.
