### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [celzero/rethink-app#493]
```
e: /builds/linsui/fdroiddata/build/com.celzero.bravedns/app/src/main/java/com/celzero/bravedns/ui/DNSDetailActivity.kt: (33, 7): Redeclaration: DnsDetailActivity
e: /builds/linsui/fdroiddata/build/com.celzero.bravedns/app/src/main/java/com/celzero/bravedns/ui/DNSListActivity.kt: (33, 7): Redeclaration: DnsListActivity
e: /builds/linsui/fdroiddata/build/com.celzero.bravedns/app/src/main/java/com/celzero/bravedns/ui/DnsDetailActivity.kt: (33, 7): Redeclaration: DnsDetailActivity
e: /builds/linsui/fdroiddata/build/com.celzero.bravedns/app/src/main/java/com/celzero/bravedns/ui/DnsListActivity.kt: (33, 7): Redeclaration: DnsListActivity
```

Could you please take a look? Thanks!

**Comment by ignoramous** [comment]
Can you please link to the logs?

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/2769773564

**Comment by ignoramous** [comment]
Interestingly, `DNSListActivity` and `DNSDetailActivity` don't show up on GitHub Desktop (which the lead dev uses). Now that I removed those files (https://github.com/celzero/rethink-app/commit/7a8f95899860e95559bf8f6769b9cd336fd5f856), `DnsListActivity` and `DnsDetailActivity` don't show up anymore... Something funky is going on.

**Comment by ignoramous** [comment]
@linsui Should we create a new tag, now (and a new version-code for the app)? Or, can we move the delete and recreate the existing tag to the new commit?

**Comment by linsui** [comment]
Both are OK. I can just use the latest commit.

**Comment by ignoramous** [comment]
> I can just use the latest commit.

Well, that's okay for us as well. Can you please see if the latest commit builds for F-Droid? Thanks.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11439 It builds fine, thanks!

**Comment by ignoramous** [comment]
No why, thank you!

**Comment by ignoramous** [comment]
The next time we tag our release on GitHub, F-Droid wouldn't pick it up though, right?

**Comment by linsui** [comment]
As long as you bump the version code, it will be picked up.
