### ISSUE TITLE
Ability to manually update local blocklists seemingly gone from v0.5.3i release

### ISSUE THREAD

**Issue by afontenot** [celzero/rethink-app#505]
The interface changed quite a bit with this new version and so it's possible that I'm missing something, in which case this should probably be treated as a request for improving the documentation or making the UX less confusing.

Prior to this release, there was a way to force an update of the on-device blocklists. This sometimes failed, which is a bug that I think was fixed. With this release, if this ability exists, I can't find it.

There was a button to check for updates that I found, and now it says "Update available", but clicking it does nothing. Clicking "Apply" also does nothing.

![Screenshot_20220728-205552_RethinkDNS](https://user-images.githubusercontent.com/3870410/181680108-c7fc2106-4357-4db5-bbf4-a7e378c05c5b.png)

**Comment by ignoramous** [comment]
Thanks. Agree that the blocklist update UX needs a redo.

That said, tapping "update available" should update the blocklists or prompt to let you re-download them. May be there's a bug that nothing happens at all when you tap on it...

**Comment by afontenot** [comment]
> That said, tapping "update available" should update the blocklists or prompt to let you re-download them. May be there's a bug that nothing happens at all when you tap on it...

Definitely nothing is happening when I click it. I can tell that the button is activating (it changes color slightly when you press it), but nothing changes after that.

**Comment by hussainmohd-a** [comment]
> 

Found and fixed the issue, will be part of next release.

**Comment by hussainmohd-a** [comment]
> > That said, tapping "update available" should update the blocklists or prompt to let you re-download them. May be there's a bug that nothing happens at all when you tap on it...
> 
> Definitely nothing is happening when I click it. I can tell that the button is activating (it changes color slightly when you press it), but nothing changes after that.

Found and fixed the issue, will be part of next release.

**Comment by afontenot** [comment]
@hussainmohd-a can you link the fixing commit? I wouldn't mind trying to build it to get the fix ahead of the next release.

**Comment by afontenot** [comment]
@hussainmohd-a friendly ping

**Comment by ignoramous** [comment]
The fix is likely in Husain's dev branch. I don't see a pull request or a commit yet: https://github.com/hussainmohd-a/rethink-app/tree/v054

**Comment by hussainmohd-a** [comment]
Yes, there are some additional UI changes added with the commit. Will finish those and create a pull request.

**Comment by ignoramous** [comment]
A user says,

> Hi, would it be possible to auto update the on-device blacklists? 

> The current behaviour isn't satisfactory. Most people simply won't bother to check for updates and the most important problem, for those who do, it is actually very hard (impossible?) to update them manually. 

auto updates...?

**Comment by ignoramous** [comment]
A user writes,

> [This issue] fixed as expected with the new version but the flow is now quite strange and probably buggy. There's now a "check for updates" option in the menu, but if you leave it open while an update completes the text doesn't change as expected - it continues to say "check for updates". And then after you leave the menu and come back it now says "redownload blocklists" instead of "check for updates".
>
> As far as I can tell it continues saying this indefinitely. That's confusing as presumably when I visit the menu after several days the reason is that I want to check for updates again, not redownload the blocklists.

**Comment by afontenot** [comment]
> A user writes,
> 
> > [This issue] fixed as expected with the new version but the flow is now quite strange and probably buggy. There's now a "check for updates" option in the menu, but if you leave it open while an update completes the text doesn't change as expected - it continues to say "check for updates". And then after you leave the menu and come back it now says "redownload blocklists" instead of "check for updates".
> > As far as I can tell it continues saying this indefinitely. That's confusing as presumably when I visit the menu after several days the reason is that I want to check for updates again, not redownload the blocklists.

This was my email. Just want to clarify that I currently can't reproduce this issue. I believe the problem initially appeared with a fresh install from F-droid, but after having used the (reinstalled) app for a few days it now seems to show the intuitive behavior.

**Comment by ignoramous** [comment]
Thanks for circling back. Though, we are changing the way "Check for updates" button works to make it less confusing. Let's see.

**Comment by afontenot** [comment]
Okay I actually can reproduce this, but only with a fresh install. Repro:

1. Install the app from F-droid.
2. Skip the intro, go immediately to the down arrow and change mode to "DNS".
3. Click "start" and accept the various VPN prompts.
4. Go to "on-device blocklists" and click the toggle that says "disabled". Click "download blocklists" on the fullscreen modal that appears. Wait for download to complete.
5. Check the box on the "aggressive" privacy filter family on the window that appears. Click apply.

This kicks you back to the "configure" screen. This actually reveals **two** bugs. 

First, you'll see that the rules section still says "0 blocklists in-use" despite the fact that we just enabled a bunch of blocklists. To actually get the blocklists functional, you have to go back into the menu again and check the blocklists you want a second time. (Let me know if you'd like me to file another issue for this bug.)

Second, if you click the down arrow on the blocklist menu again, you'll see that the "check for updates" text now just says "redownload blocklists". It'll stay stuck like this until the app is fully restarted (not just the activity closed, you have to kill it or reboot the device).

**Comment by ignoramous** [comment]
> First, you'll see that the rules section still says "0 blocklists in-use" despite the fact that we just enabled a bunch of blocklists. 

Thanks. Nasty, yes. I noticed this when chasing the memory leak. Hussain's fixing this in `v053k` (though, not sure yet why this happens).

> Second, if you click the down arrow on the blocklist menu again, you'll see that the "check for updates" text now just says "redownload blocklists". It'll stay stuck like this until the app is fully restarted (not just the activity closed, you have to kill it or reboot the device).

Thanks. This part of the code is needlessly complicated. Hussain's going to simplify both the UI flow and the business logic in `v053k`.

**Comment by ignoramous** [comment]
Fixed a bunch in `v053k` ([download from the website](https://rethinkdns.com/download); Play and F-droid flavours by next week once reviews are complete). Please re-open incase the workaround / fixes aren't satisfactory.
