### ISSUE TITLE
Add wildcard url support

### ISSUE THREAD

**Issue by HarshilPatel007** [celzero/rethink-app#507]
This is yet another awesome ad-blocker/privacy guard tool,
I'm using `dns66` which works fine until I saw a ads using same domain with different (random) sub domain names.
Ex: ``` askghtf-238f0-bkskhf.website.com,
tkrdfhzh-2382g-dhxie.website.com,
djdjeigbk-4853h-shcjc.website.com... ```

this list goes on and on.....
I'm tired now to add new domains to my block list each and every day. (Actually each hours)

I wish I could do something like this,

`*.website.com` bammm... GameOver.

**Comment by ignoramous** [comment]
Yes, functionality tracked at: #18 

NB: RDNS already supports doing so for IP addresses
