### ISSUE TITLE
Some traffic not detected by app's firewall

### ISSUE THREAD

**Issue by sm18lr88** [celzero/rethink-app#517]
App: RethinkDNS 0.53i
Device: Pixel 6
OS: Android 12, build #SQ3A.220705.004

Issue: I blocked Audible in both Wifi and Cell on the firewall, and have no other Amazon apps installed. 
When I open Audible to listen to pre-downloaded files, RethinkDNS's firewall shows blocked Audible requests, but upon checking my NextDNS log, I still see the connections to Amazon.

No other app is reportedly sending requests for Amazon related servers.

I have found Amazon apps to be the sneakiest among all apps on Android.

Let me know how I can improve the wording here, as I'm obviously not a programmer.

**Comment by ignoramous** [comment]
DNS requests are not firewalled per-app. Only TCP/UDP requests are. Per-app DNS blocking is not possible on Android unless #270 is implemented. The newer network engine (part of the v053i release) supports per-app DNS, but it isn't yet exposed via the UI.

What you're seeing are DNS requests being allowed (ones appearing in *DNS Logs*), but TCP/UDP requests must be firewalled (ones appearing in *Network Logs*).

**Comment by hussainmohd-a** [comment]
Issue #517 is wrongly added in the commit message instead of #527.
