### ISSUE TITLE
Integrate Wireguard

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#52]
Blokada integrates with Cloudflare's BoringTun and that looks pretty straight-forward.

Wireguard's official cross-platform implementation is in golang (being rewritten in Rust?) and so the integration could be relatively simpler than with BoringTun.

The traffic would probably go from app -> vpn-tun -> tun2socks -> wireguard. Wasteful?

May be, the entire firewall and DoH implementation can be moved into wireguard instead?

See also: #45 and #37

**Comment by ignoramous** [comment]
WireGuard userspace proxy impl ref: https://github.com/database64128/swgp-go

**Comment by ignoramous** [comment]
> SagerNet/Matsuri's SOCKS5 for Wireguard doesn't work correctly in combination with Rethink's SOCKS5 in latest version

Thanks for the bug report.

Strange. I haven't tested it myself, but I'd think it works because SOCKS5 is a very non-intrusive way to proxy sockets (even if UDP support is tricky)... It could be the SOCKS5 library we use that has broken UDP support, I haven't checked.

Re: WireGuard integration: We're stuck with releasing v054 first (WireGuard is v055) which is taking forever to get out the door (1.5 years and counting!) as something or the other gets in the way.

**Comment by ignoramous** [comment]
> So I think there's a problem with the handling of DNS response?

Yes, most likely (or, DNS querying is blocked, check the DNS logs in Rethink). And the reason Telegram works is it doesn't use DNS, and hits IPs directly (like you did when you hit `1.1.1.1` from a web browser).

> There's only an option to add DoH/DnsCrypt.

Other DNS -> Swipe to the third Tab, *Dns Proxy*. You'd forward it to whatever port Matsuri is listening on (if it is). Orbot does (the default port it uses is `5400`).

**Comment by ignoramous** [comment]
Just saw the screenshots you shared, the port Matsuri is listening DNS for is `6450` (3rd screenshot).

Btw, Matsuri is set to use `8.8.8.8` over DoH as upstream which is likely blocked in Iran (screenshot 1).

**Comment by ignoramous** [comment]
WireGuard integration is a go. Only UI work pending. To Hussain.

**Comment by ignoramous** [comment]
UI work is done. Rudimentary testing has come out good.

DNS won't work; ICMP won't work. The effort required is too high, unfortunately.

Split-tunnelling (multiple WireGuard upstreams) has been implemented, as well.

Next stop: Release.

**Comment by iulko** [comment]
By DNS and ICMP not working, you mean that you cant reach DNS servers inside wireguard tunnel? Please be more specific.

Thanks for hard work on implementation

**Comment by ignoramous** [comment]
> By DNS and ICMP not working, you mean that you cant reach DNS servers inside wireguard tunnel? Please be more specific.

Sorry, I can see how that can be confusing. To be clear, ICMP and DNS won't be tunneled sent to WireGuard upstreams. DNS queries will be resolved by the DoH / DNSCrypt server setup in the app, and ICMP (echo) would be sent to the local network (rest dropped).

**Comment by iulko** [comment]
any ETA?

**Comment by michaelblyons** [comment]
> any ETA?

This is not exactly an answer, but you can follow #903.

**Comment by ignoramous** [comment]
After a 1000 days, this finally [shipped yesterday](https://github.com/celzero/rethink-app/releases/tag/v0.5.5).

**Comment by iulko** [comment]
> After a 1000 days, this finally [shipped yesterday](https://github.com/celzero/rethink-app/releases/tag/v0.5.5).

Guys, thank you very much, this is the only complete firewall on android right now!

**Comment by outusuke** [comment]
Ipv6 doesn't work with wireguard tunnel

**Comment by ignoramous** [comment]
As in, IPv6 configuration is rejected (as in, unable to add such configurations), or the tunnel is unable to connect (seeing the "failing" status instead of "connected" for that WireGuard interface), or unable to even switch ON that WireGuard interface?

Can you please report more here? https://github.com/celzero/rethink-app/issues/1002

Thanks.

**Comment by ignoramous** [comment]
Tailscale: https://github.com/celzero/rethink-app/issues/1047 perhaps in 1000 days hence ;)
