### ISSUE TITLE
Bulk app firewall actions 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#524]
A user says,

> Maybe it could be accompanied with an additional "apply settings" button. I clearly understand risks. NetGuard has a policy setting, which allow block all by default. Maybe it's possible it implement a button which only would allow blocking all, not unblocking

Users want to apply block/allow/bypass/exclude with one tap across multiple apps. We removed this ability in v053i because it affected other rules in ways users may find it confusing to reason about, but well, another warning dialog can't hurt? Surely not: https://twitter.com/apenwarr/status/1549200959980683269

**Comment by puelp** [comment]
It's disappointing to hear that a firewall app that touts privacy and security as its foremost feature remove the ability to bulk-block apps from accessing the Internet.

I just installed RethinkDNS on a fresh install, and is there really no other way but to sit here and scroll and tap like a mindless robot for an hour to block all apps from Internet access?

The only solution that I could find was to install 053h, with which it took me 30 seconds to revoke all apps' Internet access.

Please reconsider the decision to remove this vital and time-saving functionality!

Thank you.

**Comment by puelp** [comment]
Maybe a one-time 'Block all apps on system' button would suffice? It would be accompanied by a warning dialog with 'Cancel' and 'OK' options, of course.

**Comment by ignoramous** [comment]
Sounds like you're ready to code it up and send a pull request? (:

**Comment by hussainmohd-a** [comment]
Introduced bulk action (allow/block) in Apps screen where users can now allow or block apps for the filtered list of apps. https://github.com/celzero/rethink-app/pull/573/commits/6dddc2c44c75563b044f4ff3a76b9d447b0711c8

**Comment by ignoramous** [comment]
Released in `v053k` ([downloadable from the website](https://rethinkdns.com/download), playstore and f-droid perhaps complete their reviews by next week).

**Comment by ignoramous** [comment]
Someone even left a 1🌟 rating on the Play Store for us not impl this soon enough (: I hope they're happy now.
