### ISSUE TITLE
Split APK

### ISSUE THREAD

**Issue by chromer030** [celzero/rethink-app#526]
Hi , Thank you for the app , it's great.

It would be great if released apks be split to every architecture separately. ( arm-v8 , armv7 , x86 ).
It would have much smaller size than 50 MiB.
Useful for both Google Play and downloading from GitHub.

Thanks.

**Comment by ignoramous** [comment]
Dip #47?

**Comment by ignoramous** [comment]
Closing as dup #47 

Please feel free to reopen if you think this issue was closed in error.

btw, thanks for showing your appreciation and also for taking time to report/suggest this issue/feature (:
