### ISSUE TITLE
When paused, excluded apps should remain excluded

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#527]
In *paused* state, only blocked apps are to be *included* in the VPN (firewall) while all others must be *excluded*. But, in `v053i`, explicitly *excluded* apps aren't *excluded* from the VPN (firewall) when they should be.

1. Add any app to the *exclude* list.
2. *Pause* the VPN (firewall).
3. Notice the *excluded* app is *included* in the VPN (firewall).

**Comment by hussainmohd-a** [comment]
Fixed as part of https://github.com/celzero/rethink-app/pull/573/commits/8ef188b3075b019abff89aaad68e134d58185b46
