### ISSUE TITLE
Hotspot vs. unknown source software

### ISSUE THREAD

**Issue by Agych** [celzero/rethink-app#528]
Situation:
2 devices, one with /e/ OS and RDNS sharing internet via hotspot and the hotspot is using the RDNS' VPN, and another one is any device using the hotspot.
The hotspot's traffic is detected as unknown source according to the RDNS' logs, and when the "unknown source software" firewall parameter is enabled, the second device cannot open anything as all the requests are blocked.
One solution could be ofc to keep "unknown source software" always disabled, but I find it to be a degraded security, as blocking unknown source stuff is a good idea.
Why is the hotspot traffic detected as "unknown source" in RDNS firewall? Is there any way to solve this situation?

**Comment by ignoramous** [comment]
>  The hotspot's traffic is detected as unknown source according to the RDNS' logs, and when the "unknown source software" firewall parameter is enabled, the second device cannot open anything as all the requests are blocked.

Hotspot (tethered) traffic shouldn't pass through the VPN. Is this something specific to e/OS? On a rooted device, one would use an app like [Mygod's VPNHotspot](https://github.com/Mygod/VPNHotspot/) to redirect Hotspot traffic via the on-device VPN.

**Comment by ignoramous** [comment]
>  Why is the hotspot traffic detected as "unknown source" in RDNS firewall? Is there any way to solve this situation?

We'd need /e/OS to expose an API (probably) to help distinguish traffic coming from Hotspot (or at least, assign the owner of the traffic to the system uid `0`). I don't think as an app, there's anything rdns can do to make that distinction on its own.

**Comment by ignoramous** [comment]
There isn't any action item for us here, unless /e/ proposes a solution that we could implement (more than happy to!). Let us know what engs at /e/ say, if you get around to asking them.
