### ISSUE TITLE
Rethink uses 50+ MB data per day

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#530]
Investigate what's the cause of high data-use, and either document it (warn user before they turn ON such a feature) or nip it (remove the feature).

The suspect feature is favicons (#105), caching for which *may not* quite be working as expected, resulting in high data use? Ex A: 5K (DNS reqs per day) * 10K (favico avg size) => 50M (assuming caching is broken).

**Comment by ignoramous** [comment]
Ref: https://www.reddit.com/r/dns/comments/wr8ay2/my_phone_says_that_rethinkdns_apk_use_40mbday/

**Comment by Lucas559-noob** [comment]
Update: its 600+ MB in a month
![Screenshot_20220827-113107](https://user-images.githubusercontent.com/54007604/187034843-fa55c5e1-5dc8-4d8f-8a0a-d5a3a76690a1.png)

**Comment by ignoramous** [comment]
Thanks.

We've increased the favico cache-size to 350MB (currently set at 30MB). 350MB would be enough to hold 35,000 favico (a month's worth of unique domains my device typically hits) of 10KB size each (favico are usually larger).

**Comment by ignoramous** [comment]
The fix is in `v053j`, released today #525. If the fix doesn't make any difference, please report back. I will keep an eye on it myself, too.
