### ISSUE TITLE
Firewall: Mobile blocking option not working

### ISSUE THREAD

**Issue by Horizonbli** [celzero/rethink-app#532]
Hello,

Can you, please, verify that the firewall option to block mobile connectivity actually works?
I have it enabled, but doesn't seem to work. Apps still connect.

Thanks

**Comment by ignoramous** [comment]
Hi,

It isn't a *mobile* network blocker, but a *metered* network blocker (which most *mobile* networks are, but needn't be the case).

Also, *Use all available networks* setting in the app and *metered*/*unmetered* firewall rules are mutually exclusive. If former is enabled, the latter won't work.

Can you please mention the OEM/ROM, and the apps that bypassed the firewall rule here? I am assuming you check the *Network Logs* after you open the app that must be disallowed on a *metered* network (any typical mobile network), and find that the Logs show the connection from the said app was allowed?

**Comment by ignoramous** [comment]
Please reopen if you think the above explanation wasn't sufficient.
