### ISSUE TITLE
Impossible to understand how to change DNS servers

### ISSUE THREAD

**Issue by Shituation** [celzero/rethink-app#545]
The app documentation refers only to [this link ](https://rethinkdns.com/configure)without giving any steps or tutorial on how to input a custom DNS server. 
For instance I would want to use some dnscrypt servers and there is no way to configure them

Users are taken to this webpage without any more info:

![image](https://user-images.githubusercontent.com/43975882/189714071-50d7b86e-79d8-4494-a504-adfcf8f45dfd.png)

These seems to be lists to block ads or annoyances, not DNS configuration, despite saying this on the documentation:
![image](https://user-images.githubusercontent.com/43975882/189714554-3c077f39-9be5-43cf-9da8-01620bc0d08c.png)

Or is it that "custom" really means: "our servers, your options on them" ? If that's the case, I would really recommend being explicit with this, instead of saying "configure custom dns servers" say "configure our dns servers" since its a very important feature for some of us.

**Comment by Shituation** [comment]
I'm completely puzzled here. [Link ](https://docs.rethinkdns.com/dns) under "Configure blocklists on the Companion Firewall App"

Step 3 is not like that. Tapping on the DNS button only shows a popup saying "**private dns has been set**"
![image](https://user-images.githubusercontent.com/43975882/189716413-16e16815-4bdc-4d37-9c93-a4beb86e6e31.png)

Is there something wrong with the guide? version? me?

**Comment by ignoramous** [comment]
Hi, click on the "+" (floating) button (at the bottom of the *Other DNS* pager) to add servers.

<details>
<summary>screenshots</summary>
Tap on the "DNS" card on the homescreen, and then:

![Screenshot_2022-09-13-05-01-32-81_c8cbde12d3521911922be4eee6a05664~3](https://user-images.githubusercontent.com/852289/189776255-094031f2-5c16-467c-9f95-bf5a505cb835.jpg)
![Screenshot_2022-09-13-05-01-16-43_c8cbde12d3521911922be4eee6a05664~2](https://user-images.githubusercontent.com/852289/189776269-dc8115ea-7317-47df-a7f5-1ffa4fe122f0.jpg)

</details>

**Comment by ignoramous** [comment]
> Step 3 is not like that. Tapping on the DNS button only shows a popup saying "private dns has been set". The only other button saying something about "DNS" are the logs.

*Private DNS* is Android's built-in DNS-over-TLS. If you're using it, you cannot Rethink's DNS changer alongside it (as *Private DNS* overrides all DNS configuration and render it useless). See: https://archive.is/lVMkZ

**Comment by Shituation** [comment]
Hi There, I fixed it
That menu didn't appear at all. I just kept getting "**private dns has been set**"
This happens if you already have configured a dns server on the system. I had to disable it so the app can control the DNS servers, then the menu to change dns inside the app appeared.

**Comment by ignoramous** [comment]
Thanks for the detailed report, btw, appreciate it.

The docs are not thorough as they could be, so you're right about that.

[Feel free to ask if you have anymore queries, all ears](https://github.com/celzero/rethink-app/discussions) (:
