### ISSUE TITLE
A setting to enable a reversed, 'Block all by default, allow-only' system

### ISSUE THREAD

**Issue by puelp** [celzero/rethink-app#559]
I remember NetGuard offering this feature.

By default, NetGuard works like this app's 053j: all apps are allowed access to the Internet, and it is up to the user to block the apps that they want to block.

But NetGuard also offer a setting that allows the user to reverse this behavior, so that all apps are blocked, and it is up to the user to only allow the apps that they specifically want.

It would be great if this app offered such a feature.

**Comment by puelp** [comment]
System apps would need to be included in this setting, of course.

**Comment by ignoramous** [comment]
> I recall Rethink had an option to achieve that "Block all" goal then you had to manually allow system apps.

Yeah, on Rethink, a close equivalent setting would be `Block apps when not in-use`. This feature still exists. Took an abnormally long time to build it, why would we remove it (it is a bit buggy, though)...

> But NetGuard also offer a setting that allows the user to reverse this behavior, so that all apps are blocked, and it is up to the user to only allow the apps that they specifically want.

Dup #486 (reopen in case you think this bug was closed incorrectly; thanks).

**Comment by ignoramous** [comment]
Thanks for your kind words.

> Is there a chance for getting it added to Rethink? If so, I can open a PR.

Sure, go ahead.

**Comment by ignoramous** [comment]
Re: accessibility service battery drain: Yes it is a bit more drain than usual.

The old UI is not coming back as it was bug ridden.

We are bringing back bulk action #524
