### ISSUE TITLE
User feedback: Choosing custom DNS endpoint from the spinner doesn't bring up editor on occassion

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#56]
If a custom DNS endpoint has been set, the spinner refuses to show the editor when _Custom_ entry in the spinner (drop-down) is selected or clicked-on once again.

This is how spinner works by default but it makes for a very confusing behaviour since to change the custom endpoint, the user has to resort to UI gymnastics:

1. Choose any other entry not named _Custom_ from the spinner.
2. Click on _Custom_ again which then brings up the editor.

Not cool.

**Comment by hussainmohd-a** [comment]
The whole logic of custom DNS is now modified and introduced a new add fab icon to add custom DNS which solved this issue.
