### ISSUE TITLE
Handle "Can't connect to Always-on VPN" dialog

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#566]
If Rethink is an *Always-on VPN*, but crashes; a System UI dialog comes up asking the user to enable the VPN back again.

But, when user taps on *Open app* (or an equivalent action button), nothing happens. I presume this is because Rethink isn't handling some start-up *Intent* or the other appropriately.

<details>
<summary>screen recording</summary>
vid:

https://user-images.githubusercontent.com/852289/191136486-04f22709-ec7a-4915-8644-758281e948d6.mp4
</details>

**Comment by ignoramous** [comment]
Curiously, with `v053j` running on OnePlus devices, the "Can't connect ..." dialog correctly open up the rethink app.

**Comment by afontenot** [comment]
This works as expected for me on a Moto X4, `v053j`.

**Comment by ignoramous** [comment]
Thanks. Now, if only I can get hands on a MIUI device...
