### ISSUE TITLE
PersianBlocker list

### ISSUE THREAD

**Issue by MasterKia** [celzero/rethink-app#569]
https://github.com/celzero/rethink-app/issues/559#issuecomment-1250103510

PersianBlocker is the default list in [uBlock Origin](https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L482) and [AdGuard](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_235_PersianBlocker).

[PersianBlockerHosts](https://github.com/MasterKia/PersianBlocker/blob/main/PersianBlockerHosts.txt) only has ad servers and trackers domains so it's suitable for DNS blockers.

Data for the [filetag.json](https://raw.githubusercontent.com/celzero/rethink-app/main/app/src/main/assets/filetag.json) file (Please fill in the blanks for `name`, `value` and `uname`):
```json
  "???": {"value": 000, "uname": "???", "vname": "PersianBlocker (Hosts)", "group": "privacy", "subg": "", "url": "https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt", "show": 1, "entries": 224}, 
```

**Comment by ignoramous** [comment]
Value is auto-filled.

uname is unused.

vname is `Persian Hosts Blocker (MasterKia)`?

Ref: https://github.com/serverless-dns/blocklists/pull/47/files

Either way, this is not an issue for the app, but for the server at https://github.com/serverless-dns/blocklists :)

**Comment by ignoramous** [comment]
> vname is "PersianBlocker (Hosts)" or "PersianBlockerHosts", I prefer the former.

`Hosts` is redundant (as it denotes the filetype, and Rethink users generally don't have to bother about the filetype)? But, just `PersianBlocker` is also too vague... 

> Oops, I got mislead by the filetag.json file :sweat_smile:

Always a good idea to read the `README`, but as a developer, I feel the urge to simply dive into the code-base and config files ;)
