### ISSUE TITLE
Move out logs into its own db

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#574]
Today, logs (network and dns) are stored in tables in the main database. Since these tables are write-once, perhaps we can move them out of the main db. Doing so simplifies (#165) import / export for one.

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/pull/709/commits/a807accbcefca286e609509712ad4525b76bdabc

**Comment by ignoramous** [comment]
a few backup and restore scenarios need to be addressed here:
- let users backup either or both logs and config dbs.
- while restoring let users restore either or both logs and config dbs.
