### ISSUE TITLE
Chosen blocklists not applied after first download

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#575]
afontenot says,

1. Install the app from F-droid.
2. Skip the intro, go immediately to the down arrow and change mode to "DNS".
3. Click "start" and accept the various VPN prompts.
4. Go to "on-device blocklists" and click the toggle that says "disabled". Click "download blocklists" on the fullscreen modal that appears. Wait for download to complete.
5. Check the box on the "aggressive" privacy filter family on the window that appears. Click apply.

This kicks you back to the "configure" screen. This actually reveals **two** bugs. 

First, you'll see that the rules section still says "0 blocklists in-use" despite the fact that we just enabled a bunch of blocklists. To actually get the blocklists functional, you have to go back into the menu again and check the blocklists you want a second time. (Let me know if you'd like me to file another issue for this bug.)

_Originally posted by @afontenot in https://github.com/celzero/rethink-app/issues/505#issuecomment-1257080391_

**Comment by hussainmohd-a** [comment]
[2b20a8b](https://github.com/celzero/rethink-app/pull/573/commits/2b20a8bbf32d67653fcd5ec3db2fb911fe4a14c2)

**Comment by hussainmohd-a** [comment]
Fixed as part of [2b20a8b](https://github.com/celzero/rethink-app/pull/573/commits/2b20a8bbf32d67653fcd5ec3db2fb911fe4a14c2)
