### ISSUE TITLE
Play Store version out of date

### ISSUE THREAD

**Issue by crisp5** [celzero/rethink-app#579]
Hello,

The Play Store version of the app is still on 053i. 
Are there plans to update it to 053j (or 053k when it comes out)?

Thank you.

**Comment by ignoramous** [comment]
Yes, the app has been in the Play Store review pit for 2 months at this point. In all likelihood, Google bans the app by November.

**Comment by ignoramous** [comment]
Unsure, but most likely because of its capabilities to interfere with other app's functionalities.
