### ISSUE TITLE
Unable to download .config file on iOS 16

### ISSUE THREAD

**Issue by marcoclg19** [celzero/rethink-app#580]
Hello everyone,
when I choose the blocklists to use on the site and then press the 🍎, it simply downloads the .config in the download section on the File app. NextDNS or AdGuard DNS successfully download the .config file, letting me find it in the Settings > DNS & VPN.
Please check this bug if possible. (iPhone 11 - iOS 16 - Safari)

Cheers!

**Comment by ignoramous** [comment]
We don't own an iOS device to check why "apple" config doesn't work (nor do we have the funds to spend just for this). If anyone can debug it for me, let me know.

**Comment by marcoclg19** [comment]
I currently do not have time to check why it does not work properly. I can leave links where it works with other services.
https://encrypted-dns.party/
https://apple.nextdns.io/

**Comment by HrBDev** [comment]
> We don't own an iOS device to check why "apple" config doesn't work (nor do we have the funds to spend just for this). If anyone can debug it for us and explain why it doesn't work, let us know, and we'll attempt to make the fixes.

I think you should directly link to a .mobileconfig file but you button is a click event then spits out a file, so the iOS browser does not understand it's a config file and handles it as a normal file download.

**Comment by marcoclg19** [comment]
I still cannot download the file correctly @ignoramous
