### ISSUE TITLE
Profile battery use

### ISSUE THREAD

**Issue by muellerto** [celzero/rethink-app#587]
This app costs a lot of energy.

When the accu of my device is nearly empty and I check the accu usage of the apps I must recognize that more than 10% are caused by rethinkDNS alone. That's a lot for a background app which is almost never visible. So it's permanently among the top 3 in the ranking. I used NetGuard for a year and this was never remarkable.

Meanwhile I switched off writing the log but this didn't bring much effect.

I'm not sure if this is here a precondition but I switch my device into Flight Mode every night. In history I had several apps where the accu consumption suddenly increased a lot when no network was present.

v053j from F-Droid, /e/ 1.4, Fairphone 3

**Comment by muellerto** [comment]
Ahm ... Firewall was on. But I saw now I can switch it off and the blocking of apps still works (right?), this is what I need.

**Comment by ignoramous** [comment]
If you need to firewall apps, you need the `DNS + Firewall` or the `Firewall-only` mode. DNS mode only blocks DNS queries.

**Comment by muellerto** [comment]
I notice something interesting: I did an OS update (/e/ from 1.4 to 1.5). Since then RethinkDNS vanished from the top ranks of accu consumption and has now 1 or 2% (formerly always 11 or 12%). I checked if it still runs - at last it does still write a log.

**Comment by marcoXbresciani** [comment]
![Screenshot_20221117-131356](https://user-images.githubusercontent.com/48018419/202547327-e20ffe7c-6b10-41ac-90f8-e172bd03d33f.png)
I also saw a huge battery usage, in the latest version.

**Comment by muellerto** [comment]
Today I had again an unexpected battery drain, my device came from about 50% to 15% in just two or three hours. On top of the accu succers list: RethinkDNS.

**Comment by muellerto** [comment]
It remains now on rank 1 even after several reboots and cache cleaning.

**Comment by ignoramous** [comment]
I suspect it may have something to do with your ROM. On OnePlus and Android One phones, I don't see Rethink go beyond 12% use.

Btw, if you can, can you share logs (privately over email: `mz`@`celzero`dot`com`? https://github.com/celzero/rethink-app/issues/409#issuecomment-968091417

**Comment by muellerto** [comment]
Ahm ... yesterday I made an update from /e/ 1.5 to /e/ 1.6 - with this Rethink completely disappeared from the ranking. And until now I did lose about 30% over all, this means it could be visible. But it isn't. Perhaps indeed my last ROM version wasn't good.

**Comment by ignoramous** [comment]
Glad that the problems magically disappeared. I won't be surprised if they magically reappeared too.

Less than 2% is crazy! I usually see 5% to 15%, seldom more than that. Are you on the latest `v053l`? It has the new network engine (which should be *less* battery efficient than the previous one).

> I went to DNS66 for a while and then came back.

Fun fact: Julian, who maintains DNS66, uses one of Rethink (DoT) & AdGuard (DoT): https://github.com/julian-klode/dns66/discussions/480 (:

**Comment by michaelblyons** [comment]
> Are you on the latest `v053l`?

I keep up-to-date with F-Droid, maybe a day behind its build of releases. So yes.

> It has the new network engine (which should be _less_ battery efficient than the previous one).

Haha. No complaints yet. 🙂 Two of my big three network hogs are allowlisted, so that may have an impact. Maybe with the new engine, I can put my podcast app back behind the blocks. The other one is Firefox, where I maintain fairly rigorous uBO rules. I suppose it might be worth hiding my DNS lookups from the carrier...?

> Glad that the problems magically disappeared. I won't be surprised if they magically reappeared too.

Same. It would be nice to know specifically which bits were having problems, but my days of Android power-use are probably over. There was a time when I would have readily helped with profiling.

> Fun fact: Julian, who maintains DNS66, uses one of Rethink (DoT) & AdGuard (DoT): https://github.com/julian-klode/dns66/discussions/480

I see you mean on _his device_ he uses Rethink. Well, that is certainly interesting.
