### ISSUE TITLE
Locking-down an app should override its sister universal lockdown rule

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#589]
If universal lockdown rule is enabled (*Block all except bypassed apps and IPs*) and an app has its local *Lockdown* mode enabled too, then ideally, we should instead respect the app's setting, and allow *its* "bypassed IPs", and not apply the universal lockdown on it.

**Comment by hussainmohd-a** [comment]
Earlier the universal lockdown feature will only allow the connections from the apps which are part of "Universal bypass". Now changes are made such that the app specific lockdown is honored and the IPs which are part of bypass app rules (only if app is in lockdown mode) will be allowed. 

Fix: https://github.com/celzero/rethink-app/pull/592/commits/c908720fe2d0dfc4d7a59c81ed918318a47f2947
