### ISSUE TITLE
Search apps with uid and package name

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#595]
In Apps screen, search based on UIDs and package names, too; not just the app name.

**Comment by hussainmohd-a** [comment]
Now user can search apps in apps screen based on UIDs, package name and app name. 

https://github.com/celzero/rethink-app/pull/592/commits/261e5ec070f79fc7a2dbbe40d19f598091278491
https://github.com/celzero/rethink-app/pull/592/commits/eeb97af60625b3f49ffd1cb1631b7cd5b8515bd8
