### ISSUE TITLE
Breaks Plex personal libraries

### ISSUE THREAD

**Issue by hobhobuk** [celzero/rethink-app#60]
Plex works but only for Plex official free content. My own server seems to vanish when using BraveDNS. Disabling it brings it back. 

Apologies unsure the best way to report the issue.

**Comment by ignoramous** [comment]
This is absolutely the best place to report the issue. Thanks.

How can I reproduce the issue?

If you can, can see if changing the DNS endpoint to "No Filter" (see the drop-down at the top of the "DNS logs" screen) fixes this? If so, the default adblocking resolver is probably mucking with Plex here.

**Comment by hussainmohd-a** [comment]
@hobhobuk Let us know if you are still facing the issue.

**Comment by ignoramous** [comment]
In `v054c`, we introduced support for multicast DNS queries #368 and ability for users to exclude local LAN routes from Rethink #26 (*Configure* -> *Network* -> *Do not route Private IPs*).

My belief is that, those two should help fix the issue with Plex you're seeing. If not, please feel free to reopen this.
