### ISSUE TITLE
Allow access to the app after verifying user credentials

### ISSUE THREAD

**Issue by aasir22** [celzero/rethink-app#609]
Kindly add biometric and password for deleting the logs and kindly add app uninstalling option as well. @ignoramous @markwmuller @pjosingh @Poussinou @HrBDev @rajeshramesh38

**Comment by ignoramous** [comment]
$100 and we impl it tomorrow ;)

For api-level 28 and below: [KeyguardManager#createConfirmDeviceCredentialIntent](https://developer.android.com/reference/android/app/KeyguardManager.html#createConfirmDeviceCredentialIntent(java.lang.CharSequence,%20java.lang.CharSequence))


For api-level 29 and above: [BiometricPrompt](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt).

**Comment by rajeshramesh38** [comment]
@ignoramous  What was that 100$ means?

**Comment by markwmuller** [comment]
Kindly don't @ people for generic BS @aasir22

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/pull/709/commits/d0aeb70c958f83dbfc7cbb7c0636e83f23955afa
