### ISSUE TITLE
System DNS can only be ever set once

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#625]
This code prevents re-enabling `System DNS` when the underlying system dns hasn't changed (which is okay, but not okay when system dns hasn't changed but the user has instead switched from say `DoH` back to `System DNS` mode):

https://github.com/celzero/rethink-app/blob/d9934b83db1fa4b70c1a1e2dd42c5fedf2c2ca97/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L1323-L1324

**Comment by hussainmohd-a** [comment]
Now tunnel options are updated on every system dns selection. But the `startDNSProxy` method is called whenever there is a difference in tunnel dns proxy and selected dns proxy (in this case System dns).
