### ISSUE TITLE
VPN disconect sometimes

### ISSUE THREAD

**Issue by Cyberdr3am** [celzero/rethink-app#631]
Hello and thank you for your application which is really very good.
however the vpn deactivates it on its own for no reason and I have to open the application again for it to relaunch.
The notification tells me everything is ok and the app is not being killed by battery optimizations.
Android 9 Sony Xperia

**Comment by ignoramous** [comment]
Thanks for the praise. Appreciate it  #(:

Could be crashes. Would you know how to fetch [`adb bugreport`](https://developer.android.com/studio/debug/bug-report) (if so, email it `mz` at `celzero` dot `com`)?

**Comment by Cyberdr3am** [comment]
I don't know how to do it. I try to look on internet tomorrow and i send you that if i can.

**Comment by Cyberdr3am** [comment]
I have the zip files but i must have RethinkDNS app open ? Now i switch to adguard because i don't have problem with it

**Comment by ignoramous** [comment]
`adb bugreport` captures historical bug reports, so no you don't need rdns app open when taking them. If you're comfortable, you can email the bugreport to me (email above).

**Comment by Cyberdr3am** [comment]
Thx for your help. Android say it's very risky to send a bug report because some critical info and personal info inside

**Comment by ignoramous** [comment]
That it is, but without bugreports developers can't fix bugs... That's okay if you can't trust us enough to send the bugreport. The only consequence is that we can't know what's going on on your Android.

That said, wait for the next release (`v053l`, due this coming week) which sports a new network engine that should *reduce* crash rates. Btw, in the current version (`v053k`), the experimental `Auto` (under *Settings* -> *Choose IP version*) uses the new network engine. But `Auto` is problematic on `IPv6` networks (which we hope to address in `v054`, due in the coming month).

**Comment by Cyberdr3am** [comment]
The problem is not you it's me =)
I wait next release and i told you if the problem is fix

**Comment by ignoramous** [comment]
> choose IP version don't fix the vpn bug

Bummer. Btw, which version did you choose?

I'd appreciate logs.

1. If and when you take a `bugreport`, it generates one big `zip` file.
2. `unzip` it and look in the `tombstones` folder for files containing crash logs.
3. One or two files in there might be related to `com.celzero.bravedns` (which is the application id / package name of rethinkdns).
4. This application id / package name should be mentioned at the top of the file (in the first 5 lines or so), that's how you know it's related to rethinkdns. 
5. The files contains nothing but `tombstone` / crash logs related to rethinkdns which is safe to share (you can go through the file once before sharing, of course).

**Comment by Cyberdr3am** [comment]
Ok i send you this in 1 or 2 days ( i have a lot of work )

**Comment by ignoramous** [comment]
Hi, we released `v053m` yesterday (f-droid and play-store) please feel free to re-open this bug in case you're still seeing persistent crashes. Appreciate if you can also share logs / bug report.
