### ISSUE TITLE
Cannot download blocklists for on-device blocking

### ISSUE THREAD

**Issue by GitteGitty** [celzero/rethink-app#664]
Hi,

first of all: Great App, thank you very much!

I really would like to use Blocklists like fanboy's annoyances and uBlock annoyances lists
to block Cookie Consent Banners. Maybe those could be implemented?

But now to the issue:
Yesterday I tried to reinstall RethinkDNS on one phone and install it for the first time on another phone.
In both cases I cannot download the Blocklists. If I click on the download button for the lists in the app to enable on-device blocklists, I always get the notification: "Blocklists are already at latest version". But they are not been downloaded and cannot be downloaded because of that. So on-device blocking is not able.
I tried both, F-Droid and GitHub-Version and different networks, too.

Do you know that issue and know, what I can try here?

Thank you and best regards!

**Comment by hussainmohd-a** [comment]
Will look into this.

**Comment by GitteGitty** [comment]
Thank you!!

**Comment by ignoramous** [comment]
Post *Clear Data*, can you share the video recording of the download attempt and of the app info screen (Goto `About` -> tap on `App info`)? Thanks.

**Comment by GitteGitty** [comment]
Hello,

sure, is this what you need?

https://201126nnwl2p7kdi2he.nextcloud.hosting.zone/s/Lfn9yHomaJRWAsA

Thank you!

**Comment by ignoramous** [comment]
Dang. We made some changes on our download server that broke this. Nothing wrong with your device or the app.

Thanks for the report. It should be fixed now (https://github.com/celzero/downloads/commit/8bef8fe797d179ae886ec41a1f08ee581879305c). Can you check?

**Comment by GitteGitty** [comment]
Great, works, thank you very much!!
I delete the video.

Thanks!

**Comment by ignoramous** [comment]
No why thank *you* for the bug report! This was probably broken for everyone... (:
