### ISSUE TITLE
Do not auto set Orbot DNS

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#665]
Multiple users have reported that Orbot DNS (that's automatically set when using one-click Orbot ie Tor-as-a-Proxy setup) does not work.

Do not set Orbot DNS, for now.

See also: https://github.com/celzero/rethink-app/discussions/523

**Comment by hussainmohd-a** [comment]
The ip and port received for DNS from Orbot Intent receiver is not working in some of the devices. 
So not setting the Orbot dns by default.
