### ISSUE TITLE
[bug] SOCKS5 proxy settings get reverted

### ISSUE THREAD

**Issue by PoneyClairDeLune** [celzero/rethink-app#667]
https://t.me/rethinkdns/58337

**Version**: v053k

As stated by the user, SOCKS5 proxy settings get reverted automatically upon modification.

**Comment by ignoramous** [comment]
Thanks. Dup #608?

**Comment by PoneyClairDeLune** [comment]
> Thanks. Dup #608?

Yup. Want to blame GitHub search so bad...

**Comment by ignoramous** [comment]
No sweat. Prefer *repeat* bug reports than *no* bug reports (:
