### ISSUE TITLE
[feature request] Excluding an app only from the DNS rules

### ISSUE THREAD

**Issue by trizen** [celzero/rethink-app#669]
Hi! First of all, many thanks for creating this useful app!

I was wondering if it would be possible to exclude an app only from the DNS blocking rules.

One scenario in which this would be useful: we want one specific app to be able to resolve and connect to the blocked domains, while still using the TCP/SOCKS5 proxy set in RethinkDNS.

Currently, if an app is excluded from RethinkDNS, it will no longer use the TCP/SOCKS5 proxy set in RethinkDNS.

The DNS requests for the excluded app could be resolved by the TCP/SOCKS5 proxy, or by using the default Android's DNS resolver, if no proxy is set (related: https://github.com/celzero/rethink-app/issues/543).

**Comment by hussainmohd-a** [comment]
Hi, Thanks for reporting. We have fixed this issue in the recent commits. Will be part of the next release. Issue: https://github.com/celzero/rethink-app/issues/611
