### ISSUE TITLE
Firewall screen: Implement Search and group firewalled apps at the top

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#67]
1. Search bar is necessary given some users have upwards of 500 apps installed.

2. Group firewalled apps to the top under each category.

3. Show sticky list breaks (like dates that show up in WhatsApp chats) or some feedback on the current first letter of the app in view in the scroll list (like in iOS)?

**Comment by hussainmohd-a** [comment]
Introduced search bar for the app firewall screen, also when the user firewalls the application, the firewalled app will be moved to top of the category list.
