### ISSUE TITLE
Blocklists do not populate

### ISSUE THREAD

**Issue by An-dz** [celzero/rethink-app#672]
Following my tests on issue [#626](https://github.com/celzero/rethink-app/issues/626#issuecomment-1316027952) I re-flashed my ROM to a clean state. And yet I still can't properly download the blocklists.

**Problem**

Blocklists finish downloading, but I'm stuck at _Disabled_ in the blocklists menu. Installing 053j allows the button to configure to work but when I go to the individual list view it's empty.

**Tested**

053k, 053j & 053i

If the internal downloader is turned on the download screen goes away once the download finishes, if it's turned off nothing seems to happen at all.

**Comment by hussainmohd-a** [comment]
Thanks for reporting the issue. Would you know how to fetch [adb bugreport](https://developer.android.com/studio/debug/bug-report) (if so, email it md at celzero dot com)

**Comment by An-dz** [comment]
Sent. Just to let you know in case it ends up in spam.

**Comment by ignoramous** [comment]
While we look at the bug report, our automation published a new set of blocklists just today. Can you see if these new ones work?

**Comment by An-dz** [comment]
Kind of, now it populates and the blocking does work, which is good.

But the _simple_ blocklist page doesn't work correctly. The last three _privacy_ options work correctly, but all the others don't select any list at all. I can choose all of them and it won't select any list. And if there's any list active then all of those broken _simple_ options show as selected.

**Comment by ignoramous** [comment]
> Edit: blocking is strange, I'm not sure if it's truly blocking or not, I'll keep an eye.

Yeah, aware of this. Next blocklist update will fix it, hopefully. We've done an extensive rewrite of how blocklists work, that the older app versions don't really understand. We need to build the newer blocklists in a backwards compatible way... we're doing it right now, it just isn't perfect just yet. 

Thanks for the bug report!

**Comment by ignoramous** [comment]
I believe this has been fixed with the blocklist version released on 25th Nov. If not, please feel free to re-open.

**Comment by An-dz** [comment]
Yep, looks good now.
