### ISSUE TITLE
Network logs: VPN in lockdown and excluded APP + invisible ping queries

### ISSUE THREAD

**Issue by ysard** [celzero/rethink-app#674]
Hi, while I was playing around with android's VPN lockdown mode settings, I realized when removing this option, that the logs related to an excluded app are still collected and visible.

For Firefox par example
- Exclude App from "Apps" section
- Go to Android VPN settings, then "Block connections without VPN"
- Wait sometime
- Refresh a page on Firefox
- Go to Firewall logs: connections are listed (supposed to be ok I think)
- Go to Android VPN settings, then unckeck "Block connections without VPN"
- Refresh a page on Firefox
- _/!\ Go to Firewall logs: new connections from Firefox are listed (supposed to be masked this time) /!\\_
- Go to App settings: Remove "Exclude" setting, then set It.
- Refresh & Go to Firewall: This time there are no new connections showed (supposed to be ok).

It's maybe a corner use case issue :p

---

I also realized that ping requests (via Termux) do not appear in the logs of this app.

**Comment by ignoramous** [comment]
Thanks for your bug report.

The app should be excluded within 30s. That's an internal timeout for when Rethink *syncs* `Block connections without VPN` setting. Unfortunately, Android doesn't proactively inform VPN apps when that setting is toggled on/off by the user. And of course, Rethink can't keep polling for changes every sec, that seems wasteful. 

So: If you still see the excluded app not getting excluded 30s *after* turning off `Block connections without VPN`, then that's a bug. Is that the case?

**Comment by ysard** [comment]
Thanks for your response, indeed, it is understandable, after this timeout the requests are hidden. :+1: 

There remains the problem of ping requests.

**Comment by ignoramous** [comment]
> I also realized that ping requests (via Termux) do not appear in the logs of this app.

Dup: To be done as part of ICMP handling (which isn't yet implemented in the new network engine): #553 and https://github.com/celzero/firestack/issues/3

Pls feel free to re-open if you think this issue was closed incorrectly. Thanks for the detailed bug report. Appreciate it (:
