### ISSUE TITLE
Button to clear an app's network log

### ISSUE THREAD

**Issue by opk12** [celzero/rethink-app#678]
Before reporting a firewall leak (NetGuard blocks Google Play Services, Rethink firewall does not log nor block, Rethink DNS sees the domain, Always-on VPN is enabled, Android 7.1 + 053k from f-droid), I want to double-check the app logs, which are cluttered with old successful connections from previous tests. So I would like to clear the firewall logs for a specific app. For example, I could tap a trash can button near the search box.

**Comment by ignoramous** [comment]
To be released in `v053l` (in a day or two... or so we think).
