### ISSUE TITLE
Exclude app from SOCKS5 proxy

### ISSUE THREAD

**Issue by MasterKia** [celzero/rethink-app#682]
It would be useful to be able to exclude banking and governmental apps from the SOCKS5 proxy since those only work using a regional IPs and not a foreign (VPN) ip thus I have to disable Rethink or the SOCKS5 proxy everytime I have to use one of those.

**Comment by ignoramous** [comment]
Thanks. Planned: https://github.com/celzero/rethink-app/issues/229

For now, a work around is to "Exclude" govt apps from the VPN altogether from the *Apps* screen. This isn't ideal in scenarios where you want control over firewall and dns rules since "Excluded apps" essentially bypass both.
