### ISSUE TITLE
How to navigate with TV remote 

### ISSUE THREAD

**Issue by finnzz** [celzero/rethink-app#697]
This seems like a great app to use with TV boxes / sticks, but it's nearly impossible to navigate with a remote.  Passing the introduction screen for example can't be done with a remote, and once you get past that it's really difficult to see what your are selecting.

Is there a remote friendly fork?

I know I can use a virtual mouse, ScrCpy or some secondary control app to navigate, but I'm hoping to recommend this app to others, and it complicates things a bit to have to tell them to download and setup two apps to get things working.

Thank you

**Comment by ignoramous** [comment]
Can't. TV support is planned for `v057` (some 6 to 12 months away, unless someone sponsors its development to make it happen before that); tracked here: #172
