### ISSUE TITLE
[Feature request] Allow internet when screen is ON

### ISSUE THREAD

**Issue by Fehertukor** [celzero/rethink-app#698]
Hello,

Thank you for your work!
Would it be possible to have more specific option to:
Allow WI-FI when screen is ON
Allow mobile internet when screen is ON

This would help a ton to restric unwanted app traffic.

**Comment by ignoramous** [comment]
There's already an option to `Block when device is locked` in Firewall's *Universal* tab. Wouldn't that be enough?

Or, you mean, you want control over this setting for individual apps? If so, we thought about it, but the UI to get this right is too complicated (I mean, there would be too many rules for users to deal with).

**Comment by Fehertukor** [comment]
Thank you for your quick answer!
Yes I know there is such a possibility.
My reason there are a ton of apps which I can't get in open sourced version(at least without useless trackers /I know there is a possibility to filter certain trackers that is super! / ).
So with an option to only get internet when it is on screen I can limit specific apps but if I turn on Block when the device is off it is universal.

Would it be more complicated?
Yes! But this option could be in the specific sub menu when clicking on the app and set these specific rules.
Normal users will not care and will not no without clickig on the app.
For us it can be a key component.

**Comment by ignoramous** [comment]
> Given that, does this sound right to you: "Per-app rule to allow / block connections when device locked"?

If the above is what you meant, then please track it at #720 If not, feel free to reopen this FR.
