### ISSUE TITLE
Firewall: Warn users from blocking System Apps

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#70]
It turns out overzealous users end up blocking all system apps that then wreacks havoc.

It is probably a good idea to warn them in the UI for the dragons that lay asleep.

Probably also disable the "Blocked" button or display a popup warning the users to do so at their own peril and probably also display a way out ("Force Stop BraveDNS from the Settings screen, for example).

**Comment by hussainmohd-a** [comment]
Introduced a warning text in the system apps category for this release. Will introduce dialog/relevant UI option to warn users.

**Comment by hussainmohd-a** [comment]
Introduced a textview in the bottom of both System apps and System components category warning about blocking the whole category. Also dialog is introduced to the users whether to proceed on blocking the System apps/System components.
