### ISSUE TITLE
Feature request - autostart on mobile network or auto off in some SSIDs

### ISSUE THREAD

**Issue by sbe-arg** [celzero/rethink-app#702]
Would be nice to have an autostart flag when leaving certain wifi networks.

Or having a whitelist to auto turn off on certain SSIDs. Specially home or enterprise SSIDs where solutions like pi-hole could be in place.

**Comment by ignoramous** [comment]
Dup? #445

**Comment by ignoramous** [comment]
> Or having a whitelist to auto turn off on certain SSIDs. Specially home or enterprise SSIDs where solutions like pi-hole could be in place.

One won't have to pause as switching to `System DNS` should do it?

As for the other part, please track #445 for the feature request.
