### ISSUE TITLE
v053l GUI issues & improvements

### ISSUE THREAD

**Issue by ysard** [celzero/rethink-app#712]
Hi, here are some GUI & translations issues for the version v053l.

- [x] Drop-down menu issue on app screen:
    - click on "Ip rules for this app" arrow
    - the drop-down menu above is displayed

    ![Screenshot_20221212-051549932](https://user-images.githubusercontent.com/14988285/207473754-63bd05b5-230b-4c03-a3ff-ecc60a29395e.jpg)

- [x] The popup menu "What's new" on the home screen displays a HTML content that is not interpreted.
- [x] The button "Activate RDNS+" on the home screen is slow to respond. If a user does multiple taps on it, multiple instances of the asked screen will be displayed. Maybe a singleton should be implemented here.

- [x] Translations on the "IP & port rules " screen. We can found 4 strings for each label.
   Ex: 
    - ci_no_rule_initial: "N" => filter shortcut
    - ci_no_rule_txt "No Rule" => rule label
    - ci_no_rule_desc "- No Rule" => filter label
    - ci_no_rule "no rule" => on the button displayed when a rule is selected

   But for `ci_bypass_app*` there is no `ci_bypass_app` for the button. So `ci_bypass_app_txt` is reused.

   See:
https://github.com/celzero/rethink-app/blob/2653757ad85acfb537ae880c90496449984347c0/app/src/full/res/layout/list_item_custom_ip.xml#L121

   Thus I can't set a specific shorter translation for the button. 
   I would like this because the content of the horizontal button layout is too wide for the screen so the rightmost "delete" button cannot be displayed unless the user switches to landscape mode.

- [x] Typo nitpicking: Some languages like French require a space before and after a `:`. It's not possible with the following implementation.

https://github.com/celzero/rethink-app/blob/2653757ad85acfb537ae880c90496449984347c0/app/src/full/java/com/celzero/bravedns/ui/CustomIpActivity.kt#L75

Thanks.

**Comment by ignoramous** [comment]
No why thank you for this. We will attempt to address it in our next release, `v053m` due end of this year (:

Re: Activate RDNS+: You mean the chip on the Homescreen, right?

**Comment by ysard** [comment]
> Re: Activate RDNS+: You mean the chip on the Homescreen, right?

Yes, on the homescreen, I just edited :)

**Comment by hussainmohd-a** [comment]
Fixed the above mentioned issues in [#3b41](https://github.com/hussainmohd-a/rethink-app/commit/3b418e2f65b44a56e7095b4899600147b238cfae)
