### ISSUE TITLE
One app to Control access to WiFi/Data/ VPN/VPN bypass, Domain/IP Block, VPN , DNS, Tor Client that works using VPN service..

### ISSUE THREAD

**Issue by Rexadev** [celzero/rethink-app#719]
1. AFWall - Blocking apps from internet and control connection to LAN, WiFi, Data, VPN
2. AdAway - Domain Block
3. IP Blocklist8. 
4. DNS - DoT10. 
5. VPN - OpenVPN, WireGuard Client12. 
6. Tor Clients

**Comment by ignoramous** [comment]
That's this app in the future.

There are individual issues open on the topic.

For ex:
1. #78 
1. #18
3. #237 
4. Already implemented
5. #52 
6. Already implemented via integration with Orbot

Closing this, as the feature requests are tracked elsewhere. Feel free to reopen in case I missed addressing anything. Thanks for the feedback, appreciate it (:
