### ISSUE TITLE
Ruleset for uninstalled apps

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#726]
When an app is uninstalled, preserve it rules until deleted by the user?

Rules cannot assume that the UID would remain the same across reinstalls.

In fact, even the package name may not remain the same across reinstalls, while app-id can never change: https://developer.android.com/studio/build/configure-app-module#set_the_application_id

**Comment by ignoramous** [comment]
AppIDs aren't accessible via the Android SDK: https://archive.is/WHFQF

Deleting rules on uninstall is the only option then. Otherwise, there are chances where rules for another uninstalled app is reflected on an unrelated app.

Another limitation is that the app-info tables track apps on package-names. But an app of same package-name can exist in Work Profile and in the main profile at once. To alleviate this, uid + package-name must be the composite key in the table.

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/pull/709/commits/872c66ae70f12e5381d60b5705b98eac16df8039
Rules related to the uninstalled apps will be deleted.
