### ISSUE TITLE
Can you add these two rule sources?

### ISSUE THREAD

**Issue by biange200** [celzero/rethink-app#728]
https://github.com/sbwml/halflife-list
https://github.com/banbendalao/ADgk

**Comment by ignoramous** [comment]
From a cursory glance, these lists are meant to be used with AdGuard, it looks like? They won't be a good fit for a DNS-based content blocker like Rethink. Also, some of the lists like EasyList China and EasyPrivacy are already included in Rethink.

That said, I'll take another look at these in the coming days, but if you have any inputs, I'd appreciate it.

**Comment by biange200** [comment]
adgk is a special rule for mobile app You can look at this



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 01/01/2023 01:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [celzero/rethink-app] Can you add these two rule sources? (Issue #728) |

From a cursory glance, these lists are meant to be used with AdGuard, it looks like? They won't be a good fit for a DNS-based content blocker like Rethink. Also, some of the lists like EasyList China and EasyPrivacy are already included in Rethink.

That said, I'll take another look at these in the coming days, but if you have any inputs, I'd appreciate it.

**Comment by biange200** [comment]
adgk is a special rule for mobile app You can look at this

**Comment by biange200** [comment]
> From a cursory glance, these lists are meant to be used with AdGuard, it looks like? They won't be a good fit for a DNS-based content blocker like Rethink. Also, some of the lists like EasyList China and EasyPrivacy are already included in Rethink.
> 
> That said, I'll take another look at these in the coming days, but if you have any inputs, I'd appreciate it.

Can you look at these rules? Do you see fit to add to rethinkdns?

https://raw.githubusercontent.com/rentianyu/Ad-set-hosts/

https://raw.githubusercontent.com/lingeringsound/10007_auto/master/all

**Comment by ignoramous** [comment]
Sure thing. Will take a look.

**Comment by biange200** [comment]
https://github.com/neodevpro/neodevhost
This rule is also very good



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 01/01/2023 21:46 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [celzero/rethink-app] Can you add these two rule sources? (Issue #728) |

Sure thing. Will take a look.

**Comment by ignoramous** [comment]
https://github.com/lingeringsound/10007_auto uses 

大圣净化 | 感谢！
-- | --
yhost | 感谢！
Steven Black | 感谢！
oisd | 感谢！
1024 | 感谢！
adhost | 感谢!

which overlap with https://github.com/rentianyu/Ad-set-hosts/

So: It'd make sense to integrate just the one among those two; and I am leaning towards rentianyu's lists here.

**Comment by ignoramous** [comment]
AdSetHosts added in this commit, should show up on the website and the app in a day or two: https://github.com/serverless-dns/blocklists/commit/79edb97369b44b898505c68037632942e777c957
