### ISSUE TITLE
Advanced log filtering or log exporting

### ISSUE THREAD

**Issue by exploide** [celzero/rethink-app#733]
Thanks for this great app. The insight it provides into app communication is really useful!

When viewing network or DNS logs, the list quickly becomes very long. While the app already provides a simple search function and basic filtering options, I would like to request some kind of advanced filtering. For example if one wants to dismiss all the `googleapis.com` entries, I have currently no way to invert the search term. I have something like `!googleapis.com` in mind. But then the need for `and`-based queries is not far away...

It might be that an advanced search query / filtering syntax is too much work or out of scope for this project. Especially because I support your design goal of being easy to use.

So alternatively (or additionally), it would be awesome to be able to export the logs to a simple file. This could easily be post-processed with `grep`, `jq` or whatever is suitable for the respective use case. I think either a simple grepable format or something like [jsonlines](https://jsonlines.org/) would be a reasonable export format.

**Comment by ignoramous** [comment]
> I have something like !googleapis.com in mind. But then the need for and-based queries is not far away...

Interesting. We could let users write (DML) SQL queries itself in that search box then... ;)

> So alternatively (or additionally), it would be awesome to be able to export the logs to a simple file. This could easily be post-processed with grep, jq or whatever is suitable for the respective use case. I think either a simple grepable format or something like [jsonlines](https://jsonlines.org/) would be a reasonable export format.

You can already export the logs (along with app settings) to a sqlite3.db file to your on-device *external* (public) storage directory since `v053k` (14 Oct). Go to *Settings* and look for *Backup & Restore*. 

From the next version, app settings and logs would be separate sqlite3.db files (in the current versions, they are in the same file). These files should be examinable with sqlite3 CLI.

Let me know how it goes, if you do try it.

**Comment by exploide** [comment]
> Interesting. We could let users write (DML) SQL queries itself in that search box then... ;)

Not sure whether this was a joke or this is really on the table :smile: 
This would certainly cover the use case. But I'm not sure how well this integrates into the UI. If the same search field would be reused it would need to magically detect whether it is a simple search term or a query. And the user somehow needs to know how exactly a query is composed, how the fields are named, ... Might be a mighty feature but also might open Pandora's box.

> You can already export the logs (along with app settings) to a sqlite3.db file to your on-device external (public) storage directory since v053k (14 Oct). Go to Settings and look for Backup & Restore.
Let me know how it goes, if you do try it.

Tried it, worked well for my use case :)
However, there are some obstacles.

First, this feature is hard to discover. Did not expect finding log export incorporated in the general app settings export. If I compare this to a "typical" desktop or web application where you can view logs, there is usually an export option near the log view (where the filter icon is for example).

Furthermore, processing this requires you to know that the exported file is a zip that can be unpacked, that the data is stored within an sqlite database and how to do SQL queries.
Overall this requires more knowledge than working with a text file in a common format.

However, the question is, is it worth the effort? Maybe I was the first one with this demand and I know how to deal with sqlite files.

You may just close this issue since we found a way to accomplish my use case. But maybe you think an app enhancement is reasonable.

Thanks! :)

**Comment by ignoramous** [comment]
> However, the question is, is it worth the effort? Maybe I was the first one with this demand and I know how to deal with sqlite files.

Well, we intend to let users export PCAP: https://github.com/celzero/firestack/issues/11 And my guess is, such a feature is almost always required by folks who typically have a hang of zip files, db files, and pcap files... 

> If I compare this to a "typical" desktop or web application where you can view logs, there is usually an export option near the log view (where the filter icon is for example).

On mobile, the screen real-estate is really limited. But you're right that we need to find a better home for "log export" if we ever support such a thing. Right now, we are just (ab)using "Backup & Restore" functionality to export logs... :D

> But maybe you think an app enhancement is reasonable.

I am open to inputs on where to show "log export" (as a db file / txt file / pcap file) given it is likely a niche use-case (as in, imo, doesn't make sense for it to occupy prime real-estate on-screen).

**Comment by ignoramous** [comment]
We've merged in support for PCAP (*Configure* -> *Settings* -> *Packet Capture*). It is already out on the website version `v054` (Play and F-Droid releases probably sometime within this week).

<details>
<summary>screenshot</summary>
Configure -> Settings -> VPN -> Packet Capture:

![Screenshot_2023-03-07-05-35-25-56_c8cbde12d3521911922be4eee6a05664~3](https://user-images.githubusercontent.com/852289/223285038-b94541fe-f2c9-4e06-bdd8-7defb24e953c.jpg)
</details>

Please feel free to reopen in case PCAP isn't satisfactory. Thanks.
