### ISSUE TITLE
Hide Notification Shade within app

### ISSUE THREAD

**Issue by smartyn13r** [celzero/rethink-app#74]
Please add a capability to hide Notification Shade as an app setting to make notifications less crowded

**Comment by ignoramous** [comment]
Hi,

Android requires for any foreground service (like a VPN) to show a persistent notification. What you could do is:

1. Long press on the `Protected! Connected to...` BraveDNS notification.

2. Then tap on `Turn off notifications`.

Note that, you'd not get any notifications hence from the app.

**Comment by smartyn13r** [comment]
That's a work around

**Comment by Ch4t4r** [comment]
You could/should use different notification channels for any notification you add in the future. This way users can disable the ongoing notification but still receive others.

**Comment by ignoramous** [comment]
Channels it is. We already have three channels I think. But they're wrongly worded. @hussainmohd-a to clean it up (:

**Comment by ignoramous** [comment]
@smartyn13r there's no other way around it. Notification needs to be shown by the app, that's how the API works.

**Comment by ignoramous** [comment]
@smartyn13r or do you mean the app should be full screen and hide the status bar? I guess not.

**Comment by smartyn13r** [comment]
Not full-screen
Notification shade should be user controlled while continuing to receive other app notification

**Comment by ignoramous** [comment]
Unfortunately, Android doesn't let us control this as the app must run as a foreground app.

More: #488
