### ISSUE TITLE
Support HTTP(S) proxy with auth

### ISSUE THREAD

**Issue by winniethepoohbear** [celzero/rethink-app#746]
Add support for configuring HTTP/S proxies that require user:pass basic authentication.

**Comment by ignoramous** [comment]
> Add support for configuring HTTP/S proxies that require user:pass basic authentication.

Wouldn't that go in the Proxy URL `https://username:password@proxy.tld/`?

---

Btw, Rethink uses Android's built-in HTTP Proxy impl which doesn't expose an API to set custom `Headers` such as basic auth.

That said, we've already impl a HTTP/1.1 proxy ourselves, but don't use it yet. Will enable it in the next version (`v054`).

**Comment by winniethepoohbear** [comment]
> Wouldn't that go in the Proxy URL `https://username:password@proxy.tld/`?

That format would work. It is common to see `host:port:user:pass` format as well.

**Comment by ignoramous** [comment]
`v055` now supports HTTP(S) CONNECT tunnles with Basic Auth (or, so we think): #906 

Please test it and let us know if it works as intended: https://github.com/celzero/firestack/commit/48541c60376542db110d4dbcc73b1100b397a85f
