### ISSUE TITLE
0.53n版本有问题

### ISSUE THREAD

**Issue by biange200** [celzero/rethink-app#749]
0.53n会导致一些软件连接不上网络或是无法显示

<details>
<summary>screenshots</summary>
3 screenshots:

![Screenshot_20230113_220324.jpg](https://user-images.githubusercontent.com/37582806/212502867-a99055df-06c0-47a1-9cfb-6493b7dcfda9.jpg)
我重新降级回0.53l fdroid 正常使用软件 网络正常 
![Screenshot_20230115_075707.jpg](https://user-images.githubusercontent.com/37582806/212502933-5028ec3e-2eb0-45e5-a64f-d63efe15b11b.jpg)
![Screenshot_20230115_081532.jpg](https://user-images.githubusercontent.com/37582806/212502956-6e1d7b98-34e4-4c4c-be39-66c84e169560.jpg)
</details>

我用的一样的规则 0.53n会导致一些软件无法连网

**Comment by ignoramous** [comment]
cc: @PoneyClairDeLune Hi: Can you please ask the user if they have setup aggressive blocklists or better yet, ask for help on Telegram (possibly translating Mandarin / Cantonese to English, if they can)?

**Comment by biange200** [comment]
Download and install the fdroid version of rethink is back to normal

**Comment by ignoramous** [comment]
Thanks.
