### ISSUE TITLE
Allow for custom on-device blocklists

### ISSUE THREAD

**Issue by signed-log** [celzero/rethink-app#754]
My usage would be to have [Red Flag Domains](https://red.flag.domains/details/), block list of French domains, in Rethink DNS

Sadly, the license of that list [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) would prevent its use in RDNS+ as soon as the paid plan is introduced, so its introduction, for a few weeks before having to retire it, is pointless

Is it planned to allow for on-device block lists that are on the file system and not necessarily those of RDNS+?

**Comment by ignoramous** [comment]
For custom domain lists, see: #293 

Likely to land in `v056` (3 to 4 months out).

(*closing as dup, pls feel free to re-open*).

**Comment by signed-log** [comment]
> > My usage would be to have [Red Flag Domains](https://red.flag.domains/details/), block list of French domains, in Rethink DNS
> 
> Red Flag Domains are already included in Rethink, but I take you know that already...?

@ignoramous Is it? I can't find it both on my app and the [`/configure`](https://rethinkdns.com/configure) page. Which is the reason I opened that issue in the first place

Has it been enabled under a different name or is it in a agregrator list?

**Comment by signed-log** [comment]
@ignoramous Found it ! It was in the same as `Malware (RPi)`

I might shoot a PR to [serverless-dns/blocklists](https://github.com/serverless-dns/blocklists) to put it out of Malware (RPi), and instead put it either its own blocklist or along with EasyList Liste FR, because it has nothing to do with the RPiList

 https://github.com/serverless-dns/blocklists/blob/6cd8d55dffc03029ba4aedf79a082ebcc7eac81c/config.json#L648-L659
