### ISSUE TITLE
Google/ThePhone gets through the firewall

### ISSUE THREAD

**Issue by lucmp** [celzero/rethink-app#755]
All apps get blocked when I enable the firewall, but I still get notifications of system updates with details such as date or version number of the updates. It seems there is some "upper class" within my phone to which the firewall rules do not apply. Is that by design or am I doing something wrong in my configuration?

**Comment by ignoramous** [comment]
> It seems there is some "upper class" within my phone to which the firewall rules do not apply.

Depends on the OEM, but these notifications usually come from GMS (Google Messaging Service) impl by apps, Google Play Framework and Google Play Service. As for *System Updates*, the app's that's sending you notification is specific your OEM. Usually, you can find the app (and even instructions on disabling it) by Googling for it.

> Is that by design or am I doing something wrong in my configuration?

Could be both, but likely the former. Also, Rethink is a user-space firewall. It isn't as powerful as firewalls like AfWall+ that runs as *root*.
