### ISSUE TITLE
Backup one one Android, restore on another

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#757]
A user said that backing up v053n on one phone didn't work on another.

This likely can happen for a lot of reasons, for instance difference in installed apps / system components / uid changes etc.

We would do well to handle such scenarios if they aren't handled already.

**Comment by signed-log** [comment]
I can confirm, 053n failed loading backups from 053l, but on the same exact phone

**Comment by ignoramous** [comment]
We changed backup format between `v053l` and `v053n`.

Btw, you can install `v053l` and then update to `v053n`, and your settings and data should be carried forward just fine. Just that we did not implement backup / restore portion for the migration (for lack of time).

This bug is different. It is about supporting restores across different Androids which may have different system apps and installed apps.

**Comment by 0xlne** [comment]
I will join this feature request.
I'm running a full lockdown/whitelist per IP/domain. The first time setup is painful enough, but I would like to ensure I'm able to restore a backup at the very least in the event of a factory reset or after an upgrade.
Moreover, I have several devices & would be grateful for the ability to restore at least the custom IP/domain rules (global & per-app) across devices.

**Comment by ignoramous** [comment]
[`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b) impl restoring across devices but *same* or *higher* app version.

https://github.com/celzero/rethink-app/blob/02c16a99764b82bd4fbcc53187134cf944c47931/app/src/main/java/com/celzero/bravedns/database/RefreshDatabase.kt#L190
