### ISSUE TITLE
Can't find rethinkDNS in the app list

### ISSUE THREAD

**Issue by Invertisment** [celzero/rethink-app#762]
I would want to filter and/or block rethink-app's own requests but this app isn't displayed in the app list.
Is this by design? Why can't I change preferences to the app itself?  
It has the internet permissions to download the blocklist and I'd like to inspect where it's coming from.

**Comment by ignoramous** [comment]
> I would want to filter and/or block rethink-app's own requests but this app isn't displayed in the app list.

If you block Rethink, then none of the apps tunneled by Rethink would have internet access. If you ask how we know... we implemented this! Network namespaces don't work quite as expected: #393 

> Is this by design? Why can't I change preferences to the app itself?

Unless Rethink implements `root` mode (#78), pretty much there's nothing we could do (or that I know of) to block Rethink itself without blocking all apps.

> It has the internet permissions to download the blocklist and I'd like to inspect where it's coming from.

Blocklists are hosted at [`dl.rethinkdns.com`](https://github.com/celzero/rethink-app/blob/f6dd37cec669f5475958c449dbd2143e0db8a5ba/app/src/main/java/com/celzero/bravedns/util/Constants.kt#L28). Btw, Rethink from F-Droid doesn't phone home for blocklist download, or for updates, or for website icons (fav icons) unless users enable settings specific to those features. That is, by default, Rethink (F-Droid flavour) shouldn't be making any connections. If it is, then please let us know 'cause we'd like to fix that.

Closing this, as it isn't technically feasible back when we tried it (the non-working code for it [is still part of the network engine](https://github.com/celzero/firestack/blob/c170cdbdc607d0da4f250ae294668a2bb643be9d/intra/protect/protect.go#L61-L115)). If you know of any other userspace (no root) Firewall that does this, let us know, and we'd explore some more. Thanks.

**Comment by Invertisment** [comment]
I actually do know and this is why I asked about this.
I used Net Blocker and it allows to block itself: https://play.google.com/store/apps/details?id=com.netblocker.apps.block.internet.access

But for some reason it got removed from Google Play. Probably it was too good.

In that app I could choose to disable WiFi or Data connection for each app, including the Net Blocker itself.

**Comment by ignoramous** [comment]
> In that app I could choose to disable WiFi or Data connection for each app, including the Net Blocker itself. 

- Did it ever work on one of the latest Android versions (11+)?
- If NetBlocker did block itself, did those entries show up in its network logs or equivalent?

> You probably have some architectural decisions in your code and this is why you think you can't do it.

From what little I know, it is the android architecture that limits us, because network namespacing doesn't work in the latest Android versions. 

> I think I should look for other and more capable blocking app.

If you find a functional one, do let us know. We are eager to learn and improve.

**Comment by Invertisment** [comment]
> Did it ever work on one of the latest Android versions (11+)?

I only tried it on Android 13 and it worked there. I don't know about other versions.

> If NetBlocker did block itself, did those entries show up in its network logs or equivalent?

It didn't have logs because it's not per-site app but per-app blocking. So it was simply black-holing the requests. So for me I don't care if some kind of calculator gets full denial of the network. I want it to have full denial of wifi and Cellular. It is a different app but the concept that you tell is unimplementable simply works there. But no, no logs are there.

I think you confuse two different things here -- Network control for the VPN service of your app and network blocking for the Activity version of your app which is always through the UI (ok, maybe some kind of async task).
I'm not asking you to control your VPN service, I ask whether it's possible to block the UI itself and its tasks.

**Comment by Invertisment** [comment]
It would be very nice if I could run two VPNs at the same time. Then this thing won't be needed :thinking: I could simply line them up and call it a day.

**Comment by ignoramous** [comment]
> If you block Rethink, then none of the apps tunneled by Rethink would have internet access. If you ask how we know... we implemented this! Network namespaces don't work quite as expected: https://github.com/celzero/rethink-app/issues/393

We've made network namespaces work (#393). Rethink will soon get the ability to block its own traffic.
