### ISSUE TITLE
Can rethinkdns be changed to the local import mode of rules?

### ISSUE THREAD

**Issue by biange200** [celzero/rethink-app#764]
Provide a link to download the rule pack on the website or github. Then download it to the mobile folder, rethinkdns click Import .txt rule package, and there you go. Don't you think it's more convenient to update the rules this way? I think this will also solve the problem of updating rules for us Chinese

**Comment by ignoramous** [comment]
Planned: https://github.com/celzero/rethink-app/issues/293

We will see if we can include this in the immediate upcoming versions. Thanks.
