### ISSUE TITLE
Apply blocklists broken?

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#768]
Some users report that they have to stop / start or even force-stop / start the app to have the new blocklist selection applied.

Ex:
> Using Quad 9 Doh with On device blocklist. I've choosed good ad and tracker blockers but in DNS LOGS nothing is blocked

Test if that is the case.

**Comment by hussainmohd-a** [comment]
Closing the issue as it is not reproducible. However, if we encounter this issue again in the future will reopen this.
