### ISSUE TITLE
Allow IP subnet rule not work in Isolate mode

### ISSUE THREAD

**Issue by lessload** [celzero/rethink-app#778]
I try to add 157.X.X.X/24 as allow rule in some app that use "isolate" mode. but in log still show as block. not sure is it just gui bug.

**Comment by ignoramous** [comment]
I'm on the latest version, and subnet allow and deny rules both work.

Are you sure you aren't looking at an older log entry? The IP rules screen should show when the rule was last added / updated, and the network log screen should also show the time a particular connection was blocked.

**Comment by lessload** [comment]
i will do more testing it.
