### ISSUE TITLE
Android 13: VPN keeps stopping even when always on VPN 

### ISSUE THREAD

**Issue by Artim96** [celzero/rethink-app#786]
Since version 053n I'm noticing that not only the (experimental) auto-connnect on boot pretty much doesn't work anymore, but the VPN disconnects a few times over the day even though it's set as always on VPN and to block all data without VPN connection. Both phenomena can be fixed by simply opening the app.

I'm not sure if that's actually a crash that would pop up in the logs included in the email bug report function.

I'm using the current Android 13 quarterly beta for Google Pixel devices, so it's not impossible that this is related to problems of the OS.

**Comment by Artim96** [comment]
I'll have to keep an eye on it, but it might have been a simple mix of user error and aggressiveness of Android. I didn't have battery optimizations enabled for this app and I guess Google increased the aggressiveness of that feature around the time of the 053n update.

Of course that's something that shouldn't even happen in the first place. Any app that currently is set as always on VPN should be exempt from any battery optimizations. I'll give that feedback to Google but no idea what that will help.

**Comment by ghostersk** [comment]
Hi, I think it is related to App lock, if you set up the app to be accessible with Fingerprint or pin lock.
I must test it, but I believe after I disabled it for the RethinkDNS it works ok now.

**Comment by Artim96** [comment]
I never set that up. Also it crashed again last night so I mailed in the logs.

**Comment by ignoramous** [comment]
I saw the email.

For the crashes you're seeing, you'd need to send us a `bugreport` (if you're okay doing so, no pressure): https://developer.android.com/studio/debug/bug-report

**Comment by ignoramous** [comment]
The hardware memory sanitizer (ARM Memory Tagging Extension) isn't happy with CGo <-> JNI boundary, I think. 

```
02-17 12:02:54.236  root     0     0 I trusty  : [GF_TA][E][gf_algo_auth][gf_algo_do_post_authenticate] skip stage=3
02-17 12:07:51.671 10477  4742  4784 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4784 (Thread-19), pid 4742 (elzero.bravedns)
02-17 12:07:52.497 10477 26888 26888 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : Build fingerprint: 'google/oriole/oriole:13/T2B3.230109.004/9554463:user/release-keys'
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : Revision: 'MP1.0'              
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : ABI: 'arm64'                   
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : Timestamp: 2023-02-17 12:07:51.853512669+0100
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : Process uptime: 92319s         
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : Cmdline: com.celzero.bravedns  
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : pid: 4742, tid: 4784, name: Thread-19  >>> com.celzero.bravedns <<<
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : uid: 10477                     
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x0  0000000000000000  x1  00000000000012b0  x2  0000000000000006  x3  0000000000000008
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x4  0000000000000001  x5  0000000000000001  x6  0000000000000000  x7  000000000000000a
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x8  0000000000000083  x9  00000076bf5e3208  x10 000000000000003e  x11 00000076bf38e16a
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 0000004001cf7000  x15 0000004001cf6000
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x16 000000769014f340  x17 00000076902467f0  x18 000000768f1e0000  x19 0000000000001286
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x20 0000007690246690  x21 0000004000210000  x22 0000000000000000  x23 ffffffffffffffff
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x24 00000076bed94a00  x25 ab6ec7d966cdcd10  x26 0000000000000000  x27 0000000000000010
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     x28 0000004000930ea0  x29 0000004001cf6db8
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :     lr  00000076bee7d794  sp  0000004001cf6dc0  pc  00000076bee98998  pst 0000000080001000
02-17 12:07:52.498 10477 26888 26888 F DEBUG   : backtrace:                     
02-17 12:07:52.498 10477 26888 26888 F DEBUG   :       #00 pc 000000000024a998  /data/app/~~AbNYNOmT330xmapVZ_1GDA==/com.celzero.bravedns-lvA0hMYlntQ6wUsoJwpYjg==/base.apk
02-17 12:12:55.380  root     0     0 I trusty  : [GF_TA][E][gf_hw_dc][hw_set_current_operation] cali_flesh_max_frame_index = 0

```

As a stop gap (perhaps, forever even), we've disabled MTE on Rethink starting `v054` ([download](https://rethinkdns.com/download))

https://github.com/celzero/rethink-app/blob/a4fd107e5be6cccecb80c636044cce87dd41d830/app/src/main/AndroidManifest.xml#L35

**Comment by Artim96** [comment]
Thanks, I'll report back once I can tell if that has worked.

**Comment by Artim96** [comment]
So far it's working as supposed. Bug seems to be fixed.

**Comment by ignoramous** [comment]
> So far it's working as supposed. Bug seems to be fixed.

It is a workaround (: If Google takes that away in the future (which they might as it is a security extension), we're in trouble (on Pixels at least).

**Comment by ignoramous** [comment]
Hi @Artim96, got another contact today that the app version `v054a` crashes repeatedly on Android 13. Just want to confirm if it is going fine for you?

**Comment by Artim96** [comment]
> Hi @Artim96, got another contact today that the app version `v054a` crashes repeatedly on Android 13. Just want to confirm if it is going fine for you?

Hey,
for me it's running great. Meanwhile I'm already on 14 beta and it's working unchanged. So as long as the person isn't running the latest 13 PQR beta 3 that I never got, I can't confirm that the app is still crashing.

**Comment by ignoramous** [comment]
- #1561
