### ISSUE TITLE
Problem with latest AdGuardHome

### ISSUE THREAD

**Issue by skibbipl** [celzero/rethink-app#789]
I'm using self-hosted AdGuardHome DNS server over https (https://domain.tld/dns-query) configured in Rethink DNS on my android phone. Today I upgraded AdGuardHome to latest v0.107.24 and Rethink stopped working. I'm getting SEND_FAIL errors in log. After downgrading to v0.107.23 everything is back to normal.
My other devices using AdGuardHome are working fine with latest version.

**Comment by ignoramous** [comment]
Sounds like you updated AdGuard Home to a new version and then Rethink started showing `SEND_FAIL`s? Can you please check with AdGuard Home first? I don't use AdGuard Home, so it is hard to tell what went wrong here.

**Comment by skibbipl** [comment]
Yeah, I think it's a AdGuardHome issue. https://github.com/AdguardTeam/AdGuardHome/issues/5518
