### ISSUE TITLE
Please add these rules to rethinkdns.

### ISSUE THREAD

**Issue by biange200** [celzero/rethink-app#796]
https://github.com/Potterli20/file

https://github.com/Potterli20/file/tree/main/Domains

https://github.com/Potterli20/file/tree/main/ad-hosts

<details>
<summary>screenshot</summary>

github:

![Screenshot_20230227_235627.jpg](https://user-images.githubusercontent.com/37582806/221613754-6d098fd4-c9c0-4a0f-afdc-804afb1859ae.jpg)
</detatils>

I really need these rules, please deal with them as soon as possible.

**Comment by mrovx** [comment]
You may ask here [serverless-dns/blocklists](https://github.com/serverless-dns/blocklists/)

**Comment by ignoramous** [comment]
Please track inclusion here: https://github.com/serverless-dns/blocklists/issues/146

There appear to be many lists maintained by Potterli, but the origin of the domains part of those list remain unclear to me, as do the categories (security / privacy / tracking / social networks / dating / gambling / adult etc).
