### ISSUE TITLE
Always-on VPN: App stopped but app thinks it isn't 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#799]
A user says,

> Rethink appears to be stopped, but when you start it it asks you whether you're sure you want to stop it
>
> Yes... it happens when I switch on my phone after having it shutdown
>
> I was just able to reproduce it.
Maybe it's also worth mentioning, that I have the app also in work profile running and this only happens on the main profile
>
> On ArrowOS

<details>
<summary>stop but how...</summary>
Screenshot:

![IMG_20230301_055552_148](https://user-images.githubusercontent.com/852289/222013901-6ce0775e-085a-429a-8aa3-bd1d0e472f09.jpg)
</details>

**Comment by hussainmohd-a** [comment]
Fixed: 5bf6082
