### ISSUE TITLE
On older Android, system buttons are white on white and very hard to see

### ISSUE THREAD

**Issue by Porkepix** [celzero/rethink-app#802]
A similar issue was reported for example there: https://github.com/beemdevelopment/Aegis/issues/531 if it might help to fix.

The issue is here seen with a stock Android 8.0 (Oreo). Device is an Xperia XZ, so it's not heavily modified Android.

<details>
<summary>
See screenshot
</summary>
notice the softbar with back, home, and recents button:

![Screenshot_20230305-224149](https://user-images.githubusercontent.com/709500/222987806-a2e1dfaf-cd32-492b-a890-b37a81315a2d.png)

</details>

**Comment by ignoramous** [comment]
Thanks: The app mostly uses all the default Android widgets and styles. We don't style it that much.

re: "system buttons": what are these?

**Comment by Porkepix** [comment]
> Thanks: The app mostly uses all the default Android widgets and styles. We don't style it that much.
> 
> re: "system buttons": what are these?

The triangle, circle and square that are the default system buttons provided by Android to go back, go home or use the app switcher.

**Comment by ignoramous** [comment]
"Softbar" that's what its called. Gotcha. Noted (:

**Comment by ignoramous** [comment]
Ref: https://github.com/beemdevelopment/Aegis/pull/540
