### ISSUE TITLE
Switching theme reset position of the scrollable button bar under apps and firewall

### ISSUE THREAD

**Issue by Porkepix** [celzero/rethink-app#803]
In the application, under firewall and apps, there's a thin scrollable bar with different buttons, the last one being the themes switcher. But once clicking the themes button to switch it, the bar scrolls back completely to the left, so if user needs to switch several times the theme, they have to scroll back to the button everytime, which is pretty annoying from a usability standpoint.

Also, there's a completely empty space under that bar, why make it scrollable rather than moving the buttons into the empty space below?

**Comment by ignoramous** [comment]
Thanks for the feedback. The scroll is unavoidable as the activity is created from scratch after applying the new theme, causing a complete state reset. Expect these buttons to mostly go away in a distant (future) release. We continue to tweak the homescreen in every release (even the minor ones).

**Comment by ignoramous** [comment]
Related: #453
