### ISSUE TITLE
Strings: Incorrect wording

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#805]
https://github.com/celzero/rethink-app/blob/ec7402389c613a9f165ba0860b99b8e363eb7d4a/app/src/main/res/values/strings.xml#L1020

Check other strings.

**Comment by hussainmohd-a** [comment]
Fixed string (`firewall_rule_domain_trusted_univ_desc`). 
Review pending for other strings

**Comment by hussainmohd-a** [comment]
reviewed most of the string literals in `strings.xml` and corrected any incorrect wording. Closing this issue for now. However, we will reopen it if needed.
