### ISSUE TITLE
v054 UI bug: Misaligned grid

### ISSUE THREAD

**Issue by PoneyClairDeLune** [celzero/rethink-app#806]
![image](https://user-images.githubusercontent.com/88174309/223359050-73a2d8ba-fbca-4e07-9803-2853a540a803.png)

The first row of the grid on the app's home screen is misaligned.

**Comment by hussainmohd-a** [comment]
Fixed: [9ed5c5c](https://github.com/celzero/rethink-app/pull/809/commits/9ed5c5cdee442559c02370338bcfa3f1101ffc7e)
