### ISSUE TITLE
Primary and secondary DoH

### ISSUE THREAD

**Issue by Potterli20** [celzero/rethink-app#811]
Can't write two doh?
I like two dohs or more on one page

**Comment by ignoramous** [comment]
Sorry, can you please be more elaborate?

**Comment by ignoramous** [comment]
DoH doesn't need primary / secondary entries unlike Plain old DNS.

**Comment by ignoramous** [comment]
The way Rethink is architected is, you can specify multiple IPs against the domain name of your DoH server and Rethink would use all of those. That said, we'll think about implementing a secondary DoH URL (but I am not yet convinced about the value of having it and not sure why AdGuard has it either).

**Comment by ignoramous** [comment]
> Because I have two DOHs
> Such as:https://dns-cdn.trli.club/doh/ad-dns
> https://dns-cdn.trli.club/doh1/ad-dns

Thanks, but the IPs for both the DoHs is the same (v4: `81.28.12.12`; v6: `2a03:90c0:999c::12`); so what's the point of having two DoHs if only the URL *path* differs?

**Comment by ignoramous** [comment]
> If the other one is not available, they can use the standby one

Btw, implemented #211
