### ISSUE TITLE
Unnamed instead of application name

### ISSUE THREAD

**Issue by 8itlew7r** [celzero/rethink-app#812]
Rethink v054
Device: Xiaomi M2006C3LG, Brand:Redmi
Android Target: 10.0 (SDK 29 Q)
Display: 720x1448 - xhdpi
CPU ABI: armeabi-v7a, armeabi

Logs usually show unnamed instead of an application name.

My guess is that I'm in a different user and not the main user. And I remember that this is not a problem in the main user.

![Screenshot_2023-03-08_15-46-50_1](https://user-images.githubusercontent.com/127256828/223655965-f91cfa45-34c0-417e-a88d-17e918860e7f.png)

And it randomly blocked an application for some unknown reason.

**Comment by 8itlew7r** [comment]
> Thanks. Rethink could potentially "guess" names of these apps in other profiles.
> 
> I'm surprised how traffic from other profiles / users end up in the main user where Rethink is running?

No, I'm sorry, I mean I'm in a different user, the Rethink app is stopped in the main user, I only mentioned it because I don't have this problem in the main user.

**Comment by 8itlew7r** [comment]
By the way, this problem is not that big a deal, nor the random blocking of applications, I just want to bring this to your attention.

**Comment by ignoramous** [comment]
> It seems like it's fixed when I reload the list of apps in Rethink, so I'm assuming it's also fixed the random blocking of apps.

You mean, when you clicked refresh in "Apps" screen, the unnamed apps shown in the network logs (secondary user) went away?

**Comment by 8itlew7r** [comment]
![Screenshot_2023-03-09_03-13-57_1_1](https://user-images.githubusercontent.com/127256828/223820641-c7c06710-184e-4409-9b18-a41decaf88c1.png)

Sometimes it works. I also use Island to freeze apps in second profile.

**Comment by ignoramous** [comment]
`v055` I believe has a fix to fetch app-name from the primary user? @hussainmohd-a link to the commit and close this bug, if that's the case?

**Comment by ignoramous** [comment]
Various fixes for this, but the key one is: https://github.com/celzero/rethink-app/commit/5bc7a632ad10fbfc39ba0b56828118994d249c6b
