### ISSUE TITLE
Wildcard rules not accepted when containing -

### ISSUE THREAD

**Issue by Artim96** [celzero/rethink-app#814]
First of all, big thanks for the v054 update, that's really great work. Though I've found some small bug when adding a domain with a wildcard to the general rule set, that contains a dash. *.domain.com is recognized as a valid domain, yet *.do-main.com is said to be an invalid domain (actually it's the same with *.domain*.com, like when you want to maybe sure all those beacons.gvt3.com domains are blocked, no matter if they are included in any list or not by simply blocking *.gvt*.com), yet it obviously it's a valid domain as it's a normal registered domain (and I doubt Rethink even asks the DNS if it's valid).

**Comment by ignoramous** [comment]
Thanks. Painful bug that should be straight-forward to fix. Will get it in `v054b` (due launch in a week or two). Btw: Did the workaround for #786 make a difference?

**Comment by Artim96** [comment]
Has been working for now, just wanted to give it a few days to be sure.

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/hussainmohd-a/rethink-app/commit/dbc0a30fcfdb6de494e73bfa33f6e2733f9ebb23
