### ISSUE TITLE
Show DNS Transport status as known to the tunnel

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#815]
Today, the app simply labels every selected DNS as "Connected" when it might not be (DNSCrypt cert refresh failures, for example). From the `resolver` of the `tunnel`, it is possible to retrieve `status` of a `transport` given an `id`. Show that in the UI instead.

**Comment by hussainmohd-a** [comment]
Allow users to quickly identify whether the selected DNS entry is currently active or experiencing issues. 
**Limitations:** The transport status is not updated in real time as the status changes. 
Fix: https://github.com/celzero/rethink-app/pull/822/commits/0bd7dc07ac96e6348670b18821458d7d516e83a8
