### ISSUE TITLE
If Blocklists / rules exist, DNS Logs UI should highlight that factt

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#817]
1. Instead of showing an `Allowed` chip, perhaps the UI must show `Blocklists` if set in the returned `Summary` obj. There's also a smaller of handling `10+ IPs` for multi-answer responses.
2. Some users are confused at blocked DNS queries being `Allowed`. Perhaps should also change the label to `Answered` instead?
3. If a given domain matches any existing DNS rule, then the label should go `May be blocked` with an orange border?

**Comment by hussainmohd-a** [comment]
The UI of the DNS logs has been updated to include a highlight, indicating the availability of blocklists for any given DNS query. Furthermore, a new filter named `Maybe Blocked` has been added to the logs, which enables users to easily filter out all DNS queries that might have been blocked or contain blocklists. Ref: https://github.com/celzero/rethink-app/pull/822/commits/a043fcf8dadbd6dc1a979b18487902a1a40bd186
