### ISSUE TITLE
Stats screen "top blocked domains" does not account for alg-based dns blocks

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#819]
As in the title.

Related: https://github.com/celzero/rethink-app/issues/818

**Comment by hussainmohd-a** [comment]
The top blocked domains will now display stats based on the app mode. In **_DNS-only_** mode, the blocked domains will be picked up from DNS logs, while in **_DNS+firewall_** mode, the blocked domains will be picked up from network logs.
