### ISSUE TITLE
Orbot v16 integration broken in v054

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#820]
In my tests, Tor-as-a-proxy (TCP) was set to `127.0.0.1:65535` when Orbot was listening on `127.0.0.1:9050`. Setting SOCKS5 proxy to explicitly forward to `127.0.0.1:9050` did work.

Related: #798

**Comment by hussainmohd-a** [comment]
This issue is being closed since the tests carried out did not result in any failures related to Orbot integration. However, if more information or logs become available, we may reopen this issue or create a new one.
