### ISSUE TITLE
[FEATURE REQUEST] DNS whitelist - allow import

### ISSUE THREAD

**Issue by 0xlne** [celzero/rethink-app#828]
As a user, I currently have ~500 whitelisted domains in my other DNS filter apps.
In addition, I run a "block all/whitelist on demand" config, meaning I will need to painstakingly manually copy/paste these whitelisted domains into Rethink.
Would it be possible to have an import/export only for user-set DNS filters?

**Comment by ignoramous** [comment]
Related #293

**Comment by 0xlne** [comment]
Thanks for referencing the duplicates; I will close this one to avoid clutter.
