### ISSUE TITLE
Help with the translation of "Bypass Universal" into Tagalog.

### ISSUE THREAD

**Issue by 8itlew7r** [celzero/rethink-app#830]
I am having a hard time translating "bypass universal" into the language of the Philippines, which is Tagalog.

Could I translate it as "Lusutan ang Pangkalahatang Firewall", which translates directly to "Bypass Universal Firewall"? Or should I just leave it alone?

Should "Bypass Universal" be "Bypass Universal Firewall"? Because there's another option called "Bypass DNS & Firewall".

**Comment by ignoramous** [comment]
Thanks for your interest in translating Rethink. Appreciate it (:

You can opt to translate it to *Bypass Universal Firewall* if that is more descriptive in Tagalog.

Sorry, I couldn't get to this issue earlier. It fell of my radar.
