### ISSUE TITLE
Validate domain chars in rules

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#831]
[RFC1035 2.3.1](https://rfc-editor.org/rfc/rfc1035#section-2.3.1)

See also: [serverless-dns/triecodec.js](https://github.com/serverless-dns/trie/blob/01336af6a0c4c962f474fcfe4ebf3bfcb83dcb35/src/codec.js#L23-L26)

**Comment by hussainmohd-a** [comment]
We have implemented a wildcard pattern matching feature based on **RFC1035** to check if the entered URL is a valid wildcard domain. For adding domain rules, we are relying on the **WEB_URL** and **DOMAIN_NAME** patterns available in the default built-in Patterns Java class.
