### ISSUE TITLE
Cannot start Rethink once stopped (/e/OS)

### ISSUE THREAD

**Issue by muellerto** [celzero/rethink-app#833]
Rethink has a button at the bottom of it's main screen, Stop or Start, depends on the situation. Pushing this button is not good.

When you have a well configured, good and solid running Rethink with lots of sophisticated settings and rules and you stop it, you can't start it again. You can, but it will not work anymore. All apps which want to have any Internet access fail then consequently and it will not be solved by itself.

I can always reproduce this.

The only way to get over this situation is a reboot of the device. Perhaps you can also kill and restart the Rethink app, never tried this.

/e/ 1.8.1 on Android 11
Rethink 053n from F-Droid

**Comment by ignoramous** [comment]
Hi: Thanks for your bug report (:

Can you please capture `adb logcat` output (if you know how) from around _exactly_ the time when Stop / Start doesn't work. from your /e/ device?

To me, this look like a bug in /e/OS, because the behaviour you describe hasn't been reported otherwise.

**Comment by muellerto** [comment]
My wife has a second device, same type, all very similar (because I configured this, too). What I found out now is: her device doesn't show this behavior. She can stop and start Rethink with this button and it will work again. So the device plays a roll here, perhaps any setting in the OS I changed on my device and not on her's.

Will see if I can get a log. I did this once, but this was 2 years ago ...

**Comment by muellerto** [comment]
I made a logfile. This file contains the following:
- 16:27 Stop RethinkDBS using the Stop button
- 16:28 Bromite does a successful web access, completely unprotected
- 16:29 RethinkDNS is started again using the Start button, the message "protected" occurs after a second
- 16:30 Bromite does a successful web access??? I'm not sure, browser cache involved?
- 16:30 Subway Tooter fails to access it's Mastodon server. And this will remain from now on.

[logcat.txt.gz](https://github.com/celzero/rethink-app/files/11011505/logcat.txt.gz)

**Comment by ignoramous** [comment]
Thanks.

From the logs, it looks like Private DNS is set to `fritz.box` which is not responding. I see that RDNS itself was setup as expected (though, I see some errors in Android's network stack that seem related). Is connecting to `fritz.box` intended to work?

**Comment by muellerto** [comment]
This fritz.box is my wifi network. It did work before I stopped Rethink, it worked while Rethink was stopped and it should also work after I started Rethink again, that's what I would expect.

The problem, that it doesn't work after a restart, doesn't depend on that concrete wifi network. It happens also in every other wifi network I tried (checked this at work).

And look, it does indeed work again after a device reboot (including Rethink running). Something must be there on this Start button which is different under some special conditions.

**Comment by ignoramous** [comment]
> It did work before I stopped Rethink, it worked while Rethink was stopped and it should also work after I started Rethink again, that's what I would expect.

Search for `fritz.box` in Rethink's DNS logs, and you should see that it isn't resolved as expected (because `.box` is a public TLD without any public DNS records, only the local wifi network knows what a `fritz.box` is, is my guess). 

Two things to get this to work:
- Use a non-public TLD like `.internal` or `.local` or `.lan` instead of `.box` (`v054`+ should be able to resolve those internal queries just fine).
- Setup public records for `fritz.box` at your domain nameserver / registrar. 
- Set Rethink to connect to "System DNS" and see if things then work.

**Comment by muellerto** [comment]
The problem is I don't know what this fritz.box indeed is. I never defined it anywhere or typed it in any edit box, never. This is a default. But as I said, the problem happens also in other networks.

This "System DNS" setting is a good hint. When I use this it seems to be good. When I start Rethink again it works. When I had it on "RethinkDNS" (and then "RDNS plus") it was reproducible not good. Oh, "RethinkDNS" with "RDNS default" works also.

**Comment by ignoramous** [comment]
So, if you're using `fritz.box` (and can't change it to `fritz.local` or `fritz.internal` or `fritz.lan` etc) then "System DNS" is what you must use. This is okay, since `fritz.box` seems to be DNS-over-TLS (encrypted) endpoint.

> But as I said, the problem happens also in other networks.

Not sure, but you can [turn off Private DNS](https://archive.is/lVMkZ) (not set it to "Automatic" or anything), or use rdns in "Firewall-only" mode.

**Comment by muellerto** [comment]
I checked this now on both wifi networks and on the plain mobile network I have around.

The entire problem depends on the setting where you can choose between "System DNS", "Other DNS" and "Rethink DNS".

When this setting is on "Rethink DNS" and this is internally configured as "RDNS plus" the problem happens. All other options ("RDNS Privacy", "RDNS Adult", ...) work correctly, this means I can stop and start as often as I want. When "RDNS plus" is checked a start after stop fails.

But I can live with that. I have it on "RDNS Privacy" now.

**Comment by ignoramous** [comment]
> When "RDNS plus" is checked a start after stop fails.

That means, some blocklist you've setup is likely blocking resolution of the Private DNS domain. You can check *DNS Logs* to see if the queries to `fritz.box` or whatever the Private DNS domain is, is blocked by tapping on its entry in the logs, and clicking the red-coloured chip that shows up in the bottom-sheet.

The rdns website tells me that `fritz.box` is blocked by two lists: `Adult (cbuijs)` and `Vanity top-level Domains (cbuijs)`: https://archive.is/LS0bh

**Comment by ignoramous** [comment]
Closing this as it doesn't look like there's *one* specific issue with the app, but rather the setup in which the app is being run. For example, with `.local` / `.lan` / `.box` domains, DoT / DoH won't work. Rethink doesn't support untrusted / user-provided TLS certs (even if it did, it is kind of a security issue, but we could consider supporting it behind a setting that can be enabled but kept disabled by default; we'll think about it. [Intra](https://github.com/jigsaw-Code/intra) support this use-case, btw but it doesn't have the firewall functionality).

Feel free to re-open this bug / create a new one, if you need more clarity or help from us. Thanks.
