### ISSUE TITLE
Add root mode

### ISSUE THREAD

**Issue by Rexadev** [celzero/rethink-app#836]
instead of using Android's inbuild VPN fuction using root will allow user to use ReThink along with VPN apps like [InviZiblePro](https://github.com/Gedsh/InviZible)

**Comment by ignoramous** [comment]
Do these issues cover it?

- #78 
- #52

**Comment by Rexadev** [comment]
> Thanks. Do these issues cover it?
> 
> * [DNS: Root mode #78](https://github.com/celzero/rethink-app/issues/78)
> * [Integrate Wireguard #52](https://github.com/celzero/rethink-app/issues/52)

Yes

**Comment by ignoramous** [comment]
Closing a dup of the above. Please feel free to reopen.
