### ISSUE TITLE
Websites fail to resolve

### ISSUE THREAD

**Issue by Doc-4** [celzero/rethink-app#838]
Some websites fail to resolve using latest update using RDNS Max as opposed to Sky. I have no related firewall settings or blocklists enabled. Reddit.com is one such example, trying to load it on max returns this: DNS_PROBE_FINISHED_NXDOMAIN
Switching to Sky fixed the problem as far as I can tell.

**Comment by ignoramous** [comment]
As part of network engine changes we undertook to support per-app domain allow/deny lists, some websites may never load if ads are blocked.

That aside, I've never seen `max.rethinkdns.com` refuse to answer queries that `sky.rethinkdns.com` does. That's a first. Worrying if you're observing it 100% of the time. Is it only a select few domain that `max` refuses to resolve? If so, apart from reddit.com (which I see `max` resolves just fine), what are those?

`max` doesn't do DNSSEC and is a recursive resolver, whereas `sky` supports DNSSEC and is a stub resolver. So, there absolutely could be some observable disparities between the two.

**Comment by Doc-4** [comment]
I'm not the most familiar with how every part of this project works on a low level, or I'd try to better understand why switching that had this result. Imgur didn't work at the time either. Previously my only configurations were running some blocklists under the DNS section and using DNS only mode with the default DNS selection. Could the issues stem from something that wiping config/app storage and starting over would fix?

**Comment by Doc-4** [comment]
This strange behavior stopped after a day or two, sorry for the inconvenience
