### ISSUE TITLE
DNS Proxy in Termux not working (Android 13)

### ISSUE THREAD

**Issue by MasterKia** [celzero/rethink-app#839]
Rethink v053n from F-Droid. LineageOS 20.0 (Android 13).

A command-line app running inside Termux is exposing a DNS proxy on `127.0.0.1` port `2053`.

If I use this command inside Termux:
`dig ANY github.com @127.0.0.1 -p 2053 +short`
Then I'll receive a valid DNS response, indicating that the DNS proxy works.

I went to to Rethink; DNS => Configure => Other DNS => DNS proxy => Add new proxy => `App: Termux`, `IP Address: 127.0.0.1`, `Port Number: 2053`; added that a proxy and enabled it.

Then I went to any app that makes a DNS request, and after that I checked the DNS logs in Rethink and all the DNS requests failed with the code "No answer" `BAD_RESPONSE`.

Is there any way to diagnose this? The phone is rooted too.

**Comment by ignoramous** [comment]
Something could be up with Lineage, but will you please try `v054` ([f-droid](https://f-droid.org/packages/com.celzero.bravedns)) and let us how it goes?

**Comment by ignoramous** [comment]
Thanks. What's this command line app that's being run in Termux? I'll have to test this to figure out what's going on

**Comment by ignoramous** [comment]
I'm going to have to test this setup and get back to you. I'm borrowing a rooted phone for this, so testing should be smooth. Give me a few days.

**Comment by ignoramous** [comment]
Chisel seems to be only responding on TCP port 2053 and not UDP. Currently, the DNS transport doesn't switch from UDP to TCP on errors, it forwards larger requests (600 bytes or more) over TCP, otherwise over UDP.

Plan to impl TCP failover in `v054b`.

Alternatively, if Chisel can be setup to also respond on UDP 2053, then that should work with the current version `v054a` too

**Comment by ignoramous** [comment]
> Plan to impl TCP failover in v054b.

Done: https://github.com/celzero/firestack/commit/9e343008dfa8a88548a8a79a8e9ddc64a629e952

will land in `v055` (day or two from today).
