### ISSUE TITLE
Android 11 Package Visibility

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#84]
Android 11, in a bid to prevent fingerprinting of users, is restricting packages returned to preinstalled apps.

[developer.android/v/11/privacy/package-visibility](https://developer.android.com/about/versions/11/privacy/package-visibility).

`QUERY_ALL_PACKAGES` permission would however bypass that restriction and is allowed for _Security_ apps.

**Comment by hussainmohd-a** [comment]
Introduced the permission `android.permission.QUERY_ALL_PACKAGES` to handle the above.
