### ISSUE TITLE
Bypassed apps are getting blocked

### ISSUE THREAD

**Issue by GBT7** [celzero/rethink-app#841]
It appears in 0.5.4a, bypassed apps are getting blocked, ~~sometimes even when "allow bypass" is switched on.~~

**Comment by hussainmohd-a** [comment]
Hi @GBT7, Thank you for reporting the issue. Could you please share some screenshots of the issue you are facing? This will help us to debug the issue more effectively.

**Comment by ignoramous** [comment]
> sometimes even when "allow bypass" is switched on

*Allow bypass* is unrelated to the firewall. It is a VPN-level setting which lets requesting apps to bind to VPN's underlying network (either wifi / mobile) instead of the VPN's virtual network.

**Comment by hussainmohd-a** [comment]
> I just realized that the apps which have "bypass universal" since last update are all blocked until I click into them in the network log, and then they start actually acting like bypassed apps after I click on them.

Fixed. It seems there was an issue while migrating the database from the previous version to v054a. Additionally, some of the UI-related fixes regarding the bypass rules have also been addressed.

The fixes will be part of v054b. 

ref: 06accda,  413c914, 5c46b34

**Comment by ignoramous** [comment]
`v054c` is live on both [F-Droid](https://f-droid.org/packages/com.celzero.bravedns/) and [Play Store](https://play.google.com/store/apps/details?id=com.celzero.bravedns). Please update and this bug should be fixed.

If it hasn't, feel free to reopen and we'll take another look. Thanks.
