### ISSUE TITLE
New functions 

### ISSUE THREAD

**Issue by Naster17** [celzero/rethink-app#842]
Add a function So that when blocking IP or DNS these rules were automatically added from the logger to the firewall section. Because if you change the rules for many IP they are all hard to find

**Comment by Naster17** [comment]
Add new features for root users. For example, remove the annoying icon VPN in raskbar

**Comment by ignoramous** [comment]
> Add new features for root users. For example, remove the annoying icon VPN in taskbar

The VPN notification is shown by Android, not by the app. These are dismissable on Android 13+, but not prior to that. Besides, see:
- #78 
- #66  

> Add a function So that when blocking IP or DNS these rules were automatically added from the logger to the firewall section. 

Sorry, I don't understand. Isn't it already possible to change IP / app rules from *Network Logs*. Tap on any log entry and a bottom sheet with various firewall-related options should show up.

**Comment by ignoramous** [comment]
Please feel free to reopen with a brief explanation in case you think your feature request / issue isn't resolved. Thanks.
