### ISSUE TITLE
Domains with a hyphen cause the wildcard verification to fail (firewall rules)

### ISSUE THREAD

**Issue by steinland1994** [celzero/rethink-app#843]
![Screenshot_20230325-020305.jpg](https://user-images.githubusercontent.com/126804672/227675062-accf8895-5a2a-44e3-b271-76659cefc53d.jpg)

**Comment by hussainmohd-a** [comment]
This issue is fixed and will be incorporated with the next release. 
Dup of: https://github.com/celzero/rethink-app/issues/814, https://github.com/celzero/rethink-app/issues/831
