### ISSUE TITLE
Network and DNS Logs not working on Android 6?

### ISSUE THREAD

**Issue by barkoder** [celzero/rethink-app#845]
Sub: Version 054a, Android 6.0. DNS log and Network log almost completely empty now. Only showing allowed requests. Isolated and Blocked system apps not showing up in log.

___

I updated from `053n (25)` to `054a (27)`. DNS logger and the app logger are not working properly on Android 6.0 after update. Also want to mention that I have no apps on "Blocked" list or "Allowed" list. Only on "Isolated" or "Bypass Universal" list.

To see if having my "isolated" apps on "blocked" works, I tried "blocking" all apps on the "isolated" list to see if they show up in the log, and it still doesn't work.

Prior to update, DNS and Network logs were very noisy, consisting of several blocked system apps and DNS queries every minute.Now, I don't know if they're being allowed or if they're being quietly blocked.

Thanks.

**Comment by ignoramous** [comment]
That sounds horrible. Can you please share a screen recording of what you're seeing?

**Comment by barkoder** [comment]
Okay I just rebooted my device and that seems to have fixed it.

The logger appears to be working normally now.

Sorry for bothering you.

I'll close this issue when after I've tested it for a while.

Thanks for the help.

**Comment by barkoder** [comment]
Okay back again after some testing.

Manual domain blocking doesn't seem to work.

I domain blocked `*.lenovomm.com` but `fsr.lenovomm.com` (among other subdomains) are still being "Allowed" in the DNS log.

I domain blocked `*.example.com` and `example.com` but https://example.com is still able to be curled through Termux.

The Network tab shows the "Input Devices" app as having been blocked from connecting by ReThink, but if I click on the app to check its own logger, it shows that it "Connected to 2 IP address(es)"

I've attached a screen recording to show this. Bear in mind I had to edit out ~13 seconds of video in between for privacy reasons.

https://user-images.githubusercontent.com/70430094/228007896-b230c40f-3a9f-4c14-9907-0cc65ff11526.mp4

--------------------------------------

Also want to show that "On-device blocklists" download fails. I don't know if I should open a new issue for this.

It used to fail in the previous version as well, but I hadn't reported it then.

https://user-images.githubusercontent.com/70430094/228009064-1553d2e8-1cdc-4cda-941d-943f57eaaa4f.mp4


---------------------------------------------

Also as I mentioned in the original post, the Network and DNS logger are *way* less noisy now(suspiciously less noisy), than in the previous version.

Thanks.

**Comment by barkoder** [comment]
Okay, and why does the blocklist download fail? It used to fail even in the previous version.

**Comment by ignoramous** [comment]
Disable *Use in-app downloader* in *DNS* UI to see if the download then works?

**Comment by barkoder** [comment]
Okay that worked.

**Comment by ignoramous** [comment]
`v054c` is now live on both [F-Droid](https://f-droid.org/packages/com.celzero.bravedns/) and the [Play Store](https://play.google.com/store/apps/details?id=com.celzero.bravedns). DNS Logs now show `maybe blocked` if the *Firewall* may eventually block a given domain name depending on user-defined `trust` (allow) / `block` (deny) rules.

If the issues reported in this bug aren't resolved for you in `v054c`, please feel free to reopen. Thanks.
