### ISSUE TITLE
Aurora Store not working, Chromium not properly loading

### ISSUE THREAD

**Issue by BayLee4** [celzero/rethink-app#850]
When enabling Rethink (in both DNS and DNS + Firewall modes), Aurora Store fails to download applications. However it is not blocked by any rules, and using 'Bybass DNS & Firewall' or 'Bypass universal' has no effect, only 'Exclude' make it works again.

Chromium (both standalone and the system webview) also has a problem loading pages: they load until some kind of timeout stop them (usually when the screen starts to dim, ~60 seconds).

I tried all settings (system dns, other dns, blocklist, no blocklist, no general firewall rules) but had no luck, only disabling Rethink seems to help unfortunately.

**Comment by BayLee4** [comment]
> My best guess is some DNS based block that's causing trouble, because I tried Aurora Store on my Android with rdns enabled, and it worked.

Does downloading works? Because entering the application (as in seeing the apps pages and available updates) works perfectly, it' just the downloading part wich fails.
If that matters: my device is a Pixel 4 XL, running GrapheneOS without Play Services

> Have you enable on-device blocklists?

Initially yes, but even after disabling it and playing with various DNS option (System DNS, DoH, RDNS Default, with/without DNS Leak prevention) the issue remains.

**Comment by ignoramous** [comment]
Able to download (with *Anonymous (insecure)* identity) just fine. Here's my blocklists: https://sky.rethinkdns.com/1:8B9lAokBAhGgXQLggAFUcyEAAAI=

I also have only 4 *Universal* firewall rules set:
- Block when device is locked
- Block when DNS is bypassed
- Block newly installed apps by default
- Block when source app is unknown

And no Aurora Store is allowed to connect over *metered* and *unmetered* networks without any other rules getting in the way (other than DNS blocklists of course).

---

You can see if any errors show up in the logs? If you know how, `adb logcat | grep GoLog` specifically when the issue happens to see what's going on.

**Comment by ignoramous** [comment]
Hi @BayLee4,

Will you please see if the issue persists with `v054c` ([F-Droid](https://f-droid.org/packages/com.celzero.bravedns/), [Play Store](https://play.google.com/store/apps/details?id=com.celzero.bravedns)). We've introduced a few tweaks in the way firewall works. If these apps still don't work, make sure that *none* of the apps are `Bypass DNS & Firewall`.

Closing this bug, but feel free to reopen in case the issue still persists. Thanks.
