### ISSUE TITLE
Feature Request: Routing

### ISSUE THREAD

**Issue by Kruegerrr** [celzero/rethink-app#869]
At its current stage, the Rethink app serves as a handy firewall for Android devices. Users can create domain/IP/app rules to allow or block certain connections and configure traffic to be forwarded to a SOCKS5 or HTTP proxy. However, this design lacks flexibility. For example, if I have established three proxy ports on my phone - a Tor proxy on port 2080, a proxy to my home server on port 2081, and a proxy to my company on port 2082 - I would need the traffic from my browsers to be forwarded to port 2080, the traffic from my SSH app to be forwarded to port 2081, and the traffic from my work apps to be forwarded to port 2082. I hope that the Rethink app will allow me to create routing rules to achieve this.

Fortunately, this functionality has already been implemented in some Chinese community-driven open-source projects initiated to circumvent [the Great Firewall of China (GFW)](https://en.wikipedia.org/wiki/Great_Firewall), e.g. [Project V](https://www.v2ray.com/en/configuration/routing.html). For Android implementation, cf. [SagerNet](https://github.com/SagerNet/SagerNet), [Matsuri](https://github.com/MatsuriDayo/Matsuri) and [NekoBoxForAndroid](https://github.com/MatsuriDayo/NekoBoxForAndroid). I sincerely hope the developer of rethink app will add this feature so that more advanced configurations can be achieved.

**Comment by ignoramous** [comment]
Hi there, the capability is there, but we haven't yet exposed it to the end user. We fully intend to ship in v055 (a release which is 2 to 3 months away): #229 

(closing as duplicate, but feel free to reopen if you think it was closed in error; thanks :)
