### ISSUE TITLE
[Question] Can I use this app as a local DNS resolver?

### ISSUE THREAD

**Issue by joe733** [celzero/rethink-app#872]
Can I map a hostname to an IP addresses on local network? When I connect to say `myhost.local.arpa` (in browser or NextCloud app), `rethink` re-directs to say `192.168.153.52`?

If not, is there any application yet that does so? (any mobile app, not pi-hole)

**Comment by ignoramous** [comment]
Hi:

[pDNSf](https://f-droid.org/en/packages/dnsfilter.android/) does this.

Rethink will add support for it, too: #316 

(closing as duplicate, but feel free to reopen; thanks for the feedback, appreciate it :)
