### ISSUE TITLE
In Logs, show all apps with the same uid

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#880]
A user writes,

> hi, when using the firewall in the logs I see being blocked "x app + 5 other app(s)". How can I see what the other 5 apps are that are being blocked?

**Comment by hussainmohd-a** [comment]
Now, there is no way to display the app list in the network log if there are more than one app. When you click on the app name in the bottom sheet of the network log, it will navigate to the app info screen. The 'i' icon on the screen will now show the list of app names.
