### ISSUE TITLE
[Feature] Add Adaway hosts blocklist

### ISSUE THREAD

**Issue by 1ennard** [celzero/rethink-app#891]
The blocklist is available here:
https://adaway.org/hosts.txt

Some description from [Adaway wiki](https://github.com/AdAway/AdAway/wiki/HostsSources) :
*Special hosts file for AdAway containing mobile ad provider.*

The list is rather small in size.

**Comment by ignoramous** [comment]
We removed it because it is unmaintained since Oct 2022 now. Besides the aggregate lists like 1Hosts / OISD / Hagezi contain the *AdAway* list in them. See: https://github.com/serverless-dns/blocklists/pull/152

**Comment by ignoramous** [comment]
Sorry, I forgot to ask: Do you strongly feel we should include AdAway even though it is unmaintained and included in other well-maintained lists like OISD, Hagezi, and 1Hosts?
