### ISSUE TITLE
v054a: "Block connections without VPN" erroneously disables local SOCKS5 proxy use

### ISSUE THREAD

**Issue by FLAGEL** [celzero/rethink-app#892]
When enabling "Block connections without VPN" in Android settings, Rethink disables configuring and running a SOCKS5 proxy. This behaviour is sensible for SOCKS5 proxies running on remote hosts as they will not be reachable. However, even with "Block connections without VPN" enabled, some local host interfaces (i.e. lo, tunX) are still reachable and can be bound by a SOCKS5 proxy*.

My suggestion is that when "Block connections without VPN" is enabled, keep Rethink being able to configure and connect to a SOCKS5 proxy. Instead, display a user message within the proxy configuration window noting that remote proxies are not reachable due to "Block connections without VPN".

*Functionality verified on Android 13 with NetGuard and Every Proxy.

**Comment by ignoramous** [comment]
Concur. This is an oversight from us. Big changes planned for the way proxies work in `v055` (#229) and we intend to fix this behaviour as part of those changes.

**Comment by hussainmohd-a** [comment]
In v055, changes have been implemented such that when in VPN lockdown mode, users are not allowed to set the app while configuring the SOCKS5 proxy. This adjustment prevents connection drops that occurred when an app was excluded during lockdown mode. [#r1297035087](https://github.com/celzero/rethink-app/pull/903/files#r1297035087)
