### ISSUE TITLE
Can't exclude app from dns and firewall rules

### ISSUE THREAD

**Issue by Rev-0** [celzero/rethink-app#895]
I've set the app just for it to block ads on my phone but when I excluded the Samsung Global Goals app, the ads still get blocked and I want that app to show ads, could you help me?

**Comment by ignoramous** [comment]
After "excluding" the app just to make sure there isn't any caching mucking with its behaviour, *Force Stop* and re-open it. Or reboot the phone.

I just checked, "exclude" functionality works just fine on `v054c` (the version I'm using).
