### ISSUE TITLE
[Request] Wireguard client built-in

### ISSUE THREAD

**Issue by candroid-man** [celzero/rethink-app#904]
RethinkDNS could be the all-in-one privacy solution for Android if there was a Wireguard/OpenVPN client built in that would allow users to simultaneously run their DNS, VPN, and firewall all in one application. To my knowledge there is not a way to do that currently with any application, which would make RethinkDNS one of a kind

**Comment by ignoramous** [comment]
Wireguard support will be out soon (7 to 10 days).

Duplicate: #52
