### ISSUE TITLE
v054c problem with autostart on powerup

### ISSUE THREAD

**Issue by raven9nine** [celzero/rethink-app#905]
The latest update v054c created an issue with autostart that did not exist in previous versions. I now have to start Rethink manually.

**Comment by GitteGitty** [comment]
Hi,

same here on a Pixel 6 and a Pixal 6a, both with GrapheneOS (Android 13).

No difference if "Always-on VPN" is selected or not and yes, similar to post #893.

Going back to v054a helps.

Nevertheless, thanks for the great app and your work!!

Best regards

**Comment by raven9nine** [comment]
Yes to always on vpn
Yes it is similar to https://github.com/celzero/rethink-app/issues/893
Android version 10

**Comment by FLAGEL** [comment]
I too am seeing the same issue, which started after installing v054c from F-Droid Store. Up-to-date Android 13 on Pixel device, Always-on VPN enabled.

**Comment by hussainmohd-a** [comment]
Related: https://github.com/celzero/rethink-app/issues/893, https://github.com/hussainmohd-a/rethink-app/commit/0979b6363082c36cb032bc113c6f48f1cb3824c6 will fix this issue

**Comment by ignoramous** [comment]
Regression: https://github.com/celzero/rethink-app/issues/1258#issuecomment-1987131283

**Comment by ignoramous** [comment]
Auto-start works in `v055` releases. Closing...
