### ISSUE TITLE
[v054] HTTP Proxy does not work

### ISSUE THREAD

**Issue by kowith337** [celzero/rethink-app#906]
I'm using F-Droid build and found web browsers throwing `net::ERR_CONNECTION_RESET` error while enabled HTTP(S) proxy.
This problem isn't occured in version 054a, however, I've downgraded back to 053n due to 054a onward are having fallback DNS settings but I'm not satisfy about it, I think I will wait until I can select fallback to be hard-fail (aka.  "None")

**Comment by ignoramous** [comment]
Just spoke to Hussain. It looks like the new proxy is up and running in `v054`! So, then this new proxy isn't working at all for you.

Are you trying to use a publicly available HTTP Proxy that we can test for the behaviour you're seeing?

**Comment by kowith337** [comment]
These are only proxy IP that I use with this app.
![pasteboard](https://gcdnb.pbrd.co/images/C1gaIvqdaWcS.jpg?o=1)
It didn't public proxy at all, however, it's only works when using same ISP, otherwise you will get `Access Denied` or `net::ERR_TUNNEL_CONNECTION_FAILED` instead.
Moreover, it's seems also affected to other apps that capable to use proxy by app settings, e.g. Lightning, Privacy Browser, monocles, etc. it will throw `net::ERR_TIMED_OUT` even I've allowed proxy IP and port as `bypassed`

As my quick test, only affected HTTP proxy, not SOCKS...

**Comment by ignoramous** [comment]
Apparently, the bug was we always assumed the proxy would support TLS (`https`). This has now been fixed in `v055`: https://github.com/celzero/rethink-app/commit/c2afd9adf846e8e3bee97058275c75c2a008f17a

nb: The app only supports `CONNECT` tunnels (both, `http` and `https`) with Auth.
