### ISSUE TITLE
[Error building from source - v0.5.4c] "error: no suitable constructor found for Integer(no arguments)"

### ISSUE THREAD

**Issue by danivideda** [celzero/rethink-app#909]
I tried building this project from source, but I got this error.
![image](https://github.com/celzero/rethink-app/assets/57628386/df1d2329-e051-43ec-a873-9554b3ada646)
The error is raised because of the absent of a parameter in `new Integer()`

I think it's because of `adroidx.room` package doesn't compile the code correctly. 
Here's the [source function](https://github.com/celzero/rethink-app/blob/2e0a19ebdcefd387c30a57a0acf4afa28c2d5e53/app/src/main/java/com/celzero/bravedns/database/RethinkRemoteFileTagDao.kt#L93) that generated the codes 
![image](https://github.com/celzero/rethink-app/assets/57628386/539f07a4-635e-48b7-9e96-5c3562d7d6de)

Strangely, my friend who has the same machine as me got this error too when building the project. 
So it might be the incompatibility with the machine.

### Machine spec:
MacBook with M1 chip
MacOS Ventura 13.3.1

### Android Studio
![image](https://github.com/celzero/rethink-app/assets/57628386/4874707a-bf7d-445c-a31e-4cea3365c3b0)

**Comment by danivideda** [comment]
### Solution

1. Re-clone the project (to clear caches, generated files, etc.)
2. Open in Android Studio
3. Go to `Android Studio` -> `Settings` -> `Build, Execution, Deployment` -> `Build Tools` -> `Gradle`
4. Change the Gradle JDK to `Amazon Coretto version 17` (If it doesn't show, choose Download SDK and look for it)
5. Now the build should be successful.
![image](https://github.com/celzero/rethink-app/assets/57628386/3cbd04c3-d2d0-4659-81c6-de882a32a737)


So the problem was the JDK itself. Previously, it used JDK 17 from JetBrains (aarch64). When I change it to the Amazon version aarch64, it worked. Maybe this is only happen on M1 machine

**Comment by ignoramous** [comment]
Thanks for reporting back. Glad you sorted it out without much sweat (:
