### ISSUE TITLE
Foreground notification and VPN state mismatch

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#91]
Foreground notification "Protected! Connected to BraveDNS + Firewall" is shown even when the VPN isn't connected at all.

Not sure in what cases this happens, but it was observed twice:

1. Once when the device woke-up from deep-sleep and a `fdsan` abort killed the app, but the foreground notification persisted, even though VPN connectivity was gone.

2. In another mysterious circumstance, the app showed "Waiting" (blue colour), but the VPN wasn't connected and yet the notification was showing.

This is frustrating as its misleading, especially when, as a user, I think the DNS queries are encrypted and apps that I have firewalled are in fact firewalled.

See also: #23, #83

**Comment by ignoramous** [comment]
One of numerous `fdsan` fixes we need: [github.com/Jigsaw-Code/Intra/commit/18f0d56f08d](https://github.com/Jigsaw-Code/Intra/commit/18f0d56f08d6e1058b38372bf80b7a545edf9e34)

**Comment by hussainmohd-a** [comment]
Known fdsan issues are fixed. (fdsan on ziparchieve/sql server/unique_fd). Also incorporated the changes form the Intra to fix the double closing of file descriptor. Testing in progress.
