### ISSUE TITLE
Port lost when editing IP rules

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#910]
Surprising UX when editing IP rules -- to reproduce:

1. Go to an app's IP/port rules
2. Add a new rule, e.g. `1.2.3.4:80`
3. Save the rule
	* IP and port are saved as typed (`1.2.3.4:80`)
4. Edit that rule
	* port is not included in the text field (`1.2.3.4`)
5. Save the rule again
	* port is now removed from the rule (`1.2.3.4:0`)

Using app version v054c.

**Comment by hussainmohd-a** [comment]
Now, users can edit the IP along with the port numbers in the edit option.
