### ISSUE TITLE
Some text is partially hidden in settings

### ISSUE THREAD

**Issue by Porkepix** [celzero/rethink-app#913]
<details>
<summary>See this joined screenshot for some settings text partially hidden (version 0.54c)</summary>

![Screenshot_20230520-172438](https://github.com/celzero/rethink-app/assets/709500/563a6637-f7a8-4574-91c3-7e6b1d1ecdd7)

</details>

**Comment by ignoramous** [comment]
Thanks. Should be a relatively easy fix.
