### ISSUE TITLE
054c : Backup Restore same version fail. Please consider as urgent fix.

### ISSUE THREAD

**Issue by lessload** [celzero/rethink-app#925]
From i saw in .db from two device. All same `packageName` have different `uid`. 
- it may cause the problem ?
- why config db rely on `uid` ? it seem like unreliable. why not use  `packageName` or something like hash of  `packageName`

In firewall application
- you can not separate `CustomDomain` and `CustomIp`  because it make rule order impossible ( like block only 8.8.8.8 but allow dns.google that have two ip, this seem impossible )
- or add `order` flags in .db , but seem too complex.

**Your app may got strike from play store. if you target on "ads block"**

**Comment by ignoramous** [comment]
Thanks. The issues you raise are valid and tracked elsewhere. See below.

> Your app may got strike from play store. if you target on "ads block"

You mean, our ban got banned?

> you can not separate CustomDomain and CustomIp because it make rule order impossible ( like block only 8.8.8.8 but allow dns.google that have two ip, this seem impossible )

Ordering is some what of an undefined behaviour at this point. We need to do better, but it isn't easy to fix either #781 

> From i saw in .db from two device. All same packageName have different uid.

Yeah we will impl this soon! #757
