### ISSUE TITLE
Browser blocked but still loding content normally

### ISSUE THREAD

**Issue by smexyy** [celzero/rethink-app#932]
For example.. let's say I'm browsing facebook from the browser and want to block the browser now and blocked and back again to **same page** it keeps scrolling and loding content normally.Once I close the facebook tab OR close the browser and reopen it, this moment it will be blocked.

Here is a video

https://streamable.com/gct87n

**Comment by smexyy** [comment]
Here is a video 

https://streamable.com/gct87n

**Comment by ignoramous** [comment]
`v055` now shows `Active` (with a green-coloured dot) in *Network Log*s against open connections. While this doesn't fix the bug reported here, it does help users identify any long-running connections.

**Comment by ignoramous** [comment]
More,

> I need to emphasis that this issue exist for any app. today I tried same steps in whatsapp and I blocked and still send and receive messages. plese do somthing to close open connection Or else. this is a serious bug.
> 
> By the way same issue exist in adguard only for newer verion 4.x.x.x and old version once i blocked the connection everything stopped.
> 
> In netguard working flawlessly once toggle off every connection stoppd.
> 
> We need a solution quickly

**Comment by smexyy** [comment]
Hello, any update.

**Comment by ignoramous** [comment]
It is not straight forward, but we know how we could potentially do this, as some of the pieces (not all) are already in place. Given the complexity, we're prioritizing other bugs.

**Comment by smexyy** [comment]
Thanks, I'am not expert but I think other firewalls reload the rules when toggle on or off button to close the open connection.

**Comment by ignoramous** [comment]
> other firewalls reload the rules when toggle on or off button to close the open connection

Nah, reloading rules does nothing. Rethink does acts on the *latest* rules always, just that it doesn't retrospectively apply them to past connections (regardless of whether they are *active*).

Some Firewalls resort to restarting the entire *firewall* engine on rule changes. This is something unacceptable to Rethink due to potential for packet leaks.

**Comment by ignoramous** [comment]
We've implemented closing all active connections from apps which app-level firewall rules (not IP-level / domain-level) have been *changed*.

In [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b): https://github.com/celzero/rethink-app/commit/cfbc4ee6618a3699b38980b2977331b44755aeb5

https://github.com/celzero/rethink-app/blob/02c16a99764b82bd4fbcc53187134cf944c47931/app/src/main/java/com/celzero/bravedns/service/FirewallManager.kt#L427-L441
