### ISSUE TITLE
Question and request

### ISSUE THREAD

**Issue by Mahantor** [celzero/rethink-app#935]
Is there a way to use both firewall app and vpn at the same time? Is it possible to add the ability to use root to the app, in the past, firewall apps used root, but currently no app has this feature.

**Comment by ignoramous** [comment]
Hi there,

We have been working on adding WireGuard for quite sometime now (a year at this point). The integration is *almost* complete #52 

I'm using a test version with WireGuard built-in, but isn't released to public yet.

If you are technical enough to build the app yourself, and are okay with an untested perhaps bug-ridden release, the code is here: https://github.com/celzero/rethink-app/pull/903

(closing this a dup of #52)
