### ISSUE TITLE
Suggested white list for core system apps

### ISSUE THREAD

**Issue by orbiterFan** [celzero/rethink-app#939]
This has become a staple security app on my phone. Thanks for the hard work.

I tend to over-block my phone and then cripple my browser and WhatsApp inadvertently. I sometimes have only two apps that are allowed to comm out, but I do not know the system apps that must be whitelisted.

Can you guys put a tag on the app's you recommend should not be blocked to allow system functionality?

This could be a feature with its own button, like four levels of lockdown for system apps. Full block, strict, moderate and relaxed.

**Comment by ignoramous** [comment]
Thanks for your kind words.

It is hard to recommend which apps to allowlist / whitelist. But the rule of the thumb is, allow *Google Play services* / *Google Play Framework*; and other OEM apps (which are specific to a manufacturer, and often change across updates, let alone different phone models).

That said: This is a good feature request. We'll explore just how we may solve this problem (as it is a really painful issue like you point out).

**Comment by ignoramous** [comment]
Duplicate: #163
