### ISSUE TITLE
Custom bootstrap DNS servers

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#94]
Today, the DNS over HTTPS client resolves IPs for the DNS over HTTPS endpoint over OS / network supplied DNS resolvers which may or may not block resolution of the DNS over HTTPS endpoint.

To circumvent that, consider supplying custom DNS resolvers to the `http.Client` [0].

The environment can still block / rewrite all requests on port 53... so that still remains unmitigated. 

[0] [nextdns/run.go#L427](https://github.com/nextdns/nextdns/blob/7106d9b4a265f93e32ff1b842e87e90cea7e480e/run.go#L427).

**Comment by ignoramous** [comment]
Whoops. Intra does support this but we don't use it. Miss!

https://github.com/celzero/brave-android-app/blob/97344853fa275eeec3438e63ac837260eeda9754/app/src/main/java/com/celzero/bravedns/net/go/GoVpnAdapter.java#L205

**Comment by ignoramous** [comment]
I mean, what intra does is better.

Having bootstrap servers might still help but not as much since, at the end of the day, it relies on plain old DNS without encryption.

**Comment by ignoramous** [comment]
https://github.com/Jigsaw-Code/Intra/issues/256

**Comment by ignoramous** [comment]
BraveDNS resolver IPs:

```
104.26.6.92
172.67.70.173
104.26.7.92
```

**Comment by ignoramous** [comment]
Adguard's `dnsproxy` supports a variety of bootstraps and the impl pretty straight forward too: [dnsproxy/upstream/upstream.go#L86](https://github.com/AdguardTeam/dnsproxy/blob/master/upstream/upstream.go#L86).

**Comment by ilikenwf** [comment]
And for those of us who use a VPN with internal hostnames, it would be nice if we could fallback to the custom bootstrap so that we can resolve our internal lan hostnames, unless it would be easier to let us add our own extra encrypted resolvers.

**Comment by ignoramous** [comment]
> we can resolve our internal lan hostnames, unless it would be easier to let us add our own extra encrypted resolvers.

You mean, split-horizon DNS (for ex, `.lan`, `.local`, `.internal` etc) must be resolved by OS/Network provided DNS? If so, that's a combination of #368 and #355 ?

**Comment by ilikenwf** [comment]
I don't...remember, sorry, but that sounds right.

I'm using GrapheneOS, and with the power of Wireguard split tunneling, it seems that "auto" mode at the OS level is working well enough.

**Comment by ignoramous** [comment]
We've decided to limit *bootstrap* servers to Rethink (DoH), Cloudflare (DoH), Google (DoH), and System DNS (plain old DNS): #211 

https://github.com/celzero/firestack/commit/2430028453ff2f38a11eab476314c4f19f6e8920 and https://github.com/celzero/rethink-app/commit/2adbb5d8b8bc1b7853b7768bda8ba5445be0662b

**Comment by mvevitsis** [comment]
> We've decided to limit *bootstrap* servers to Rethink (DoH), Cloudflare (DoH), Google (DoH), and System DNS (plain old DNS): #211 
> 
> https://github.com/celzero/firestack/commit/2430028453ff2f38a11eab476314c4f19f6e8920 and https://github.com/celzero/rethink-app/commit/2adbb5d8b8bc1b7853b7768bda8ba5445be0662b

Why?

**Comment by mvevitsis** [comment]
In dnscrypt-proxy you can add the IP address of your DoH server to the stamp and it will connect directly to the DoH server *without* any bootstrap. 

I have done this and set the fallback (bootstrap) DNS to null.

I would like to do the same in rethink.

**Comment by ignoramous** [comment]
> 
> nothing if the DoH setting page could accept an IP directly)

Please track
- #232
- #1223
