### ISSUE TITLE
Filters for metered and unmetered in All Apps screen

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#941]
A user writes,

> On the rethink apps, I blocked wifi and mobile data connections for all apps but allowed just wifi for a handful of apps. However, they don't show at the [top](https://postimg.cc/WDjFFvPf). The apps also do not show in the [allowed section](https://postimg.cc/WtsB9f2L) nor do they appear when I [search](https://postimg.cc/0brLv1gD) for them in the allowed section. But they appear when I search for them in the [all section](https://postimg.cc/VrQYrL8x). This is quite inconvenient. Is there a way to show these apps at the top? If not, please let me know there is no way.

via [r/rethinkdns](https://www.reddit.com/r/rethinkdns/comments/14ob5tj/make_rethinkdns_show_allowed_apps_at_the_top/).

**Comment by MicroBeast** [comment]
While at it. Network Log will list the app as Blocked on Dropdown list, due no differentiation to Wifi/Mobile. The target app do work otherwise.

**Comment by ignoramous** [comment]
A user writes,

> Oh. I was using netguard. On that app if only one of them is allowed it is still categorized at top alongside with both wifi and data allowed. I think it makes sense that way. Because most hundred apps are blocked and therefore with those only few apps that has one of them only allowed is buried among them. It's kind of difficult to find.

**Comment by hussainmohd-a** [comment]
Fix:https://github.com/celzero/rethink-app/pull/1581/commits/6427b2ff2ce81edc328028b3e1f6e8de8180c9ea
added new filter for `block: Unmetered` and `block: Metered` along with other firewall related filters which will be part of `v055o` release.
