### ISSUE TITLE
does Rethink start by itself after a reboot?

### ISSUE THREAD

**Issue by muellerto** [celzero/rethink-app#950]
I'm not sure anymore. Earlier versions did reliably start after each reboot. I never had to think about this.

With v54c I have the impression that it doesn't start by itself anymore. I'm never protected after a reboot, I must always switch it on manually, then it runs. And yes, it has been running before.

Rethink's auto-start option is on. The OS has also a VPN option to always use this VPN which is also on (can be off, doesn't matter).

/e/OS 1.12.3 on Android 12

**Comment by Dyras** [comment]
I've noticed the same. It doesn't seem to start automagically on boot on Android 12. I'm using a Fairphone 4.

**Comment by ignoramous** [comment]
Thanks. Bug creeped into v054c... Fixed in v055 (:

Ref: #893 (closing it as dup, pls feel free to reopen if you think this was a mistake).
