### ISSUE TITLE
Old rules of different app applied to new installation?

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#951]
After cycling through various app installations, one that I've just installed appears to have inherited a handful of domain trust rules from what appears to be a previous installation of Google Chat.  At a guess, this app was given a UID previously given to Chat*, and so Rethink has matched up the old rules despite the change in package name?

Note that the new app did start in Blocked state (the previous installation would have been in Isolated state).

---

\* I don't have a list of old UIDs and I'm not aware of a way to get this information to confirm, but I'm fairly sure I've seen this reuse happen before with file ownership on internal storage.

**Comment by GEkuL** [comment]
Hello guys,
I'm struggling with the related however, opposite trouble.
I wish to keep the settings for apps I temporary delete. But the probelm is that once I delete an app, it's Rethink setting gets removed, so I have to set everything up again and again on next installs.

Can we think of a feature to allow keeping settings for deleted apps?

Should I create a separate issue for that? (Wanted to start with the easier way discussing it here, and maybe move on in a separate issue).

What do you think?

**Comment by Terrance** [comment]
The "correct" solution would probably be to associate all rules and data to application IDs (i.e. `com.celzero.bravedns`), rather than UIDs (`10123`/`u0_123`), as that should prevent different apps inheriting each other's rules whilst also retaining rules across reinstalls (e.g. downgrades, switching between build signatures).

For removed apps, it would be nice if their rules etc. were persisted in a way that they could still be tidied up later -- perhaps an "Uninstalled apps" screen listing by application ID, where either individual or all app data can be removed?

**Comment by ignoramous** [comment]
Restoring rules for deleted apps is likely to cause confusion if retained for large periods of time, but I can see why some users would prefer it. We'll attempt to implement this in the coming months.

As noted above, Rethink only scrubs its database once every 3 hours, so there's a window where the rules are restorable after an uninstall.

**Comment by GEkuL** [comment]
@ignoramous 
> Rethink only scrubs its database once every 3 hours, so there's a window where the rules are restorable after an uninstall.

As I understand, it scrubs it at the time of update as well, which can be triggered from the app. And sometimes it needs to be triggered to be able to see newly installed apps.

But anyway, I'm happy that you considered implementing this feature :blush:

> Restoring rules for deleted apps is likely to cause confusion if retained for large periods of time

Not sure what you mean here, though. But as I understand, you can always check the rules now, and delete them for an app, if needed.

Retaining the rules for a large period of time can be my use-case, as I change a country and removing apps non relevant in the current one. But once I get back, I'll need those apps and the privacy set up already configured for them.

**Comment by ignoramous** [comment]
> > For removed apps, it would be nice if their rules etc. were persisted in a way that they could still be tidied up later -- perhaps an "Uninstalled apps" screen listing by application ID, where either individual or all app data can be removed?
>
> > Retaining the rules for a large period of time can be my use-case, as I change a country and removing apps non relevant in the current one. But once I get back, I'll need those apps and the privacy set up already configured for them.

please follow impl at:
- #978 

> The "correct" solution would probably be to associate all rules and data to application IDs (i.e. com.celzero.bravedns), rather than UIDs (10123/u0_123)

we do this now in `v055b`, but only for the *Backup & restore* scenario, not for app update or generally while "refreshing" Rethink's database.

https://github.com/celzero/rethink-app/blob/02c16a99764b82bd4fbcc53187134cf944c47931/app/src/main/java/com/celzero/bravedns/database/RefreshDatabase.kt#L190C13-L190C43
