### ISSUE TITLE
Themed Icon

### ISSUE THREAD

**Issue by user44000** [celzero/rethink-app#953]
Can you add a themed icon for Android 13+?

**Comment by ignoramous** [comment]
Is this request similar to #511?

**Comment by user44000** [comment]
A themed icon follows the system accent color. Here's a link with information about them. https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by ignoramous** [comment]
Adaptive icons have already been implemented in `v054b`. Unsure why they don't work. Assigning it to Hussain.

**Comment by hussainmohd-a** [comment]
Adaptive icon implementation is done only for handling different shapes. Implementation of monochromatic layer drawables is still pending.
