### ISSUE TITLE
Notifications don't work when rethink is enabled

### ISSUE THREAD

**Issue by coughrelief** [celzero/rethink-app#960]
Notifications from most apps just don't send when I enable rethink.

**Comment by ignoramous** [comment]
You may want to "Bypass DNS & Firewall" for *Google Play services* (GPS). Search for it in "Apps" screen. Most notifications are sent using *Firebase Messaging Service* that is implemented by GPS.

**Comment by coughrelief** [comment]
Fixed, thanks
