### ISSUE TITLE
Misleading description for Google DoH service

### ISSUE THREAD

**Issue by someplaceguy** [celzero/rethink-app#965]
When selecting Google as a DoH provider, there's an "info" button which, when pressed, presents the following information:

> Traditional DNS queries and replies are sent over UDP or TCP without encryption, making them subject to surveillance, spoofing, and DNS-based Internet filtering.

I think this description was copied [from this web page](https://developers.google.com/speed/public-dns/docs/secure-transports), but I think the chosen sentence is highly misleading because it seems to indicate that when you select this option, most queries are sent to Google unencrypted rather over DNS-over-HTTPS, which is rather alarming.

Other providers have less alarming descriptions, e.g. Quad 9's says the following:

> Quad9 routes your DNS queries through a secure network of servers around the globe.

For reference, Google's description seems to come from this line of code:

https://github.com/celzero/rethink-app/blob/9899a3483dde63bdf1c2cfe6903f9dd476ad3be5/app/src/main/java/com/celzero/bravedns/database/AppDatabase.kt#L359

And I think it was introduced in commit c70eeeae5cb26ad014eda9f792c87ede5bd12901.

**Comment by ignoramous** [comment]
Fixed. Will land in `v055` (which has been close to a release since forever...)
