### ISSUE TITLE
Suggestion to create android activity for starting/stopping Rethinkdns

### ISSUE THREAD

**Issue by Crunchbits** [celzero/rethink-app#969]
Would be nice to have an activity that toggles on/off Rethinkdns. Similar to the quick tile that is already available. This would allow for Rethinkdns to be automated by launching the activity using apps such as tasker, macrodroid, etc.

**Comment by ignoramous** [comment]
For tasker, we need only declare launcher / quick-settings "shortcuts"; ref: #63 / #402

Would macrodroid work with those, too?

**Comment by Crunchbits** [comment]
Yes, upon looking into it further app 'shortcuts' would be the correct way not app 'activities'. And yes that would work with macrodroid. I did, however,  want to clarify the comment made in #402 that says the following:

> Apparently, Tasker can call into [these shortcuts](https://developer.android.com/develop/ui/views/launch/shortcuts/creating-shortcuts):
> 
> [tailscale/tailscale#3547 (comment)](https://github.com/tailscale/tailscale/issues/3547#issuecomment-1191413818)

From my understanding app shortcuts will work fine as long as they are not 'deep shortcuts' (generally meaning dynamic and pinned shortcuts). This [post](https://www.reddit.com/r/tasker/comments/gkounp/pluginbeta_taskerlaunchershortcut/) on reddit goes into depth about how these 'deep shortcuts' can't be launched by other apps other than default launcher apps or currently active voice interaction service. If I understand correctly, this means that static shortcuts are the type needed for apps such as tasker and macrodroid to use them.

Don't know if that clarification was already known or not but thought I might mention it anyways.

**Comment by ignoramous** [comment]
Thanks. The information about static / dynamic shortcuts was indeed useful. I hadn't heard of it before.

Closing this as dup of #63 / #402, then.
