### ISSUE TITLE
Unknown app with no process ID connecting between users?

### ISSUE THREAD

**Issue by fourpartswater** [celzero/rethink-app#972]
I am running rethink on grapheneos. In multiuser setting there is an unknown app with no PID showing up connecting to 10.111.222.3. Is this normal? I have searched online but can't find an explanation.

**Comment by ignoramous** [comment]
10.111.222.3 is the tunnel's local DNS resolver (one which forwards DNS requests to user-set plain-old DNS / DNS-over-HTTPS / DNSCrypt endpoint). You're likely seeing DNS requests (in *Network Logs* albeit) sent to Rethink to resolve the Private DNS (DoT) domain name.

Unknown PIDs (UID actually) could also mean the app is installed in a secondary user (Rethink, if installed in the primary user, cannot "see" those apps except for their UIDs). We've tried to "guess" the app given a UID, but that fix is only in `v055` (unreleased as of today).

Also, unknown UIDs are much common in Android 9 and below, and that's down to a few bugs we haven't yet root-caused: #821

Can you post a screenshot, if you're comfortable?

**Comment by ignoramous** [comment]
`v055b` has better support to detect app-name given a UID (even if multi-user is enabled). It may or may not have fixed this issue. Please feel free to re-open if it hasn't.

**Comment by ZBE69** [comment]
> [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b) has better support to detect app-name given a UID (even if multi-user is enabled). It may or may not have fixed this issue. Please feel free to re-open if it hasn't.

Hello, I am not the OP, but with v055b, all the apps are now appearing as Unnamed but without an icon in my user profile:
| Before | After |
| ----     | ---- |
|![1](https://github.com/celzero/rethink-app/assets/89342451/e8938d85-5e74-4ffd-937b-bc2aad8d9d54)|![2](https://github.com/celzero/rethink-app/assets/89342451/77931c5d-559a-45ca-abc3-4402f9ff3d55)|


If I search the app list by UID:
<img src="https://github.com/celzero/rethink-app/assets/89342451/f12c6371-ee1b-41ac-8e8e-e08a5f29c69f" width="400" />

**Comment by ignoramous** [comment]
Looks like we got the "uid" (`10098`) right, but the package name / icons are still not recognized.

**Comment by ZBE69** [comment]
For context, I'm running Rethink in a secondary user profile only (not in primary/owner profile). Feel free to ping me if you need anything from my side

**Comment by ignoramous** [comment]
When you say secondary user, you mean *Work Profile*? Or, a second user?

**Comment by ZBE69** [comment]
I realize that my wording is still a bit confusing. Hopefully this should clear any doubts:

[This](https://github.com/GrapheneOS/Auditor/blob/6887c462302df4fa3bf88d490e075b3a2c558eeb/app/src/main/java/app/attestation/auditor/AttestationProtocol.java#L1564)  is what I refer to as as the owner/main/primary user.

The secondary user is just another user which I created. It doesn't mean it's an inactive user (e.g I'm using the main user while this user is running in the background)

**Comment by ZBE69** [comment]
Fixed in [v0.5.5c](https://github.com/celzero/rethink-app/releases/tag/v0.5.5c). Many thanks!

**Comment by ignoramous** [comment]
Detailed bug reports help us fix (https://github.com/celzero/rethink-app/commit/5bc7a632ad10fbfc39ba0b56828118994d249c6b) these sooner (: Thank you.
