### ISSUE TITLE
v0.5.5 Backup / Restore function broken.!

### ISSUE THREAD

**Issue by lessload** [celzero/rethink-app#975]
( v0.5.5 from github )
From my test 
- i set all app to isolaed mode / after restore, all off it change to allow mode
- after restore, domain/ip rule each app gone. ( not found any domain/ip in backup *.db file )

How i test
  install > config the test > backup > clear app data > restore config

**Comment by ignoramous** [comment]
Thanks for the bug report. Backup and restore is one of our most fragile features.

Can you confirm whether, backup from v054c and restore in v055 broke? Or, backup from v055 and restore in v055 broke?

Note that backup and restore doesn't yet work across different Androids.

**Comment by lessload** [comment]
> Can you confirm whether, backup from v054c and restore in v055 broke? Or, backup from v055 and restore in v055 broke?

from my test v0.5.5 to v0.5.5 same device

**Comment by ignoramous** [comment]
From v055 -> v055 restores not working is strange. We'll take a look

Cross device restores wouldn't work unless we fix #757

**Comment by ignoramous** [comment]
A number of improvements to backup & restore in [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b). It is way better now; or should be.
