### ISSUE TITLE
DNS over WireGuard for apps part of the tunnel

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#979]
Today, the app-wide DNS resolver is used regardless of whether an app is connecting over WireGuard (which defines its own DNS configuration).

Using WireGuard-supplied DNS is critical for some users since some of the domains may be private within a given WireGuard network.

Since the network engine already supports per-app DNS (#270), it can be re-purposed to support this particular use-case of tunneling DNS specific to apps over WireGuard.

This is related to but different from #421 / #284

**Comment by 2Belette** [comment]
Am exactly on this situation... My servers have my public IP address but going through Wireguard I would need to use my internal DNS server to get the proper/internal IP instead as for now I am in a NAT hairpinning situation and I prefer to solve that by DNS rather than fancy nftables rules...

**Comment by michaelblyons** [comment]
Is this done with v0.5.5b?

**Comment by ignoramous** [comment]
Yes, but there are reports that on-device blocklists are broken, so proceed with caution: #1235 

https://github.com/celzero/rethink-app/blob/02c16a99764b82bd4fbcc53187134cf944c47931/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L2379-L2839

https://github.com/celzero/rethink-app/blob/02c16a99764b82bd4fbcc53187134cf944c47931/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L2450-L2649

**Comment by Alexander-Shukaev** [comment]
How to use this?  Say for example `fritz.box` domain in browser gets proxied all the way through the tunnel and results in accessing internet instead of resolving to local Fritz router...

**Comment by ignoramous** [comment]
There are multiple on-going issues with FritzBox. Since we don't have one, we can only guess as to what's happening. Wait for `v055o` which may (or may not) have fixed issues with FritzBox.

> How to use this? Say for example fritz.box domain in browser gets proxied all the way through the tunnel and results in accessing internet

This is because per-app "split tunneling" DNS queries/answers is *not* possible on Android, and whatever heuristics Rethink uses may end up breaking apps in weird ways, though, we constantly try to improve upon those heuristics as breakages get reported.

Related: #1491
