### ISSUE TITLE
v055 homescreen bug in DNS-only mode

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#980]
<details>
<summary>screenshot</summary>
v055 in dns-only mode missing text in "Apps" tile:

![Screenshot_20230815-012252_Rethink](https://github.com/celzero/rethink-app/assets/852289/134890fe-24d4-4d40-a29a-2e8edf5712c8)
</details>

**Comment by hussainmohd-a** [comment]
The above screenshot will be shown only when the app is in a stopped state. When in DNS-only mode, the app details are displayed in the Apps tile. Closing this as not an issue. Please reopen if otherwise.
