### ISSUE TITLE
Direct requests to IP shown and ruled based on (cached?) domain

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#981]
I'm not sure where in the stack the problem lies, but the setup is roughly the following:

* make a request somewhere (can be a different app) to `example.com`, let's say the A record is `1.2.3.4`
* make a different request to `1.2.3.4` directly

In the request log and rule processing, the second request shows as `example.com` despite the domain not being used to access it.

This is problematic when multiple domains resolve to a single IP but the app in question expects an IP rather than a hostname, as the hostname Rethink presents seems to be the most recently resolved domain for that IP address.

If I try to connect to an IP directly, I'd expect no domain rules to be required.

**Comment by ignoramous** [comment]
This is a limitation we have to live with on Android since there's no way to properly attribute a DNS request to an app (and so, a rough heuristic is used that breaks in cases like you mention above). Can you check if enabling *Advanced DNS Filtering* (`v054c` and above) gets rid of such behaviour? 

See also: #876

**Comment by Terrance** [comment]
I hadn't really noticed that option, but apparently I already have it enabled -- maybe I enabled it before without realising what it's for...  but I guess it's not helping with this situation (with it disabled, the problem and workaround are as above).

**Comment by ignoramous** [comment]
Ah, okay. Likely a bug since if *Advanced DNS Filtering* is enabled, that attribution shouldn't happen. Will take a look.

**Comment by Terrance** [comment]
I've raised [a similar bug in Portmaster](https://github.com/safing/portmaster/issues/1322) (a Windows DNS/firewall app that operates largely like Rethink) and I suspect it's the same underlying problem: DNS requests and actual connections are two distinct tasks, so there's a race condition of sorts if a different domain is seen for a shared IP.

If that is indeed how Rethink operates, would [my proposed solution over there](https://github.com/safing/portmaster/issues/1322#issuecomment-1732553595) also be applicable here: to maintain a _set_ of domains resolved to a given IP, and parse rules by substituting the domain with any of the currently-known domains for that IP address if cached?

**Comment by ignoramous** [comment]
> If that is indeed how Rethink operates, would https://github.com/safing/portmaster/issues/1322#issuecomment-1732553595 also be applicable here

We already implement a more capable heuristic than the one presented in the solution (briefly explained here #270). This current bug was a result of a silly miss on our part, and has been fixed (https://github.com/celzero/firestack/commit/d63ccb45032ba5fa4a211efe6c76e2170e7ded9e) in yet to release `v055b`. Or, so we think (:

**Comment by ignoramous** [comment]
Must have been fixed a time ago (with *Advanced DNS filtering* turned ON, which may or may not confuse some apps)...

Feel free to re-open, if that isn't the case.

**Comment by Terrance** [comment]
Yes, I don't think I've seen this in a while.

I potentially have a separate issue of requests appearing without an associated domain when they should have one, but I think that may down to the DNS server malfunctioning -- will raise a separate issue if I can get a solid repro for it.
