### ISSUE TITLE
Backup and restore completely broken

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#986]
A user writes,

> The backup feature just doesn't work, on any version, and I wasn't expecting that.
>
> Why I do, and what I dont do:
> I backup the F-Droid v054c apk and backup file (.rbk file), uninstall, install Github v054c, restore, "successful restore", however, what I appreciated more, the Stats info, now it's empty.
> 
> Seeing a no successful restore, I uninstall the Github v054c version, reinstall the F-Droid v054c version, I then try to restore using the backup file, a "Successful restore", however no import stats, no Firewall rules, nothing.

**Comment by ignoramous** [comment]
Another user writes,

> Not all rules are restored from the settings backup. To restore them, you need to: in addition to restoring the bravedns.db file, delete the bravedns.db-shm and bravedns.db-wal files.

**Comment by hussainmohd-a** [comment]
We are closing this issue as it is being tracked in #975. We will update the progress there.
