### ISSUE TITLE
v055 DNS-only mode - network timeout

### ISSUE THREAD

**Issue by skibbipl** [celzero/rethink-app#991]
I've updated today to v055 on my OnePlus device. And my network is completely broken. I can see in the logs that DNS names are resolved, but I get timeouts for getting real data. I tried my own self hosted DoH server and also RethinkDNS servers - none of them works. I don't use any firewalls or VPN, just DoH. Disabling DNS fixes network access.

**Comment by 2Belette** [comment]
Did you try to switch off "Enable network visibility" under Network ?
Had exactly the same issue and that's what I found to fix it

**Comment by ignoramous** [comment]
> Disabling DNS fixes network access.

Does this mean turning OFF Rethink? Or, moving to Firewall-only mode?

> Nah, I'm still getting timeouts

If you're comfortable doing so, will you please post screenshot of what you see in *Network Log*s for any one such entry (tapping on these entries should throw up a bottomsheet with more information about the connection, including its err status) that you suspect is timing out?

Also, have you changed IP version (Configure -> Network -> Choose IP version) to anything other than IPv4?

Are all connections timing out, or just a few but randomly, or just a few always to the same host / endpoint.

**Comment by ignoramous** [comment]
Oh, I think if you're using DNS-only mode, things are breaking, yeah? If so, turn OFF *Advanced DNS Filtering* from the DNS UI and see if things recover.

**Comment by skibbipl** [comment]
Yes, disabling Advanced DNS Filtering solves the issue.

**Comment by hussainmohd-a** [comment]
Fixed: f3221f0
