### ISSUE TITLE
v055: Domain blocks are always enforced at L4

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#992]
Instead of custom domain blocks (without corresponding *Trust* (allow) rules) being grounded by DNS (with `0.0.0.0` or `::`) is instead blocked by the L4 firewall.

This is a regression and highly undesirable behaviour as L4 blocks are more expensive (resource wise) than DNS blocks.

This bug is reproducible regardless of what the DNS upstream is (Rethink, Quad9, Cloudflare, Google etc)

<details>
<summary>rules</summary>
DNS: 

![Screenshot_2023-08-19-00-31-03-94_c8cbde12d3521911922be4eee6a05664~2](https://github.com/celzero/rethink-app/assets/852289/5a166b46-416d-4a23-a44c-0476d0d215ad)

L4:

![Screenshot_2023-08-19-00-30-53-38_c8cbde12d3521911922be4eee6a05664~2](https://github.com/celzero/rethink-app/assets/852289/b5447312-63cf-40b4-9422-75fbd299130b)
</details>

**Comment by hussainmohd-a** [comment]
Fixed: 89466344d105f9e632ace0ef138d61bd77335b74
