### ISSUE TITLE
v055: Camera Permission

### ISSUE THREAD

**Issue by user44000** [celzero/rethink-app#993]
Why does the latest version have a camera permission?
![Screenshot_20230819-003105_Permission controller_1](https://github.com/celzero/rethink-app/assets/138707369/fde1ddec-0013-4ad7-b066-148d3b80e8bf)

**Comment by ignoramous** [comment]
To scan the QR Code for WireGuard configuration.

**Comment by iulko** [comment]
Well people are uncomfortable with that permission even if its disabled by default :<

https://prabhakarthota.dev/google-code-scanner-api-scanning-codes-without-camera-permission

This looks interesting, but idk how possible is this to implement

**Comment by ignoramous** [comment]
Ah, thanks. We most definitely prefer using an external QR Code API if there's one (you point out that there is for SDK Level 21+?). Will prioritize impl this feature after exploring the robustness and support for the API across ROMs.

**Comment by ignoramous** [comment]
> https://developers.google.com/ml-kit/vision/barcode-scanning/code-scanner

Oh wait, `ML Kit` is *not* open source? That's a non-starter as F-Droid wouldn't build Rethink if it bundles in non-FOSS deps.

**Comment by iulko** [comment]
> > https://developers.google.com/ml-kit/vision/barcode-scanning/code-scanner
> 
> Oh wait, `ML Kit` is _not_ open source? That's a non-starter as F-Droid wouldn't build Rethink if it bundles in non-FOSS deps.

Yes, seems like its not open source unfortunetly :< so better to have camera permission disabled by default :)

**Comment by ignoramous** [comment]
> so better to have camera permission disabled by default like its now

Can you please clarify what you mean by this? I tried googling a bit about "disable camera permission by default" but all I could find was this was something that the users can do in Android's Settings and not something the app can "request" for?

Besides, isn't it the case that Rethink asks for Camera permission only at the time of scanning the QR Code? At least on my Android 12, Rethink was temporarily granted Camera permission just that one time. As in, every time I scan the QR Code from Rethink, I grant it temp access to Camera which is auto-revoked by the OS. May be it is a Android 12+ thing...

**Comment by iulko** [comment]
> > so better to have camera permission disabled by default like its now
> 
> Can you please clarify what you mean by this? I tried googling a bit about "disable camera permission by default" but all I could find was this was something that the users can do in Android's Settings and not something the app can "request" for?
> 
> Besides, isn't it the case that Rethink asks for Camera permission only at the time of scanning the QR Code ([as suggested by Google](https://developer.android.com/training/permissions/explaining-access))? At least on my Android 12, Rethink was temporarily granted Camera permission just that one time. As in, every time I scan the QR Code from Rethink, I grant it temp access to Camera which is auto-revoked by the OS. May be it is a Android 12+ thing...

So sorry I was not more clear what I meant, what I meant was that now everything is as best as it can be, that the permission is only granted when you give it as a user when you scan, sorry for wasting your time

**Comment by ignoramous** [comment]
Ah, gotcha.

> sorry for wasting your time

Not at all! Don't be sorry.

Rethink is positioned as a security app, so it only makes sense that its users are not too impressed with its increasing permissions list, especially a permission as intrusive as Camera. 

Appreciate you sharing about `ML Kit` and other links. We didn't know about it at all. Shame it isn't open source, though.

(closing this, but if you want us to investigate more or have suggestions for a different implementation, feel free to reopen this bug to let us know).

**Comment by t1u1** [comment]
>  have suggestions for a different implementation

Well, I have one suggestion. You could let the user take the picture from their choice of camera app. And only read the picture from your app. But wait, doesn't that require a read storage permission?! No, it doesn't if you use the `ActivityResultsContract.openDocument()`.

A sample in Compose would look like:

```kotlin
@Composable
fun ImageChooser(uri: Uri?, withIO: (suspend () -> Unit) -> Unit, update: (Uri?) -> Unit) {
  val context = LocalContext.current
  var documentDescr by remember {mutableStateOf("Choose an image...")}

  val launcher = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) {
    withIO {
      documentDescr = if (it != null) {
        update(it)
        DocumentFile.fromSingleUri(context, it)?.name ?: uri.toString()
      } else {
        "Choose an image..."
      }
    }
  }

  Button(onClick = { launcher.launch(arrayOf("image/*")) }) {
    Text(documentDescr)
  }
}
```

This might be slightly inconvenient, but since setup is done only occasionally, it might be a good trade off.
