### ISSUE TITLE
Add Mullvad DNS

### ISSUE THREAD

**Issue by shuvashish76** [celzero/rethink-app#996]
Request to add [mullvad DNS](https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/) to our list.
Reason : AFAIK this is the only [audited DNS](https://mullvad.net/en/blog/2021/3/3/mullvad-doh-and-dot-beta-release/) _that I'm aware of_.
We should add `Vanilla` & `Ad-block` version to our list other Base/Extended/All are not necessary for most users.
Thanks.

**Comment by ignoramous** [comment]
Can add the `vanilla` flavour. The `ad block` flavour might be against Play Store terms of use?

**Comment by shuvashish76** [comment]
I think we should use
PlayStore - only `vanilla`
F-Droid - both `vanilla` & `ad-block`

For future reference : They've no logging of DNS requests policy https://mullvad.net/en/help/no-logging-data-policy/
